### ISSUE TITLE
Question: is there any particular reason that .nextIndex cannot be referred as a readable field of a header stack?

### ISSUE THREAD

**Issue by QinshiWang** [p4lang/p4-spec#1003]
Refer to the title.

**Comment by mbudiu-vmw** [comment]
We only promise this field exists in the parser.

**Comment by QinshiWang** [comment]
So `nextIndex` can only be accessed in a parser, just like `lastIndex`, right?

**Comment by mbudiu-vmw** [comment]
That is the current status. It would be perhaps nice to have it in available elsewhere too.

**Comment by QinshiWang** [comment]
From my read of the manual, it's not clear whether `.nextIndex` can be used as a field. It's part of the struct, but it's not mentioned if it can be accessed, in comparison that `.size` accessing is clearly documented.

**Comment by mbudiu-vmw** [comment]
No, `nextIndex` does not actually exist in the language, it is part of the abstract specification of the language. Only `lastIndex` can be used in P4 programs.

**Comment by mbudiu-vmw** [comment]
The spec says this: 

> hs.lastIndex: produces a 32-bit unsigned integer that encodes the index hs.nextIndex - 1.

**Comment by mbudiu-vmw** [comment]
So you can compute nextIndex, but currently it is not available.
I will close this issue, I don't think it needs work in the spec.
