### ISSUE TITLE
Should spec define header validity after lookahead operation on a header?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1014]
That question was raised in this p4c issue: https://github.com/p4lang/p4c/issues/3041

I am not aware of this issue being mentioned in the spec today.

**Comment by mbudiu-vmw** [comment]
If `lookahead` returns successfully it should return a valid value of the requested type. So for a header it should return a valid header. 

There is an alternative design we could use where a failed `lookahead` returns an invalid header and does *not* transition to `reject`. We could have an alternative function for that purpose.
