### ISSUE TITLE
Slicing arbitrary-width integers

### ISSUE THREAD

**Issue by MollyDream** [p4lang/p4-spec#1015]
p4c compiler allows the statement `bit<4> x = 16[3:0]`. This suggests variable-width integers should support slices, but the spec does not list bit slices among the supported operations for arbitrary-width integers.

Based on the p4lang/p4c#3058, the spec should add this operation to section 8.7.

**Comment by jfingerh** [comment]
@MollyDream Interesting corner case you found there.

Does p4c also support any of the following?

`int<4> x = 16[3:0]`   - like your example, but assigned to a variable with signed int type
`bit<4> x= -3[3:0]`   - negative arbitrary-width integer with slice, assigned to unsigned fixed-width integer
`int<4> x = -3[3:0]` - negative arbitrary-width integer, assigned to a variable with signed int type

Note: I do not have a proposed suggestion right now for which of these should be allowed by the spec and which should be disallowed, but it seems worth knowing the answers to what p4c does now, and address all of these cases in the spec (and perhaps other similar ones, if anyone can think of more) at the same time.

**Comment by jafingerhut** [comment]
I have compiled several variations of the attached program using the latest version of p4c as of today:
```
$ git log . | head -n 3
commit 3272e79369f20813cc1a555a5eb26f44432f84a4
Author: Kamlesh Kumar <kamleshbhalui@gmail.com>
Date:   Sat Feb 5 10:52:20 2022 +0530
```

including uncommenting the assignments to variables with names like x2, x6, etc. that are currently commented out.  The ones that are commented-out gave the error messages indicated in comments immediately before those assignment statements.

The ones that are not commented out give no compile-time errors or warnings with that version of p4c.

It appears that regardless of whether an integer literal like `16` or `-37`, with no prefix like `4w` or `4s` to indicate it is a literal of type `bit<4>` or `int<4>`, p4c supports doing a bit slice on them, and always treats the result as of type `bit<4>`, i.e. always an unsigned `bit<W>` type of the width of the slice.

I do not know if that is what the LDWG will agree should be the behavior in the language specification or not, but wanted to report my findings at least for the current p4c version.

[p4-spec-issue-1015-bmv2.p4.txt](https://github.com/p4lang/p4-spec/files/8009186/p4-spec-issue-1015-bmv2.p4.txt)
