### ISSUE TITLE
Parser example P4 code missing closing curly brace.

### ISSUE THREAD

**Issue by rcgoodfellow** [p4lang/p4-spec#1033]
The opening curly brace at the line below is missing a corresponding closing curly brace.

https://github.com/p4lang/p4-spec/blob/c4f237940472262ab978a28312ce20770607e34f/p4-16/spec/P4-16-spec.mdk#L5981

**Comment by jafingerhut** [comment]
Thanks for catching that and creating the issue.  Should be fixed in next release after this PR is merged in: https://github.com/p4lang/p4-spec/pull/1034
