### ISSUE TITLE
type keyword only applies to base types?

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1044]
I didn't know if I should filed this as a specification bug or as a bug in the reference compiler but I think it is just a specification issue.
Take:
```
header t
{
 bit y;
}
type t tyu;
```
The specifications in section 7.5 there is no requirement for type keyword to only handle with a base type (or a type which is type or a base type) but the reference compiler rejects the code:
```
t2.p4(6): [--Werror=type-error] error: tyu: `type' can only be applied to base types
type t tyu;
       ^^^
```

**Comment by mbudiu-vmw** [comment]
This looks like a spec bug; the intent was to only allow this for base types.

**Comment by apinski-cavium** [comment]
Note even what is a base type here is restrictive.
Because the following works:
```
type bool tyu;
```
But not this:
```
type int tyu;
type string tyu1;
```

**Comment by apinski-cavium** [comment]
The reference compiler has the following check:
    if (!argType->is<IR::Type_Bits>() &&
        !argType->is<IR::Type_Boolean>() &&
        !argType->is<IR::Type_Newtype>())

Which means it only apples to bit<> and int<> and bool.
Here is the change to the reference compiler which added the support for type:
https://github.com/p4lang/p4c/pull/1244

**Comment by apinski-cavium** [comment]
https://github.com/p4lang/p4-spec/pull/623
Is the addition to the spec.

**Comment by mbudiu-vmw** [comment]
The discussion is recorded here: https://github.com/p4lang/p4-spec/wiki/LDWG-Meeting-minutes:-May-7,-2018
But perhaps there were earlier discussions too - they are archived in the wiki.

**Comment by jafingerhut** [comment]
This issue is on the list to discuss at the 2022-Nov-07 LDWG meeting, but the corresponding PR #623 has already been merged in.  Is there a reason to discuss this further?  Are there aspects of this issue that have not yet been addressed by that PR?
