### ISSUE TITLE
Bitwise logical operations not allowed for fixed-width signed integers?

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4-spec#1047]
Is it really the case that signed bitwise operations (and, or, xor, complement) are not allowed for fixed-width signed integers (`int<W>`)? Section 8.6 of P4-16 spec v1.2.2 says that:

> Note that bitwise operations on signed integers are well-defined, since the representation is mandated to be two's complement. 

However, the list below that paragraph does not define any of the aforementioned bitwise operations. This seems to be a weird combination. If there are not bitwise operations on `int<W>` than this sentence does not make sense to me. Or was the intention to include them and they are missing?

**Comment by jafingerhut** [comment]
It would be great if you could write a quick test program for p4c, e.g. using the v1model architecture, perhaps, and see which operations it already supports for `int<W>` types, and which it does not, and record the results here.  That helps provide additional evidence for making a decision on any spec changes.

**Comment by mbudiu-vmw** [comment]
The spec seems to imply that |, ^, & are supported for int, but they do not appear in the list of supported operations.

**Comment by mbudiu-vmw** [comment]
This program compiles: 
```
const int<32> x = 10;
const int<32> z = x ^ x;
```

**Comment by mbudiu-vmw** [comment]
The strange thing is that the spec source madoko seems to be correct. The html is wrong.

**Comment by mbudiu-vmw** [comment]
I guess that this bug has been fixed already but we haven't published a new spec yet. The new version of P4 is coming up in May.
I will mark this as fixed.

**Comment by vlstill** [comment]
Thanks, next time I will have a look into the repository version of spec too.
