### ISSUE TITLE
generic (specializable) functions and the expressions inside them

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1049]
Maybe I missed it but I thought this would be valid but the reference compiler rejects it:
```
y func<y>(in y a)
{
  y b = a >> 1;
  return b;
}
```
I know in the specifications it say generic types can be bit types so I had assumed this would be valid so you could use func<bit<2>> later on. I didn't realize type checking for expressions was done before hand.

**Comment by jnfoster** [comment]
Yes, P4's type system is currently based on Java-style parametric polymorphism, not C++-style templates.

**Comment by mbudiu-vmw** [comment]
The plan - long unfulfilled - is to add a notion of type constraints to make such code expressible.
Maybe we can look at the new generics in Go for an example.

**Comment by apinski-cavium** [comment]
Really I am just asking for the specification to be tightened up and formalized rather than asking for a new feature.
If there are going to have multiple implementations of the compiler, it would be a good idea to make sure they conform to the specifications and the specifications to be as tight as possible.
I come from a compiler background and is implementing my own parser/tokenizer/AST, so when things are unclear I test out the reference compiler to see what is being done there. If I think the spec should change rather the reference compiler, I file it in the spec repo.
In this case the spec is very weak in terms of any definition of generic types so I assumed the reference compiler is what was meant so I filed this one here.

Note here is another testcase which shows a similar issue:
```
bit f<t>(in bit a)
{
  const t c = 1;
  bit<(c)> y = 1;
  return y;
}
```
I am just asking for is improvement on the wording of the specifications for the generic types rather than accepting this; because the above code will be harder to handle really because you need to keep around the the type b<((t)1)> as that type until instantiation time which I think will be too hard for most compilers to implement.
