### ISSUE TITLE
Recusive function vs overload set

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1050]
Take:
```
bit f(in bit t)
{
  return t;
}

bit<2> f(in bit<2> t)
{
  bit b0;
  bit b1;
  b0 = (bit)t;
  b1 = (bit)(t>>1);
  b0 = f(b0);
  b1 = f(b1);
  bit<2> b = (bit<2>)b0;
  b = b | (((bit<2>)b1)<<1);
  return b;
}
```
f is not recusive even though f is named the same but the reference compiler rejects it. I think this should be valid but it is not obvious in the specification if it is valid or not.

**Comment by jnfoster** [comment]
FWIW, the type checker for my Cornell group's clean-slate reimplementation of P4 type checks this example just fine.

https://github.com/verified-network-toolchain/petr4

**Comment by jnfoster** [comment]
So I agree `p4c` is wrong in giving this error message:
```
% p4test pinski.p4 
pinski.p4(13): [--Werror=type-error] error: f: Recursive function call
  b0 = f(b0);
       ^
pinski.p4(14): [--Werror=type-error] error: f: Recursive function call
  b1 = f(b1);
       ^
```

**Comment by mbudiu-vmw** [comment]
This should have been filed against the compiler.

**Comment by mbudiu-vmw** [comment]
I will close this issue in favor of the one in the compiler - which refers to this one...
