### ISSUE TITLE
func and generic type overloads

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1056]
Take:
```
void func<t>(t y){}
void func<t, u>(t y){}
void func<t, u>(t y, u i){}
void f<t>(t tt)
{
  func<t,bit>(tt);
}
void ff(bit ttt)
{
  f(ttt);
}
```

The reference compiler first binds the overload based on argument types and rejects it because it will match the func which takes one or two type paramaters.
This is shocking when coming from C++. Plus I don't see anywhere in the specifications which mention that order.

**Comment by mbudiu-vmw** [comment]
Is this a spec or a compiler problem?
Perhaps you want both.

**Comment by apinski-cavium** [comment]
As I said I was shocked coming from a C++ but I think it is decent behavior based on the rest of the P4 language. I am just trying to figure out how I would do the overload in my own parser really and trying to figure out the exact behavior of the reference compiler to copy it. If the specifications is improved to match the reference compiler behavior here I am ok with that.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
