### ISSUE TITLE
int -> int cast is invalid but doing int -> bit<w> -> int is valid

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1058]
Take:
```
bit<4> func1()
{
  bit<4> t = (int)1;
  return t;
}
bit<4> func2()
{
  bit<4> t = (bit<4>)(int)(bit<4>)1;
  return t;
}
```
It seems a bit odd that func2 is allowed but func1 is not. int -> int cast is just a no-op even so allowing it will not change any backends even.
This is a request for more consistency rather than anything else really.

**Comment by mbudiu-vmw** [comment]
Is this a spec issue or a compiler issue?

**Comment by mbudiu-vmw** [comment]
BTW: for such pointwise spec issues feel free to submit a PR that fixes them since you dug through the text anyway.

**Comment by mbudiu-vmw** [comment]
I think this was a compiler bug, so I will close the spec bug. Feel free to reopen if you think I am wrong.
