### ISSUE TITLE
Direct type invocation vs generic types

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1068]
I can't tell if this is a reference compiler issue or a spec issue or both.
Take:
```
parser MyParser<t>(t tt) {
    state start {
        transition accept;
    }
}
parser MyParser1() {
    state start {
        MyParser<bit>.apply(1);
        transition accept;
    }
}
```
I would assume this would work but instead the reference compiler gives a parser error:
```
t.p4(8):syntax error, unexpected .
 MyParser<bit>.
              ^
[--Werror=overlimit] error: 1 errors encountered, aborting compilation
```
If we do instead:
```
parser MyParser<t>(t tt) {
    state start {
        transition accept;
    }
}
parser MyParser1() {
    state start {
        MyParser.apply(1);
        transition accept;
    }
}
```
Which I had assume would figure out the generic type (but does not), we get:
```
t.p4(8): [--Werror=type-error] error: MyParser_inst.apply
 MyParser.apply(1);
 ^^^^^^^^^^^^^^^^^
  ---- Actual error:
  t.p4(1): 'int' type can only be unified with 'int', 'bit<>', or 'signed<>' types, not with 't'
  parser MyParser<t>(t tt) {
                  ^
  ---- Originating from:
  t.p4(8): Type of argument '1' (int) does not match type of parameter 'tt' (t)
   MyParser.apply(1);
                  ^
  t.p4(1)
  parser MyParser<t>(t tt) {
                       ^^
  t.p4(1)
  parser MyParser<t>(t tt) {
                  ^
  ---- Originating from:
  t.p4(8): Function type 'MyParser' does not match invocation type '<Method call>'
   MyParser.apply(1);
   ^^^^^^^^^^^^^^^^^
```
Which is a mouthfull for saying using a generic type without specializing it in this location.

**Comment by apinski-cavium** [comment]
And if do this, thinking maybe using a typedef will workaround the issue, still no luck:
```
parser MyParser<t>(t tt) {
    state start {
        transition accept;
    }
}
typedef MyParser<bit> mytype;
parser MyParser1() {
    state start {
        mytype.apply(1);
        transition accept;
    }
}
```
Error message:
```
t.p4(9): [--Werror=type-error] error: Cannot extract field apply from mytype which has type Type(parser MyParser<...>)
 mytype.apply(1);
        ^^^^^
t.p4(9)
 mytype.apply(1);
 ^^^^^^
```

**Comment by mbudiu-vmw** [comment]
This is probably both a spec and compiler bug. It is meant to be covered by https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-direct-type-invocation, but the example there does not allow for type arguments.

**Comment by mbudiu-vmw** [comment]
You could also argue that this is not really necessary, since you can always do it by doing an explicit instantiation.
I will submit a patch for this, but even the patch will not support constructor arguments, which is also something you may reasonably want to use.

**Comment by mbudiu-vmw** [comment]
This should be discussed in the LDWG. Closed by mistake.

**Comment by mbudiu-vmw** [comment]
LDWG agreed to amend the spec to say that controls/parsers with constructor arguments cannot be invoked directly. @mbudiu-vmw will submit this PR.
