### ISSUE TITLE
abstract methods and the argument names

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1071]
This is a question since the overload is normally done by argument names, one would think even for abstract methods and their implementations would need to match. This is not the case for the impelementation of the methods; at least with the reference compiler.

Take:
```
extern e {
  e();
  abstract bit f(bit a);
}

e() t = {
  bit f(bit b)
  {
    return b + 1;
  }
};
```
Either we change the refence compiler and add explicitly in the spec that the argument names need to match or we just add to the specifications that the names don't matter here.
This is related to https://github.com/p4lang/p4c/issues/4001 at least in the sense the reference compiler only checks if the types (not names) match and rejects it if there is already a duplicated method named.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
