### ISSUE TITLE
style (minor) issue, infinite-precision integer vs arbitrary-precision integer

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1084]
I noticed in the specifications, there are places where arbitrary-precision integers is used and some places where infinite-precision integer. It would be a good idea to chose one or the other.
for an example
```
#### Infinite-precision integers {#sec-infinite-precision-integers}
```
and
```
## Operations on arbitrary-precision integers { #sec-varint-ops }
```

**Comment by jnfoster** [comment]
Agree. FWIW, I prefer "arbitrary precision."
