### ISSUE TITLE
style issue: operators list vs type operator lists

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1085]
I find while implementing the compiler having to switch between the operators on int and bit and arbitrary-precision integers sections to see which type is valid for each operator. I also noticed there are many of the same verbage for each type.
A big example is the slicing operator which only differs by the last setence which says the type of the operator is always unsigned.

The C language is the opposite of what the P4 specifications is. That has sections for similar expressions and then list constraints and semantics of each operator. Obvious this is easier for compiler development. You still can help the current sections but much shorter and provide links to the new sections which then have only one copy of almost the same thing.

The reason why I filed this is to record this style issue I found. Plus someone might also run into this issue.

Also Concatenation and shifts seems to be handled this way but then still duplicate verbage in both signed and unsigned type sections.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
