### ISSUE TITLE
extern types should be similar to parser/control/package and not allowed as a type argument

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1087]
I don't see why extern types should be allowed as a type argument. In the similar behavior as parser/control/packages are disallowed.
I can't think of any usecase that would allow for them to be passed around in this way.

That is making the following invalid code:
```
extern void f<t>(t a);
extern g
{
  g();
  void f();
}
g()  gg;
void h()
{
  f(gg);
}
```

**Comment by mbudiu-vmw** [comment]
I think this is a matter of policy which we should leave to various backends to enforce.
I can imagine cases where externs are parameterized by other externs: e.g., a filter extern parameterized with a policy extern.
There is also a proposal from Alan Lo about having properties of tables that are controls (or even parsers), containing code that is invoked on certain events (for example, entry expiration).

**Comment by mbudiu-vmw** [comment]
I will close this, since I think we plan no changes related to this question. 
Feel free to reopen if you disagree.
