### ISSUE TITLE
Is header stack fixed width or not?

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4-spec#1088]
Hi, I am wondering if a header stack is a fixed-width type and the spec does not seem to help me here (I have checked the `main` branch too). Could you please elaborate on this? Considering that header unions are explicitly not-fixed width ("A header union is not considered a type with fixed width." at the end of the section 7.2.4) I expect that header stacks will also not be fixed width. However, I have came across a P4 code that uses `lookahead` on struct with a header stack and `lookahead` is only allowed on fixed width data (sec 12.8.3). The `lookahead` could actually make sense here as it would allow an "array lookahead".

**Comment by vlstill** [comment]
Thank you. OK, just to be safe, the size of `some_type_t stack[N]` is `N * sizeof(some_type_t)` if and only if `some_type_t` is sized?

**Comment by mbudiu-vmw** [comment]
We have methods minSizeInBits and maxSizeInBits which should be defined for all cases in the spec.

**Comment by vlstill** [comment]
Thanks, but I am actually concerned with the size in the `p4c` compiler which (`Type::width_bits()`) is currently returning zero in this case.

**Comment by mbudiu-vmw** [comment]
I would recommend using the typeMap-based method instead:
```
    /// The width in bits of this type.  If the width is not
    /// well-defined this will report an error and return -1.
    /// max indicates whether we want the max width or min width.
    int widthBits(const IR::Type* type, const IR::Node* errorPosition, bool max);
```

**Comment by mbudiu-vmw** [comment]
Maybe this is not the right API, since it will report an error if the width is not well-defined, but it handles all sorts of types, including typedef and unions. You could add a flag to make it not report the error.

**Comment by mbudiu-vmw** [comment]
Come to think of this some more, I am not sure what we should add to the spec. Perhaps this is a problem with the compiler?
