### ISSUE TITLE
P416 spec: Inconsistent "architecture" terminology

### ISSUE THREAD

**Issue by akertesz** [p4lang/p4-spec#1091]
From reading the P416 specification, it seems that at some point in the evolution of P416, the term "model" was used to describe what later became the P416 architecture. Is my inference correct?

For example, in section 7.13:
> The declaration of new `match_kinds` can only occur within model description files; P4 programmers cannot declare new match kinds.

I think this a minor spec bug; it should read "... within architecture description files...". This is the term used in most of the spec.

Elsewhere in the spec, the terms “architecture definition”, “architecture description”, “architectural description”, “architecture description file” and “architecture model” all seem to be used loosely interchangeably. (And Figure 2 has "P4 architecture model".) A pedantic quibble, but it would be helpful if consistent terminology were used throughout!

**Comment by jnfoster** [comment]
Yes, this looks like an oversight. 
I have been pedantic about ensuring consistent use of certain terms, but clearly not all. 
We welcome PRs ;-)

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
