### ISSUE TITLE
P416 spec: Inconsistent lookup table terminology

### ISSUE THREAD

**Issue by akertesz** [p4lang/p4-spec#1093]
This is a minor (and genuinely pedantic) quibble about the inconsistency in the usage of lookup table-related terminology in the P416 specification!

Context: My team is implementing a P4 compiler, and I want our user-facing documentation to use terminology well aligned to that of the specification. The inconsistencies in the P416 spec make that more difficult.

**Table definition:**
- Section 13.2 notes that the word “table” is overloaded; it can refer to the P4 table object (which describes a match-action unit) or to a lookup table.
- But Section 3 gives a formal definition of “tables” which I read as equivalent to “lookup table”. I think this definition should be revised, or associated with “lookup table” instead.

**What do you call the thing you look up in a lookup table?**

- Throughout the spec I variously found this referred to as "lookup key", "search key", and "table search key"
- It was quite clear what was meant in each case, but it would nonetheless be helpful to have a consistent term. “Lookup key” is the most commonly used, and the one that appears in Figure 11. (I’ll grant that this is unlikely to bother anyone who isn’t on the hunt for correct terminology as I was!)

**What do you call the act of performing that lookup?**

- I variously found this referred to as "table lookup", "lookup", and "key lookup"
- Again, it’s clear what is meant, but consistency would be nice.

**Comment by mbudiu-vmw** [comment]
That's the whole point of having an open-source spec: you can always suggest fixes.

**Comment by mbudiu-vmw** [comment]
I was hoping that you would actually submit a pull request with suggested fixes...

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
