### ISSUE TITLE
eq and ne is currently not allowed on tuple expressions

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1094]
I don't see why '==' and '!=' are not mentioned in #sec-tuple-exprs as operations on it. It is very similar to struct and should have the same behavior as struct really.

The other thing is in #sec-ops-on-structs, "all of their fields can be recursively compared for equality." is not needed as all of the types allowed after tuples are added to the list of allowed for equality.

I will submit a pull request for both of these issues over the weekend. I just wanted to file this issue now so I don't forget.

**Comment by jafingerhut** [comment]
This seems like a reasonable enhancement to make to the spec to me.  Is there a PR ready for review yet?

**Comment by mbudiu-vmw** [comment]
See #1178
