### ISSUE TITLE
is bool a valid type for select expression

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1101]
Take:
```
parser MyParser1(in bool tt1) {
    state start {
        transition select(tt1) {
                true: state1;
                _: accept;
        }
    }
    state state1 {
        transition accept;
    }
}
```

I assume it is and should be added to the following setence:
```
The type of the values in the set must be one of
bit<>, int<>, tuple, struct, bool and serializable `enum`.
```

**Comment by vgurevich** [comment]
It is absolutely a valid type for the `select()`. Moreover, we the `if()` statements in the parser are transformed into very similar selects already. 

The only thing is that one can't probably create a set of booleans using the `&&&` operation, but other than that I think that set of booleans are well defined and the semantics of `_` in that context is fully understood

**Comment by apinski-cavium** [comment]
https://github.com/p4lang/p4c/issues/3336 is a related issue but only because it uses bool inside a struct for the case which causes an internal compiler error :).

**Comment by apinski-cavium** [comment]
So this is a dup of issue #954  really.
And the pull request https://github.com/p4lang/p4-spec/pull/968 .

**Comment by mbudiu-vmw** [comment]
Maybe then we should close this issue?

**Comment by jnfoster** [comment]
Let's close it.
