### ISSUE TITLE
Does p4 support a layer 2 protocol other than ehternet?

### ISSUE THREAD

**Issue by Saigut** [p4lang/p4-spec#1102]
From the [example](https://github.com/p4lang/p4-spec/blob/main/p4-16/psa/examples/psa-example-hello-world.p4), we can see there is no code for processing padding bytes and crc bytes of ethernet. So I think the compiler treats all packets as ethernet packet, and it processes padding bytes and crc bytes automatically, is this right?

So what if I define a custom layer 2 protocol, which could have a packet less than 64 bytes?
Does compiler still think it should have padding bytes (for small packets) and crc bytes, and should have a 64 bytes minimal size?

**Comment by mbudiu-vmw** [comment]
P4 has no capability to process packet trailers, only packet headers.
The processing of bytes and crc for ethernet is assumed to be done by the target architecture itself. The packet that reaches P4 is stripped of this information. 
Note that some switches may do cut-through routing and perform the P4 packet processing *before* the last byte of the packet has even been received; they may even start sending the packet before the trailer has been checked! These architectures will probably do something appropriate, like making sure that in case of corrupted CRC the output packet(s) also have corrupted trailers.

So P4 has really nothing to do with this. There is no minimum packet size in P4, and P4 does not require the first protocol to be ethernet. The compiler does not do the padding or compute the CRC, it's part of the target. The target *knows* what kind of input and outputs ports exist.

**Comment by Saigut** [comment]
Thanks for your explanation.
