### ISSUE TITLE
range and mask operator and implicit casts

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1106]
Take:
```
parser MyParser1(in bit<8> v) {
  state start {
    transition select(v) {
     (0x100)..(0x1ff): accept;
     (0x00)..(0x101): accept;
     _: reject;
   }
 }
}
```
it is not obvious what the range should do here? I think it should be saturation cast rather than a truncation cast because that would make better sense really. This is not mentioned anywhere in the specifications of what should happen here.

The specifications has the following for cast (sec-implicit-casts):
```
To keep the language simple and avoid introducing hidden costs, P4
only implicitly casts from `int` to fixed-width types and from enums
with an underlying type to the underlying type. In particular,
applying a binary operation (except shifts and concatenation) to an expression of type `int` and an
expression with a fixed-width type will implicitly cast the `int`
expression to the type of the other expression. 
```
But in this case we have int...int and set<int> as the type which is being casted to set<bit<8>> which is not defined here or anywhere really.

mask has a similar issue if the non mask part has any bits which are outside the number of bits;
that is `0x1ff&&&0x3ff` which for bit<8> should be always false.

From what I can tell p4c just truncates both operands of mask and range but that seems wrong.

**Comment by mbudiu-vmw** [comment]
I don't see any other reasonable behavior really except casting in this way.
The compiler should generate warnings for overflows - and currently it does.
