### ISSUE TITLE
Table entry lists should be allowed to be empty

### ISSUE THREAD

**Issue by QinshiWang** [p4lang/p4-spec#1112]
TL; DR: It is useful to allow `const entries = { /* empty */ }`.

Currently, the syntax is
```
tableProperty
 : const ENTRIES '=' '{' entriesLlist '}' /* immutable entries */

entriesList
 : entry
 | entriesList entry
 ;

entry
 : keysetExpression ':' actionRef optAnnotations ';'
 ;
 ```
 So the constant table entry lists cannot be empty. But this is useful when we want to define a table that always calls an action, as follows.
 ```p4
 table single_action_table {
    key = { }
    actions = {
        my_action();
    }
    const entries = { }
    default_action = my_action();
    size = 1;
}
```
The table is a wrapper for `my_action()`. We can directly call `my_action()` and P4 will synthesize a table. But it is nice to manually define this table when we want to name the table.
@MollyDream

**Comment by jnfoster** [comment]
I believe this was fixed in #1013.
