### ISSUE TITLE
What error is set when there is an explicit reject state is used

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1114]
Maybe I missed it but I cannot figure out what error is set to when there is an explicit reject state reached (not via verify extern).
I have an use case where I want to set the error during the transition rather than via the verify extern too.
An example would where I want to set the error during transition to reject would be :
```
#include <core.p4>
header ethernet_t {
    ethernet_addr_t dst_addr;
    ethernet_addr_t src_addr;
    bit<16>         ether_type;
}
struct headers_t {
    ethernet_t ethernet;
}
error {
unknownethtype
}
parser packet_parser(packet_in packet, out headers_t headers) {
    state start {
        transition parse_ethernet;
    }
    state parse_ethernet {
        packet.extract(headers.ethernet);
        transition select (headers.ethernet.ether_type)
        {
           0x0800: accept; // ip
           0x86dd: accept; // ipv6
           //... other ethernet types
           default: reject; // set error to unknownethtype
        }
    }
}
```
Yes, I could in theory add an extra state for the reject state which just does `verify(false, unknownethtype);` but that might be too much typing.

**Comment by jnfoster** [comment]
This is not specified. The relevant part of the spec is this:

> An architecture must specify the behavior when the accept and reject states are reached. For example, an architecture may specify that all packets reaching the reject state are dropped without further processing. Alternatively, it may specify that such packets are passed to the next block after the parser, with intrinsic metadata indicating that the parser reached the reject state, along with the error recorded.

**Comment by mbudiu-vmw** [comment]
Can we close this, or should we discuss it?

**Comment by mbudiu-vmw** [comment]
I will close this, I think the answer is pretty clear in the spec. Feel free to reopen.
