### ISSUE TITLE
 Question about the ambiguity of P4 grammar

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4-spec#1131]
I’ve been studying the [P4 Language Specification](https://p4.org/p4-spec/docs/P4-16-v1.2.3.html), and noticed that [it is said](https://p4.org/p4-spec/docs/P4-16-v1.2.3.html#sec-grammar):

> The grammar is actually ambiguous, so the lexer and the parser must collaborate for parsing the language. In particular, the lexer must be able to distinguish two kinds of identifiers:
> * Type names previously introduced (`TYPE_IDENTIFIER` tokens)
> * Regular identifiers (`IDENTIFIER` token)

I wonder if some examples could be given to illustrate such ambiguities?

The background is that we are currently working on a P4 language tool. We adopted a language tool framework optimized for interactive usage, which requires all source code files to be parseable in isolation, meaning a single source file should be parseable to an AST on its own, not considering other files. Unfortunately, P4's grammar does not satisfy this constraint. Because to properly parse a P4 source file, we need a symbol table to distinguish `TYPE_IDENTIFIER` and `IDENTIFIER`. But that symbol table can only be constructed considering all the include files, not just the source file itself.

As an alternative, we would like to modify the P4 grammar a little bit so it doesn’t have to distinguish between `TYPE_IDENTIFIER` and `IDENTIFIER` in the parsing phase. We are currently experimenting through trial and error, which is not very effective. So we would like to get some help here.

For the P4 language experts here, do you think this is achievable? And if so, what do you think is the best way to approach this?

Thanks!

I [asked on the P4 forum previously](https://forum.p4.org/t/question-about-the-ambiguity-of-p4-grammar/444), and was suggested to post here too.

**Comment by qobilidop** [comment]
Thanks! That's a very illuminating example.

I think for our purpose, we could modify the grammar to merge the different productions into a single `CastOrFunctionCallExpr`, and then try to distinguish these 2 cases later during the reference resolution phase.

**Comment by qobilidop** [comment]
Follow up on the example, just out of curiosity, from the language design point of view, why does P4 allow function or method name to be any `expression`, as specified in:

```
expression
    : ...
    | expression '<' realTypeArgumentList '>' '(' argumentList ')'
    | expression '(' argumentList ')'
```

instead of a more restrictive subset? I would never write `(f)(x)` if I could write `f(x)`, for example.

**Comment by apinski-cavium** [comment]
> Follow up on the example, just out of curiosity, from the language design point of view, why does P4 allow function or method name to be any `expression`, as specified in:
> 
> ```
> expression
>     : ...
>     | expression '<' realTypeArgumentList '>' '(' argumentList ')'
>     | expression '(' argumentList ')'
> ```
> 
> instead of a more restrictive subset? This implies the syntax of `(1+1)(x)` is correct?

yes that syntax is valid but semantically it will be rejected. C has the same thing too.
Even "(1+1)<bit>(1)" is syntaxically correct but semantically incorrect.
I worked through many of these items because I wrote my own recursive decent parser/front-end for P4.
The cast was one of the few places were I didn't like how I implemented in the end; I thought I could get away with a few token lookahead but it got more complex.

Do note (3w1+3w1).minSizeInBits() is a well defined expression. It is defined as a compile time know constant (3).

Oh the place where it becomes ambiguous is instantiation vs function call:
type_identifier(1,2,3) identifier;
identifier(1,2,3);
unless you have an infinite lookahead and such, trying to figure out if you are doing a type instantiation or a function call would be hard.

**Comment by qobilidop** [comment]
@apinski-cavium What do you think about our plan to merge ambiguous productions into `AOrB` type of AST nodes? For our use case, we just want to get some reasonable AST out of a single source file. And we think we could disambiguate these merged nodes later on the AST during semantic analysis phase. In this phase, we can check all include files' ASTs for reference resolution.

I'm still in the middle of trying. If you think this could work, that would give me much more faith in what I'm doing.

**Comment by jnfoster** [comment]
Should we close this issue? Not sure if there is an immediate action item here.

**Comment by mbudiu-vmw** [comment]
I usually keep questions open if I think they can be useful to a broader audience, but this one is indeed fairly narrow and I think the answer reached the intended audience.
