### ISSUE TITLE
Inconsistent section link in P4_16 Language Specification v1.2.3

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4-spec#1137]
The link to the P4_16 Language Specification is: https://p4.org/p4-spec/docs/P4-16-v1.2.3.html

But if I click on a section, it becomes: https://p4.org/wp-content/uploads/2022/07/P4-16-spec.html#sec-overview

The one I expect is: https://p4.org/p4-spec/docs/P4-16-v1.2.3.html#sec-overview

This link actually works, but it's not used by default.

This is not a big issue, but I think it would be nice to fix it.

**Comment by jnfoster** [comment]
Ugh. I’ve repeatedly asked ONF staff to fix this. Let my try again.

**Comment by jnfoster** [comment]
Closing as I believe this has been fixed.
