### ISSUE TITLE
Support for generic list types and list literals

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#1140]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [ ] **Document**: https://github.com/p4lang/pna/pull/52

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/1168
- [x] **`p4c`**: https://github.com/p4lang/p4c/pull/3520
## Process
- [ ] **LDWG discussed**: August 2022
- [ ] **LDWG approved**: 
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**: 

=======================================

**Comment by mbudiu-vmw** [comment]
Prototype implementation in https://github.com/p4lang/p4c/pull/3520

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
