### ISSUE TITLE
Unclear woring of `inout` parameters vs. initialization

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4-spec#1142]
I had a discussion with @bleibig regarding behavior of `inout` arguments and initialization. In [sec 6.7](https://p4.org/wp-content/uploads/2022/07/P4-16-spec.html#sec-calling-convention) it is mentioned that

> Direction `out` parameters are always initialized at the beginning of execution of the portion of the program that has the `out` parameters, e.g. control, parser, action, function, etc.  This initialization is not performed for parameters with any direction that 
is not `out`.

this suggests that initialization only applies to `out`.

However, there is also:

> `inout` parameters are both `in` and `out`. An argument passed as an `inout` parameter must be an l-value.

which suggests that `inout` has properties of both `in` and `out`, which could be interpreted to include the initialization mentioned before.

I would assume that `inout` arguments are not intialized (as if they were, they would be functionally the same as `out`), but this wording is inconclusive in my opinion.

**Comment by jnfoster** [comment]
I see how this is a bit confusing. I do think it's fairly clear to anyone reading the whole spec, that the `in` component of an `inout` parameter governs its initialization behavior. Still, we should try to eliminate this confusion. Do you have a suggested rewording?

**Comment by jnfoster** [comment]
One possibility would be to weaken this phrasing,

> inout parameters are both in and out. 

and clarify the small differences to just the intersection of those two.

**Comment by vlstill** [comment]
Maybe just be more explicit, at the cost of text duplication. So I would suggest something like this:

> `inout` parameters are combination of `in` and `out`. The initialization works just like for `in` parameters (the argument is copied), and the results are copied out into an l-values as for `out` parameter.  An argument passed as an `inout` parameter must be an l-value.
