### ISSUE TITLE
Question about extern declaration grammar

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4-spec#1158]
In the language spec [H. Appendix: P4 grammar](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-grammar), the following two production rules are shown:
```
externDeclaration
    : optAnnotations EXTERN nonTypeName optTypeParameters '{' methodPrototypes '}'
    | optAnnotations EXTERN functionPrototype ';'
    ;
```

But in the actual p4c parser, [a third rule is shown](https://github.com/p4lang/p4c/blob/e2c99936dc1d44cafec5c5b58e90232c440d2a32/frontends/parsers/p4/p4parser.ypp#L894):
```
externDeclaration
    : optAnnotations EXTERN nonTypeName optTypeParameters '{' methodPrototypes '}'
    | optAnnotations EXTERN functionPrototype ';'
    | optAnnotations EXTERN name ';'
    ;
```

I wonder if this is a mismatch?

Moreover, only extern objects and functions are explained in [section 4.3](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-external-units). I'm not sure what the third rule declares.

**Comment by mbudiu-vmw** [comment]
This third rule is there for "forward declarations", similar to C incomplete type declarations `struct X;`.
Some architectures wanted recursive externs I guess and needed such declarations.
These are not really officially supported by the compiler, that's why the spec does not mention them.
But there would be no harm in discussing them perhaps.

**Comment by qobilidop** [comment]
I see. Thanks for the clarification!

**Comment by apinski-cavium** [comment]
So it was added in aa88d998c3 to support "architecture-specific conversion of P4_14 externs to P4_16".
I remember looking into this while working on this area for my front-end. In the end I decided it was not needed.

**Comment by apinski-cavium** [comment]
Oh I did file this on the p4c side
https://github.com/p4lang/p4c/issues/3223

**Comment by jnfoster** [comment]
It seems like this might be addressed...

In any case, in the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
