### ISSUE TITLE
Duplicated table properties

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1162]
I didn't see anything in the specifications which says that duplicated properties is invalid but p4c rejects it.
I agree this should be invalid even and not last one wins situtation even.

The specifications does say this:
```
Syntactically a table is defined in terms of a set of key-value properties.
```
But that could mean last one wins, errors out on duplicate or even merge them. It would be best if it was explict of what happens here.

test example:
```
action a() {}
control c() {
    table t {
        actions = { .a; }
        actions = { .a; } // { dg-error "uplicates" }
        size = 100;
        size = 100; // { dg-error "uplicates" }
        default_action = a;
        default_action = a; // { dg-error "uplicates" }
    }
    apply {}
}
```

**Comment by jafingerhut** [comment]
It seems reasonable to me to make it slightly more explicit in the spec.  Do you want to take a shot at a PR for such a change?
