### ISSUE TITLE
action_run with an action that shadows in the global namespace and the local namespace

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1169]
Take:
```
action NoAction() {}
action a() {}
control c()
{
  action a() {} // { dg-warning "" }
  action b() {}
  action d() {}
  table t {
    actions = {a; b;}
  }
  apply {
    switch(t.apply().action_run) {
      .a: {}
      b: {}
      default: {}
    }
  }
}
```
The language specification is not clear that this would be valid or not. 
p4c accepts this right now (with a warning about shadowing).
But the action .a is not in the action table, only a.
In this one case, I don't have any thoughts on if it should be valid or not.

Note I suspect with namespaces it will get even more confusing when implemented on how action names are specified for the switch table and all.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.

@apinski-cavium please tell us if you want to modify the spec to clarify the semantics.
