### ISSUE TITLE
Is there any specific timing method defined in p4 language?

### ISSUE THREAD

**Issue by IIRezaII** [p4lang/p4-spec#1170]
Hi
I was wondering if there is any specific timing method or function available in p4 language(BMV2). 
For example, if we want the switch to read/write a value from/to a register every 1 seconds or send a metadata to CPU every 10 seconds.
Is it possible to have a timer "Completely Inside" the switch and do actions based on that timer value?

Thank you.

**Comment by jafingerhut** [comment]
The P4 language does not specify such a mechanism.  There are some particular P4 architectures that enable such a feature, e.g. Tofino has in internal packet generator hardware block that can be configured to generate a packet with a header having configurable contents, that can generate packets and send them into the pipeline periodically.  Other implementations are free to implement similar features, but it is not a standardized part of the language.

**Comment by IIRezaII** [comment]
Thank you for your quick response. I personally assumed that maybe there is such a mechanism implemented in BMv2 as well. According to meters  which enables the switch to measure Packets/s or Bytes/s, the BMv2-based switch is somehow able to measure the time, unless i am misunderstanding about the switch functionalities and how it works. Maybe it is not directly accessible by the programmer.
Please let me know if im having a misunderstanding here, and any suggestions on BMv2 and such mechanism will help. 
Thank you.

**Comment by IIRezaII** [comment]
Yes, that is correct. Thank you for your time, it is crystal clear now.

**Comment by jnfoster** [comment]
Closing as this question has been anwered.
