### ISSUE TITLE
https://p4.org/p4-spec/docs/P4-16-working-spec.html is not being generated correctly or stopped being generated

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1175]
Something is wrong with the working draft not being generated correctly.
See ![image](https://user-images.githubusercontent.com/6335315/198735239-10158518-e2fb-4708-85f3-31e0c0407128.png) 

In the table in the section "Type nesting rules" does not list the `string` type but the source definitely has it:
https://github.com/p4lang/p4-spec/blob/465d5a886e336f4f5a342a86d49a34a87346409e/p4-16/spec/P4-16-spec.mdk#L2559

**Comment by apinski-cavium** [comment]
It is correct for 1.2.3 though:
https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-type-nesting

**Comment by jafingerhut** [comment]
The working draft is NOT up to date with the latest commit to the p4-spec repo.  This has unfortunately been the case for quite some time, and hopefully we can get that fixed on the p4.org site some time soon, but until then, you can generate HTML and PDF by installing the software using this script on a supported OS and type `make` in the spec directory: https://github.com/p4lang/p4-spec/blob/main/p4-16/spec/setup-for-ubuntu-linux.sh

**Comment by apinski-cavium** [comment]
>The working draft is NOT up to date with the latest commit to the p4-spec repo
It is not even up to date even for 1.2.3.
Maybe we should just link to 1.2.3 really.

**Comment by jafingerhut** [comment]
2020-Oct-30 update: I have contacted a couple of people at ONF that I hope can help us resolve this.  It might take a while (e.g. weeks) before everyone involved agrees on how to achieve this.

**Comment by apinski-cavium** [comment]
We can close this as fixed as pre Andy Fingerhunt's email (and I double checked it).  Thanks everyone for their work on this one.
