### ISSUE TITLE
key element not being scalar is not mentioned in the spec

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1176]
I didn't see anywhere that keys cannot be non-scalar types. Obviously I agree that they cannot be non-scalar types.
This is a minor issue; adding the following should fix it but I don't have time to do a diff:
```
Each key element must be a scalar fixed type (`bit<W>`, `int<W>`, an `enum`, a `bool` or an `error` type).
```
---- CUT ---
Note I am not a fan of allowing `error` type here but p4c accepts it.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
