### ISSUE TITLE
PSA: problem definition

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4-spec#119]

**Comment by jafingerhut** [comment]
Note that there is newer work on this p4lang/p4c PR: https://github.com/p4lang/p4c/pull/569

**Comment by jnfoster** [comment]
Shall we close this issue now that there is a pull request?

**Comment by cc10512** [comment]
This was opened for both the arch definition and for @dandaly to work on p4 examples validating the idea of PSA. The latter is still pending.

**Comment by jnfoster** [comment]
Okay. Can you assign it a milestone so we can keep track of it?

**Comment by dandaly** [comment]
I've made progress on this, let's set a deadline for the end of May?

Dan

**Comment by cc10512** [comment]
I did create a milestone for the end of June, but if we can finish this earlier, it would be great.

**Comment by jnfoster** [comment]
We should investigate modeling the packet generator (#25). I'm going to close that issue since this one subsumes it.

**Comment by cc10512** [comment]
obsolete.
