### ISSUE TITLE
Add list type to P4

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1194]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @jnfoster

## Design
- [x] **Document**: No design document, but an example of use that motivated the addition of this language feature here: https://github.com/p4lang/pna/pull/52

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/1168
- [x] **`p4c`**: https://github.com/p4lang/p4c/pull/3520
## Process
- [x] **LDWG discussed**: 2022-Dec-05
- [x] **LDWG approved**: 2022-Dec-05
- [x] **Merged into `p4-spec`**: 2022-Dec-06
- [x] **Merged into `p4c`**: https://github.com/p4lang/p4c/pull/3520

=======================================

**Comment by jafingerhut** [comment]
Nate, I proposed you as a supporter for this issue.  Feel free to request I take you off and add someone else if I have been too presumptuous there.

**Comment by jnfoster** [comment]
I support!!
