### ISSUE TITLE
Open to a few changes to grammar.mdk file to make it easier to compare to grammar in p4c?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1195]
Here are some changes that I have in mind, and have verified that it can make the contents of the grammar.mdk file much quicker for a person to compare against the file p4parser.ypp in the p4c compiler:

+ Change the order that some non-terminal symbols are defined in the file (no semantic changes)
+ Change the order of some alternatives in the definition of some non-termainsl (e.g. `x: alt1 | alt2 ;` would become `x: alt2 | alt1 ;` to match the order in p4parser.ypp)
+ Replace all single quotes with double quotes, e.g. `','` would become `","`, to match what is used in p4parser.ypp

There might be one or two other changes I'm forgetting right now, but this is the idea -- changes that do not make any semantic change to the contents of grammar.mdk, but syntactically make it closer to something that you can use "diff" to compare it against p4parser.ypp -- or more precisely, a text file mechanically produced from p4parser.ypp via a tiny Python program that removes all of the C++ code in braces from p4parser.ypp.

If this would be of interest, what kind of PRs would make such changes quickest to review?

One PR with all of these changes combined into one commit?

Separate PRs for each of the bullet items above?

Something else?

**Comment by jnfoster** [comment]
One PR seems fine to me, if it's all confined to the grammar.

**Comment by jafingerhut** [comment]
I think I will wait until after some of my other PRs are merged in to create such a PR, to avoid merge conflicts.  That said, there are likely to be some open PRs that would experience merge conflicts no matter when such a change to the grammar.mdk file was made, so it will likely lead to that annoyance for some currently open PRs.

As an example of the kinds of changes I have in mind, made in a step-wise fashion for easier verification what each step does, see https://github.com/jafingerhut/p4-guide/tree/master/compare-p4c-grammar-with-spec

**Comment by jnfoster** [comment]
Sounds great. This will be a valuable improvement of hygiene!

**Comment by mbudiu-vmw** [comment]
Ideally we should build a tool to mechanically verify that the two are identical.
Otherwise we'll always be behind. This could be a cute intern project.
Write a parser in ANTLR for the two grammars and then compare trees.

**Comment by jafingerhut** [comment]
A separate but related question: Currently the Madoko source file P4-16-spec.mdk uses the Madoko INCLUDE capability only once, to include the entire grammar.mdk file in an appendix.

For some other P4_16 specs, I have often used a capability to INCLUDE a portion of a file like psa.p4 that is marked by specially formatted comments.  Example:

+ This line in PNA.mdk: https://github.com/p4lang/pna/blob/main/PNA.mdk#L460
+ causes this sequence of lines from the pna.p4 file in that same repo to be included when PNA.mdk generates HTML/PDF output: https://github.com/p4lang/pna/blob/main/pna.p4#L106-L167 (note the BEGIN and END comments immediately before and after those lines with the string Type_defns on them, which matches the string Type_defns in the PNA.mdk INCLUDE directive)

We could do something similar for excerpts of grammar.mdk in P4-16-spec.mdk, if there is interest.  One advantage is that it helps avoid duplication, and ensuring that changes to the grammar can be made in one place but appear in multiple places.

**Comment by jafingerhut** [comment]
Hmm, maybe.  I can check whether those comments will be included in the full include in the appendix, or not.  The makefile could easily be made to remove those specially formatted comments, if so.

**Comment by jfingerh** [comment]
Proposed PR making syntactic changes to grammar.mdk, but should be zero changes in the semantics of the language generated by the grammar, here: https://github.com/p4lang/p4-spec/pull/1199

**Comment by jfingerh** [comment]
@mbudiu-vmw wrote in an earlier comment: "Won't insertions in the grammar mess up everything else?"

See this PR for an example of what I mean of using the Madoko INCLUDE directive to include small sections of the grammar.mdk file within the specification document: https://github.com/p4lang/p4-spec/pull/1201

Note: The mechanism uses specially formatted comments as begin/end markers of the sections to include, not line numbers, so there is no issue with line numbers getting out of date as future changes are made to the grammar.mdk file.

**Comment by jafingerhut** [comment]
Closing this issue, now that grammar.mdk has been made closer to p4c's Bison grammar for easier diff'ing, and with this PR https://github.com/p4lang/p4-spec/pull/1201 merged in, P4-16-spec.mdk now makes extensive use of Madoko's INCLUDE directive for including excerpts of the grammar.mdk file in the spec.
