### ISSUE TITLE
Several definitions of grammar rules in P4-16-spec.mdk that differ from those in grammar.mdk file

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1202]
If you search for occurrences of the string `Begin P4Grammar` in the file P4-16-spec.mdk, most of those blocks of text between `~ Begin P4Grammar` and `~ End P4Grammar` line pairs use only one or more Madoko INCLUDE directives to include excerpts from the file grammar.mdk.

A few, however, do not, and they do not because the definition in the file P4-16-spec.mdk differs from the one in grammar.mdk.  Some of these may require thought by a language expert to determine why they differ, and if they should be made the same, or not.

If you search P4-16-spec.mdk for the definitions of these nonterminal grammar symbols, they are the ones that appear to me to be different in a way that might be significant:
```
name
expression
tableProperty
```
At least for tableProperty, I believe the difference is that grammar.mdk is closer to p4c's definition, which includes a experimental implementation of the changes in this PR: https://github.com/p4lang/p4-spec/pull/1180   If that PR is approved and merged in, likely the two definitions of tableProperty will become the same, and INCLUDE can be used in P4-16-spec.mdk for it as well.

The differences below appear to me to be only because P4-16-spec.mdk defines the alternatives between different `|` branches in different parts of the spec, a piece at a time, not because the definitions are actually different.  However, it seems quite awkward to try to use Madoko's INCLUDE directive to include these partial definitions from grammar.mdk, so I have not attempted to do so:
```
lvalue - 2 excerpts
typedefDeclaration
methodPrototype - 2 excerpts
argument
expression - 4 excerpts
instantiation - 2 excerpts
statement - 1 excerpts
```

**Comment by jnfoster** [comment]
This is a good observation. I'm closing it though as it doesn't appear to involve a technical change... Please reopen if there is a discrepancy that needs addressed.
