### ISSUE TITLE
Can we allow trailing comma in P4?

### ISSUE THREAD

**Issue by tiantianz** [p4lang/p4-spec#1205]
In some situations, for example if we want to something like:

```
     headers.some_header = {
         field_1 = value_1,
         field_2 = value_2,
#ifdef MACRO
         field_3 = value_3
#endif
      };
```
      
It will cause error, we have to change it to: 

```
    headers.some_header = {
        field_1 = value_1,
        field_2 = value_2
#ifdef MACRO
        , field_3 = value_3
#endif
      };
```
      
This seems a bit ugly. Can we allow trailing comma to make P4 code more elegant in such situations? @smolkaj

**Comment by mbudiu-vmw** [comment]
The only language I know which does this systematically is Rust.
So we know it can be done. (Even in Rust, I don't think you can do it for all lists, e.g., generic type argument lists).
But it's not clear whether such a change can be performed without causing problems elsewhere (e.g., bison's grammar is very sensitive to changes which can introduce ambiguities).

**Comment by apinski-cavium** [comment]
The following locations seems they would be useful and where I had a hard time remembering when writing P4 when coming from a C/C++ background:
enum, match_kind and error definitions
tuple literals

Note C/C++ allows this too:
```
  struct t{
    int t;
    int t1;
};

void f(void)
{
  struct t t1 = {1, 2, };
  int t2[2] = {1, 2, };
}
// Even for enum definitions but only for C++11+ and C99+
enum e {
  a, b, 
};
```

**Comment by smolkaj** [comment]
+1 on this feature request, this has been a common source of frustration for us. @jonathan-dilorenzo can attest to that :)

Reiterating what @apinski-cavium said, C++ allows this (though I don't know if it supports it "systematically"), and so does Python. p4-constraints also supports something similar in the form of trailing `;`.
