### ISSUE TITLE
Add assert and assume extern functions to core.p4

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1207]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @thomascalvert-xlnx

## Design
- [X] **Document**: See this comment below https://github.com/p4lang/p4-spec/issues/1207#issuecomment-1351764302

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: Has been implemented for p4c BMv2 back end since 2019.  Moving definitions to core.p4 would require some changes to p4c that have not been done as of 2022-Dec-14.
## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**: 
- [ ] **Merged into `p4-spec`**: 
- [ ] **Merged into `p4c`**: 

=======================================

**Comment by jafingerhut** [comment]
Current status of extern functions `assert` and `assume` as of 2022-Dec:

+ 2019-Jun-18: Added to these include files in p4lang/p4c repo:
  + https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4
  + https://github.com/p4lang/p4c/blob/main/p4include/dpdk/psa.p4
  + https://github.com/p4lang/p4c/blob/main/p4include/bmv2/psa.p4

Proposed to be added to PNA in 2022.  This led to the question of "Is it reasonable to add it to core.p4 now?" instead of having it defined identically in v1model, PSA, and PNA architectures.

**Comment by jafingerhut** [comment]
If we add this to core.p4, one way would be to copy their current definitions from this psa.p4 include file into core.p4, with the comments: https://github.com/p4lang/p4c/blob/main/p4include/dpdk/psa.p4#L335-L400

Descriptions similar to these proposed for the PSA specification could be added to an appropriate section of the P4_16 language specification: https://github.com/p4lang/p4-spec/pull/1187/files

**Comment by apinski-cavium** [comment]
+1 from me

Note there might be some small backwards compatibility issue dealing with if someone had an out of tree arch definition which had those, they would need to resolve by removing them. Maybe having a feature preprocessor macro might help here.
Something like:
#define __p4_assume_assert 20221214

Similar to how C++ handles features in the language.

**Comment by thomascalvert-xlnx** [comment]
Another option could be to introduce a new include file for these (and log_msg). Something like `debug.p4` which could be optionally included by targets/programs wanting to use them.

(This would also make it easier to solve the issue raised by Andrew above.)

**Comment by jafingerhut** [comment]
Discussed at 2023-Jan-09 LDWG meeting.

The primary objection to adding a function like assert is that unless assert calls are completely removed from the program somehow (e.g. #ifdef'd out, deleted), the value of that expression must be possible to compute at that point in the execution flow of the output of the P4 compiler.  This is not what one wants when compiling for a high-performance target with significant fitting constraints.

Andy Fingerhut: One could imagine making a fine distinction where the compiler has a mechanism, before any significant optimization passes have been applied, where assert calls are removed before that point, which would make them effectively as if they had been #ifdef'd out or deleted from the source code.  That effectively makes such function names a bit more special than other functions that exist today.

A recommendation from Vladimir Gurevich: Come back to the LDWG with a proposal if we see 3 vendors implementing a feature like this in the same (or very similar) way.

Nate Foster agrees that it seems early for these to be in core.p4, and encourages P4 implementers to experiment and prototype these things and come together when we have multiple implementation experiences to share.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
