### ISSUE TITLE
Enhancement to P4 tables to enable "lookup" method with no side effects, and can be called from within P4 actions

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1209]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @thomascalvert-xlnx

## Design
- [ ] **Document**: 

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 
## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**: 
- [ ] **Merged into `p4-spec`**: 
- [ ] **Merged into `p4c`**: 

=======================================

**Comment by jafingerhut** [comment]
Origin and background of this issue:

I (Andy Fingerhut) have proposed the creation of externs called ExactMap and TernaryMap for addition to the PNA architecture, described here: https://github.com/p4lang/pna/pull/52

If you read that, you will note that they are very much like P4 tables in their behavior.  Their proposed control plane API is _exactly_ like P4 tables of a certain restricted form.  This is intentional, by design.

Why did I create that proposal, instead of simply using P4 tables?  For two reasons:

(a)

The P4 language spec does not support calling `table_name.apply()` from within the body of a P4 action.  See the last table in Appendix F of the language spec.  The cell at the row labeled "table" and the column labeled "action" contains "no", which is defined to mean: "A table cannot be apply'd from within the body of an action."

The P4 language spec _does_ support calling extern object methods from within the body of a P4 action.  See the same table mentioned above.  The cell at the row labeled "extern" and the column labeled "action" contains "yes", which is defined to mean: "An extern can be called from within the body of an action."

(b)

In the use case within Intel that motivated the definition of externs ExactMap and TernaryMap, it was useful to define something like a table, except it does not have side effects.  Instead, it simply returns a value.  Yes, you can create P4 tables with actions that only assign a value to a particular user-defined metadata field, and then use that user-defined metadata field in later code after apply'ing the table, which is very similar in effect, but syntactically it is different.  Semantically it is also different, in that if you as a P4 developer KNOW simply from looking at the definition of ExactMap and TernaryMap that their `lookup` method only returns a value, with never any side effects, that is a guarantee a P4 developer has when reading your code that such code has no side effects, which can be very useful in understanding code behavior.

So, naturally when proposing these externs ExactMap and TernaryMap, the question arose: "These look a lot like P4 tables, except for restriction (a).  What if we just removed restriction (a), and maybe generalized P4 tables to have an option like (b) while we are at it?"

I did raise the question in the language design work group during 2021 or 2022 (I forget exactly when) about removing restriction (a).  The initial reaction was "That seems like a pretty significant restriction to lift.  Do you really need it?", and I did not press the issue as the extern definitions do what I want.

One potential difference this time around is that if we add an option for P4 tables to have a restriction like (b), with a suggested syntax and semantics briefly described below, involving adding a new `table_name.lookup(key)` method to tables, perhaps people would be less worried if we kept restriction (a), but said "It is supported to call table_name.lookup(key) inside the body of actions."  That would be sufficient for the purposes I have, and would be fine with me if both of those things were done in the language spec.

Proposed addition of `lookup` method to some P4 tables.

(1) If a table has a property named `actions`, then it only supports `table_name.apply()` method calls, as defined in the language spec today.  No changes there.

(2) (new with this proposal, but there are other ways to do this, too, of course) A table is allowed to define a new table property `lookup_type = T;` where `T` is a type expression (e.g. `bit<16>` or `my_struct_type_t`).  A table is allowed to specify exactly one of `actions` or `lookup_type`.  It is an error to attempt to specify both for the same table.  If a table specifies `lookup_type`, then it is a compile-time error to attempt to invoke `table_name.apply()` on that table anywhere in the P4 program.  Instead you can invoke `table_name.lookup();` on such a table, and that method is defined to return a value of type `T`.  No P4 action will be executed as a result of calling `table_name.lookup()`.  It is explicitly allowed for `table_name.lookup()` calls to appear in P4 action bodies.

**Comment by mbudiu-vmw** [comment]
See https://github.com/p4lang/p4c/pull/2739 as well

**Comment by jfingerh** [comment]
"See https://github.com/p4lang/p4c/pull/2739 as well"

Thanks for adding that link.  It appears that proposed extern currently has no ways to give names for the fields of the key.  Do you see a way?

**Comment by mbudiu-vmw** [comment]
if they key is of a struct type there is one obvious way to do it

**Comment by apinski-cavium** [comment]
Link to previous discussion on this: https://github.com/p4lang/p4-spec/issues/840#issuecomment-873159650

**Comment by jfingerh** [comment]
"See https://github.com/p4lang/p4c/pull/2739 as well" I will let Thomas Calvert reply to this one if he is interested, but I suspect he would have the same reaction to it as he has to the ExactMap/TernaryMap extern definitions: These are so similar to P4 tables, why not generalize P4 tables so that they have the capabilities of the proposed externs?"

**Comment by jafingerhut** [comment]
@mbudiu-vmw Have you thought about how you might add something like `const entries` and/or the new non-const `entries` constructor parameters to your externs in https://github.com/p4lang/p4c/pull/2739 ?  It seems to me that supporting arbitrary match kinds leads to different parameters one needs to specify for the key matching data for each case, e.g. min/max value for range, value and prefix-length for lpm, value only for exact, etc. which doesn't seem to be easily expressible without something like a union type.

**Comment by mbudiu-vmw** [comment]
You can implement such lookups by having a single action that has a single out argument.
So you can convert lookup tables to traditional tables automatically.
We could even make the compiler do this automatically.
```
table t() { ... // no actions
}
apply {
   bit<32> leftValue = t.lookup(); // all lookup calls must return the same value
}
```

could be rewritten into:
```
action t_lookup(out bit<32> result, bit<32> value) { result = value; }

bit<32> leftValue;
table t() {
   actions = { t_lookup(leftValue); }
}
apply { 
     t.apply();
}
```

**Comment by mbudiu-vmw** [comment]
But this wouldn't allow actions to invoke tables.

**Comment by mbudiu-vmw** [comment]
I still think it's nicer to have a separate extern for maps.

**Comment by thomascalvert-xlnx** [comment]
Both https://github.com/p4lang/pna/pull/52 and https://github.com/p4lang/p4c/pull/2739 seem to be very similar. As such, I think that we should aim to not merge both, but instead come up with something flexible enough to address both needs.

Now the present issue is suggesting to implement this functionality as a new table attribute rather than a separate extern. Since these externs are so similar to existing tables, using the table syntax & constructs would be a friendlier programming experience. On the other hand, it does sound like externs would be easier to implement in the spec & toolchain, in particular when it comes to allowing lookups from within an action body (one of the drivers for this feature).

**Comment by mbudiu-vmw** [comment]
Tables are close, but not quite exactly the same thing. My intuition says that an extern is the right way to go.

**Comment by mbudiu-vmw** [comment]
Can we close this?

**Comment by jafingerhut** [comment]
I do not have any new arguments to bring forward in favor of this proposal that I have not already mentioned, so no objections from me to closing this issue.
