### ISSUE TITLE
@optional annotation wording is confusing

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1211]
The current wording is:
```
A parameter to a package, parser type, control type, extern method, extern function or extern object constructor can be annotated with @optional to indicate that the user does not need to provide a corresponding argument for that parameter. The meaning of a parameter with no supplied value is target-dependent.
```
Is it only the parameters of the type or can it be on parser or control declarations' arguments too?
I had assumed it was only valid for arguments of the type themselves and not declarations.
That is:
```
control g(@optional inout bit t)
{
  apply { t = t + 1;}
}
control h()
{
  g() y;
  apply { y.apply(); }
}
```
Would be invalid.

```
control g(@optional out bit t);
control h()(g y)
{
  apply { y.apply(); }
}
```
Should be valid. But then does it make sense?
Reference to where this was added to the spec: https://github.com/p4lang/p4-spec/pull/987

Even the last example in that pull request means the backend can and should reject the package if it violates their understanding if the paramater is not optional or not.

Reference to some P4C bugs I found while starting to implement `@optional` support to the Marvell compiler:
https://github.com/p4lang/p4c/issues/3814
https://github.com/p4lang/p4c/issues/3813

The way I would have allowed matching of an optional paramater for a control type would be:
```
control C(@optional inout bit<8> x);
control D(inout bit<8> x);
package P(C c, D d);

control MyY(inout bit<8> x) { apply { } }
control MyZ() { apply { } }
P(MyZ(), MyY()) main;
```
That is allow `@optional` only on the type and not the declaration.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
