### ISSUE TITLE
Add expression to represent an invalid header_union value

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1215]
This issue is identical in motivation as this earlier issue and PR: https://github.com/p4lang/p4-spec/pull/1184 except that this issue is to ensure that invalid headers can be written with a header_union type.

**Comment by apinski-cavium** [comment]
We should most likely also add header union expressions.
There only allows one key/value pair. e.g.:
```
header H1 { bit t; }
header H2 { bit<2> t; }
header_union HU { H1 h1; H2 h2; }

HU f()
{
  return (HU){h1 = {1w1}};
}
HU f1()
{
  return (HU){h2 = {2w1}};
}
```
If there is more than one, then the expression is invalid.

**Comment by mbudiu-vmw** [comment]
This should probably be a new issue

**Comment by jafingerhut** [comment]
Agreed with Mihai that I would appreciate if the syntax for an arbitrary value of a header union type was a separate issue.  The reason for my preference is that the sooner we have syntax for invalid headers and a handful of other things, the sooner we can have a complete implementation of `...` default value syntax in the implementation.

That said, I am also perfectly happy if we have a _partial_ working implementation of `...` syntax even earlier, even if it gave a compile-time error if the `...` was for a header union type or a compound type that contained one (not sure whether such a partial goal motivates anyone for implementing that in p4c, though -- it does seem likely to cover a large fraction of desired use cases, though, since use of header unions is somewhat uncommon).
