### ISSUE TITLE
Loose description of implicit cast

### ISSUE THREAD

**Issue by pataei** [p4lang/p4-spec#1223]
# Summary
Implicit cast insertion is partially specified in the spec but many of the details are left up to implementers. Type equality and type inference have received similar treatments. This means that two different compilers may insert implicit casts differently, which will affect the portability of programs between different P4 type checkers. The spec should avoid this.

P4 spec handles implicit cast haphazardly which takes the following shapes throughout the spec:
* Instead of spelling out where and how implicit cast occurs, it just hints at it. 
* It doesn’t use consistent language to describe implicit cast. For example, sometimes it uses (automatic) conversion instead of implicit cast. 
* The description of the implicit cast is very limited, it only discusses implicit cast when binary operations are used or when it comes to enums. However, these are absolutely not the only cases where implicit cast occurs. 

Addressing these issues will require addressing similar issues with type inference and [type equality](https://github.com/p4lang/p4-spec/issues/875), which are related to implicit casts. Inference may solve constraints between types and type variables by inserting casts. Type equality comparisons are often (but not always!) meant to check type equality modulo implicit casts.

## Examples 
We provide various examples for each of the problems.
### Not spelling out implicit cast when it occurs
* [Assignment](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-assignment). P4 spec states: "An assignment, written with the = sign, first evaluates its left sub-expression to an l-value, then evaluates its right sub-expression to a value, and finally copies the value into the l-value. Derived types (e.g. structs) are copied recursively, and all components of headers are copied, including “validity” bits. Assignment is not defined for extern values."
This explanation doesn't say anything about inserting an implicit cast on the RHS to match the type of the LHS of an assignment. However, P4 spec has lots of examples in various subsections of needing to cast the RHS of an assignment. For example, in [Section 8.12](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-list-exprs) P4 spec states that "A list may be used to initialize a structure if the list has the same number of elements as fields in the structure. The effect of such an initializer is to assign the nth element of the list to the nth field in the structure:" Here, for the assignment to type check, an implicit cast from list to struct has to be inserted. 
```
struct S {
    bit<32> a;
    bit<32> b;
}
const S x = { 10, 20 }; //a = 10, b = 20
```
* [Enum type declaration](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-enum-types). P4 spec doesn't say anything regarding inserting an implicit cast for the initializers of an enum's fields. However, in some examples, this scenario seems to be legal:
```
enum bit<8> FailingExample {
  first           = 1,
  second          = 2,
  third           = 3
}
```
* [Operations on structure-valued expressions](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-structure-expressions). Similarly, as mentioned in #953, it is important to recognize when assigning lists to structs a recursive insertion of implicit cast is allowed, such as the one needed in the following example which is taken from P4 spec:
```
struct S {
    bit<32> a;
    bit<32> b;
}
S s;
// Compare s with a structure-valued expression
bool b = s == (S) { a = 1, b = 2 };
```
### Inconsistent language
P4 spec uses implicit cast for types and conversion for values of types. However, this can be misleading in some places. For example, in [section operations on list](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-list-exprs), it gives the following example and states that "A list expression can have an explicit structure or header type specified, and then it is converted automatically to a structure-valued expression". However, what P4 spec states as _automatically converted_ is in reality inserting an implicit cast. Using consistent language throughout the spec would help P4 developers and researchers. 
```
struct S {
    bit<32> a;
    bit<32> b;
}

extern void f<T>(in T data);

f((S){ 10, 20 }); // automatically converted to f((S){a = 10, b = 20});
```
As another example, in [Section 8.13](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-structure-expressions) P4 spec states that "For a structure-valued expression typeRef is the name of a struct or header type. The typeRef can be omitted if it can be inferred from context, e.g., when initializing a variable with a struct type. The following example shows a structure-valued expression used in an equality comparison expression:"

```
struct S {
    bit<32> a;
    bit<32> b;
}

S s;

// Compare s with a structure-valued expression
bool b = s == (S) { a = 1, b = 2 };
```

### Limited list of implicit cast
As discussed in the examples above, the implicit cast of list/record to struct/header is missing from the discussion of implicit cast in the spec, see [Implicit cast](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-implicit-casts).

## How to fix
* Spell out where an implicit cast is inserted.
* Use consistent language. Instead of saying "a is automatically converted to b", say "an implicit cast inserted to convert a to b".
* Provide a type inference and type equality algorithm. The lack of clarity of when an implicit cast is inserted is partly due to the spec missing a type inference and type equality algorithm. More specifically, P4 spec only hints at the fact that type inference happens (see [constructor invokations](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-constructor) and [example architecture program](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-target-instantiation)) but doesn't provide any details of when and how it happens. Having a clear type inference algorithm is especially important for constructor/method/function invocation/call. Having such an algorithm also clears up all possible implicit casts as well. 

Smaller steps to address this issue:
- [x] Replace all automatic conversions with implicit cast or the insertion of an explicit cast. State that this can happen while type checking or as a pass beforehand. E.g., p4c does this at the same pass as type checking.
- [ ] Add exactly where an implicit cast occurs. This includes 
  - [x] Assignment
  - [x] Enum type declaration 
- [ ] Complete the list of legal explicit casts. 
  - [x] tuple --> struct. tuple --> header.
  - [ ] tuple --> record ?
  - [ ] We need record types. I'll create a PR for adding record types to synthesized types.
  - [ ] I noticed lists have been added to P4. So we need to see what kinds of casts we allow from and to lists. 
- [x] Expand the implicit cast section. Also, states that when needed, implicit cast will occur recursively.

**Comment by mbudiu-vmw** [comment]
Great list. Can you help us remedy some of these problems?

**Comment by pataei** [comment]
Absolutely. Having a clearer spec is one of our goals for formalizing the spec. Maybe we discuss this more in today's LDWG meeting, I believe Nate added this to the agenda.

**Comment by pataei** [comment]
I'll leave type equality and type inference for later. However, they may require more additions/revisions to this issue's todos.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
