### ISSUE TITLE
Reason for limiting fixed-length types to have a constant width

### ISSUE THREAD

**Issue by pataei** [p4lang/p4-spec#1228]
I'm wondering why P4 spec forces `bit<W>` or `int<W>` in some places, such as when they're used as [the underlying type of a serializable enum](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-enum-types) or as [the element type of a header](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-type-nesting). Why doesn't it just require a compile-time-known expression instead of a constant?

Also, does the use of `W` in spec always indicate a constant?

**Comment by vgurevich** [comment]
@pataei  -- compile-time-known expressions are supported as long as you enclose them in parentheses. See Section 7.1.6.2 in the spec.

**Comment by mbudiu-vmw** [comment]
it should be a compile-time known value in the spec.

**Comment by pataei** [comment]
To double check my understanding, as an example, so there isn't anywhere in P4 that allows only `bit<4>` and not `bit<(2+2)>`?

**Comment by mbudiu-vmw** [comment]
These two should be fully equivalent and can be used in the same contexts. See also #1213

**Comment by pataei** [comment]
Closing this after the merge.
