### ISSUE TITLE
Sum QoS throughout 

### ISSUE THREAD

**Issue by guy-davidi** [p4lang/p4-spec#1229]
Hi,

I'm trying to assign a value to each packet, and eventually I want to hold a counter that sums this value for every packet that passes through my switch. ( I want to measure the throughput kind of)
I tried reading and implementing the code in the specification file but it didn't work for some reason.

Note I use DPDK as switch - psa arch.
```

action update_pkt_count (inout bit<8> counter, in psa_ingress_output_metadata_t ostd )
{	
	counter = counter + (bit<8>)ostd.class_of_service;
}

control ingress(
	inout my_ingress_headers_t hdr,
	inout my_ingress_metadata_t meta,
	in psa_ingress_input_metadata_t ig_intr_md,
	inout psa_ingress_output_metadata_t ostd
)
{

	Register<bit<8>, bit<8>>(5) reg_counter;

	/*
	 * If got match -> egress
	 * to port 1 else drop
	 */
	action send(PortId_t port, ClassOfService_t class) {
		bit<8> tmp;
		
		tmp = reg_counter.read(0);
		update_pkt_count(tmp, class);
		reg_counter.write(0, tmp);

		ostd.egress_port = (PortId_t) port;
		ostd.drop = false;
		ostd.class_of_service = (ClassOfService_t) class;


	}
```

**Comment by jnfoster** [comment]
Hi Guy,

Good question! However, this is the repository for the P4 Language Specification. We mostly use it to track issues related to the definition of the language, and develop new features. Can I recommend asking your question on the [P4 Forum](https://forum.p4.org) instead?

**Comment by guy-davidi** [comment]
Sure, thsnka

**Comment by guy-davidi** [comment]
https://forum.p4.org/t/sum-qos-throughout/648
