### ISSUE TITLE
Rationale for allowing 0-width type `bit<0>` ?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1252]
I know I was there in the P4 language design work group meetings where this was discussed.  I had no objections at the time, and I still don't actually have any objections.  I do have a few questions, though:

+ Has anyone used a type `bit<0>` in a P4 program for something?  If yes, what for?
+ If not, can you imagine a situation where it seems useful?

I am not sure, but my guess is that the primary reason for making a change to the spec to allow type `bit<0>` was along the lines of: well, we support structs and header type with no member fields, and tuples with 0 members, why not type `bit<0>`, also?

One of my reasons for asking is in thinking about whether it is considered important to make changes to the P4Runtime API specification to allow values of type `bit<0>` in control plane API messages, or whether to simply say "that type is not supported in the P4Runtime API": https://github.com/p4lang/p4runtime/issues/428

**Comment by mihaibudiu** [comment]
For exeample 
```
#define WIDTH 0 
struct H { bit<WIDTH> field; }
```

**Comment by jafingerhut** [comment]
Thanks, Mihai, for the example.

Are you intending that as an example of something you have found useful to include in a P4 program before?

Or is it more along the lines of: "I (Mihai) would guess that someone might find code like this useful?"

**Comment by jnfoster** [comment]
I think the point is that you might write a program with a macro that gets filled in according to a profile or configuration. If the value of the macro determines the width of a bitstring, and can assume the value `0`, then having `bit<0>` may be useful. (It would be even better if the compiler optimized the code aggressively, so there was zero cost for using that feature instead of `#ifdef`-ing the code away by hand.)

**Comment by chrispsommers** [comment]
Thanks for the explanations. That makes sense: widths of zero might be the outcome of some profile, not so much a goal as much as a consequence.

**Comment by jnfoster** [comment]
Do we keep this open? Or has it converged?

**Comment by jafingerhut** [comment]
I think the issue has served its purpose of asking and answering the question.  I will close it now.
