### ISSUE TITLE
Streaming the payload

### ISSUE THREAD

**Issue by Dawoodoz** [p4lang/p4-spec#1266]
It would be very useful to have access to the remaining input data after parsing, so that one can process the payload a few pieces at a time using multiple FPGA pipelines. Extract a block from the remaining input and emit a block of the same or varying size for encoding, encrypting or compressing on the link layer.

The hardware would be placed next to the parser to allow looping, but execute after deparser, with a communication to the deparser for emitting payloads and adding them to the Ethernet checksum.

ProcessPayload(packet_in input, packet_out output, in headers) {
    block_t data;
    input.extract(data);
    if (isValid(input)) {
        // Add input to each pipeline while it is still processing old requests
        thread (
            process(data.pipelineA);,
            process(data.pipelineB);,
            process(data.pipelineC);,
            process(data.pipelineD);
        , output.emit(data););
        // Go to the next block while the pipelines are running
        transition repeat;
    } else {
        WaitForPipelines;
        transition done;
    }
}

The Pipeline objects would be collections of functions processed in steps and storing intermediate results in FPGA registers to allow using a high frequency and not stall too much. They would only have read access to the shared header and must flush out all results before another header may be connected.

Model:
Parser
VerifyChecksum
Ingress
Egress
ComputeChecksum
Deparser
ProcessPayload

This would not be able to merge or split packets, but maybe a better suggestion can be functionally complete.

**Comment by jnfoster** [comment]
Thanks for the comment. 

There are many ways to model packet data, its operations, and their restrictions in a P4 program. But I don't believe the question of whether the packet is available in the pipeline is a P4 language issue -- it's really a matter for architectures to figure out. 

This repository is primarily for work on the language specification. So I'm going to close this issue. But I encourage you to discuss this capability on the [P4 Forum](https://forum.p4.org/) and, if there is interest in fleshing it out, coming back with a concrete proposal for an architecture that implements the desired functionality.
