### ISSUE TITLE
L-Value Syntax

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#1273]
The current spec provides the following definition (section 6.7):
```
prefixedNonTypeName
    : nonTypeName
    | dotPrefix nonTypeName
    ;

lvalue
    : prefixedNonTypeName
    | lvalue "." member
    | lvalue "[" expression "]"
    | lvalue "[" expression ":" expression "]"
    ;
```
This is fine overall, but as one can notice, it does **not** allow parentheses. In other words:
```
a = 1;
```
is OK, but
```
(a) = 1;
```
is not.

This is a minor issue, but it gets confusing for the people that are used to define their C preprocessor macros "defensively" by putting parentheses around the parameters just in case. As a result, macros, defined that way work as R-values, but not as L-values. Here is an example where it hurts:
```
#define DEVPORT_PIPE(port) ((port)[8:7])
```
The macro above should be usable both as the R-value and L-value, but it isn't. (Yes, I know, these macros are not officially allowed, but everyone uses them, since they are not disabled either :) )

I do not know what's the story there. Perhaps it was done in such a way to eliminate the ambiguity in the grammar. In that case, it's just a minor annoyance that we can accept. 

On the other hand, if there is no specific reason to not allow parentheses in L-values, perhaps we should.

**Comment by jnfoster** [comment]
This seems to be fine. I've made a quick patch.

**Comment by jnfoster** [comment]
This has been merged into the compiler. @vgurevich will you write a PR on the spec?

**Comment by vgurevich** [comment]
@jnfoster -- done. And thanks again. Would you like to review it first?
