### ISSUE TITLE
Incomplete list of operators in compile-time known values section?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1283]
One of the list items in the section 18.1 "Compile-time known values" says:

```
The following expressions (+, -, *, / , %, !, &, |, &&, ||, << , >> , ~ ,  >, <, ==, !=, <=, >=, ++, [:], ?:) when their operands are all compile-time known values.
```

I have not scrubbed thoroughly to see if there are other operators missing from that list, but at least the saturating arithmetic operators `|+|` and `|-|` are not included.

I am guessing that is an oversight, rather than an intentional omission.

**Comment by jnfoster** [comment]
Yes, and this is fixed in #1213. We should merge that PR...
