### ISSUE TITLE
The type nesting and typedef rules are not clear

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4-spec#1285]
The tables in (v1.2.4 spec) [sec 7.2.8 type nesting rules](https://p4.org/p4-spec/docs/P4-16-v1.2.4.html#sec-type-nesting) obviously contain two kinds of "objects" in the "element type"/"base type B".

- actual types (possibly generic), like `int`, `bit<N>`, `bool`
- categories of types defined with specific construct: header, header stack, header union, struct, ...

It would be nice to re-word this so that this distinction is clearer as it can lead to some confuction.

For example, one could interpret the `match_kind` line in the second table as "it is imposible to do `typedef match_kind foo`", or one could interpret it as "one can't apply `typedef` to the match kind values (like `typedef lpm foo`)". I presume the second is what was intended and indeed in P4C, `typedef match_kind foo` works, which, while not useful, seems consistent to me (and `typedef lpm foo` does not work). But this interpretation contrasts with what that line means for e.g. `bit<N>`. Obviously there we are saying that `typedef bit<42> foo` is possible, not that `typedef 8w42 foo` is possible. Or possibly the spec is actually suggesting that `typdef match_kind foo` should not be accepted, in which case we have a bug in the compiler.

But in general I believe it would be clearer to have the first column contain things like: `bit<N>`, `int`, "header types"/"headers", "header stacks", "structures", etc. Maybe with some explanation that we mean e.g. all types defined with the `header` keyword.

**Comment by jafingerhut** [comment]
@vlstill Would you like to take a shot at a proposed PR that would make the result as clear as you would have liked to find?

**Comment by jafingerhut** [comment]
And if the compiler accepts `typedef match_kind foo`, I am not sure how that could possibly ever be useful.  Do you?

**Comment by vlstill** [comment]
> And if the compiler accepts `typedef match_kind foo`, I am not sure how that could possibly ever be useful. Do you?

OK, so the intention was to not allow `typedef match_kind foo`, right?

I don't think it would *useful*. I am just saying it would be somewhat consistent as `match_kind` is a type (and even has values, unlike `void`, although note that both C and C++ allow `typedef` even for `void`). I am not sure what can be done with `match_kind` though, it can't even be used as a constructor parameter of a control and then used in the control.

**Comment by jafingerhut** [comment]
The table with "Base type B" in the leftmost heading I thought should be clear that all of those are _types_, not _values_, because `typedef B <name>` is only defined to have a meaning where `B` is an expression denoting a type.  That is explained in the section defining what `typedef` does, so it seems redundant to repeat it in that table.

**Comment by jafingerhut** [comment]
Technically, even `bit<N>` is not one type, but many.  Just as `header` in that table refers to many types, not one.
