### ISSUE TITLE
[proposal] Syntactic sugar for constructors

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4-spec#129]
> This proposal refines Item 1 in #125.

# Problem

Names of parser/control definitions and instances must be distinct.  When a definition is instantiated only once, this leads to boilerplate code in the beginning of a block:

```p4
// Control definitions.
control c1(...) { ... }
control c2(...) { ... }
control c3(...) { ... }

control main_c(...) {
    // Control instantiations.
    c1() do_c1;
    c2() do_c2;
    c3() do_c3;
    apply {
        do_c1.apply(...);
        do_c2.apply(...);
        do_c3.apply(...);
    }
}

V1Switch<H, M>(..., main_c(), ...) main;
```

For large programs, eg. switch.p4, there may be many controls instantiated once in a top-level control, and the list of control instantiations---with names like "do_X"---can be quite long.

This example uses controls, but the same problem arises for parsers.

# Proposal

Add syntactic sugar to ease the case where a parser/control is only instantiated once.  With no constructor parameters, this:

```p4
control c1(...) { ... } 
```
is considered equivalent to this:

```p4
control c1_t(...)() { ... }
c1_t() c1;
```

where the name `c1_t` is not used elsewhere in the program.

# Examples

Under this proposal, there would be three ways to define parsers/controls.

```p4
// No constructor arguments, so c1 can be used as a literal in later controls.
control c1(...) { ... } 

// With constructor arguments, objects have to be instantiated by data constructor.
control c2(...)() { ... }
control c3(...)(...) { ... }

control c4 ( ... ) {
    c2() my_c2;
    c3(...) my_c3;
    apply {
        c1.apply(...);
        my_c2.apply(...);
        my_c3.apply(...);
    }
}
```

The first example would now look like:

```p4
// Control definitions.
control c1(...) { ... }
control c2(...) { ... }
control c3(...) { ... }

control main_c(...) {
    apply {
        c1.apply(...);
        c2.apply(...);
        c3.apply(...);
    }
}

V1Switch<H, M>(..., main_c(), ...) main;
```

**Comment by jnfoster** [comment]
Closing after discussion with Cole.
