### ISSUE TITLE
[proposal] Remove generics from parsers/controls

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4-spec#131]
> This issue refines Item 3 in #125.

## The problem

It's unclear how to use the ability to define generic parsers and controls as currently defined.  Consider the following control.

```p4
control c<T> (T foo) {
    // What can you do with foo?
}
```

Because the type parameter `T` can range over any type, the only operations available on terms of type `T` are those operations defined for *every* type.  In practice, that includes:
* assigning `foo` to another variable of type `T`, and
* passing `foo` to a generic extern function or constructor.

You can't even use `foo` as a key, because there are some types, like structs, that are not valid keys.

Presumably, we would like the ability to say that `T` is, say, a numeric type, which would enable us to perform numeric operations on values of type `T`.  However, it's unlikely that we can add these kinds of type constraints to the language in the short term.  

## Proposal

We should remove the ability to define generic controls and parsers.  This will reduce the complexity of the language and the compiler, at the cost of being able to wrap generic externs in generic controls.

Note that this proposal is *not* to remove generics entirely.  Externs and architectures will still have generic types.  Intuitively, this is possible because the *implementations* of these things are outside the P4 language and are not bound by the P4 type system.

## Examples

This proposal only removes things from the language, so there are no examples of new features in use.  However, here is an example of a previously valid program that would no longer be valid:

```p4
// Generic externs remain valid.
extern Foo<T> { ... }

// But wrapping a generic extern in a generic control is no longer valid.
control c<T> {
    Foo<T> f;
    apply { f(); }
}
```

Instead, one would need to specify a particular type when instantiating the extern:

```p4
extern Foo<T> { ... }

control c {
    Foo<bit<8>> f;
    apply { f(); }
}
```

**Comment by jnfoster** [comment]
Can this be closed?
