### ISSUE TITLE
Question for implicit cast in table action

### ISSUE THREAD

**Issue by wooyechan** [p4lang/p4-spec#1310]
I have a question about implicit cast in table action.

In P4 spec, I saw P4 example code below.

action a_params(bit<9> x) { standard_meta.egress_spec = x; }
/* omitted */
const entries = {
(0x01, 0x1111 &&& 0xF) : a_params(1);
It seems implicit cast is allowed for action arguments. But I couldn't find description for this. I found this instead.
At 8.20. Method invocations and function calls,

The compiler only inserts implicit casts for direction
in arguments to methods or functions as described in Section 8.11. The types for all other arguments
must match the parameter types exactly.

So, even though action is a kind of function, does it not follow that explanation, but it allows implicit cast for all arguments?

**Comment by jafingerhut** [comment]
Section 8.20, as implied by its title, is restricting its attention to method calls and function calls, and does not have anything to say about action calls.

See Section 8.11.2, where it says:

"To keep the language simple and avoid introducing hidden costs, P4 only implicitly casts from int to fixed-width types and from enums with an underlying type to the underlying type."

In the example you show, `1` has type `int`, and it is being implicitly cast to a fixed-width type, `bit<9>` in your example.

**Comment by wooyechan** [comment]
I got confusion between action calls and function calls. Thank you for ypur answer!
