### ISSUE TITLE
Clarification on directionless action arguments behaving like direction in

### ISSUE THREAD

**Issue by jaehyun1ee** [p4lang/p4-spec#1350]
The spec mentions about directionless action arguments:

> For an action, a directionless parameter indicates that it is “action data”. See Section [14.1](https://p4.org/wp-content/uploads/2024/10/P4-16-spec-v1.2.5.html#sec-actions) for the meaning of action data, but its meaning includes the following possibilities:
>- The parameter's value is provided in the P4 program. In this case, the parameter behaves as if the direction were in.

The phrase "behaves as if the direction were `in`", I believe, is not quite clear, particularly regarding compile-time known-ness.

The differences between an `in` parameter and a directionless parameters, aside their copy-in/out semantics, is:
- `in` can be implicitly cast, while directionless cannot (as per the current spec)
- directionless argument should be compile-time known, while no such restriction exists for `in` argument.

**So, I wonder if "behaves as if the direction were `in`" also imply that the directionless arguments supplied to actions in a P4 program (not by the control plane) need *not* be a compile-time known value?**

Relevant to this issue, [`issue473.p4`](https://github.com/p4lang/p4c/blob/main/testdata/p4_16_errors/issue473.p4-stderr) in the p4c test suite is expected to be rejected by the frontend.

```p4
action b(inout bit<32> x, bit<8> data) {
    meta.a = meta.a ^ (bit<4>) x ^ (bit<4>) data;
}
table t1 {
    key = { hdr.ethernet.srcAddr : exact; }
    actions = { b(meta.c); }
    default_action = b(meta.c, (bit<8>) meta.d);
}
```

```plaintext
issue473.p4(70): [--Werror=type-error] error: (bit<8>)meta.d: action argument must be a compile-time constant
        default_action = b(meta.c, (bit<8>) meta.d);
                                   ^^^^^^^^^^^^^^^
```

**Comment by jafingerhut** [comment]
Would it address your question fully if we were to replace this text of the spec:

```
The parameter's value is provided in the P4 program. In this case, the parameter behaves as if the direction were in.
```

with something like the following?

```
The parameter's value is provided in the P4 program. In this case, the parameter behaves as if the direction were in, with the restriction that arguments must be compile-time known.
```

**Comment by jaehyun1ee** [comment]
Yes, I think it addresses my question :) Would it be alright if I create a PR based on your suggestion?

**Comment by jafingerhut** [comment]
Certainly.  Please do.

**Comment by jaehyun1ee** [comment]
I just found out that I overlooked the spec saying:

> For an action, a directionless parameter indicates that it is "action data". See [Section 14.1](https://p4.org/p4-spec/docs/p4-16-working-draft.html#sec-actions) for the meaning of action data, but its meaning includes the following possibilities:
>    - The parameter’s value is provided in the P4 program. In this case, the parameter behaves as if the direction were in. Such an argument expression need not be a compile-time known value.

So it was stated that a directionless action argument need *not* be compile-time known.
Seems like the test program wasn't in line with the current spec.

**Comment by jafingerhut** [comment]
It is a small enough detail that it is easy to miss (I did in my comment above -- good that you found it later).  Perhaps it would be more appropriate to file a bug against p4c, then, if it does not follow the spec?

**Comment by jaehyun1ee** [comment]
I believe so. Closing in favor of [p4c issue](https://github.com/p4lang/p4c/issues/5042)!
