### ISSUE TITLE
[proposal] Require unambiguous names

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4-spec#138]
> This proposal refines #107 and Item 5 in #125.

There are three parts to this proposal:
1. Extending P4_16 to explicitly assign names to keys.
1. Extending P4_16 to explicitly assign names to actions.
1. Clarifying how control plane names are generated from a P4_16 program.

The dominant motivation is this: Control plane names should be unambiguously derived from the structure of every P4_16 program, but this is not currently the case.

## Problem

Although the implementation of the control plane API is outside the scope of the P4_16 specification, the specification of control plane *names* is not: See [Section 16.3](http://p4.org/wp-content/uploads/2016/12/P4_16-prerelease-Dec_16.html#sec-cp-names).

It is currently possible to write a P4_16 program without clear names.

```p4
control c(inout bit<8> x) {
    table t() {
        keys = { x[3:0] : exact; x[7:4] : exact; }
        actions = { ... }
    }
    apply { t.apply(); }
}
```

How does the control plane refer to the keys of the table `t`?  Currently, the compiler generates names for these, which is brittle and unintuitive.

### Secondary problem

As #107 points out, the ability to assign names to actions makes some corner cases of the language simpler.  If we're adding names to keys, we should do the same for actions, both for uniformity and for the reasons in #107.

## Proposal

Extend the syntax to allow for explicitly assigning names to keys and actions:

```p4
control c(inout bit<8> x) {
    action a(bit<8> y) { x = y; }
    table t() {
        keys = { 
            k1 = x[3:0] : exact; 
            k2 = x[7:4] : exact;
        }
        actions = {
            a;
            clear = a(0);
        }
        default_action = clear;
    }
    apply { t.apply(); }
}
```

Name assignments are always allowed but only mandatory when the name is otherwise ambiguous.  For example, this is allowed:

```p4
action a() { ... }
actions = { a; }
```

And it desugars to this:

```p4
action a() { ... }
actions = { a = a; }
```

# Controllable entities

There are four kinds of things that can be controlled and thus need names:
* tables
* keys
* actions
* externs

A controllable entity is hence an instance of a table, key, action, or extern.  A fully qualified name uniquely identifies a controllable entity.

### Algorithm for generating fully qualified names

This will enable a simple algorithm for computing fully qualified, unambiguous control plane names from the structure of the P4_16 program.

Intuitively:

> A fully qualified name is for any controllable entity is its local name prepended with the fully qualified name of its enclosing namespace.

Specifically:

1. For each table, keys and actions use the names assigned to them, if present.  If not, they use the name of the action/key if unambiguous.  Otherwise the program is rejected.  The fully qualified name of a key or action is its local name prepended with the fully qualified name of its enclosing table.
1. Table names must be unique within a control.  Fully qualified table names are table names prepended with the fully qualified name of the control instance.
1. Extern local names must be unique in their namespace.  The fully qualified name of an extern instance is its local name prepended with the fully qualified name of its enclosing scope.
1. In the case where an extern is supplied as a parameter, the formal parameter name is considered the local name of the extern, and its fully qualified name is derived as above.
1. Control/parser instances take the names of the variables to which their instances are assigned.  The only anonymous instantiation allowed is in package instantiation, in which case the names of the instances are the corresponding formal parameter names of the package.

### Aliasing

Note that more than one name may refer to the same thing.  For example:

```p4
// Architecture:
control C (header_t h);
package Arch(C c);

// Program:
control c (header_t h) {
    action a() { }
    table t1 {
        keys { h.f; }
        actions { a; }
    }
    table t2 {
        keys { h.f; }
        actions { a; }
    }
    apply { t1.apply(); t2.apply(); }
}

Arch(c()) main;
```

This program has the following fully qualified names:
* Tables: `c.t1` and `c.t2`
* Keys: `c.t1.k1` and `c.t2.k2`
* Actions: `c.t1.a` and `c.t2.a`

Note that `c.t1.a` and `c.t2.a` refer to the same action but reflect that `a` is used in two different tables.

## Examples

Consider the example above, extended with a package definition and instantiation.
```p4
control C_In (inout bit<8> x);
package P(C_in package_c);

control c(inout bit<8> x) {
    action a(bit<8> y) { x = y; }
    table t() {
        keys = { 
            k1 = x &&& 0x0F; 
            k2 = x &&& 0xF0; 
        }
        actions = {
            a;
            clear = a(0);
        }
        default_action = clear;
    }
    apply { t.apply(); }
}

P(c()) main;
```

The fully qualified (absolute) names generated from this program are:
* Tables: `package_c.c.t`
* Keys: `package_c.c.t.k1, package_c.c.t.k2`
* Actions: `package_c.c.t.a, package_c.c.t.clear`

### Externs as parameters

Rather than defining an extern constructor, some architectures may instead require that users supply controls and parsers parameterized on extern types.  Intuitively, this implies that the architecture will supply a fixed supply of extern instances directly as arguments, rather than allowing the P4 programmer to instantiate externs directly.

```p4
// Architecture:
extern ArchExtern {
    bit<9> get();
}
control ArchC(ArchExtern e, standard_metadata_t m);
package Arch(ArchC c);

// Programmer-supplied P4 program:
control MyArchC(ArchExtern e, standard_metadata_t m) {
    action write_e_to_m() { m.egress_spec = e.get(); }
    apply { write_e_to_m(); }
}

Arch(MyArchC()) main;
```

This file generates only one controllable entity name: `c.e`.

**Comment by jnfoster** [comment]
Closing after discussion with @cole-barefoot
