### ISSUE TITLE
Example illegal default_action looks like it should be legal

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#142]
Section 12.2.1.3 "The default action"

The examples for legal and illegal settings of default_action contains
the following two lines:

    default_action = a(5); // OK - no control-plane parameters
    // default_action = a(z); – illegal, a’s x parameter is already bound to 5

If the second line were given all by itself for the example table, it
looks like it should be legal to me.  Why is it marked as illegal?

EDIT: I think I may understand the example now.  The second line has nothing to do with the first line.  The second line is illegal because the x parameter is already bound to 5 in the earlier example 'actions = { a(5); ... }' code snippet, and the default_action in/out/inout parameter values must agree with the ones in the actions.  If that is the reason for the example, feel free to close this issue without any changes.

**Comment by jnfoster** [comment]
Can this be closed?

**Comment by jafingerhut** [comment]
As far as my investigation into this has gone, I haven't found anything incorrect in the spec.  My initial understanding of the examples was wrong.
