### ISSUE TITLE
Global instances

### ISSUE THREAD

**Issue by cole-barefoot** [p4lang/p4-spec#150]
The issue of global instances---i.e. top-level control or parser instantiation---came up at the LDWG meeting on Monday, March 27th, 2017.

## The Problem

What should the P4_16 spec say about global instantiation, if anything?  Here are some situations to consider.

1. If a control is instantiated at the top level but (a) not used in another control, and (b) not passed as an argument to a package, then is that instance dead code?  Can the control plane install rules to its tables?

1. If a control or parser is instantiated at the top level and used exactly once in another control or parser, is this equivalent to instantiating it locally in the namespace where it is used, and can the compiler inline it?

1. If a control or parser is instantiated at the top level, can it be used more than once?  Does this differ from how a control or parser instantiated locally (inside another control or parser) can be used?

**Comment by jnfoster** [comment]
Do we need to revisit this issue at the 5/8 meeting? We've now resolved #129 differently.

**Comment by jnfoster** [comment]
Closed by #197
