### ISSUE TITLE
Action calls from parsers

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#151]
Can parsers directly call actions?

**Comment by jnfoster** [comment]
@jafingerhut I think we resolved not to take this and think about adding proper functions down the road. If you agree, can we close this? If not, let's update the spec?

**Comment by jafingerhut** [comment]
@jnfoster I am perfectly fine with either of these: (a) rename this issue as 'Add functions to P4' and mark it as post P4_16, (b) close this issue and create a new one for adding functions to P4.

**Comment by jnfoster** [comment]
Tagged as post P4_16.
