### ISSUE TITLE
Is default_action required or not?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#160]
The latest spec seems inconsistent on this.  Early in section 12.2.1.3 it says:

    this property [default_action] must be present for all tables.

Later in that same section it says:

    If the user does not specify a value for the default action, the runtime behavior of the
    program is undefined until the control-plane initializes the default_action to one of
    the legal values. The compiler should produce a warning in this case.

If default_action must be present, then the later statement should be removed.  If the later statement is true, then the earlier phrase should be removed.

In case it matters, the 2017-Apr-08 compiler behavior for both p4test and p4c-bm2-ss is to warn about a table with no default_action, but no error.

**Comment by vgurevich** [comment]
I think we need to do the following (as was discussed at the last meeting):

1. If default_action is not specified, let's make the default to be NoAction(). It will also be the default action in case the default_action attribute is  specified in a manner that is not fully resolvable at the compile-time. 
   -- The rationale: this is by far the most typical case and we do not want to burden people with the requirement to specify NoAction() in 99% of all the tables in their programs: it will serve no informational purpose, will make reading the programs more difficult and will also open the door for more bugs or compiler warnings. In addition, it is more compatible with P4-14. This was decided at the last meeting.

2. It might make sense to add another attribute, that would allow P4 programmers to specify that there is no such "default-default" action for a given table. Alternatively, the attribute can specify that there can be no miss. It can also be an annotation, but I would prefer an attribute.
   -- The rationale: it allows important optimizations on a wide variety of hardware. Essentially a traditional "indexed" table is typically the one to be expressed in such a way. This is an addition I'd like to propose.

**Comment by mbudiu-vmw** [comment]
You should submit a pull request against the spec with these changes

**Comment by jnfoster** [comment]
>
> I think we need to do the following (as was discussed at the last meeting):
>
>    1.
>
>    If default_action is not specified, let's make the default to be
>    NoAction(). It will also be the default action in case the default_action
>    attribute is specified in a manner that is not fully resolvable at the
>    compile-time.
>    -- The rationale: this is by far the most typical case and we do not
>    want to burden people with the requirement to specify NoAction() in 99% of
>    all the tables in their programs: it will serve no informational purpose,
>    will make reading the programs more difficult and will also open the door
>    for more bugs or compiler warnings. In addition, it is more compatible with
>    P4-14. This was decided at the last meeting.
>
>
Actually, I believe we agreed on was to take a declarative approach and
specify what should happen (no-op) but not the how.

Here are Calin's notes:

Default actions
>     - P4_14 clearly defines what happens (pg 57)
> AI (Vladimir): we need to define what happens in P4_16. Use the wording
> from P4_14 and specify that nothing happens to the packet (whether NoAction
> or some other (hidden op?) in the compiler implementation)
>     - Future: should we have a table type that enforces defining
> default_action always?


Unless I'm mistaken, mandating that the default is "NoAction" is specifying
the how.

Can we just take text similar to what's in the P4-14 spec?


>    1.
>
>    It might make sense to add another attribute, that would allow P4
>    programmers to specify that there is no such "default-default" action for a
>    given table. Alternatively, the attribute can specify that there can be no
>    miss. It can also be an annotation, but I would prefer an attribute.
>    -- The rationale: it allows important optimizations on a wide variety
>    of hardware. Essentially a traditional "indexed" table is typically the one
>    to be expressed in such a way. This is an addition I'd like to propose.
>
> Sounds interesting, but I think we should defer this until after we
release P4-16. We are past the point of freezing features and need to get
everything nailed down. This seems like a nice-to-have more than a
show-stopper and it can be cleanly added in a future version without
breaking existing programs.

**Comment by jnfoster** [comment]
Closed by #195
