### ISSUE TITLE
Why have implicit casts for assignment?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#163]
The code snippet below gives no error or warning from the current compiler, and the spec even implies that it should be OK with the statement: "Implicit casts are allowed ... In assignments when the right-hand side has a different type from left-hand side." (Section 8.9.2 "Implicit Casts"):
```
    bit<16> y;
    bit<8> x;
    x = y;
```
This surprises me quite a bit.  Why do we think programmers will make fewer mistakes of mismatching widths during assignment than in all the other situations where the spec and compiler say it is an error, i.e. during arithmetic ops, or passing arguments to actions, control blocks, etc.?

I for one would prefer it if such assignments were an error.

**Comment by jnfoster** [comment]
Close by #173
