### ISSUE TITLE
Unused controls and parsers

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#169]
We have flip-flopped on this issue several times.
The core question is the following:

```
// architecture
control proto();
package top(proto p);

// user program
control c() { .... }
control d() { ... }

d() dinst;

top(c()) main;
```

Are `d` and `dinst` dead code in the previous example or not? In a discussion related to issue #150 we claim that the compiler should never delete an instance, because it could have implications for the control-plane. This means that we have to keep d in the program, even though it can never be invoked.

I really think that we should define as being "live" only code that is reachable from `main`. Since `d` and `dinst` cannot be reached, they are dead code and thus they can be removed.

**Comment by jnfoster** [comment]
According to Calin's notes, at 4/24 meeting we agreed on the following:

>Unused code
    - what can the compiler do with tables and controls that are deemed dead-code but can be accessed by the control plane.
        - one option is to delete them, and if they are accessed, these should be handled at a different level
        - should they be made programmatically available to the control plane? Transparently handling calls to removed resources?
AI: compilers may optionally remove dead code and the control plane spec should deal with the behavior.

I think there is nothing to change in the spec, unless we want to highlight the dangers of dead-code elimination for control-plane visible elements. 

Can we close this?

**Comment by jnfoster** [comment]
I believe this can be safely closed.
