### ISSUE TITLE
Assigning a list to a header

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#170]
The question is about the semantics of the following statement:

```
header H { bit<32> x; }
H h = { 0 };
```

We have three choices:
- this is illegal
- this assigns the header fields, but does not change the header validity
- this also makes the header valid 

I can see very good arguments for all of these options.
One constraint is that it would be nice to have initializers be equivalent semantically to assignments; so we don't want the meaning of

```
H h = { 0 };
```

be different from

```
H h;
h = { 0 };
```

**Comment by jnfoster** [comment]
@mbudiu-vmw I think this can be safely closed. Do you agree, or do we also need to expand what's in the spec?
