### ISSUE TITLE
Update the spec version on p4.org

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4-spec#176]
A lot of people stumble on the P4_16 spec hosted on p4.org (http://p4.org/spec/) which dates back to December (a few things have changed, like table parameters).
Would it be possible to have http://p4.org/spec/ point to http://p4lang.github.io/p4-spec/docs/P4-16-draft-spec.html ?

**Comment by jnfoster** [comment]
We're going to stick with the current process for updating the official version of the spec, but I will work with Prem to expand the page hosted on p4.org.
