### ISSUE TITLE
Incorrect `out` parameter on `packet_in.extract`?

### ISSUE THREAD

**Issue by TMVector** [p4lang/p4-spec#179]
In the spec, [`packet_in.extract`](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-draft-spec.mdk#L2884) has an `out` parameter for the header l-value.  
In the first line of the pseudocode body, the `valid$` bit of the header is checked.

```p4
void packet_in.extract<T>(out T headerLValue) {
   ParserModel.verify(!headerLValue.valid$, error.OverwritingHeader);
   bitsToExtract = sizeofInBits(headerLValue);
   ...
```

Yet in [6.7](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-draft-spec.mdk#L991), we are told `out` parameters are undefined, and specifically, **parameters of type `header` are set to “invalid”**. So surely the `valid$` bit is always false?

Is this some special case for the `valid$` bit, or should the parameter really be `inout`?

*I'm assuming `sizeofInBits(headerLValue)` and `sizeOfFixedPart(headerLvalue)` are actually operations on the type `T` (like in [lookahead](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-draft-spec.mdk#L2991)), not the value?*

**Comment by mbudiu-vmw** [comment]
Great observation. This is a very good reason to give up on the OverwritingHeader error.

In C sizeof is defined for both types and values, but yes, strictly this applies to the type.

**Comment by jnfoster** [comment]
I concur. Let's remove the check, as we already discussed in another thread.

-N

**Comment by jnfoster** [comment]
This is addressed by the pull request for #166, which removes this check. Closing now.

**Comment by mbudiu-vmw** [comment]
I want to point out another inconsistency in the spec; in general, given a function
`void f(out T x)` you want the semantics of the following two to be equivalent:
`f(h);` and `f(tmp); h = tmp;`

However, for extract they are not, when dealing with header stacks extract also updates the hidden counter.

**Comment by ChrisDodd** [comment]
It seems like the correct way to do this (if you want to keep the OverwritingHeader error) is to have the *assignment* trigger that error if you assign to an entire header that is already valid in a parser.  Assigning to a field of a header would not trigger the error.

**Comment by mbudiu-vmw** [comment]
Yes, are are right. But it's even better without this error; otherwise you'd have to invalidate any header prior to copying another one into it.

**Comment by mbudiu-vmw** [comment]
Unfortunately the problem with extract and header stacks remains; the assignment does not change the pointer to the last element according to the spec.

**Comment by ChrisDodd** [comment]
Actually the spec never talks about how and when the hidden `nextIndex` of a header stack changes, as far as I can see.

Requiring an explicit invalidate before overwriting a valid header in a parser might superficially seem annoying, but having the Overwriting error helps in the common case where overwriting should not happen or should be rare.

**Comment by mbudiu-vmw** [comment]
If the spec does not talk about this it's a bug we should fix.

You can implement the check manually: `verify(!dest.isValid(), error.OverwritingHeader);`
I prefer this approach.

**Comment by mbudiu-vmw** [comment]
The spec does talk about this, it's the pseudo-code of extract.
```
if headerLValue.isNext$ {
   verify(headerLValue.nextIndex$ < headerLValue.size, error.StackOutOfBounds);
   headerLValue.nextIndex$ = headerLValue.nextIndex$ + 1;
}
```

**Comment by ChrisDodd** [comment]
Which seems just as broken as checking the valid bit in the extract method, as the parameter really a temporary out, and not the actual thing being extracted into.

**Comment by mbudiu-vmw** [comment]
Yes, that is my point exactly. This is a pretty ugly special case. This was changed by https://github.com/p4lang/p4-spec/commit/4ce09ca2766bdf300c3fc8bb7d21c904e08fdb67. The previous design was different.
