### ISSUE TITLE
lookahead() behavior for the headers with varbits

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#180]
extract() method for packet_in has two forms:
1. extract(fixed_header)
2. extract(header_with_varbit_field, legth_of_varbit_field)

The problem is that more often than not, the length of the varbit field is contained inside the same header. For example, this is the case with IPv4. The current examples solve this problem by using two headers to represent an IPv4 header: one for the fixed part and another one, containing onlythe options. 

I tried the "canonical" way:
```
header ipv4_t {
    bit<4>       version;
    bit<4>       ihl;
    bit<8>       diffserv;
    bit<16>      totalLen;
    bit<16>      identification;
    bit<3>       flags;
    bit<13>      fragOffset;
    bit<8>       ttl;
    bit<8>       protocol;
    bit<16>      hdrChecksum;
    ipv4_addr_t  srcAddr;
    ipv4_addr_t  dstAddr;
    varbit<320>  options;
}
```

To extract the header I need to do a lookahead first and, in my view, the most "natural" way looks like this:
```
    state parse_ipv4 {
        bit<4> ihl = packet.lookahead<ipv4_t>().ihl;
        packet.extract(hdr.ipv4, ((bit<32>)ihl - 5) * 4);
        . . . 
```

The spec is not saying anything about whether it is OK to do a lookahead on a header with varbit field. The current compiler rejects it:
```
l3_switch.p4(53): error: varbit<320>: unexpected type in lookahead argument
    varbit<320> options;
           ^^^
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../ir/vector.h:126
../ir/vector.h:126: Null e

Aborted (core dumped)
```

It would be nice to clarify and make an explicit decision on the behavior. I believe, it should be allowed (at least as long as we ask for a header that precedes varbit one). It is certainly possible to work around this issue, but it would be nice if the straightforward code is allowed too.

**Comment by jnfoster** [comment]
[Section 11.8.3](http://p4.org/wp-content/uploads/2016/12/P4_16-prerelease-Dec_16.html#sec-packet-lookahead) states:
> One invokes lookahead as follows:
> ```b.lookahead<T>()```
> where T must be a type with fixed width

So we should clean up the error message but I think the spec is perfectly clear.

-N

**Comment by jnfoster** [comment]
Will you please open an issue on p4c with a complete source listing so we can improve the error message? Thanks!
