### ISSUE TITLE
Initializing Header Stacks

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#198]
## Personnel
- [x] **Owner**: @vgurevich 
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [ ] **Document**: See below

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [x] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

Hello, 

I was wondering if it is possible to initialize header stacks, and if yes, how. 

Obviously, we can initialize headers using tuples:
```
vlan_tag_t vtag = { 3w5, 1w0, 12w100, 16w0x0800 };
```

However, it is not clear what to do with a stack. I tried a tuple of tuples, which didn't go well:
```
vlan_tag_t[2] vtag = {
    { 3w5, 1w0, 12w100, 16w0x0800 },
    { 3w5, 1w0, 12w100, 16w0x0800 }
};
```

The compiler said: "Cannot unify Tuple(2) to header vlan_tag_t[]"

I tried to flatten the initializer, by removing the internal braces. In that case the compiler could not unify Tuple(8) to vlan_tag_t[].

Casting didn't work either.

Is there any kind of tuple that can be unified with a header stack? 

Thanks,
Vladimir

**Comment by mbudiu-vmw** [comment]
There are no array initializers, you have to initialize each element by hand.

**Comment by vgurevich** [comment]
This is definitely an inconsistency, (since other compound types can be initialized),  but the one we can live with. Something for the future?

**Comment by jnfoster** [comment]
Let's punt this until after the release. It would be good to have, but the
interaction with `next` and `last` could be subtle. And we wouldn't be able
to initialize stacks with holes...

On Wed, May 10, 2017 at 8:16 PM, Vladimir Gurevich <notifications@github.com

**Comment by mbudiu-vmw** [comment]
Let's implement something.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
