### ISSUE TITLE
P4 Spec ToC: Sections 12.1 Actions and 12.2 Tables at wrong page number

### ISSUE THREAD

**Issue by akeep** [p4lang/p4-spec#199]
Hey All,

I noticed in the table of contents that section 12.1 Actions is listed at page 93 (should be 75) and 12.2 Tables is listed at page 92 (should be 76).  I think the problem is that there are two sections listed for each of these.

Sections 12.1 and 16.3.1.3 are both "Actions"

Sections 12.2 and 16.3.1.1 are both "Tables"

I'm happy to fix this, but I wasn't sure what which we should change, or how we should change it.

**Comment by jnfoster** [comment]
The issue is that Madoko generates default TeX / HTML labels for unlabeled sections. I have a PR coming that fixes this.
