### ISSUE TITLE
What happens after the reject state?

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#200]
The spec seems to be silent about the further handling of the packet in case the parser reaches the `reject` state. From the current reading it looks very much like the `accept` state, except that the error is set to something other than error.NoError. 

To me this implies that unless something special is done, the `reject`-ed packet will also reach the other P4-programmable blocks and thus at least some of them should have access to parser errors. For example, does it mean that the verifyChecksum() control should have access to parser errors as well? 

Obviously it can all be left to the architecture, including the decision on whether to drop rejected packets or not, the ability to have special intrinsic metadata or externs that can be used to parser drops, etc., but then we should probably put it in writing.

**Comment by mbudiu-vmw** [comment]
Yes, it is up to the architecture. The exemple vss architecture shows how the documentation for a target should be written.

**Comment by jafingerhut** [comment]
I have created a proposed PR to make it explicit that the behavior of handling packets reaching a reject state in a parser must be specified by the architecture, with a couple of examples.  Please read it and see if you think it is worth adding to the spec: https://github.com/p4lang/p4-spec/pull/232

**Comment by jafingerhut** [comment]
@vgurevich The PR mentioned above has been merged into the spec.  Hopefully that addresses this issue for you?

**Comment by vgurevich** [comment]
Yes, thank you!
