### ISSUE TITLE
Copy latest p4lang/p4c core.p4 into Section B?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#210]
I did a quick diff on them, and the one in p4c has more comments than the one in the spec.

The one in core.p4 has a comment "match expression has no matches" that is probably better replaced with "'select' expression has no matches".  I can open a PR for that if desired.

**Comment by mbudiu-vmw** [comment]
Please just copy the stuff.

**Comment by jafingerhut** [comment]
I have opened a PR for this: https://github.com/p4lang/p4-spec/pull/221

Closing this issue in favor of that PR.
