### ISSUE TITLE
Is it ever correct for a P4 compiler to reorder calls to externs relative to each other?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#215]
I am pretty sure that for counters and meters, at least, as long as the counters or meters being updated are in different 'collections', it should be correct for a compiler to reorder the execution of those updates relative to each other.  Such reordering can be a very useful optimization for many targets.

However, given this statement in the draft spec "**extern functions are arbitrarily powerful: they can store information in global storage, [ ... ], "collude" with each other to share information**", it seems like such reordering would in some cases be incorrect.  Without some kind of knowledge in the compiler of which kinds of reorderings are correct and which are not, it seems unsafe for it to *ever* do so.

Does this sound correct, or am I missing something?

If it is correct, should there be some way to annotate externs so that the compiler knows it can safely reorder them while optimizing?

**Comment by mbudiu-vmw** [comment]
The backend knows the semantics of externs.
We could also add some additional annotations: pure, privatestate.

**Comment by jafingerhut** [comment]
So maybe this is only an issue for those P4 systems where they allow user-defined externs (I think you mentioned that you had heard of such implementations before).

Does p4c-bm2-ss allow reordering of counter and meter updates relative to all other operations?

Does it prevent reordering of register read relative to register write, but only for accesses to the same named collection of registers?  i.e. allow reordering between accesses to different named register arrays?

**Comment by mbudiu-vmw** [comment]
None of the back-ends I work on does any such reordering or scheduling yet.

**Comment by jafingerhut** [comment]
Thanks.  I realized about 5 mins after I posted that question that p4c-bm2-ss probably never reorders any operations, since it has no good reason to do so.

**Comment by jnfoster** [comment]
@jafingerhut are you happy? Can we close this?

I agree that reordering operations would be useful and may be tricky when the code involves externs. But I also agree with Mihai that a back-end would have full knowledge of the semantics of externs. So the front-end might have to be conservative, but the optimizations could still happen somewhere.

**Comment by jafingerhut** [comment]
I am happy, about this and many other things :-)  Closing.
