### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#223]
What happens if I remove data that was not previously added? What happens if I add the same data twice and then remove once?

-N

**Comment by mbudiu-vmw** [comment]
This is just a hypothetical example, it is not part of the P4 definition.
We don't describe how the 16-bit checksum unit works, that's folklore.

**Comment by jnfoster** [comment]
I think this is my fault actually -- last fall, I insisted that the VSS checksum have the same interface as the full one. :-P

**Comment by mbudiu-vmw** [comment]
Yes, VSS does not need such a complicated checksum unit.
In principle it's relatively easy to explain, but it is not in the scope of this document.

**Comment by jnfoster** [comment]
(I'm still curious what a real checksum unit would do, but that can wait for later.)

**Comment by mbudiu-vmw** [comment]
Think of it is a streaming unit; you add a stream of bits and ask for a checksum at the end.
What you add and remove must be aligned on byte boundaries for this to make sense.

**Comment by jnfoster** [comment]
So would ck.remove<T>(T data) just remove the last sizeof(T) bits?

**Comment by jnfoster** [comment]
I can't do 
```
ck.add(ethernet);
ck.add(ipv4);
ck.remove(ethernet);
```
and expect it to do something reasonable.

But 
```
ck.add(ethernet);
ck.remove(ethernet);
ck.add(ipv4);
```
would be equivalent to just
```
ck.remove(ipv4);
```
?

**Comment by mbudiu-vmw** [comment]
No, it would "complement" the data.
Here is a C implementation: https://github.com/vmware/p4c-xdp/blob/master/xdpProgram.cpp#L122.
There are some subtraction routines too.
This is a custom unit just for IPv4.

**Comment by mbudiu-vmw** [comment]
If your operations are commutative then the first would work too.
It all depends on the algebra of how the checksum is defined.

**Comment by mbudiu-vmw** [comment]
https://tools.ietf.org/html/rfc1624

**Comment by jnfoster** [comment]
:-)
