### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#226]
* Should all references to "arrays" really be to "header stacks"?

* The discussion of direction conventions in the Justification section seems too early: constructor parameters and action data haven't been defined yet. I think @jafingerhut added this recently. But maybe it should be moved elsewhere.

* Do we want to say that there is no user-facing `string` type?

**Comment by jafingerhut** [comment]
I cannot think of anything other than "header stacks" in the current P4-16 language that "arrays" can refer to, so "header stacks" is more clear.

No strong opinion on the others, but they both seem fine to me.  I'm not trying to avoid blame if it is due, but I haven't done anything nearly so useful for p4.org as write entire sections of the spec yet :-)

**Comment by jnfoster** [comment]
The rest of these are trivial. Closing this.
