### ISSUE TITLE
Add description of assignment between header_union variables

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#228]
The current spec seems silent on the topic of assignments between variables of type header_union.  That should probably be addressed explicitly.  Perhaps some text like the following could be added to the section on header union operations (unless my idea of the behavior differs from what others expect it ought to be):

Assignments between variables of the same type of header_union are permitted.  When the assignment `u1 = u2` is executed, if `u2` is valid (i.e. any of its member headers is valid), then there is some member header `u2.hi` that is valid.  The assignment behaves the same as `u1.hi = u2.hi`. 
 If `u2` is not valid, then `u1` becomes invalid (i.e. if any member header of `u1` was valid, it becomes invalid).

Also, I didn't see isValid() described for header_union in that section?

**Comment by jafingerhut** [comment]
Created a PR for this in case it helps: https://github.com/p4lang/p4-spec/pull/230

**Comment by jnfoster** [comment]
Closed by #230
