### ISSUE TITLE
casts

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#235]
I guess we disallow casts involving `varbit<W>`?

**Comment by mbudiu-vmw** [comment]
Correct.

**Comment by jnfoster** [comment]
`bit<32> a = 10`. Legal or no?

**Comment by mbudiu-vmw** [comment]
Yes

**Comment by jnfoster** [comment]
Sorry, which way?

**Comment by mbudiu-vmw** [comment]
You can assign an int to a fixed-width.
