### ISSUE TITLE
constructor confusion

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#238]
This is mostly a placeholder for myself: #sec-constructor distinguishes "constructors" (for externs) and "instantiations" (for parsers/controls/packages), but we instantiate using "constructor parameters." This is confusing.

**Comment by mbudiu-vmw** [comment]
One is an expression, the other a declaration. Both have to supply arguments for constructor parameters.

**Comment by jnfoster** [comment]
I know. Our terminology just seems less than ideal. Definitely low-priority to fix and easiest done on a global pass once everything else is converged.

**Comment by jnfoster** [comment]
Closing this. It's not worth addressing now.
