### ISSUE TITLE
Minor build issue: How to install UtopiaStd-Regular font on Mac?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#271]
Just a question for anyone who has successfully built the P4-16 spec on Mac OS X without getting this error:

    The font "UtopiaStd-Regular" cannot be found.

I have installed many texlive-* packages using MacPorts to no avail, so far.  If people are using Brew to install TeX on a Mac and not getting this error, I may just have to do that.

**Comment by cc10512** [comment]
checkout the gh-pages branch of the repository and add the UtopiaStd-Regular.otf file to your font book. As well as luximr.ttf for the code fonts.

**Comment by jafingerhut** [comment]
@cc10512 That worked.  Thanks.  I should create a PR to add this note to the README for building the P4-16 spec.
