### ISSUE TITLE
Use `tuple` in type declarations?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#272]
The following sentence in the spec did not mention `tuple`. But from the context before and after the paragraph, it would make the spec more clear to state whether `tuple` can or cannot be used in a type declaration.

```
The types `header`, `header_union`, `enum`, `struct`, `extern`, `parser`, `control`,
and `package` can only be used in type declarations, where they
introduce a new name for the type. The type can subsequently be
referred to using this identifier.
```

Also, just nitpicking, it would be easier on the reader if the order of the type keywords matches to the order of the type keywords in the bullet points right above this paragraph (so that the readers don't have to mentally sort the keywords while reading this paragraph).

**Comment by jafingerhut** [comment]
@hanw Or perhaps it would be even easier on the reader to add a table of the relevant properties of each type, especially if there are more of them we want to summarize, besides 'can only be used in type declarations'.

You should double check with a little test program yourself, but I believe p4c already supports tuple in this way.

**Comment by mbudiu-vmw** [comment]
All these declarations introduce a new type by name. `struct S {}` introduces the name S. There is no such case for tuple or stacks. That's the meaning of the paragraph.

**Comment by jafingerhut** [comment]
@mbudiu-vmw I am not sure how to reconcile your statement with the fact that the attached P4-16 program compiles cleanly with a recent p4test and p4c-bm2-ss.  See the type named myTuple_t in there.  Is this an example of the compiler allowing something that the spec does not?  Or something else?

**Comment by mbudiu-vmw** [comment]
Which attached program?

**Comment by jafingerhut** [comment]
It should be there now, called tuple-with-type-name.p4.txt.  I missed attaching it on my first send, and added it about a minute later, so refresh browser may be needed to see it.  The link to the file ended up before my text, not at the end.

**Comment by mbudiu-vmw** [comment]
The name is introduced by `typedef`, not by `tuple`.
