### ISSUE TITLE
Meaning of 2nd arg in 2-argument extract?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#276]
The P4-16 spec says that the second argument is in units of bits, and it is the length of the varbit field of the header, not the complete header.

That is consistent with this sample extract call for IPv4 options in a p4c test program: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/match.p4#L64-L65

If both of the above are correct, then one of the sample programs in the spec uses a wrong 2nd argument in an extract call, the one showing how to parse TCP options.  The call to extract in this code fragment:
```
    state parse_tcp_option_sack {
         bit<32> n = (bit<32>)b.lookahead<Tcp_option_sack_top>().length;
         b.extract(vec.next.sack, n);
         transition start;
    }
```
should be something equivalent to this, where the -16 part is to subtract out the length of the fixed length fields of the Tcp_option_sack_h header:
```
        b.extract(vec.next.sack, 8*n-16);
```
and the corresponding change should be made in this p4c test program: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/spec-ex19.p4#L55-L56

This is based upon my understanding that the 8-bit length field in the SACK option header is equal to the total length of the SACK option header in bytes, including the 2 bytes of type and length field, plus all bytes of variable length part after that.

I am happy to make PRs for the spec and for spec-ex19.p4, but wanted to verify that it was those that should be corrected, and not the first 2 things above.

**Comment by mbudiu-vmw** [comment]
It looks like you are right.
