### ISSUE TITLE
emit method does not specify the order of fields in a header

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4-spec#281]
In the P4_16 spec of 2017-05-22 section 14.1 it says that the packet_out emit method, when applied to a struct, "recursively invokes itself to each field."  Then below, when explaining the pseudo-code, it says that "We also use standard for notation to iterate through the elements of a stack (e : data) and list of fields for header stacks and unions (f : data.fields$)."

Now I understand that it is the INTENT of the specification to mean that the fields are processed IN ORDER OF DECLARATION.  But the spec DOES NOT SAY THIS EXPLICITLY.  There is no definition of what "standard for notation" is supposed to mean.  (I note that if you use a C++ for-range loop to iterate over an unordered_map, there is no guarantee on the order in which the elements of the map are encountered.  So here is an example of "standard for notation" in which there is no guaranteed order.)

I note that in section 5.2.4, when discussing extern blocks in the Very Simple Switch example, it says "update<T>(in T data): add some data to be checksummed. The data must be either a bit-string, a header-typed value, or a struct containing such values. The fields in the header/struct are concatenated in the order they appear in the type declaration."

So the spec does have a place where the order of processing of fields in a struct is explicitly specified.  I can find no other place in the spec in which order of processing of fields in a struct is discussed.

Consequently one might be led to infer that maybe it was INTENTIONAL that the order was not explicitly specified in section 14.1 and so no assumptions about the order there can be made.  Surely this it not what the spec is supposed to mean.

**Comment by mbudiu-vmw** [comment]
Yes, we should amend the spec saying that struct fields are emitted in the order they appear in the strict declaration.

**Comment by jafingerhut** [comment]
Agreed that this appears to be an explicit statement of the original intent, rather than an intentional ommission, given that an emit of a struct with unspecified emit order wouldn't be very useful for anyone.  Created a proposed PR: https://github.com/p4lang/p4-spec/pull/283
