### ISSUE TITLE
Clarifications on behavior of P4-14 remove_header and P4-16 setInvalid

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#284]
I was analyzing some switch.p4 code here: https://github.com/p4lang/switch/blob/master/p4src/int_transit.p4#L425-L449

To refresh my memory, I went to the P4-14 spec (latest version as of now, v1.0.4), and found this statement that surprised me regarding remove_header behavior when applied to an element of a header stack:
```
If the \texttt{header_instance} is an element in a header stack, the effect is to 
pop the indicated element from the stack. Any valid instances in the stack 
at higher indices are copied to the next lower index.
```
Reference: https://github.com/p4lang/p4-spec/blob/master/p4-14/v1.0.4/tex/p4.pt#L1834-L1836

If that statement in the P4-14 spec is correct, then the portion of switch.p4 linked above is incorrect, because it will invalidate and pop int_val[0], which shifts what is currently the value of int_val[1] into the position int_val[0].  Then it does remove_header on int_val[1], which leaves the original value of int_val[1] still valid, if it was valid before the action started execution.

My guess is that the quoted behavior from the P4-14 spec might never have been implemented that way in behavioral-model code (I have scanned the code briefly, but haven't yet created a test case to verify with certainty).

The latest p4c as of 2017-May-15 compiles that P4-14 action to this P4-16 action: https://github.com/jafingerhut/p4lang-tests/blob/master/v1.0.3/switch-2017-03-07/out1/switch-translated-to-p4-16.p4#L3879-L3908

My reading of the P4-16 spec is that setInvalid() does _not_ have the effect of doing a 'pop', the way the P4-14 spec claims remove_header is supposed to do.

Given all of this, should we do anything about it?  If it is true that the P4-14 spec is out of date here, perhaps it should be updated to say that remove_header does not have the 'pop' effect, but just leaves a 'hole' in the middle of an otherwise valid stack of headers?

A similar comment applies to P4-14's documented behavior for add_header, which says it should cause a push in the middle of a header stack.

**Comment by mbudiu-vmw** [comment]
I really hope that we decide that the P4-14 spec is wrong, because the P4-16 spec will create a hole.
If both specs are right, then we have a bug in the translation from P4-14 to P4-16, which won't be very easy to fix. Either way, we need to do something.

**Comment by jafingerhut** [comment]
@antoninbas Is it quick for you to explain the current behavior of add_header and remove_header primitives in p4lang/behavioral-model?

To your knowledge, have either of them ever implemented push/pop-like behavior when applied to an element in a header stack?

**Comment by antoninbas** [comment]
I guess bmv2 is conforming to neither P4_14 and P4_16.
Validating / Invalidating header instances in a stack can only be done through the push and pop primitives. Validating / Invalidating a header in the "middle" of a stack will result in some very strange behavior. As an example, if I have a stack of 3 MPLS tags, all of them invalid. If during match-action processing, the tag in the middle (stack[1]) is set to be valid, it will not show up on egress after deparsing. See this bmv2 issue for more details: https://github.com/p4lang/behavioral-model/issues/111

**Comment by jafingerhut** [comment]
I have run some tests with a recent version of simple_switch from p4lang/behavioral-model, and it seems to have no trouble creating header stacks with 'holes' in the middle, i.e. invalid headers with a valid header earlier and later in the same stack.  I did this with a test program that performed add_header() and remove_header() primitives on a stack of up to 4 headers.  See a recent comment on https://github.com/p4lang/p4-spec/issues/431 for more details.

**Comment by antoninbas** [comment]
bmv2 has undefined behavior when using `add_header` and `remove_header` on elements of a header stack, as explained in https://github.com/p4lang/behavioral-model/issues/111.

**Comment by jafingerhut** [comment]
@antoninbas I have tried running the sample program on the issue you mention, and I see the weird behavior for the pop() operation, but remove_header(ext[0]) and remove_header(ext[1]) operations do change the header validity bits even in that example, i.e. remove_header(ext[0]) clears the valid bit for ext[0] but leaves the valid bit for ext[1] at 1, and conversely for remove_header(ext[1]).

Do you perhaps mean that bmv2 has undefined behavior when using push and pop on elements of header stacks?

**Comment by antoninbas** [comment]
no i did mean `add_header` and `remove_header`. It may change the header validity as you expect, but header stack primitives, such as `size()`, will not work thereafter.

**Comment by jafingerhut** [comment]
Current simple_switch add_header and remove_header seem to be working as specified in the latest P4_16 spec -- there those operations are not specified to do anything special for header stacks at all, i.e. no updates to lastIndex or nextIndex values.  Perhaps that is an ommission in the intent of the P4_16 spec, I don't know.

`size()` is a compile time constant for each header stack, so I'm guessing you were referring to things that change at run time like `next`, `nextIndex`, etc.?

**Comment by jafingerhut** [comment]
A few more comments: At least in the P4_16 spec, it explicitly says that 'holes' are allowed in header stacks, i.e. invalid headers with valid headers earlier and later in the stack.

The only things that mention nextIndex are extract() methods, which are only allowed in the parser, so by the time the parser is complete in a P4_16 program, I don't think nextIndex is used for anything else.  emit() is not 100% explicit about this in the P4_16 spec, but it could be read to mean that all valid headers in index ranges 0 through size-1 are emitted.  The text says: "We use standard `for` notation to iterate through elements of a stack", but doesn't explicitly say whether the elements of a stack are 0 through size-1 or only 0 through nextIndex-1.

**Comment by jnfoster** [comment]
@jafingerhut Thanks as always for the careful thought to this.

1. This is not an omission.

2. I believe the intention is to go from 0 through size - 1.

**Comment by jafingerhut** [comment]
Yesterday I dug through all the details I could find on header stack operations in P4_14 v1.0.4 spec, P4_16 v1.0.0 spec, and the p4lang/behavioral-model implementation in simple_switch.  I found several differences that we may want to address, either in the specs, in the simple_switch implementation, or in the automatic p4test translation from P4_14 to P4_16 programs.  I will put the details of those findings on some p4lang/p4-spec issue, perhaps via a link since putting all the text in a github issue might be a bit much.

**Comment by jafingerhut** [comment]
I've put a link to the details of my digging in a recent comment on this issue: https://github.com/p4lang/p4-spec/issues/431

**Comment by jnfoster** [comment]
Can we close this issue now that we've addressed the semantics of header stacks?

**Comment by jafingerhut** [comment]
The short answer is: yes.

If anyone is curious about the more detailed status of things, here is what I know of:
+ P4_16 language spec - no plans to change anything there.  People seem agreeable with the existing definition of behavior of header stack operations.
+ P4_14 language spec - v1.0.5 has the changes that bring it to match P4_16, with the one backwards-compatible preservation of behavior that push always inserts valid headers, whereas P4_16 push_front always inserts invalid headers.  This seems reasonable to keep as a difference, for backwards compatibility of existing P4_14 programs that may rely upon that.
+ behavioral-model implementation in release 1.10 has a build-time option to match P4_16 semantics, and the plan is for that to become the default behavior when version 1.11 is released.  There is a P4_16 program and set of packet tests that fail with 1.10 (and should), and should pass when the new 1.11 default behavior is released.
+ p4c has been updated so that when compiling P4_14 programs to bmv2 JSON, or translating them to P4_16, it creates a push operation, and then enough setValid() operations as required to make all of the new pushed headers valid, for the backwards-compatible P4_14 behavior as mentioned above.

**Comment by jnfoster** [comment]
👍
