### ISSUE TITLE
Question: How undefined is the result of accessing a field in an invalid header?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#285]
A quote from the P4-16 v1.0.0 spec:
```
The result of reading or writing a field in an invalid header is undefined.
```
Reference: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L3287-L3288

I could interpret this in at least a few different ways, and I am sure other interpretations are possible:

(1) If you attempt to read a field in an invalid header, _that value read_ is undefined, but except for that (and any other places in the program that the value's undefined-ness spreads to, e.g. the result of an arithmetic expression using that value), the behavior of the P4 program on that packet is defined.  If you attempt to write to a field in an invalid header, that write is effectively a no-op.

(2) If you attempt to read or write a field in an invalid header, the behavior of the rest of the P4 program on that packet is completely unspecified, even if the program never attempts to access that header or any of its fields again.

(3) The device behavior is completely unspecified from that point an ongoing, even for later arriving packets.  The device must be reset before its behavior becomes defined again.

I was wondering whether (1) is the way people think the statement was intended?  In particular, the part about attempting to write to a field in an invalid header being a no-op?  If so, it seems more precise to replace that sentence of the spec with something that has the same meaning as statement (1).

**Comment by jnfoster** [comment]
From our discussions this fall and winter, interpretation (1) is what was
intended.

**Comment by jafingerhut** [comment]
Do you know whether the statement "If you attempt to write to a field in an invalid header, that write is effectively a no-op." is intended to be true even if the assignment is to a field in an invalid header that is a member of a header_union?

For example, suppose we define:
```
header h1_t {
    bit<8> f1;
}
header h2_t {
    bit<8> f2;
}
header_union u_t {
    h1_t h1;
    h2_t h2;
}
u_t u;
u.h1 = { 8w5 };
// u.h1 is now valid, u.h2 is invalid
u.h2.f2 = 7;
// Is the state of u.h1.f1 now guaranteed to be 5?  Or is it undefined because of the attempted
// assignment to a field of the invalid header u.h2?
```
If so, that means that at least assignments to fields of headers within header unions must be conditional upon the validity of the header in which the the field lies.

This question doesn't matter so much for assignments to fields within a variable whose type is a normal header (i.e. not a header union), because reading from such a normal header results in an undefined value.  Thus even if the assignment were performed unconditionally, as long as the storage space for the currently-invalid header were not used by some other data in the implementation, it is a correct implementation to make the assignment's side effect unconditional.

**Comment by jnfoster** [comment]
My reading of the spec doesn't settle this issue :-(

I can argue for both semantics. I need to ponder this some more.

**Comment by jnfoster** [comment]
One view, and the one that I recall @mbudiu-vmw and I started out from, is that a sequence of operations that only involve one component of the union should behave as if those operations were applied to a header instance declared at the top-level of the scope.  So if `u.h2` is invalid, then the semantics of assigning to `u.h2.f` should be the same as assigning to a top-level header instance that is invalid -- i.e., `u.h2` is still invalid and accessing `u.h2.f` returns an undefined value.

**Comment by mbudiu-vmw** [comment]
Whatever we choose we have to edit the spec to make the intent clear.

Regarding "undefined" values: P4 does not have runtime exceptions, so the program can never crash. An undefined operation can only affect the values of the variables in scope. But indeed, the spec should qualify writes with undefined behaviors, saying which variables can NEVER be modified.

Reads are simpler, an undefined read just returns an unspecified value.

So, to summarize, for writes with undefined behavior, we should edit the spec and indicate what the maximum damage that each write can perform. The union is the only interesting case, we can choose for a write to an undefined field to affect the whole union. This is what would happen if you implemented the header_union as a C-like union. If we don't want this behavior we'll have to compile writes to unions to always have additional runtime checks for validity.

**Comment by ChrisDodd** [comment]
If we allow writes to undefined union elements to affect the header
actually in the union, should we extend that to allowing writes to
undefined headers to affect some (apparently) unrelated header, if the
optimizer has decided it can combine the two headers into the same physical
storage, as they can't be simultaneously valid?

**Comment by mbudiu-vmw** [comment]
If we define the "blast radius" of an undefined write to be unbounded, then people will really have to make sure that they are writing to a defined header - possibly by inserting explicit checks in the code. @jafingerhut : do you want to take ownership of this issue?

**Comment by jafingerhut** [comment]
@mbudiu-vmw If by taking ownership, you mean writing up a description and sending it out to the p4-design email list and calling for comments, and later a vote after refinement, then yes, I am happy to do that.

If you mean something else, let me know.

**Comment by jafingerhut** [comment]
@mbudiu-vmw "blast radius"   I like it!    I presume there is probably a more technical term for this in the field of programming language semantics, though :-)  Anyone know what that is?

**Comment by mbudiu-vmw** [comment]
It means that you will make sure that it is solved.
We should have a separate section to summarize all undefined behaviors for reads and writes.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Glad to do it.  I will discuss with @jnfoster to learn his thoughts on proceeding here.

**Comment by jafingerhut** [comment]
@ChrisDodd wrote: If we allow writes to undefined union elements to affect the header
actually in the union, should we extend that to allowing writes to
undefined headers to affect some (apparently) unrelated header, if the
optimizer has decided it can combine the two headers into the same physical
storage, as they can't be simultaneously valid?

I add the following to that:

And if you are going to allow that, why stop only at other headers?  Why not allow metadata values that an optimizer might allow to 'reuse' the space of the invalid header to be affected?

Also, even if you write a spec that only allows writes to fields of invalid header union members to propagate undefined values to the currently valid header union member, how would you actually implement that?  If the write was to a large header, to its last field, but the currently valid header of the union was much shorter, an optimizer could also reallocate the unused header union space for other purposes, too, yes?

My current thinking is that the most sane specification is the most defined one.  Something like this:

```
If you attempt to write to a field in an invalid header, that write has _no effect_
on any value in the system that is currently defined.
```

**Comment by jafingerhut** [comment]
OK, sorry if this is getting to the point of spamming people following this discussion, but I wrote up some thoughts on 3 possible options for spec'ing the behavior of assigning a value to a header field within a header that is currently invalid.

The option in my previous comment is called option (1) here, and my current recommended approach.  Option (2) seems not to make an implementation's job any easier than (1), and causes undefined results in more situations.  Option (3) is easiest for an implementation to satisfy, but seems like utter chaos to me for a person who is trying to reason about a P4 program's possible behaviors.
[undefined-behavior.txt](https://github.com/p4lang/p4-spec/files/1057644/undefined-behavior.txt)

**Comment by vgurevich** [comment]
@jafingerhut,

The rule you are proposing is really nice, but it will pretty much kill any practical implementation of header unions, because the idea was that the headers that form them  would typically be overlaid. If you write into a header that is a member of a header union that is not valid, it pretty much guarantees corrupting the one that is currently valid. 

I am all for safety, but we are taking about systems with fairly limited resources that also need to operate at very high speeds. What you are suggesting here can only be achieved by either

1. Allocating separate resources for all headers (not overlaying them) 

or

2. predicating each write on header validity.

Both are very expensive, while probably will help very little in terms of helping to weed out the bugs. Instead, they will simply be masked.

Therefore, I would suggest that the results of such writes are, indeed, undefined and, yes, any other value can be corrupted. At the same time, nothing prevents a model (e.g. BMv2) to perform all these checks (at least in a special debugging mode) and report them as strongly as one desires. Given that most P4 programs are going to be extensively debugged on models and simulators well before they go onto the real silicon, I would propose we leave this behavior as undefined.

**Comment by mbudiu-vmw** [comment]
@vgurevich : it is fine to leave the behavior undefined, but we have to say how undefined it is.
And this has nothing to do with unions, the problem is present even just with invalid headers.

**Comment by vgurevich** [comment]
@jafingerhut ,

One of the things we need to keep in mind is that compiler can have only limited insight into a P4 program. because it cannot (even theoretically) deduce the program's state (i.e. table and extern programming) from the program's inputs and outputs (i.e. packets). That's a fundamental difference between P4 and most other languages, where the internal state can be deduced from the program's other inputs.

The more rules we place in the spec, the compilers will have little choice: either they will have to become too conservative, follow the spec "to the letter" and as a result become not very useful in practice. Or, they will ignore these rules and then the rules themselves will become useless.

In this particular case, I see very high cost and little practical benefit (even bordering on the harm, since it is not clear if masking a bug in the user code is better than letting it to show through).

**Comment by vgurevich** [comment]
@jafingerhut ,

I agree that this problem exists with invalid headers. But I am not sure I understand how to define the undefined or whether it makes sense :)

Let's take an example from C. How undefined is the result of this program:
```
#include <stdio.h>

int main(int argc, char *argv[]) {
    unsigned long    l;
    unsigned long * p;

    if (scanf("%ld", &l) == 1) {;
        printf("Let's try ... ");
        p = (unsigned long *)l;
        *p = l;
        printf("DONE");
   }
   return 0;
}
```

I mean, anything can happen, right? Depending on the user input, the program can crash, can work perfectly fine, can corrupt some of the code, can corrupt the printf() strings, etc., etc. And we still find the language quite useful. I specifically use C, because that is the language that was specifically designed to be close to the HW.

**Comment by jafingerhut** [comment]
@vgurevich Your example C program uses not only pointers, but casts to pointers, two of the wonderful reasons why P4 doesn't have pointers :-)

My option (2) in the attached file is a bit more lenient in its requirements, and maybe something you would be in favor of.  I will copy it here for easy reference:
```
(2) If you attempt to write to a field in an invalid header that is
    _not_ part of a header union, that write has no effect on any
    value in the system that is currently defined.

    If you attempt to write to a field in an invalid header that is
    part of a header union, and a different member header of that
    header union is currently valid, all of its fields become
    undefined.  All other values in the system that are currently
    defined must remain unchanged.
```

**Comment by jnfoster** [comment]
Let's take an example from C (Ellison & Rosu, 2012)

```
int main(void){
  int r = 0, d = 0;
  for (int i = 0; i < 5; i++) {
    printf("%d\n", i);
    r += 5 / d; // divides by zero
  }
  return r;
}
```

Pop quiz: does running this program always print something to the console?

It's 2017. Please let's not look to C for inspiration about undefined
behavior. It is the source of countless programming errors, billions of
dollars of loss, many security vulnerabilities, etc. We can do better.

-N

**Comment by jnfoster** [comment]
Let's take an example from C (Ellison & Rosu, 2012)

```
int main(void){
  int r = 0, d = 0;
  for (int i = 0; i < 5; i++) {
    printf("%d\n", i);
    r += 5 / d; // divides by zero
  }
  return r;
}
```

Pop quiz: does running this program always print something to the console?

It's 2017. Please let's not look to C for inspiration about undefined
behavior. It is the source of countless programming errors, billions of
dollars of loss, many security vulnerabilities, etc. We can do better.

**Comment by jafingerhut** [comment]
@vgurevich Just so I am clear here, is it your preference that if a P4 program attempts to write to any field in any invalid header, whether it is in a header union or not: "the results of such writes are, indeed, undefined and, yes, any other value can be corrupted."

And by "any other value" you mean any header field, whether it is in a currently valid header or not, or any metadata field?

If so, you do realize that effectively that means that afterwards, that packet's behavior could be _any_ state reachable from that point in the program onwards, with some arbitrary bit patterns stored in all of the header and metadata fields?  If the P4 program could possibly send a packet to the control CPU, it could be sent with completely unknown sequence and contents of headers?  If the P4 program could possibly cause the packet to go to a PRE and replicate the packet 100 times, it can do so, and each of those packets will have completely unknown sequence and contents of headers, and if there are register arrays that might be written, they will be written with unknown contents?

Words that spring to my mind: chaos, havoc, confusion, pain, suffering.

I realize, of course, that it is more likely that an implementation would just corrupt as many bits as the invalid field being written, but subtlety in bugs isn't a virtue.

Regarding P4 being special here for program analysis vs. other programming languages, I don't see it.  Try analyzing any program that takes input from some external source, and you've got either careful input validation, or _assumptions_ in the program about the format or contents of that input, if you trust that source.  Often unwritten assumptions.

**Comment by jafingerhut** [comment]
@vgurevich I am really deeply confused here.  You say "predicating each write on header validity." is "very expensive".  Have you read the P4_14 spec definition of modify_field?  This sentence, in particular: "If the parent header instance of dest is not valid, the action has no effect."  Did someone choose not to implement that sentence for the most commonly used primitive operation in every P4_14 program I have ever seen?

**Comment by vgurevich** [comment]
Sorry for the late reply guys -- I am traveling 

@jnfoster,

Yes, it is 2017 in the world of **general purpose processors**, but in the world of P4 processors we are  somewhere in 1950s, limited literally by **bytes** (not gigabytes) of instruction and data memory. So, let's not confuse these two worlds here. If people tried to implement <insert your favorite safe language>  on 1950s hardware, before they implemented all these "ancient" and "unsafe" languages, I am afraid we would not have the computing world we have today. 

Similarly, I did choose C on purpose: for all its faults it was the first truly successful system programming language that made using assembly to write OS-es unnecessary. And this happened precisely because it was both sufficiently high-level, while at the same time close enough to the HW to allow the programmer to understand what's going on, support efficient compilation/optimizations, etc.

@jafingerhut,

Same thing, with regards to P4_14 spec. If you look at the real implementations (and I think that includes BMv2), you will see that this sentence from the specification is not implemented. 

And this is precisely my point:  we can spec the language in any way we want, but if practical implementations will have not choice but to do things differently (or simply choose so because it is more convenient for them/their customers), then the spec will have to be changed anyway. Obviously, we cannot make optimal choices 100% of time, but in this case I think we have  enough insight.

**Comment by jafingerhut** [comment]
So it sounds to me like we may have one vote for something equivalent to the description below as part of the next P4-16 language specification, regardless of whether header unions are used in the program.  I understand that the C language specification achieves equivalent descriptions in fewer words than this, and we may get 0 votes for copying and pasting this text into the spec :-)

If you attempt to write to a field in an invalid header, the behavior of the rest of the P4 program may be any behavior that results from replacing the current values of all valid header fields and all metadata fields with arbitrary values.

Depending on the contents of the rest of the P4 program, this may include:
+ updating packet/byte counters
+ updating meters
+ writing register arrays
+ sending packets to a local control CPU
+ recirculating packets back to the same pipeline where the erroneous write occurred.  Depending upon the P4 program contents, this might continue indefinitely.

Depending upon the architecture implementation details, the device may need to be reset before its behavior becomes easier to predict.  Consequences for the control CPU and devices reached by output ports are outside of the scope of this specification.

A P4 compiler is strongly recommended to give an error or warning message at compile time for any assignment to a header field for which it cannot prove the header is always valid at that point in the program.

**Comment by vgurevich** [comment]
@jafingerhut,

Your description would definitely work. Let me offer an equivalent description, that might describe what's happening in more familiar terms:

The resources (e.g. memory) required to carry header fields are guaranteed to be allocated only for valid headers. If a header is invalid, those resource should be considered unallocated. Therefore, reading or writing fields of invalid headers have the same general effects as reading from or writing into unallocated (but generally valid) memory in other programming languages.

Note, that unlike truly dynamic memory allocation, setValid() can never fail: the compiler must ensure that the system has all the resources, required to execute the program at a compile time.

**Comment by jafingerhut** [comment]
@vgurevich I think your description is better as a rationale for motivating why the undefined behavior could exist.

Another paraphrasing -- you are effectively proposing that all headers and metadata are allocated in a common memory, hdr.setValid() is a C malloc() for the header space that can never fail (if the program compiles successfully), and hdr.setInvalid() is a C free() for that header space.  Thus writes to a field in an invalid header are like writing to a C struct through a free'd pointer.

Would your proposal include header valid bits and header stack lastIndex values in the collection of data that might be corrupted by an invalid header write?  Or would those be excluded from possible corruption?  I guess it doesn't matter too much whether they are included at this point.  The behavior doesn't get that much more undefined if they are included in the blast radius.

**Comment by vgurevich** [comment]
@jafingerhut ,

You got me 100% correctly. 

As for the potential to corrupt header valid bits and other special metadata, I think it depends on the implementation, but I'd think it would not be that difficult for a compiler not to overlay valid bits with anything else.

**Comment by vgurevich** [comment]
@jafingerhut ,

With regards to allocating all headers and metadata in the common memory: This is not something I'd necessarily mandate in the spec. Generally it is true at the low-level, but if the compiler chooses to never use the same memory for headers and metadata (which is easy to do), then logically you can consider those spaces to be separate and the "blast radius" will be greatly reduced. Again, I would not put anything in the spec and leave it to the implementors, similarly how C spec does not mandate the section where string constants are put, whether code segment should be read-only, etc.

**Comment by jafingerhut** [comment]
Are you proposing that the spec should say that writing a field in an invalid header _cannot_ cause metadata fields to change values?  I would have guessed that in your view, that would be restricting an implementer's choices too much.

**Comment by vgurevich** [comment]
@jafingerhut ,

I am not proposing that writing a field in an invalid header cannot change the values of metadata fields. I do not think this should be mandated. 

I only said that if an implementation wants to limit the "blast radius" it can fairly easily do so. But formally speaking non-zero "blast radius" is a non-zero "blast radius", so it's not clear if anyone will feel any better should an implementation do so. Obviously, if another implementation has a way to predicate all the writes easily, it can even reduce that "blast radius" to 0. The nice thing is that all three implementations will be within the spec. If we later decide to tighten it, we will be able to do so easily.

**Comment by jafingerhut** [comment]
@vgurevich Maybe I'm off base here, but in my view the language specification should specify the largest blast radius allowed by any implementation that calls itself a conforming P4 implementation.

Unless you want to go to the point of a spec that specifies larger and smaller blast radius effects, and give a name to each one, and recommend that implementations document their blast radius, I do not see a point in the spec mentioning smaller than the biggest allowed blast radius.

You recall the discussion where I asked whether an implementation could say "this one initializes all metadata and header fields to 0, always, guaranteed".  That is a much smaller blast radius, but you were concerned it could lead to non-portability to implementations, which it could.  Defining more than one blast radius in the spec and encouraging implementations to name how big theirs is, is exactly the same thing, and an approach you have said you want to discourage.

**Comment by vgurevich** [comment]
@jafingerhut ,

The maximum blast radius is all transient data, i.e. headers and metadata, but not the program code and not the persistent state.

**Comment by jafingerhut** [comment]
@vgurevich If by persistent state you mean things like the table contents that are only matched or read by the P4 program, I agree with you.

There are other kinds of state that persists across the processing of many packets, such as:
+ packet/byte counters, meter state, and register arrays writable from the P4 program
+ any state maintained within other P4 extern objects

While that state might be outside of the 'immediate blast' of undefined behavior caused by the write to a field in an invalid header, they are potentially in the 'after shock' caused by undefined values propagating to other places in your particular P4 program.

**Comment by vgurevich** [comment]
@jafingerhut ,

I am afraid we need to press the "reset" button, and go back to my original statement (with which I thought you agreeed), because it looks to me that the more clarifications/editorials I provide, the more confusion occurs.

So, I stand by this statement with which I thought you agreed.

> Reading or writing fields of invalid headers have the same general effects as reading from or writing into unallocated (but generally valid) memory in other programming languages -- the results are undefined, meaning that you cannot predict the value that reading this field will return and you cannot predict what will be overwritten when you write into that field by using the spec alone.

I think we should stop there instead of trying to go further and define what "undefined" means (because then undefined becomes defined). The rest of the discussion we had will be good for a book, but not for the spec.

**Comment by jafingerhut** [comment]
I am not saying that all of my comments belong in the spec.

Do you agree that your statement logically implies that an incorrect write could result in an arbitrary change to all valid header fields and metadata, including changing it to a packet that violates 'if' conditions already executed in the P4 program?

**Comment by vgurevich** [comment]
@jafingerhut ,

Yes, I do agree with the statement that writing into an invalid header field might result in an arbitrary change to a valid header or metadata field and as a consequence the packet can get processed in a way different than what the programmer has envisioned. The spec can say that, but it cannot say more, meaning that it cannot describe what this processing can actually be.

**Comment by jnfoster** [comment]
@vgurevich @jafingerhut 

It sounds like this GitHub discussion is not converging. Perhaps we need to have a quick phone call or in-person meeting to hash it out. I would like to be there but am traveling through June 23. Should we plan to talk the following week?

A few reactions:

* I believe we've all agreed to make P4 an unsafe language, at least in the short term, by which I mean that some expressions will have undefined values. It seems this may be what's needed to write the programs we want on hardware targets with limited resources and capabilities. 

* Having said that, I believe we do not actually have enough experience to understand that cost. It may well be that a large program like switch.p4 can be refactored into one that is statically safe with minimal overhead. Some of the general statements that have been made in this thread (on both sides) would be more convincing if backed up with concrete evidence---e.g., precisely how many run-time checks would one need to add to make switch.p4 safe? This is a question we should be able to settle definitively. 

* I'll note that a number of us (including me), are somewhat uneasy about having a very unsafe language and would like to find ways to confine it to as few features and as few situations as possible---i.e., smallest blast radius that doesn't preclude an efficient implementation.

* Historical analogies may be outliving their usefulness in this thread, but it's worth noting that high-level languages like LISP were also invented in the 1950s. Machines have certainly gotten faster, but compilers have also gotten much more sophisticated. It may well be that P4 programmers can write the programs they need in a way that avoids use of unsafe features. And sophisticated compilers may well be able to eliminate the overheads that would result from the "obvious" translations.

* I think we do want the semantics to either specify the value of each expression, statement, etc. precisely or say that it is undefined.

**Comment by jafingerhut** [comment]
@jnfoster @vgurevich @jafingerhut had a discussion on this issue, and how to proceed.
 
It seems wise to bring up this issue to the P4 language design work group during its next meeting, given the significance of how different approaches can affect P4 implementations, and developers writing P4 programs.  That would give us time to collect more data on the prevalence of assigning to fields in headers that may be invalid, in at least a few P4 programs such as switch.p4.
 
At that meeting, the best alternatives known will be presented, and language design work group members will be given time to think on the matter before a change to the spec is made.
 
Specifying that reading a field from a currently invalid header produces an undefined value appears to be non-controversial.
 
The more controversial part is what the spec should say about attempting to assign a value to a field in a currently invalid header.
 
Among the approaches that that may be presented at the next meeting are:
 
(1)
 
(1a) If the field is part of a header in a header union, and if a different member header of the header union is currently valid, then that valid header’s field values become undefined.  (1b) If the field is part of a header that is not a member of a header union, then the assignment is guaranteed to have no effect upon any currently defined value in the system.
 
Given that this guarantee may be expensive in some implementations, an implementation would be allowed to provide an option that reduces the safety to option (2).  Whether the form of this option is standardized as part of the P4 specification remains to be decided.  Examples of how this might be done include defining some kind of annotation or pragma that globally affects the safety of all such assignments in an entire P4 program, in addition to annotations that reduce the safety of individual assignments or those in blocks of code.
 
(2)
 
If a field in an invalid header is assigned a value, regardless of whether that header is part of a header union, all metadata, header fields, and header valid$ and nextIndex$ ‘hidden fields’ for the current packet being processed become undefined.
 
It is recommended that a P4 compiler should issue a warning or error message if it detects such an unsafe assignment statement.

**Comment by jafingerhut** [comment]
PR #450 has been merged in, intended to address this issue.  Closing this issue.
