### ISSUE TITLE
Question: Use cases for advance?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#288]
If my understanding of a typical parser and deparser behavior is correct, it seems that advance() has very limited use cases, if any.  Even if this is true, I am not here making any suggestions to change the spec -- just an observation that advance() might not be as useful as some may have originally thought.  Does anyone have any suggested use cases for advance()?

My understanding of the common parser/deparser behavior is that the parser advances through the packet as headers are extract'ed or advance'd past, and whatever part of a packet is _not_ extract'ed or advance'd past becomes the payload (as far as that P4 program is concerned, regardless of what any RFCs or other standards might say).  The deparser emits whatever headers the programmer wants it to, and when the deparser is complete, the typical architecture will then append the payload for that packet after the last emitted header.

If that is correct, then note that any bits of a packet that a parser advance's past _cannot_ later be emitted, and are _not_ part of the payload.  Thus the parser has effectively removed it from the packet, before any table lookups can be done (for architectures where the parser is before any table lookups).

I know there are many valid use cases for removing headers from a packet, but most of those are for things like tunnel decapsulation, and those are only done if the outer headers meet certain conditions that are best checked via table lookups (e.g. the IP destination address is one of several configured as loopback addresses on the router, which would typically be put into the IP route lookup table).

**Comment by mbudiu-vmw** [comment]
We don't have any examples using advance.
Someone asked for it, and it didn't seem like a difficult thing to add, regardless of target.
Also, from a mathematical point of view, this is a reasonable operation to have on streams of bits.

**Comment by vgurevich** [comment]
@jafingerhut ,

One of the examples for advance() is TLV processing, where you might choose to skip over (drop) an unknown element instead of preserving it. Other than that, the mathematical completeness is a good enough reason for met.

**Comment by jafingerhut** [comment]
@vgurevich Thanks for the TLV example -- I can see advance being used in a case like that, without needing table lookups to decide that one wishes to discard part of the packet.
