### ISSUE TITLE
Possible inconsistency with annotation position

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4-spec#289]
Annotations on match key elements come after the key element, while in all other cases, it seems that the annotations come before the object they annotate (e.g. struct fields).
Is there a reason for this?

**Comment by mbudiu-vmw** [comment]
Yes, it is due to the bison grammar.
Putting them in front makes the grammar ambiguous, since the annotation has an optional list of expressions, which could be interpreted as the key expression.
