### ISSUE TITLE
Width declaration a compile-time known value or an integer literal

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4-spec#294]
In P4_16 Language Specification 2017-05-22, Section 7.1.6.2 says:

> An unsigned integer (which we also call a “bit-string”) has an arbitrary width, expressed in bits. A bit-string of width W is declared as: bit<W>. W must be a compile-time known value (see Section 16.1) that evaluates to a positive integer greater than 0.

There is a similar statement in Section 7.1.6.3 regarding signed integers.

Section 16.1 gives an enumeration of productions of compile-time known values, including:

> - Integer literals, Boolean literals, and string literals.
> - The following expressions (+, -, *, / , %, cast, !, &, |, &&, ||, << , >> , ~ ,  >, <, ==, !=, <=, >=, ++, [:]) when their operands are all compile-time known values.

Great, I thought.  I can write

```
header LocID {
  bit<16 - (4 + 3)> panel;
  bit<4> shelf;
  bit<3> item;
}
```

But alas, this does not conform to the grammar in Section E, where it says:

```
baseType
    : BOOL
    | ERROR
    | BIT
    | BIT '<' INTEGER '>'
    | INT '<' INTEGER '>'
    | VARBIT '<' INTEGER '>'
    ;
```

That is, the grammar insists that the width must be an integer literal.

Now, an integer literal is *one* kind of compile-time known value, so Section 7.1.6.2 is not technically wrong, but it is certainly misleading, as it strongly implies that *any* compile-time known value that evaluates to a positive integer greater than 0 would be acceptable.  Otherwise, why even mention it, rather than just simply saying "must be an integer literal greater than 0".

I would definitely prefer the more liberal interpretation of "any compile-time known value", but that requires changing the grammar.

**Comment by jnfoster** [comment]
Good catch and I totally agree. 

Several data structures and early compiler passes will need to be changed. For example, the current [IR](https://github.com/p4lang/p4c/blob/master/ir/type.def#L81) doesn't even allow `size` to be an expression.

**Comment by mbudiu-vmw** [comment]
We have issue https://github.com/p4lang/p4c/issues/47 to track this; at some point we had an implementation supporting arithmetic in bitwidths, but it didn't make it to the current version of the spec/compiler. In fact, this is one reason that the compiler does constant folding before type-checking.
The discussion for the issue above describes some problems with the actual implementation, including ambiguities in the grammar.

**Comment by jnfoster** [comment]
Okay, but we should still make the spec internally consistent. @mbudiu-vmw, which do you prefer: generalize the grammar (beyond what we currently implement) or restrict the informal description?

**Comment by mbudiu-vmw** [comment]
It is a question of time really. If someone signs up to work on issue 47 soon we can change the spec. It wasn't the highest priority item. My estimate for this is about 1.5 days of work. The most unpleasant part is writing a new set of productions for custom expressions in the grammar.

**Comment by jnfoster** [comment]
We need to change the spec either way -- it's internally inconsistent. 

-N
