### ISSUE TITLE
[spec] New wording for the preprocessing section

### ISSUE THREAD

**Issue by jblazquez** [p4lang/p4-spec#30]
This is a proposal for the definition of a new source code preprocessing behavior that obviates the need to use an actual C preprocessor over P4 source files prior to compilation. This wording would replace the contents of the **8.2 Preprocessing** section of the spec.

The most important change here is replacing the **#include** directive with a new **#import** directive that behaves somewhat differently. For example, it's no longer a blind copy-and-paste of the target file.

I think **#include** brings too many undesirable behaviors from C (e.g. include guards, multiply defined symbols, context-dependent parsing, etc) that I think a more modern language shouldn't have.

A prototype implementation of this proposal for the `p4c` compiler can be seen here: https://github.com/p4lang/p4c/pull/68

---
#8.2 Preprocessing

P4 does not support separate compilation or linking: a P4 compiler must be provided a complete P4 program. To aid composition of programs from multiple source files the P4 language supports ~~the following subset of the~~ a small set of preprocessing directives that are inspired by similar C preprocessor functionality:
- **#import**
- **#define** ~~for defining macros without arguments~~ / **#undef**
- **#if** / **#elif** / **#else** / **#endif** ~~/ #ifdef~~
- **#line**

This functionality allows P4 programs to be built from multiple source files, potentially produced by different programmers at different times:
- the P4 core library, produced by the P4 language designers
- the target architecture interfaces, specified by the target manufacturer
- target libraries, describing **extern** blocks provided by the target architecture
- user-defined and other libraries of useful components (e.g, standard protocol header definitions)
- the P4 programs that control programmable functional blocks of a target
## 8.2.1 P4 core library

Similar to the C standard library, the P4 language specification defines a core library, that declares useful P4 constructs. A description of the P4 core library is provided in the Appendix 21. All P4 programs must include the core library.
## 8.2.2 Preprocessor directives

Preprocessor directives begin with the '#' character and must appear at the beginning of a line (ignoring leading whitespace). They always occupy a separate line of source code and may end with a single-line comment.

Preprocessor directives aren't part of the final structure of the program. The grammar definitions used in this section are for explanatory purposes and don't form part of the actual P4 language grammar.
## 8.2.3 Preprocessor definitions

At every point in the program the compiler has a list of preprocessor variables that are currently defined. This includes predefined variables - which are always available - as well as user-defined variables passed to the compiler or defined previously in source code using the **#define** directive.

Preprocessor variables don't carry a value; they can only either be defined or undefined. They may only be used in preprocessor directives and are not otherwise available to the P4 program.
## 8.2.4 Predefined variables

The following table lists preprocessor variables that are implicitly defined by the compiler and available automatically at every point in the program. These variables can't be undefined by the user:

| Name | Description |
| --- | --- |
| `__p4__` | Defined when building P4 source code. |
## 8.2.5 **#import** directive

```
importDirective
    : '#' IMPORT '<' path '>'
    | '#' IMPORT '"' path '"'
    ;
```

The **#import** directive is used to make definitions from another file available to the current file. The effect of an **#import** directive is as if all definitions from the named file, as well as all definitions from transitively imported files, were present in the current file at the point of inclusion.

Preprocessor variables defined in the current file via **#define** directives have no effect on the contents of the imported file, that is, the set of definitions imported by an **#import** directive depends exclusively on global definitions and **#define** directives found in the included file. Similarly, **#define** directives found in the included file have no effect on the current file's preprocessor state.

There are two forms of the **#import** directive: an angle bracket form and a quoted form. They both require a valid relative or absolute path between those separators. The two forms differ when presented with a relative path. The angle bracket form instructs the preprocessor to search for the included file in the system import directories. On the other hand, the quoted form makes the preprocessor first search for the file starting in the including file's directory, and then moves to the system import directories if it wasn't found there.

Multiple **#import** directives that resolve to the same file behave as if only the first **#import** directive were present in the source file. That is, importing a given file multiple times has no effect.
## 8.2.6 **#define** / **#undef** directives

```
defineDirective
    : '#' DEFINE name
    ;

undefDirective
    : '#' UNDEF name
    ;
```

The **#define** directive makes a new definition available from the point of definition to the end of the current source file. A **#define** directive that defines an already-defined variable has no effect.

The **#undef** directive removes a variable definition, making it unavailable from that point to the end of the current source file. An **#undef** directive that references an undefined variable has no effect.

The **#define** and **#undef** directives must appear at the beginning of a source file before any other program tokens. This doesn't include comments or other preprocessor directives, which can appear before a **#define** or **#undef**.
## 8.2.7 **#if** / **#elif** / **#else** / **#endif** directives

```
ifDirective
    : '#' IF ppExpression
    ;

elifDirective
    : '#' ELIF ppExpression
    ;

elseDirective
    : '#' ELSE
    ;

endifDirective
    : '#' ENDIF
    ;

ppExpression
    : name
    | '(' ppExpression ')'
    | '!' ppExpression
    | ppExpression AND ppExpression // &&
    | ppExpression OR ppExpression  // ||
    ;
```

The **#if** directive is used for conditional compilation and it defines a region of code that will be parsed only if the associated expression evaluates to **true**. The affected code is the region from the line following the **#if** directive to the line preceding the next matching **#elif**, **#else** or **#endif** directive.

The **#elif** directive is used to provide a new condition to test when the previous **#if** or **#elif** directive evaluated to **false**. The **#else** directive is used to include a region of code only if the previous condition evaluated to **false**.

Every **#if** directive must be followed by zero or more **#elif** directives, then by an optional **#else** directive, and finally one **#endif** directive. It's possible to nest conditional compilation blocks.

The expression in an **#if** or **#elif** directive involves one or more preprocessor variables and can only contain the logical operators **!**, **&&** and **||**. These operators have the same precedence rules as they have in regular P4 expressions. Preprocessor variables evaluate to the logical value **true** if they are defined and evaluate to **false** otherwise.
## 8.2.8 **#line** directive

```
lineDirective
    : '#' LINE INTEGER
    | '#' LINE INTEGER STRING_LITERAL
    ;
```

The **#line** directive is used to provide the compiler with mapping information that can be used to translate locations in the input source file to locations in the original source file. This is useful to provide better diagnostics when the input source file was generated from another file, potentially written in a different language.

The **#line** directive provides a line number and optionally the original source file name that apply to the block of source code following it. The compiler applies the new line numbering starting with the next source code line.

---

Below is my original proposal's wording:

---
#8.2 Preprocessing and compilation (ORIGINAL PROPOSAL)

P4 does not support separate compilation or linking: a P4 compiler must be provided a complete P4 program as a set of input source files. These source files must contain a definition for all the declarations used throughout the program, with the exception of declarations from the standard library which are always available.

This functionality allows P4 programs to be built from multiple source files, potentially produced by different programmers at different times:
- the P4 core library, produced by the P4 language designers
- the target architecture interfaces, specified by the target manufacturer
- target libraries, describing **extern** blocks provided by the target architecture
- user-defined and other libraries of useful components (e.g, standard protocol header definitions)
- the P4 programs that control programmable functional blocks of a target

To aid ~~composition of programs from multiple source files~~ conditional compilation of source code the P4 language supports a small set of preprocessing directives that are inspired by similar C preprocessor functionality:
- **#define** ~~for defining macros without arguments~~ / **#undef**
- **#if** / **#elif** / **#else** / **#endif** ~~/ #ifdef~~
- **#line**
## 8.2.1 P4 core library

Similar to the C standard library, the P4 language specification defines a core library~~,~~ that declares useful P4 constructs. A description of the P4 core library is provided in the Appendix 21. All P4 programs ~~must~~ include the core library implicitly.
## 8.2.2 Preprocessor directives

Preprocessor directives begin with the '#' character and must appear at the beginning of a line (ignoring leading whitespace). They always occupy a separate line of source code and may end with a single-line comment.

Preprocessor directives are consumed by the lexer and aren't part of the final structure of the program. The grammar definitions used in this section are for explanatory purposes and don't form part of the actual P4 language grammar.
## 8.2.3 Preprocessor definitions

At every point in the program the compiler has a list of preprocessor variables that are currently defined. This includes predefined variables - which are always available - as well as user-defined variables passed to the compiler or defined previously in source code using the **#define** directive.

Preprocessor variables don't carry a value; they can only either be defined or undefined. They may only be used in preprocessor directives and are not otherwise available to the P4 program.
## 8.2.4 Predefined variables

The following table lists preprocessor variables that are implicitly defined by the compiler and available automatically at every point in the program. These variables can't be undefined or redefined by the user:

| Name | Description |
| --- | --- |
| `__p4__` | Defined when building P4 source code. |
## 8.2.5 **#define** / **#undef** directives

```
defineDirective
    : '#' DEFINE name
    ;

undefDirective
    : '#' UNDEF name
    ;
```

The **#define** directive makes a new definition available from the point of definition to the end of the current source file. A **#define** directive that defines an already-defined variable has no effect.

The **#undef** directive removes a variable definition, making it unavailable from that point to the end of the current source file. An **#undef** directive that references an undefined variable has no effect.

The **#define** and **#undef** directives must appear at the beginning of a source file before any other program tokens. This doesn't include comments or other preprocessor directives, which can appear before a **#define** or **#undef**.
## 8.2.6 **#if** / **#elif** / **#else** / **#endif** directives

```
ifDirective
    : '#' IF ppExpression
    ;

elifDirective
    : '#' ELIF ppExpression
    ;

elseDirective
    : '#' ELSE
    ;

endifDirective
    : '#' ENDIF
    ;

ppExpression
    : name
    | '(' ppExpression ')'
    | '!' ppExpression
    | ppExpression AND ppExpression // &&
    | ppExpression OR ppExpression  // ||
    ;
```

The **#if** directive is used for conditional compilation and it defines a region of code that will be parsed only if the associated expression evaluates to **true**. The affected code is the region from the line following the **#if** directive to the line preceding the next matching **#elif**, **#else** or **#endif** directive.

The **#elif** directive is used to provide a new condition to test when the previous **#if** or **#elif** directive evaluated to **false**. The **#else** directive is used to include a region of code only if the previous condition evaluated to **false**.

Every **#if** directive must be followed by zero or more **#elif** directives, then by an optional **#else** directive, and finally one **#endif** directive. It's possible to nest conditional compilation blocks.

The expression in an **#if** or **#elif** directive involves one or more preprocessor variables and can only contain the logical operators **!**, **&&** and **||**. These operators have the same precedence rules as they have in regular P4 expressions. Preprocessor variables evaluate to the logical value **true** if they are defined and evaluate to **false** otherwise.
## 8.2.7 **#line** directive

```
lineDirective
    : '#' LINE INTEGER
    | '#' LINE INTEGER STRING_LITERAL
    ;
```

The **#line** directive is used to provide the compiler with mapping information that can be used to translate locations in the input source file to locations in the original source file. This is useful to provide better diagnostics when the input source file was generated from another file, potentially written in a different language.

The **#line** directive provides a line number and optionally the original source file name that apply to the block of source code following it. The compiler applies the new line numbering starting with the next source code line.

---

**Comment by apinski-cavium** [comment]
I think this should be reopened and either remove all references of the preprocessor directives or expanded on.  Some of the P4 integer constants won't work with C preprocess constants.  Plus things like defined() is not documented to be there even though I suspect it was expected to be supported inside #if.  Also undefined identifiers turning into 0 is not documented even though that is a standard part of C preprocessor.
Also there is no definition of should in the spec so is this optional but recommended?

**Comment by mbudiu-vmw** [comment]
Perhaps instead of reopening this one we should start a new discussion. This is a long thread; we should focus on the relevant parts only. Please feel free to create a new issue (or more).

**Comment by mbudiu-vmw** [comment]
BTW: we always hoped we would have a new custom preprocessor, and one of the early pull requests against the compiler had a new preprocessor (it wasn't merged), but we never spent enough time to design it.
