### ISSUE TITLE
[PSA] Unit of truncate operation

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#303]
The sentence below describing the truncate operation should specify
the units of the length, e.g. bits?  bytes?

    "The length parameter represents the packet length."

**Comment by jafingerhut** [comment]
Other questions that should be answered in the PSA spec, I think:

I will assume here that the unit of the truncate() operation is in bytes, and can be any number of bytes.

If one calls truncate(64) in the egress pipeline (if it is even allowed in the egress pipeline), does that mean that the entire packet as sent out of the deparser will be at most 64 bytes, even if that would chop it off in the middle of a header that is explicitly deparsed for this packet?

If one call truncate(64) in the ingress pipeline, does that affect the packet as it is written into the packet buffer before egress in any way that affects the packet as received by the egress pipeline?  Or does it only affect the packets as they go out of the egress pipeline?  Something else?

What is the minimum value N for which truncate(N) is guaranteed to work?  truncate(0) and truncate(1) seem pretty useless, unless the truncate affect only starts after the last deparsed header.

**Comment by cc10512** [comment]
@jafingerhut I do not think it is a good idea to truncate headers. And in any case, for headers we have remove_header primitives to "truncate" the size of packet headers. I believe that truncate should refer to payload only. The unit should be in bytes, and in that case, does it make sense to have truncate(0) to fully remove the payload?

**Comment by jnfoster** [comment]
+1

-N
