### ISSUE TITLE
[PSA] question on random hash algorithm

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#305]
Regarding this question: "are random hash algorithms useful?"  It is
not clear to me what is meant by a random hash algorithm.  If you mean
"a random value that is independent of the content of the packet and
its metadata", then that sounds like a pseudo-random number generator,
which is useful for things like implementing RED and similar
algorithms with randomized choices.  If you mean a hash algorithm that
takes as input some kind of "seed" value that is randomly generated,
plus some header fields, but the result is a deterministic function of
the seed and the header/metadata values, then that can be described as
a normal deterministic hash function with some input bits that were
randomly generated, and I would recommend it be implemented that way.
If something else is meant, better to add more detail to the question.

**Comment by jafingerhut** [comment]
@cc10512 Do you know who wrote the question "are random hash algorithms useful?" in the PSA draft?  If it was you, do you have any thoughts on this?

**Comment by vgurevich** [comment]
Actually the current semantics is "an algorithm that a compiler picks for you in some fashion", so it is more like "any"/"auto"/"don't really care because anything will do".
