### ISSUE TITLE
[PSA] counter size S

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#307]
For counters that have a number of counters that is an exact power of
2, e.g. 1024, a single type S that is bit<10> is just right for the
'index' parameter to 'count', but it is 1 bit too small for the
'n_counters' parameter of the constructor.  Might be good to have a
separate type for the 'n_counters' paremeter?

**Comment by jafingerhut** [comment]
Latest PSA draft as of today has changes that address this comment, by always using bit<32> type for n_counters.
