### ISSUE TITLE
[PSA] Direct counter

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#311]
If direct counters with a byte count are intended to be supported, it
should be specified what byte count is used for a packet.  Note:
Someone will be unhappy with the choice in at least some situations,
no matter what you choose.  You could recommend using simply packet
counters if they don't like the specified choice, or use an explicit
counter that is not direct, where they get to choose the length
themselves.

**Comment by jafingerhut** [comment]
This PR proposes relevant changes: https://github.com/p4lang/p4-spec/pull/348

**Comment by jafingerhut** [comment]
The latest PSA master version as of today addresses this question by explicitly documenting that the length in bytes that is added when updating a byte counter is implementation-specific, and should be documented by the implementation.
