### ISSUE TITLE
[PSA] Random distribution enums

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#313]
"PRNG" as a choice for "RandomDistribution" doesn't mean anything to
me.  "Uniform" has a well-defined meaning in pseudo-random number
generation, and seems a better name to use, if that is what "PRNG" was
intended to mean.  I have commented before elsewhere that supporting
_only_ uniform seems quite reasonable.  If a P4 program writer wants a
non-uniform distribution, there are multiple ways to achieve that,
such as doing arithmetic on the uniformly generated value to make the
results non-uniform, or also performing a table lookup using the
uniform random value as the search key, so the control plane can
create whatever distribution it wishes.

**Comment by jafingerhut** [comment]
Proposal:

+ Remove the type 'RandomDistribution' enum definition, and remove argument 'dist' from extern Random's constructor method.  Specify that all Random externs return pseudo-randomly generated values that are as close to uniformly distributed in the range [min, max] (inclusive) as the implementation can achieve.  For example, if the implementation is limited to generating 32-bit values uniformly in the range [0, 2^32-1], and a program constructs a Random object with min=0 and max=(3/4)*(2^32), the best that implementation can probably achieve is to have 1/3 of the results be twice as likely to occur as the other 2/3, e.g. by returning (32-bit random value) % ((3/4) * (2^3))

+ Recommend that P4 programmers wishing to generate values non-uniformly do so by first generating a uniform random value, then doing arithmetic on the result and/or table lookup operations to create the desired non-uniform random value.  Consider giving some potentially useful examples of this.

**Comment by cc10512** [comment]
We decided at the Sept 7 meeting that uniform is sufficient for PSA's needs (https://github.com/p4lang/p4-spec/wiki/PSA-Meeting-Minutes-Sep-7,-2017#random-number-generation--what-should-psa-support)

**Comment by cc10512** [comment]
Fixed by #435.
