### ISSUE TITLE
[PSA] programmable block metadata

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#314]
In the section on 'Programmable blocks', it would be best if the
following things were specified explicitly.

+ The original value of fields inside 'user_meta' when the Parser is
  invoked.  Are they all undefined?

+ Is every field of 'hdr' and 'user_meta' given as input to
  VerifyChecksum supposed to be identical to the result output by
  Parser?  If so, best to say it explicitly.  Similarly for the rest of the pipeline.

+ An implementation will likely have limits on how much data it can
  pass through the packet buffer in the PRE.  Should the PSA spec say
  any words about this, and how it affects P4 program writers?  For
  example, it could affect the portability of programs quite significantly
  if some programs expect they can carry 1000 bits of user-defined
  metadata with values written in the ingress control block, and have
  them all available in the egress block for use.

**Comment by cc10512** [comment]
No longer relevant.
