### ISSUE TITLE
[PSA] getHash() base and max arguments.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#322]
It would be nice if the behavior of getHash() could be specified more formally. What is "base", what is "max", how are they used? The usage example (BTW, is it really allowed to instantiate hash engine in the parser?) does not match the definition of the extern. Also, it is not clear how a 56-bit hash can be generated using crc16 algorithm.

**Comment by jafingerhut** [comment]
Perhaps the 'base' and 'max' are intended to implement modulo behavior as P4_14 had for its modify_field_with_hash_based_offset primitive operation?

**Comment by jafingerhut** [comment]
Should be fixed with this commit: https://github.com/p4lang/p4-spec/commit/0aae596698144f4897984550b937467af6e42218
