### ISSUE TITLE
[PSA] meter and register initial state

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#324]
Meters and registers: what's the initial state?

**Comment by jafingerhut** [comment]
Proposal:

For meters, the primary dynamic state I am aware of is the number of tokens/bytes allowed to be permitted by the meter as GREEN or YELLOW result before RED is hit.  The most reasonable initial state I can think of for that would be the maximum burst size configured for the meter.

For registers, every register can be used to implement a completely unique feature that the compiler has no way of knowing.  The two most reasonable initial values I can think of are:
+ all 0, or
+ a value specified in some annotation of the P4 program, annotated on the register constructor call, or perhaps an additional argument to the register constructor.

**Comment by vgurevich** [comment]
For an unprogrammed meter, I'd suggest either always return GREEN, that way, if it's not programmed it is not really visible. 

Alternatively, it can always return RED -- a little safer, but a lot more annoying choice.

+1 on registers.

**Comment by cc10512** [comment]
At the risk at shooting ourselves in the foot and let undefined slip in, there is also the option of allowing the target implementation define what is the initial value, and if the PSA programmer wishes a particular value, then she should set it with the appropriate control plane API.

**Comment by jafingerhut** [comment]
@cc10512 Definitely.  For the contents of tables and externs with a significant amount of state, it is likely going to be control plane software that will be the actual determining factor in what the state is that the P4 program 'sees' when it processes its first packet after booting up a system.

**Comment by DGeorgeNetro** [comment]
I like @vgurevich "For an unprogrammed meter, I'd suggest either always return GREEN, that way, if it's not programmed it is not really visible." The exact state of a programmed meter should be opaque to the user so I don't think it needs to be specified; the meter must just behave as specified from the runtime.

**Comment by DGeorgeNetro** [comment]
I like:
"perhaps an additional argument to the register constructor." 

Being able to have the register initialized in the program mitigates potential races between traffic being affected by the value and the runtime populating the value.
