### ISSUE TITLE
[PSA] Parser enums

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#326]
ParserStatus_t -- how exactly it relates to the predefined "error" type?
What is ParserErrorLocation_t?

**Comment by jafingerhut** [comment]
If no one wants to keep ParserErrorLocation_t in psa.p4 -- it isn't used anywhere else in the PSA spec nor in the example code -- I would recommend we delete the only mentions of it from psa.p4 and close this issue.

**Comment by vgurevich** [comment]
+1

**Comment by jafingerhut** [comment]
@cc10512 @hanw Do you know who proposed adding ParserErrorLocation_t to the PSA, and whether they want to keep it?

**Comment by hanw** [comment]
Probably @cc10512, I think we can remove it.

**Comment by hanw** [comment]
It's used to encode which parser state triggers the parser error, which does not have a use case, AFAIK.

**Comment by jafingerhut** [comment]
I have created this PR that removes ParserErrorLocation_t type, and adds a note of how a P4 programmer can add explicit parser code to update metadata fields, if they wish to record information about where a parser error occurred: https://github.com/p4lang/p4-spec/pull/402

If that PR is merged in, I believe this issue can be closed.

**Comment by jafingerhut** [comment]
PR #402 was approved and merged, so closing this issue.
