### ISSUE TITLE
[PSA] Should PRE be defined to have multiple class-of-service queues per output port?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#334]
It is a relatively common feature for a queueing system to have multiple queues per output port, not merely one queue per port.  Perhaps the PSA could have a constant that is part of the architecture spec, that could vary across implementations, that gives the maximum number of queues per output port, and a way to specify not only which output port a packet is enqueued for after ingress, before egress, but also which class-of-service queue for that output port?

**Comment by jnfoster** [comment]
See my comment on #335

**Comment by jafingerhut** [comment]
In 2017-Aug-07 PSA work group meeting, the decision was made to include in the PSA a standard way to specify a class-of-service queue number from P4 code.  A PSA implementation need only support 1 queue per output port to be compliant, but it is allowed to support more, e.g. N queues per output port, where N is implementation-specific.

Details: Add a control plane API for reading the value N from the device.  Specify the behavior is the P4 code gives a class-of-service value that is outside of the range supported by the device, perhaps being a clean drop of the packet with no other harmful effects, and an optional error status register that counts the number of times such a drop has occurred, and a queue of 1 or more of the first class-of-service values this occurred for.

**Comment by jafingerhut** [comment]
PR created for one proposed way of adding this to PSA: https://github.com/p4lang/p4-spec/pull/403

Please read and comment on it if you are interested in this topic.

**Comment by jafingerhut** [comment]
The PR mentioned in the previous comment: https://github.com/p4lang/p4-spec/pull/403

has now been merged in after review and addressing at least most of the comments in the P4 Arch working group.  Closing this issue.  Feel free to open a new issue if you have questions or suggested changes for the latest PSA draft.
