### ISSUE TITLE
[PSA] Parser value sets in PSA even possible without modifying P4_16 spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#337]
@vgurevich You mentioned the idea of adding parser value sets to the PSA during the p4-arch meeting on 2017-Jun-26.  I reviewed the part of the P4_14 spec on those, which had no examples, so I looked in the p4lang repositories and found only these examples in test programs:

* https://github.com/p4lang/PI/blob/master/tests/testdata/pragmas.p4#L19-L28
* https://github.com/p4lang/behavioral-model/blob/master/tests/testdata/parse_vset.p4#L21-L40

I have not thought of any way that this functionality could be added to P4_16 without changing the spec, so I do not see how you expect to add this to the P4_16 PSA.  Do you have any thoughts on that?

**Comment by cc10512** [comment]
@jafingerhut did you also see this discussion: https://github.com/p4lang/p4-spec/issues/65? I believe that the thought is to encapsulate that proposal into a standalone extern.

**Comment by jafingerhut** [comment]
I had not seen that discussion before, but I have read through it now.  It isn't clear to me which of the alternatives discussed in that issue was decided to be implemented.  Also, it isn't clear that whatever was decided upon in that discussion actually made it into the spec.  Do you know?

**Comment by cc10512** [comment]
I believe the compiler currently supports having a set<T> type and using a member function to select on. AFAIK, he implementation is what @mbudiu-vmw posted here: https://github.com/p4lang/p4-spec/issues/65#issuecomment-256967699.

**Comment by jafingerhut** [comment]
If that is intended to work, then I think it would be a very good idea to mention it somewhere in the P4_16 spec.  It is quite easy to take away from the P4_16 spec that every set expression in a 'transition select' statement is a compile time constant expression.

**Comment by jnfoster** [comment]
@jafingerhut, I could be wrong, but my recollection of the "Option 1" we settled on in #65 did not include relaxing the language to require support for expressions as labels. (Although we left the door open to exploring that in the future.) @mbudiu-vmw should confirm.

So for a strictly spec-compliant and portable implementation, you'd have to do the somewhat tedious plumbing shown in Mihai's earlier examples in that thread, where the labels are all compile-time-known-constants.

**Comment by mbudiu-vmw** [comment]
One cannot have variables of type set even in theory.
Currently the compiler does not handle side-effects in select labels, and the bmv2 backend requires constant labels.

**Comment by jafingerhut** [comment]
As a follow-up to my earlier comment, the P4_16 v1.0.0 spec does already say this: "Some targets may require that all keyset expressions in a select expression be compile-time known values."  I haven't noticed any place yet where it explains how one might construct a select expression that is not a compile-time known value, but as @mbudiu-vmw said, perhaps the spec does not include any such ways today.

**Comment by jnfoster** [comment]
The grammar allows arbitrary expressions as labels to selects.
```
simpleKeysetExpression
    : expression
    | DEFAULT
    | DONTCARE
    | expression MASK expression
    | expression RANGE expression
    ;
```

**Comment by jafingerhut** [comment]
@jnfoster So are you saying that you believe that the P4_16 v1.0.0 spec does allow a program fragment like the one in this comment, where a key expression could be <extern_object_name>.<extern_method_name>()?  https://github.com/p4lang/p4-spec/issues/65#issuecomment-256967699

**Comment by hanw** [comment]
Just putting a concrete example here, following example works with p4test.
```
extern ValueSet<T> {
    ValueSet();
    T members();
}

ValueSet<bit<16>>() trill;

parser ParserI(packet_in b,
               out headers hdr,
               out metadata meta,
               out ingress_intrinsic_metadata_t ig_intr_md) {

    state start {
        b.extract(hdr.data);
        transition select(hdr.data.h1) {
            trill.members() : accept;
            default : accept;
        }
    }
}
```

**Comment by jafingerhut** [comment]
@hanw @jnfoster Looks like Han answered my question as a definite "yes", although I fully realize that being accepted by "p4test" doesn't necessarily imply today that it is accepted by p4c-bm2-ss and implemented in bmv2.

**Comment by jnfoster** [comment]
I think Mihai answered the other question "the bmv2 backend requires constant labels". Obviously this could be changed if someone was inspired...

And yes, we don't need to change P4_16 itself to include something like ValueSet in PSA and have it be useful...

**Comment by vgurevich** [comment]
I guess, I'll rest for a while :), but, @jafingerhut , if you like perhaps we can have an offline discussion :)

**Comment by jafingerhut** [comment]
@vgurevich I believe that the result of this discussion is that you got what you wanted in the P4-16 spec, i.e. the ability to write code for parser value sets like in the example above by @hanw.  If we define a ValueSet extern in the PSA, and agree on its methods and at least part of its control plane API, we should be done with this issue.

**Comment by vgurevich** [comment]
I agree, that as it was previously discussed,  it is possible to construct an extern that will do the job (albeit slightly differently from P4_14 way) without any changes to the language. I believe that final proposal was slightly different from what @hanw put above (his code looks more like the initial proposal to me). 

Specifically, the idea was to have an extern that will consume some number of bits (i.e. what you normally put in the select()) and return 1 (or True) if there is a match. How this match will be determined (a list of values (how long?), a list of ternary matches, a list of ranges, a formula, etc.) can be either left out or standardized by defining control plane API (or at least a schema for the data). 

In any case, we just need to put something in the spec and make sure it is reasonable.

**Comment by hanw** [comment]
@vgurevich Is this example closer to what you had in mind? (from p4c/testdata/p4_16_samples/value-sets.p4)

```
extern ValueSet {
    ValueSet(bit<32> size);
    bit<8> index(in bit<16> proto);
}

#define ETH_KIND_TRILL 1
#define ETH_KIND_TPID  2

parser TopParser(packet_in b, out Parsed_packet p) {
    ValueSet(5) ethtype_kinds;
    state start {
        b.extract(p.ethernet);
        transition select(p.ethernet.etherType) {
            16w0x0800: parse_ipv4;
            16w0x0806: parse_arp;
            16w0x86DD: parse_ipv6;
            default: dispatch_value_sets;
        }
    }

    state dispatch_value_sets {
        bit<8> setIndex = ethtype_kinds.index(p.ethernet.etherType);
        transition select(setIndex) {
            ETH_KIND_TRILL: parse_trill;
            ETH_KIND_TPID: parse_vlan_tag;
        }
    }
```

**Comment by vgurevich** [comment]
@hanw ,

This one represents an intermediate option that was discussed and later rejected. Here is the code that represents what we agreed to finally. 

Not that I am super in-love with it (the code is a little cumbersome and will require compiler optimization), but that's the only way we found so far to make sure the feature can be implemented relatively efficiently and without unnecessary HW dependencies.


```
extern ValueSet<S,D> {
    ValueSet<D>(S size);
    bit<1> is_member(in D data);
}

parser TopParser(packet_in b, out Parsed_packet p) {
    ValueSet<bit16>>(1) trill_types;
    ValueSet<bit<16>>(4) tpid_types;

    state start {
        b.extract(p.ethernet);
        transition select(p.ethernet.etherType) {
            16w0x0800: parse_ipv4;
            16w0x0806: parse_arp;
            16w0x86DD: parse_ipv6;
            default: dispatch_tpid_value_set;
        }
    }
    state dispatch_tpid_value_set {
        bit<1> is_tpid = ethtype_kinds.is_member(p.ethernet.etherType);
        transition select(is_tpid) {
            1: parse_vlan_tag;
            default /* or 0 */: dispatch_trill_value_set;
        }

    state dispatch_trill_value_set {
        bit<1> is_trill = ethtype_kinds.is_member(p.ethernet.etherType);
        transition select(is_trill) {
            1: parse_trill;
            default /* or 0 */: accept;
        }
    }
```

**Comment by hanw** [comment]
With some clean up on the extern definition, here is what a `value_set` looks like.
```
extern value_set<D> {
   value_set(int size);
   bool is_member(in D data);
}
```

This is also another motivating example for issue #331 that it would be nice to allow user to use `int` as a type for constants.

**Comment by vgurevich** [comment]
Thanks, Andy!

I totally agree that `bool` is cleaner. 

I am still not quite sure, but it feels to me that the constructor need to be templated(ized?) by the same type that will be passed into the is_member() method. The reason is that this constructor is going to do resource allocation and the width of that type D is an important input to that allocation.

**Comment by hanw** [comment]
The compiler grammar does not require typeParameter on constructor method prototype.
```
extern ValueSet<D> {
    ValueSet<D>(bit<8> size);
    bool is_member(in D data);
}
```
gives a frontend parsing error.
```
../../p4-tests/p4_16/min.p4(20):syntax error, unexpected (
    ValueSet<D>(
               ^
error: 1 errors encountered, aborting compilation
```

But since we do not support `int` as a type yet, we will have to do either:
```
extern value_set<D> {
    value_set(bit<32> size);
    bool is_member(in D data);
}
value_set<bit<16>>(4) vs;
```

or 
```
extern value_set<S, D> {
    value_set(S size);
    bool is_member(in D data);
}

value_set<bit<3>, bit<16>>(4) vs;
```

**Comment by vgurevich** [comment]
@jafingerhut 

I like the last option the most. It just seems weird that the types are present in the first line of the extern definition, but not in the constructor itself, even though we then use them to call that constructor...

**Comment by jafingerhut** [comment]
I understand getting Andy Keep and Andy Fingerhut mixed up (both from Cisco, even!), but @hanw may start wondering who you are conversing with :-)

**Comment by jafingerhut** [comment]
I created this PR with some proposed changes to add ValueSet extern to PSA spec: https://github.com/p4lang/p4-spec/pull/354

**Comment by jafingerhut** [comment]
The pull request has been committed to the draft PSA spec: https://github.com/p4lang/p4-spec/pull/354

Thus closing this issue.  If there are any suggested changes to that section of the spec, they can be made via separate issues.
