### ISSUE TITLE
Crazy idea: run-time int values

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4-spec#347]
The spec permits `int` literals but forbids the declaration of `int` run-time values for the very good reason that hardware cannot plausibly handle infinite-precision values.

But, you know, if we wanted to entertain a wild and crazy idea, we could permit `int` declarations for run-time values with the semantics that the allocated width would be big enough to handle any value that could actually happen during run-time.  This of course requires a solver to determine "big enough" and some P4 programs will not have a fixed point. But many useful programs would.

Since headers have to parse from an input bit stream, `int` would not be permitted in headers.  But variables could be `int` and structs and tuples could contain `int` fields.  It would be convenient to add implicit casts to permit assigning any `int<w>` or `bit<n>` to an `int`, with the minimum width of the `int` being constrained as >=w or >n respectively.  Arithmetic operations on `int` run-time values would follow worst-case minimum width requirements.  Examining the entire program, a solver would have to produce a solution to all of the minimum width requirements.

Because P4 does not permit loops or recursion, the set of executions is finite.  Variable uses can be expanded out into static single-assignment form (the &#981; operator just takes the worst-case minimum width).  The only way to induce data loops is through externs that can pass data from one execution to another.  So there would only be a problem if such data were declared `int`.  (Such as a register whose data type was `int`.)  This seems unlikely to be a significant objection.

In particular, this idea would solve the counter/meter method index argument problem brought up by Chris in https://github.com/p4lang/p4-spec/issues/331 and p4lang/p4c#764.  One would just write:

```P4
extern counter {
  counter(int size, CounterType type);
  void count(in int index);
}
```

and all uses of `count` for a given counter would be examined to determine what the minimum width of that counter's `int index` would have to be.

As I said, a crazy idea.

**Comment by jnfoster** [comment]
In fact, P4_14 already does something quite similar to this. There are no types, but the Python implementation infers types from the code -- when it needs to satisfy two constraints, it takes the wider one. 

So... I like this idea too :-)

On the other hand, I also think it's fine to treat this extension as low-priority given that the current restrictions are not too onerous and there are lots of other things to do / fix.

**Comment by mbudiu-vmw** [comment]
I would prefer a programming style where the resources required are readily apparent from the code.

**Comment by mbudiu-vmw** [comment]
I will close this issue.
