### ISSUE TITLE
verifyChecksum semantics

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4-spec#360]

**Comment by jafingerhut** [comment]
With recent commits to the PSA spec, I think this issue has been resolved with the following answers: There is no separate verifyChecksum control block in PSA.   All (or at least most) checking of header checksums is expected to be performed in the parsers, setting some kind of result for use in the following Ingress or Egress control block, such as the parser error.  The Ingress and Egress control blocks are expected to check for parser errors, if desired, and then also perform the desired actions on packets that experienced errors during parsing.

This issue can be closed then, I think?

**Comment by jafingerhut** [comment]
@cc10512 I think this issue can be closed now, with recent commits to the draft PSA spec?

**Comment by cc10512** [comment]
Agreed.
