### ISSUE TITLE
Question: Should it be possible to pass externs to controls as a parameter?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#361]
In v1model.p4 the extern packet_in is passed to the Parser: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L149 and similarly the extern packet_out is passed to the Deparser.

These things also occur in the current draft psa.p4, and in addition, an extern of type PacketReplication is passed to the Ingress control: https://github.com/p4lang/p4c/blob/master/p4include/psa.p4#L558

I do not necessarily _want_ to do this in my own P4_16 programs, but was curious to know whether it is legal to write my own controls that can take references to externs as parameters (and if that is the correct way to think about the examples above).

I tried to write a test program to see if the current p4test code compiles it, and wrote this: https://github.com/jafingerhut/p4-guide/blob/master/instantiation/extern-ref.p4#L64-L70

The 2017-Jul-19 version of p4test gives the error below when I tried to compile that program:
```
extern-ref.p4(70): error: Could not find declaration for rand
        my_headers.ethernet.srcAddr[47:38] = ~rand.read();
                                              ^^^^
```
Is this only allowed for some externs, but not others?

If so, how does the compiler determine which ones to allow?

If it should be possible to do, am I seeing a compiler bug, or am I writing the program incorrectly?

If it is possible to do, does this make program analysis of where externs can be accessed any more challenging for a compiler?

Is it intended to be allowed to pass controls as parameters to other controls?

**Comment by jnfoster** [comment]
> Is this only allowed for some externs, but not others?

All externs should behave the same way wrt parameter passing

> If so, how does the compiler determine which ones to allow?

N/A

> If it should be possible to do, am I seeing a compiler bug, or am I writing the program incorrectly?

Compiler bug.

> If it is possible to do, does this make program analysis of where externs can be accessed any more challenging for a compiler?

Yes, but I don't see why a conservative analysis wouldn't be sufficient for most of the compiler problems I can imagine... 

> Is it intended to be allowed to pass controls as parameters to other controls?

As constructor parameters, yes.

**Comment by jafingerhut** [comment]
Thanks for the answers.  I went back to re-read a few parts of the P4_16 spec to see if it is explicit whether this is allowed, and it appears that it is (if I read carefully enough).  In the "Calling convention" section, it says that parameters with no direction can be a compile-time known value (and a couple of other possibilities that are irrelevant to this example).

In the section "Compile-time known values", one of the possibilities listed is "Instances constructed by instance declarations and constructor invocations".

It appears like my example falls into this case.  Does that sound correct?

Would it be correct to describe this kind of passing as 'by reference' rather than copy-in/copy-out?

Do you think it should be allowed for a control that receives an extern as a parameter, to then itself call <control_name>.apply() on another control, and pass that parameter to it?  I guess that would also be the same kind of compile-time known value as the first call (an instance constructed by instance declarations), even though different calls at run time might refer to different instances?

**Comment by jnfoster** [comment]
1. A little later, there's a sentence that I think clarifies exactly what's going on here.

> When used as arguments, extern objects can only be passed as directionless parameters—e.g., see the packet argument in the very simple switch example.

Possibly the text on directionless parameters could be edited to note that compile-time known values include instantiations of extern objects.

2. 

> Would it be correct to describe this kind of passing as 'by reference' rather than copy-in/copy-out?

Since the value being copied in/out by the invocation is a reference to the extern object which cannot be modified, is there a difference?

3. 

> Do you think it should be allowed for a control that receives an extern as a parameter, to then itself call <control_name>.apply() on another control, and pass that parameter to it? I guess that would also be the same kind of compile-time known value as the first call (an instance constructed by instance declarations), even though different calls at run time might refer to different instances?

Yes, I think it is allowed.

**Comment by jafingerhut** [comment]
I agree that copy-in/copy-out of a reference is pretty much identical to 'by reference'.

But it isn't obvious to me that the P4_16 spec says that what is being passed is a reference to the extern instance.

I mean, this is maybe again a difference that makes no difference in the language semantics, but if it was copy-in/copy-out of the entire hidden state of the extern, that can be a huge amount of state.  I can't think of any examples of code and call/apply sequences where passing an extern by reference would be different than copy-in/copy-out of its entire hidden state, but I wouldn't be surprised if there were such an example.

**Comment by jnfoster** [comment]
I don't think the data plane has any visibility into the state of extern objects so I wouldn't see how to do anything other than treat it as a reference. 

I agree the spec is not clear on this point.

Before we go about thinking how to clarify, however, perhaps @mbudiu-vmw can weigh in...

**Comment by mbudiu-vmw** [comment]
copy-in/out and by reference have different semantics.
You can talk of something being passed "by reference" only if it is stored in memory (traditionally the reference is the address where something is allocated).
For some architectures the externs are in fact real pieces of hardware that gets allocated. So there is no "reference" to speak of. 

I can tell you that the inliner simply replaces these textually in the callee (as in call-by-name).

**Comment by jnfoster** [comment]
Now I'm more confused. 

Let's see if we can make sense of it with an example.

```
extern Counter { 
   ... 
   bit<8> get();
   void increment();
   ...
}

control MyControl(Counter c1, Counter c2) { 
  apply { 
    c1.increment();
    c2.increment();
  }
}

control Main(out bit<8> x) {
  MyControl() myc; 
  Counter() c;
  myc.apply(c,c);
  x = c.get();
}
```
What is the value of `x` when `Main.apply(x)` is executed?

**Comment by mbudiu-vmw** [comment]
After inlining you will have two increments on counter c.
x should be 2. I am not sure you can actually run this in bmv2 though.

**Comment by jnfoster** [comment]
Fine but... isn't that result consistent with call-by-reference and not copy-in-copy out? If it were copy-in-copy-out then I would expect the implementation to somehow create two copies of `c`, and its state, pass those to `MyControl` and copy them back (in some order). Hence, the result would just be `1`.

(Unless I'm missing something essential with the computational model for externs.)

**Comment by mbudiu-vmw** [comment]
Yes, I said that the semantics of this call is not the same as copy-in/copy-out.
It looks like call-by-reference in other languages.
One difference, for example, is that the callee cannot save the reference for later use.

**Comment by jnfoster** [comment]
Okay, I think I understand.

We should work on improving the text to make this clearer before the next release of the spec.

**Comment by jafingerhut** [comment]
@jnfoster Following up on a small point you answered earlier.

I asked: "Is it intended to be allowed to pass controls as parameters to other controls?"
You answered: "As constructor parameters, yes."

So there should be no legal way to try to pass a control as a "normal" parameter?

If there were, I'd like to see what an example of that would look like.  It seems like that would be all of the ingredients necessary to make a mutually recursive chain of apply() calls between controls.

**Comment by jnfoster** [comment]
>
> So there should be no legal way to try to pass a control as a "normal"
> parameter?
>
Correct.

> If there were, I'd like to see what an example of that would look like. It
> seems like that would be all of the ingredients necessary to make a
> mutually recursive chain of apply() calls between controls.
>
Indeed. One could quite easily encode any number of fixpoint combinators.
And that's why it's disallowed :-)

-N

**Comment by jafingerhut** [comment]
OK, so one more clarifying question for me on this topic, and I hope I'm done with it:

Given the P4_16 v1.0.0 definition,

True or false: Suppose control c1 is declared before control c2 in the program.  There is _no_ way for an instance of c1 to call an instance of c2.

I believe the answer is true, because: For c1 to call another control c2, c1 must either instantiate c2 inside of c1's declaration, or it must take an instance of c2 as a constructor parameter.  c1 cannot name or refer to an instance of c2 in any other way.  To do either of those things, c2 must be declared before c1, otherwise the type c2 is undefined while c1 is being declared.

The same reasoning applies to parsers and their instances, too.

**Comment by jnfoster** [comment]
Never say never... (I think this code should be legal, however, the current compiler has a bug.)

```
#include <core.p4>

control C1();
control C2();
control C3();
extern E {
  E();
  void set1(C1 c1);
  void set2(C2 c2);
  C1 get1();
  C2 get2();
}

package S(C3 c3);
        
control MyC1()(E e) {
  apply {
    C2 c2 = e.get2();
    c2.apply();
  }
}        
control MyC2()(E e) {
  apply {
    C1 c1 = e.get1();
    c1.apply();
  }
}        
control MyC3()(E e, C1 c1, C2 c2) {
  apply {
    e.set1(c1);
    e.set2(c2);
    c1.apply();
  }
}        

E() e;
    
S(MyC3(e,MyC1(e),MyC2(e))) main;
```

**Comment by jafingerhut** [comment]
Cool.  So it looks like with the right kind of extern, you can (very inconveniently) execute loops within a single control in P4 after all.

Do you think this would be possible if externs could not take and return references to controls?

**Comment by mbudiu-vmw** [comment]
Controls and externs are supposed to be all compile-time constants, they cannot be returned from functions. We were assuming that the architecture would enforce this.

**Comment by jafingerhut** [comment]
@mbudiu-vmw I am all for the PSA disallowing @jnfoster's example program via some appropriate restrictions.  I don't know the best way to write those restrictions yet, but perhaps it might very well be: no externs that can take or return references to controls or parsers.

**Comment by mbudiu-vmw** [comment]
You can pass such objects only using directionless parameters. The spec should make it clear that nothing else is permitted.

**Comment by jafingerhut** [comment]
@mbudiu-vmw @jnfoster's example above uses only directionless parameters, as far as I can tell.  I think the spec might already say that, but could be made somewhat more explicit.

Are you saying that by doing both of these things:

(a) making that restriction explicit, plus
(b) Disallow (references to) externs, controls, and parsers as return values.

not only would run-time loops be impossible, but a compiler for a PSA-like architecture should be reasonable to write?

If there were no restrictions against passing externs, controls, and parsers as run-time parameters, it seems that the target device would need to be able to make control.apply(), parser.apply() and extern method calls to control/parser/extern instances that could be one of multiple different instances at run time.

**Comment by jafingerhut** [comment]
In an earlier comment on this issue, I asked:

True or false: Suppose control c1 is declared before control c2 in the program. There is no way for an instance of c1 to call an instance of c2.

I have confirmed that this is false, and it seems reasonable to me, e.g. because of this example program, where control MyC2 calls an instance of MyC1, even though MyC1 is declared later in the program.
```
#include <core.p4>

// Architecture
control C1();
control C2();
control C3();
package S(C3 c3);

// User Program
control MyC2()(C1 c1) {
    apply {
        c1.apply();
    }
}
control MyC1() {
    apply { }
}
control MyC3() {
    MyC2(MyC1()) c2;
    apply {
        c2.apply();
    }
}

S(MyC3()) main;
```
If we restrict our attention to programs where controls and parsers cannot be returned from function/method calls, I think the following statement is true:

True or false: Suppose control c1 is _instantiated_ before control c2 during the instantiation steps for the program, performed in the order described in the P4_16 spec. There is no way for an instance of c1 to call an instance of c2.

**Comment by jnfoster** [comment]
Here's another variant.
```
#include <core.p4>

// Architecture    
control C();
package S(C c);

extern WrapControl {
  WrapControl();
  void set(C c1, C c2);
  void execute1(); // invokes c1.apply()
  void execute2(); // invokes c2.apply()
}

//User Program     
control MyC1()(WrapControl wc) {
  apply {
    wc.execute2();
  }
}
control MyC2()(WrapControl wc) {
  apply {
    wc.execute1();
  }
}
control MyC3() {
  WrapControl() wc;  
  MyC1(wc) c1;
  MyC2(wc) c2;
  apply {
    wc.set(c1,c2);
    c1.apply();
  }
}
    
S(MyC3()) main;
```
If you grant the ability to invoke `apply` for a control from an extern (which admittedly lies outside of the semantics of the language), then we can achieve the same effect without ever returning a control...

**Comment by ChrisDodd** [comment]
(Catching up on stuff -- I've been on vacation)

PSA already disallows all this, because all architectures implicitly disallow all externs they don't explicitly define -- externs are (currently) only definable by architectures and user programs can only instantiate them.

There has been some discussion of allowing user defined externs for some architectures, but that would require also having a mechanism for the user to specify the behavior of the extern, which doesn't currently exist in the language.  Any restrictions on what can be done in an implementation of an extern would have to apply to that part of the language, somehow.

**Comment by jnfoster** [comment]
@ChrisDodd I could be mistaken, but I thought @jafingerhut was asking a general question about P4_16 and not a specific question about PSA.

**Comment by jafingerhut** [comment]
With the merging of this PR: https://github.com/p4lang/p4-spec/pull/427

I believe it is now documented all of the possibilities of passing externs to other things, and what things can and cannot be passed to externs, or returned from externs.

I am therefore closing this issue.  Feel free to reopen or create other issues if I've missed something.
