### ISSUE TITLE
Question: In multi-package arch, which one is supposed to be 'main'?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#362]
I have created a sample architecture file by copying some code from the P4_16 spec that demonstrates an architecture with 3 package type declarations, here: https://github.com/jafingerhut/p4-guide/blob/master/multipackage/example-arch.p4

I have created nearly the simplest possible P4 program that tries to use that architecture, here: https://github.com/jafingerhut/p4-guide/blob/master/multipackage/example-arch-use.p4

I get the following error trying to compile it with the latest version of p4test as of 2017-Jul-19:
```
example-arch-use.p4(106): error: main: Cannot unify package Egress to package Egress
Switch(ig, eg) main;
               ^^^^
```
Am I doing something incorrect in the sample program, or is this a compiler bug?

If there are multiple package type declarations in an architecture, there seems to be no way in the architecture #include file by itself to say which package instantiation should be named 'main'.

For example, in this slightly modified program using the same architecture above: https://github.com/jafingerhut/p4-guide/blob/master/multipackage/example-arch-use2.p4

I instantiate a package Ingress named 'main', and have no instantiation for packages Egress and Switch, and p4test compiles it with no errors.  Perhaps the intent is that a compiler for a particular architecture will know which package types to check for instantiations of them, but p4test does not have any such checking because it is intended to have less knowledge of any particular architecture?

**Comment by jnfoster** [comment]
I believe `main` comes from the user program not the architecture. That is, the architecture may define many packages and the user program gets to designate one as `main`.

So I think this is a compiler bug -- the implementation of type inference doesn't add constraints between packages. Assuming these should be type checked structurally, then I think we should simply check that the two packages have the same number of components and then recursively unify those components pairwise. Concretely, I think we would need to add a new function `unifyPackages` similar to `unifyFunctions` here (https://raw.githubusercontent.com/jafingerhut/p4-guide/master/multipackage/example-arch.p4).

**Comment by mbudiu-vmw** [comment]
I hope that this issue has been solved; at least the one related to the compiler should be fixed.
There is an example project which declares multiple packages in an architecture, and the user can choose which one to instantiate: https://github.com/vmware/p4c-xdp. In that project the xdp_model.p4 architecture includes ebpf_model.p4, and defines an additional package. So there are two packages in the architecture: ebpfFilter and xdp. The user can instantiate either of them for main; depending on the choice the compiler will in fact generate a different kind of code (one is a filter and the other one is a switch).

**Comment by jafingerhut** [comment]
I've closed p4c issue https://github.com/p4lang/p4c/issues/803 since the latest p4test as of 2017-Aug-16 gives no error on my example program.  Thanks.
