### ISSUE TITLE
P4_16 spec: Document that methods/functions may not return references to stateful objects

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#367]
This PR for p4lang/p4c: https://github.com/p4lang/p4c/pull/815 proposes making it an error for a method to have a return type that is a parser, control, package, or extern.

Without this restriction, it is definitely possible to create an extern method that returns references to controls that enables a loop of apply() calls between controls, or similarly for parsers.  The test program testdata/p4_16_errors/issue807.p4 added by that PR is one such program.

If this is considered a reasonable restriction on all P4_16 programs, it would be good to document it so in the spec (Note: I haven't checked thoroughly to see if this is already disallowed by the current v1.0.0 P4_16 spec, but if so, please point it out and we can close this issue with no changes).

**Comment by akeep** [comment]
Are parser, control, package, or externs allowed as arguments?  If so, I
think banning them as a return type is insufficient to achieve the result
you are trying for, since you can express the same thing with an out
parameter.

-the other andy:)

On August 1, 2017 at 9:15:14 PM, Andy Fingerhut (notifications@github.com)
wrote:

This PR for p4lang/p4c: p4lang/p4c#815
<https://github.com/p4lang/p4c/pull/815> proposes making it an error for a
method to have a return type that is a parser, control, package, or extern.

Without this restriction, it is definitely possible to create an extern
method that returns references to controls that enables a loop of apply()
calls between controls, or similarly for parsers. The test program
testdata/p4_16_errors/issue807.p4 added by that PR is one such program.

If this is considered a reasonable restriction on all P4_16 programs, it
would be good to document it so in the spec (Note: I haven't checked
thoroughly to see if this is already disallowed by the current v1.0.0 P4_16
spec, but if so, please point it out and we can close this issue with no
changes).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/p4lang/p4-spec/issues/367>, or mute the thread

**Comment by jafingerhut** [comment]
@akeep Good point.  I don't know if the current spec already disallows controls/parameters/packages/externs to be parameters with an 'out' direction, but if they are currently allowed in the spec, it would be good to explicitly disallow them as well.

**Comment by mbudiu-vmw** [comment]
These should only be allowed as directionless parameters.

**Comment by jnfoster** [comment]
Here's a silly counter-example. It harnesses the recursion available in parsers to call a pair of controls in a loop forever. 
```
#include <core.p4>

// Architecture    
parser P();
control C();
package S(P p);
extern BoolReg {
  BoolReg();
  bool get();
  void flip();
}
extern WrapControl {
  WrapControl(C c);
  void execute();
}
   
// User Program
BoolReg() r;
    
parser Loop()(WrapControl c1, WrapControl c2) {
  state start {
    r.flip();
    transition select(r.get()) {
      true: q1;
      false: q2;
      default: accept;
    }
  }
  state q1 {
    c1.execute();
    transition start;
  }
  state q2 {
    c2.execute();
    transition start;
  }
}
    
control MyC1() {
  apply {
    // Code for Control 1
  }
}
control MyC2() {
  apply {
    // Code for Control 2
  }
}
    
S(Loop(WrapControl(MyC1()), WrapControl(MyC2()))) main;
```
As best I can tell, none of the restrictions that have been proposed so far forbid this program, although the compiler currently rejects it with a mysterious error (see p4c #818).
```
cyclic.p4(50): error: Could not find declaration for tmp_0
S(Loop(WrapControl(MyC1()), WrapControl(MyC2()))) main;
                   ^^^^^^
cyclic.p4(50): error: Could not find declaration for tmp_1
S(Loop(WrapControl(MyC1()), WrapControl(MyC2()))) main;
                                        ^^^^^^
```
It seems like we need to also forbid controls as constructor parameters to externs, or impose a deeper restriction forbidding controls from being used  in parsers. 

However, I'm not sure if the latter restrictions would be in-line with the design for P4-16 as @mbudiu-vmw and others originally envisioned it. I vaguely recall some discussions of architectures people were imagining in which parsers and controls might invoke each other...

**Comment by jnfoster** [comment]
And actually, this version is accepted by the compiler.
```
#include <core.p4>

// Architecture    
parser P();
control C();
package S(P p);
extern BoolReg {
  BoolReg();
  bool get();
  void flip();
}
extern WrapControl {
  WrapControl(C c);
  void execute();
}
   
// User Program
BoolReg() r;
    
parser Loop()(WrapControl c1, WrapControl c2) {
  state start {
    r.flip();
    transition select(r.get()) {
      true: q1;
      false: q2;
      default: accept;
    }
  }
  state q1 {
    c1.execute();
    transition start;
  }
  state q2 {
    c2.execute();
    transition start;
  }
}
    
control MyC1() {
  apply {
    // Code for Control 1
  }
}
control MyC2() {
  apply {
    // Code for Control 2
  }
}

WrapControl(MyC1()) c1;
WrapControl(MyC2()) c2;        
    
S(Loop(c1,c2)) main;
```

**Comment by jnfoster** [comment]
Here's another version that doesn't use parser loops.

```
#include <core.p4>

// Architecture    
control C();
package S(C c);

extern WrapControls<T1,T2> {
  WrapControls(T1 t1, T2 t2);
  void execute1(); // invokes c1.apply on self
  void execute2(); // invokes c2.apply on self
}
    
//User Program            
control MyC1(WrapControls<_,_> wc) {
  apply {
    wc.execute2();
  }
}
control MyC2(WrapControls<_,_> wc) {
  apply {
    wc.execute1();
  }
}
control MyC3() {
  MyC1() c1;
  MyC2() c2;
  WrapControls<MyC1,MyC2>(c1,c2) wc;
  apply {
    c1.apply(wc);
  }
}
    
S(MyC3()) main;
```
This makes the compiler crash with a pretty serious bug.
```
In file: p4c/ir/visitor.cpp:54
Compiler Bug: IR loop detected 
```
This actually shouldn't type check with our current restrictions on generics -- the underscores cannot be filled in with suitable types. But if we were to add them back, then I believe it would be possible to make it a well-typed program.

**Comment by jafingerhut** [comment]
@jnfoster wrote: "It seems like we need to also forbid controls as constructor parameters to externs, or impose a deeper restriction forbidding controls from being used in parsers.

However, I'm not sure if the latter restrictions would be in-line with the design for P4-16 as @mbudiu-vmw and others originally envisioned it. I vaguely recall some discussions of architectures people were imagining in which parsers and controls might invoke each other..."

Andy's response:

I don't know who wrote the relevant part of the P4_16 spec, but it explicitly says that it is illegal to instantiate a control block within a parser: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L4066-L4067

I understand that _calling_ a control from a parser is not the same thing as _instantiating_ a control within a parser, but why make instantiating illegal if you wanted to allow calling controls from parsers?

Similarly, it is illegal to instantiate parsers within control blocks, as stated here: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L4731-L4732

**Comment by jafingerhut** [comment]
Your WrapControl extern seems intended for its execute() method to call apply() on the control it was given when a WrapControl instance is constructed.

This seems to me against the following intent given in the P4_16 spec here: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L1563-L1572

In particular the parts about limiting the possible side effects that extern calls can have on objects in the P4 program.

**Comment by jnfoster** [comment]
I agree -- this is a naughty program!

Language design is interesting because features tend to interact in unintended ways...

**Comment by jnfoster** [comment]
See the discussion of #361 (https://github.com/p4lang/p4-spec/issues/361#issuecomment-319612892). I don't think this repair fully fixes the problem.

**Comment by jafingerhut** [comment]
With the merging of this PR: https://github.com/p4lang/p4-spec/pull/427

I believe it is now explicitly documented that extern methods cannot return references to stateful objects, nor can they accept references to parsers or controls as run-time parameters, nor can they call them.

I am therefore closing this issue.  Feel free to reopen or create other issues if I've missed anything.
