### ISSUE TITLE
P4_16 spec: What should actions be allowed to call?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#368]
Which of these things should an action be permitted to call in a P4_16 program?

- actions?  I think the answer here ought to be yes, as long as no self or mutual recursion is allowed.

- parsers?  If "parser land" and "control land" are nearly separate islands inside P4_16, then no, actions should not be allowed to call parsers.  If someone proposes "yes", I would like to know how they propose to pass the "packet_in" parameter that every parser definition I have seen has.  There is no constructor for this type, and most definitions of ingress and egress control blocks I have seen have no such parameter.

- controls?  One simple answer would be "no".  A slightly more permissive answer would be "if an action can be invoked due to a table match, then no.  If an action can never be called due to any table match in a program, but only due to being directly called from a control apply block, then yes."

- extern methods?  Yes, at least some of them, e.g. a meter's execute() method, for certain, and register read/write methods.  Each extern should document whether it is allowed to be called from an action.  I would expect some might be restricted to only be called from parser states.

- constructors?  No.  Restricting all constructors to be called at compile time seems to be the design intent of P4_16.

**Comment by mbudiu-vmw** [comment]
I think this is a very good summary.

**Comment by jafingerhut** [comment]
With the merging of this PR: https://github.com/p4lang/p4-spec/pull/427

I believe it is now explicitly documented what the possibilities are for actions calling other things at run time.

I am therefore closing this issue.  Feel free to reopen or create other issues if I've missed anything.
