### ISSUE TITLE
[PSA] What passes from ingress to egress, and how?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#369]
Should the PSA have an explicit deparser after the ingress control block, before the packet buffer?  And also an explicit parser after the packet buffer, just before the egress control block?
 
If this were done, it seems it would make explicit several things that are otherwise kind of murky in the PSA (to me, at least).
 
For example, it would make explicit exactly what packet contents are written into the packet buffer.
 
With the current psa.p4 file here: https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/psa.p4#L384-L409
 
It makes me wonder: What _is_ written to the packet buffer?  Are all ingress-parsed headers, with any potential modifications that the ingress control block might have made to them, and their valid bits, available in the egress control block, just “somehow”?  If there is some limit on how many modifications ingress can make, and can be preserved from ingress to egress, how do we specify that?
 
Similarly, if every bit of user-defined metadata that was assigned a value on ingress was defined to be available in egress, that could be hundreds or thousands of bits per packet (I haven't double-checked this calculation carefully, but I believe that switch.p4 has over 4000 bits of user-defined metatadata per packet).  That has serious performance implications for a terabit per second switch.  If only what is ‘live’, i.e. read by some code on egress before it is assigned a value, is passed, that seems quite dependent upon how good a compiler’s liveness analysis is.
 
If instead we had:

+ an explicit deparser after ingress
+ an explicit parser before egress
+ an explicit statement that all user-defined metadata was undefined at the beginning of the egress, i.e. any modifications or assignments made to it on ingress are lost.

Then we could simply say “the only packet data passed from ingress to egress is the contents of the packet, plus a few intrinsic metadata fields like egress_port, maybe a multicast group id, and/or a replication id”.  The size of this data would be completely under the control of the P4 program, very visible to it, with little or no variation across PSA implementations.

Note: In many common cases, the ingress and egress parser could be the same (perhaps with a few extra user-defined ingress-to-egress headers allowed to be parsed in the egress parser, that the ingress parser would not allow).  Similarly the deparser definitions could be the same, as long as the egress code did setInvalid() on any user-defined ingress-to-egress headers before it completed.

**Comment by vgurevich** [comment]
Hi Andy,

I totally agree that having an explicit ingress deparser and an explicit egress parser will make things significantly clearer. 

I am not sure bridged metadata is the best reason for these -- it is not very difficult for the programmer to keep most of the stuff local (i.e. outside of that M struct) and it is also not very difficult for the compiler to find out which exact fields are used in both ingress and egress controls and pass only those (that's what the P4_14 compiler is doing anyway). My bigger concern is with things like clone(), resubmit(), generate_digest() (using P4_14 names) that seem to require explicit deparsing at the ingress is we want to be able to pass (additional) data. 

At the early days of PSA I thought it was more of a choice and the decision was made at that time to make PSA closer to P4_14, but after we explored more "interesting" parts of P4_14, I think we should seriously consider your proposal.

**Comment by cc10512** [comment]
@jafingerhut We have now explicit ingress deparser and egress parser blocks, as well as an open issue for bridged metadata. Is this issue ready to be closed?

**Comment by jafingerhut** [comment]
@cc10512 Yes, we can.  Closing it now.
