### ISSUE TITLE
[PSA] Entry key for direct counters in standard metadata

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#371]
There is an entry_key in the standard metadata (lines 36 and 52). It is being used to address the direct counters and meters by the control plane API. However, P4Runtime is using the table entry as the key to address direct meters and counters from the control plane.

Would it be acceptable to remove entry_key from standard metadata and change the control plane API (in comments) for direct meters and counters to use the p4.TableEntry type instead?

**Comment by cc10512** [comment]
Yes, certainly. Thank you for opening the issue, we discussed this briefly, and there is agreement in the WG that these should be handled using p4runtime.

**Comment by samar-abdi** [comment]
I don't have permission to push to p4-spec. Can you please help? Username is samar-abdi. Thanks!

**Comment by cc10512** [comment]
@samar-abdi, thank you for the patch.
Can you please fork, push to the fork and issue the pull request? The maintenance process (https://github.com/p4lang/p4-spec/wiki/Maintenance-Process) for the spec has only a few people who have write access.

**Comment by jafingerhut** [comment]
It appears that this issue has been resolved with the commit of this pull request: https://github.com/p4lang/p4-spec/pull/374

Closing this issue.  Feel free to reopen, or create additional issues, if I've closed this one in error.
