### ISSUE TITLE
[PSA] Selective dropping of cloned packets in PRE

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#372]
Apologies in advance for my limited understanding of PRE.

Is it possible to selectively drop only the cloned packet and not the original? In other words, replacing pre.drop() with pre.drop_all() and pre.drop_cloned()?

**Comment by samar-abdi** [comment]
And by the same token, drop_original(), even though I am not aware of such a use-case.

**Comment by jafingerhut** [comment]
@hanw I don't have a good answer to this question.  Just calling this issue to the attention of Han Wang, who is thinking about PRE issues for PSA.

**Comment by hanw** [comment]
To remind everyone about the context, in the last meeting, we voted to use metadata to control the clone operation in PRE. The current thinking is to have a metadata bit that is an `out` parameter from ingress to PRE that represents if a clone operation needs to happen for the packet-in-process. If that bit is not set anywhere in the pipeline, then the packet is assumed to be (by default) not cloned. A packet is only cloned if the `clone` bit is set to true.

Further, the cloned copy of a packet has a metadata bit (to the parser) to identify it as a cloned copy. Therefore, the pipeline can drop the cloned packet by setting the `drop` bit when processing the cloned copy of the packet.

drop_original() can be implemented by setting both the `drop` bit and `clone` bit for the original packet. It might be useful to implement pipeline bypassing.

**Comment by hanw** [comment]
drop_all() is encoded as `drop == 1 && clone == false`
drop_clone() is encoded as `drop == 0 && clone == false`
drop_original() is encoded as `drop == 1 && clone == true`
normal clone is encoded as `drop == 0 && clone == true`

**Comment by samar-abdi** [comment]
Thanks @hanw 
Just to confirm, the clone is a copy of the packet as seen at ingress (or egress) and not the current state of the packet at the time of cloning. For example, would the TTL modification earlier in the pipeline be reflected in the clone? Perhaps this can be clarified in the PRE spec. Thanks!

**Comment by jafingerhut** [comment]
@samar-abdi @hanw With Han's recent changes where when cloning a packet, you also specify whether the packet is the original packet, or the modified packet, I think that should address Samar's question, although having a few more explicit sentences describing this in the PSA spec would be worthwhile.
