### ISSUE TITLE
P4_16 spec: Restrictions on use of stateful objects

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#375]
Discussion on several recent issues has raised questions about whether P4_16 the language has certain restrictions on the use of stateful objects, i.e. packages, parsers, controls, tables, and extern objects.

The text below is intended to be one possible addition to the P4_16 spec that summarizes these restrictions.  It seems worth bringing this up in a future P4_16 language work group meeting, to verify that these restrictions are accurate, and to decide upon changes to the spec to make these restrictions explicit.

Any of this that is judged too restrictive for the P4_16 language in general, should still be considered as a restriction for PSA, over and above P4_16 language restrictions.

The following issues probably address only a subset of topics that this one does, and if so, they can be closed if this larger issue is addressed:

- https://github.com/p4lang/p4-spec/issues/361
- https://github.com/p4lang/p4-spec/issues/364
- https://github.com/p4lang/p4-spec/issues/367
- https://github.com/p4lang/p4-spec/issues/368

```
## Restrictions on use of stateful types

The stateful types of objects in P4_16 are packages, parsers,
controls, externs, and tables.  All other types are referred to as
"value types" here.

Some guiding principles:

- Packages can be instantiated, but have no run-time behavior, so
  there is no use in passing them to anything else other than another
  package.
- Controls are not allowed to call parsers, and vice versa, so there
  is no use in passing one type to the other in constructor parameters
  or run-time parameters.
- Externs are not allowed to call parsers or controls, so there is no
  use in passing objects of those types to them.
- Tables are always instantiated directly in their enclosing control,
  and cannot be instantiated at the top level.  There is no type by
  which a table can be passed as either a constructor or run-time
  parameter anywhere else.  They are only intended to be used from
  within the control where they are defined.
- No recursion is allowed, neither at run time, nor in the instantiation
  process during compile time.

The first table lists restrictions on what types can be passed as
constructor parameters to other types.

|-------------|-------------------------------------------------|
|             | can be a constructor parameter for this type ||||
|             |---------|--------|---------|--------|
| This type   | package | parser | control | extern |
|-------------|:-------:|:------:|:-------:|:------:|
| package     | yes     |  no    |  no     |  no    |
| parser      | yes     | yes    |  no     |  no    |
| control     | yes     |  no    | yes     |  no    |
| extern      | yes     | yes    | yes     | yes    |
| table       |  no     |  no    |  no     |  no    |
| value types | yes     | yes    | yes     | yes    |
|-------------|---------|--------|---------|--------|

The next table lists restrictions on what types can be instantiated
where.  The answer for `package` is always "no" because there is no
"inside a package" where instantiations can be written in P4_16.  One
can definitely make constructor calls and use instances of stateful
types as parameters when instantiating a package, and restrictions on
those types are in the table above.

For externs, their implementations are typically written in some other
language, and so what can be instantiated inside of them is not the
concern of the P4_16 language.

The entries for "value types" are yes for parsers and controls,
because you can define variables of any of those types inside of
parsers and controls.  Variables of these types may not be defined at
the top level of your program.

|-------------|-------------------------------------------------|
|             | can be instantiated in this place |||||
|             |-----------|---------|---------|---------|--------|
| This type   | top level | package | parser  | control | extern |
|-------------|:---------:|:-------:|:-------:|:-------:|:------:|
| package     | yes       |  no     | no      | no      |  no    |
| parser      |  no       |  no     | yes     | no      |  no    |
| control     |  no       |  no     | no      | yes     |  no    |
| extern      | yes       |  no     | yes     | yes     |  no    |
| table       |  no       |  no     | no      | yes     |  no    |
| value types |  no       |  no     | yes     | yes     |  no    |
|-------------|-----------|---------|---------|---------|--------|

The next table lists restrictions on what types can be passed as
run-time parameters to other callable things that have run-time
parameters: parsers, controls, extern methods, and actions.

|-------------|-------------------------------------------------|
|             | can be a run-time parameter to this callable thing ||||
|             |-----------|---------|---------|---------|
| This type   | parser    | control | method  | action  |
|-------------|:---------:|:-------:|:-------:|:-------:|
| package     |  no       |  no     | no      | no      |
| parser      |  no       |  no     | no      | no      |
| control     |  no       |  no     | no      | no      |
| extern      | yes       | yes     | yes     | no      |
| table       |  no       |  no     | no      | no      |
| value types | yes       | yes     | yes     | yes     |
|-------------|-----------|---------|---------|---------|

The restrictions on return types of extern methods is the same as for
parameters, with the addition that `void` can be a return type for
methods that return no value.

The next table lists restrictions on what kinds of calls can be made
from which places in a P4 program.  Calling a parser, control, or
table means invoking its `apply()` method.  The row for `extern`
describes where extern method calls can be made from.

|-------------|-------------------------------------------------|
|             | can be called at run time from this place in a P4 program |||||
|             |-----------|---------|---------|------------|--------|
|             |           | control | action  | action not |        |
|             | parser    | apply   | used by | used by    |        |
| This type   | state     | block   | table   | any table  | extern |
|-------------|:---------:|:-------:|:-------:|:----------:|:------:|
| package     | N/A       | N/A     | N/A     | N/A        | N/A    |
| parser      | yes       |  no     | no      | no         | no     |
| control     |  no       | yes     | no      | yes        | no     |
| extern      | yes       | yes     | yes     | yes        | no     |
| table       |  no       | yes     | no      | yes        | no     |
| action      |  no       | yes     | yes     | yes        | no     |
| value types | N/A       | N/A     | N/A     | N/A        | N/A    |
|-------------|-----------|---------|---------|------------|--------|

There may not be any recursion in calls, neither by a thing calling
itself directly, nor mutual recursion.

An extern can never cause any other type of P4 program object to be
called.  See the "Justification" subsection in
[#sec-calling-convention].

An "action used by a table" means an action that is either in the
`actions` list of a table, or it is possible for the action to be
called from such an action, perhaps through one or more intermediate
action calls.

Any action can be called from a control `apply` block.

It is allowed to write actions that are not used by any table.  Such
"actions not used by any table" have exactly the same restrictions on
what they can call as a control `apply` block does.  A potential
convenience of creating such an action is that it can be defined
within the control that calls it, giving the action access to all
parameter values and local variables defined earlier within its
enclosing control.  By contrast, control definitions cannot be nested.

Note that while the extern row shows that extern methods can be called
from many places, particular externs may have additional restrictions
not listed in this table.  Any such restrictions should be documented
in the description for each extern.  In most cases, it is expected
that the restriction will be "from a parser state only" or "from a
control apply block or action only".

TBD example in PSA: The `ValueSet` extern `is_member` method is only
intended to be called from a parser state, never a control or action.
```

**Comment by jnfoster** [comment]
The last point is certainly false -- we want to allow recursive parsers.

**Comment by jnfoster** [comment]
Also, recirculate.

N

**Comment by jafingerhut** [comment]
I agree that we want to allow parsers with loops in parser states.  Also we want to allow parsers to call sub-parsers, which in turn might call sub-parsers.  Do you believe we should be allowing recursive calls of a parser to itself, or between different parsers?  I thought that was to be avoided, just as recursive calls between different controls was.

Would it sound any more precise if I wrote something like: By "no recursion" we mean no recursion from the time that a packet begins a single top level parser until it finishes that parser, or from the time that a packet begins a single top level control until it finishes that control call.  Outside of those calls, there can be bigger loops created by operations such as recirculate, resubmit, clone, etc.

**Comment by mbudiu-vmw** [comment]
There is no reason to have recursive parsers; parser already can have loops.
In general, we don't want to allow programs use unbounded storage, which a recursive parser may need on the stack.

**Comment by jnfoster** [comment]
I see. We might think about how to phrase this so readers do not get
confused between parser loops (legal) and recursion between parser
instances (proposed illegal). Looping is a form of recursion, as is
recirculation, so I found the wording "No recursion is allowed, neither
during compilation time nor at runtime" a bit strong.

-N

**Comment by mbudiu-vmw** [comment]
@jafingerhut : it may be better to actually create a pull request with these changes, because otherwise it is difficult to comment on specific lines in your proposal. In principle I like this proposal a lot, but I would like to make some point corrections.

**Comment by jnfoster** [comment]
Taking a step back, with these new restrictions we have really limited what you can do with parsers and controls: they cannot be instantiated at the top level and they cannot be passed around, even as constructor parameters at compile-time. What's left? Well, you can instantiate a parser/control, you can assigning it to a variable, I suppose you can assign a parser/control to another variable (although from a language perspective, this is fundamentally no different than parameter passing, so it seems odd to allow one but not the other) and you can `apply` a parser/control to data plane arguments. 

I don't have a concrete proposal yet, but it feels less intuitive me to overload the same language-level mechanisms (types, variables, etc.) that are used to do standard imperative programming with data plane values for something that is so restricted. For instance, it might be cleaner to have a different domain-specific construct for specifying the static parser/control instantiation graph.

**Comment by jafingerhut** [comment]
@jnfoster - The tables I wrote _do_ allow parsers to take other parsers as compile-time constructor parameters,  e.g. the first table, row "parser", column "parser" is yes.  Similarly they allow controls to take other controls as compile-time constructor parameters.

That is still quite static, I understand, and still open to the ideas you raise in your last paragraph.

**Comment by jnfoster** [comment]
Mea culpa. Noted :-)

**Comment by jafingerhut** [comment]
@jnfoster Section 8.18 of the P4_16 v1.0.0 spec says "Several P4 constructs denote resources that are allocated at compile time: extern objects, parsers, control blocks, packages".  This seems to imply that it has been the intent for some time that constructors in P4 are only called at compile time.

This is perhaps only an idle curiosity question, so skip it if you are busy, but which of these restrictions do you consider to be new?

**Comment by jafingerhut** [comment]
@mbudiu-vmw Created this PR: https://github.com/p4lang/p4-spec/pull/381
Please comment to your heart's content.

**Comment by jafingerhut** [comment]
@jnfoster In an earlier comment you say: "What's left? Well, you can instantiate a parser/control, you can assigning it to a variable, I suppose you can assign a parser/control to another variable (although from a language perspective, this is fundamentally no different than parameter passing, so it seems odd to allow one but not the other) and you can apply a parser/control to data plane arguments."

I have a question about the "you can assigning it to a variable" part.

See this part of the P4_16 spec, copied below for reference: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L3747-L3749

"However, it is impossible to declare variables with types that are only synthesized by the compiler (e.g., `set`). In addition, variables of type  `parser`, `control`, `package`, or `extern` types must be declared using instantiations (see Section [#sec-instantiations])."

At least one way to interpret that line in the spec is that you cannot declare a variable of a type control like this: "C1 c1;" because that is not an instantiation.  I know the latest compiler is allowing code like this.  Too-tight restriction in the spec?  Compiler bug?

**Comment by jnfoster** [comment]
My mistake. I believe I wrote some code that did exactly this about a year ago, but possibly the compiler was too lenient at the time. Based on this wording from the spec, I think it's fine if such assignments are rejected.

Cheers.

**Comment by jafingerhut** [comment]
With the merging of this PR: https://github.com/p4lang/p4-spec/pull/427

I believe this issue is addressed.

I am therefore closing this issue.  Feel free to reopen or create other issues if I've missed anything.
