### ISSUE TITLE
P4_16 spec: Control plane operation atomicity

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#377]
Perhaps this is all obvious and/or understood as minimum requirements by everyone, but was wondering whether some text like the below is worth including in the P4_16 spec, or if not, the PSA spec?

```
## Atomicity of control plane API operations

All table add, delete, and modify operations must be atomic relative
to packet forwarding.  That is, for every table `apply` operation, and
every _single_ control plane API operation on a table, the `apply`
operation should behave as if that single control plane API operation
has not yet occurred at all, or as if the single control plane API
operation is complete.  The P4 program should never behave as if the
control plane API operation is partially complete.

For example, suppose a table `T` has an action `A` with 256 total bits
of action parameters, and the control plane has added a table entry
with a search key `K` and action `A`.  Later the control plane
performs an update operation on the entry with key `K` that leaves the
key `K` the same, but changes the 256 bits of action parameters.
Every packet doing an `apply` on table `T` and matching the entry with
key `K` should execute action `A` with either the old 256 bits of
action parameters, or the new 256 bits of action parameters.

There is no requirement that a sequence of _multiple_ table entry add,
delete, or update operations should be atomic relative to packets
being processed.  There are common "write tables from latest to
earlier in the data flow" techniques used by existing control planes
to achieve this, and control planes must either use techniques like
this, or it is possible for some packets to be processed with the
intermediate state that exists after each individual table operation
is complete.

The same applies for all control plane API operations on externs,
unless the control plane operation explicitly documents otherwise.
```

**Comment by mbudiu-vmw** [comment]
I think that this belongs to the API specification rather than the P4 specification, or perhaps in the architecture specification. This is because the actual API to modify tables depends on a table implementation. For example, tables with action profiles first have to insert entries in the profile, and then in the table, requiring two operations. Tables implemented by tries may require insertions in every level of the trie. And so on. We don't really know in this document what are the actual API operations to modify tables, so we cannot make any promises on their behaviors.

**Comment by vgurevich** [comment]
Agree with @mbudiu-vmw -- this is a very good text and a very reasonable requirement, but it belongs to the API spec.

**Comment by jafingerhut** [comment]
Closing this issue in favor of addressing the questions in the PSA spec.

Reference to issue for PSA spec: https://github.com/p4lang/p4-spec/issues/525
