### ISSUE TITLE
[PSA] Traffic class

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#378]
Wondering if it would make sense to introduce a Traffic class type in PSA and have the PRE and Buffering engine send_to_port/clone methods take a traffic class parameter as input.

In several use cases, the controller may want the switch to assign different priorities to packets. I believe given the diversity of scheduling policies (and the difficulty of modeling a generic scheduler), we should not try to define a full-blown scheduler extern in PSA. 

But the ability to define the traffic class and the reference implementation (BMV2) implementing a strict priority scheduler, for example, might be a good middle ground.

What do others think?

**Comment by jafingerhut** [comment]
I believe this is the same issue as this one: https://github.com/p4lang/p4-spec/issues/334

See the latest comment that mentions the 2017-Aug-07 PSA working group meeting, where this was discussed briefly and there seemed to be agreement to go forward with writing up a draft piece of spec for this idea.  My thinking on this sounds like it might be the same as yours, i.e. the ingress control block would have a default traffic class assigned when it starts, and the P4 code could optionally assign a different value to that, and that value would be used in the PacketReplicationEngine to select a particular class-of-service queue for the selected output port (or ports, for multicast).

Different implementations would be allowed to support differing numbers of traffic classes per output port, even perhaps as low as only 1 class per output port on some implementations.

**Comment by samar-abdi** [comment]
Thanks Andy and sorry for the duplication. My understanding from #334 and the Aug 7 meeting was that we were considering modeling CoS queues in PSA. And I recall the push back from @vgurevich was that we don't want to model schedulers, given their diversity. I agree with that.

Just to be clear, are you suggesting a class_of_service field in the ingress input metadata? That is definitely an option. Alternately, just a parameter in the PRE and Buffering Engine functions should be ok.

P4Runtime can define a set of service classes and their priorities. Then, it is the job of the P4Runtime service on the switch to interpret flows that set a service class, and generate table entries with CoS queue assignment on the switch hardware.

If that sounds OK, I can start a PR or @hanw can incorporate into his existing PRE work.

**Comment by hanw** [comment]
Hi, @samar-abdi, my existing proposal for PRE does not include CoS. Could you start a PR on this issue? Thanks!

**Comment by jafingerhut** [comment]
@samar-abdi @hanw I have created a PR proposing one way to allow the ingress control block to choose among multiple class-of-service queues that a PSA implementation provides, but allowing that number of queues to be as low as 1 in a particular PSA implementation.  Please take a look and add any comments you have: https://github.com/p4lang/p4-spec/pull/403
