### ISSUE TITLE
match_kind selector

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#399]
What is the semantics of the `selector` `match_kind`? It's listed in the P4 source, but not discussed in the current documentation for PSA.

**Comment by jafingerhut** [comment]
I know it is supposed to be related to the ActionSelector extern, but don't yet know the proposed semantics in enough detail to write them up.

@samar-abdi I know you volunteered to write up some more detail on the ActionProfile extern.  Were you also thinking of including ActionSelector in that work?

**Comment by jnfoster** [comment]
My main request is that if we include a top-level `match_kind` type in PSA (or any other architecture), it should have a compositional semantics that stands alone and only affects the meaning of table lookup. I don't know how to formulate such a semantics for `selector`. Hence, my question. It's probably just my ignorance.

**Comment by jafingerhut** [comment]
@jnfoster So perhaps what you may be hoping for is: the field (or fields?) that people want to use to modify ActionSelector extern behavior should perhaps be specified via a new table property, or a parameter to the ActionSelector constructor, rather than being part of the table search key?  I don't know if those ideas are a good fit for this purpose.

**Comment by mbudiu-vmw** [comment]
I think that the semantics of "selector" in v1model is pretty clean. The documentation is essentially split between the P4-14 definition of action selectors and the migration guide document: https://github.com/p4lang/p4-spec/blob/master/p4-16/discussions/migration-guide.pptx.

You cannot use a different table property, these fields are actually read when the table lookup is done. Other fields are not evaluated at runtime.

**Comment by jnfoster** [comment]
So is the compiler broken? 

Compiling this program on Bmv2:
```
/* -*- P4_16 -*- */
#include <core.p4>
#include <v1model.p4>

struct metadata { }

header h_t {
   bit<8> f;
}
    
struct headers {
    h_t h;
}

parser MyParser(packet_in packet,
                  out headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    state start {
        packet.extract(hdr.h);
        transition accept;
    }
}

control MyVerifyChecksum(in headers hdr, inout metadata meta) {   
    apply {  }
}

control MyIngress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) { 
    table tbl {
        key = {
            hdr.h.f : selector;
        }
        actions = {
            NoAction;
        }
    }
    
    apply {
        tbl.apply();
    }
}

control MyEgress(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    apply {  }
}

control MyComputeChecksum(inout headers  hdr, inout metadata meta) {
     apply { }
}

control MyDeparser(packet_out packet, in headers hdr) {
    apply { }
}

V1Switch(
MyParser(),
MyVerifyChecksum(),
MyIngress(),
MyEgress(),
MyComputeChecksum(),
MyDeparser()
) main;
```
produces this snippet of JSON:
```
        {
          "name" : "tbl",
          "id" : 0,
          "source_info" : {
            "filename" : "foo.p4",
            "line" : 31,
            "column" : 10,
            "source_fragment" : "tbl"
          },
          "key" : [],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [0],
          "actions" : ["NoAction"],
          "base_default_next" : null,
          "next_tables" : {
            "NoAction" : null
          },
          "default_entry" : {
            "action_id" : 0,
            "action_const" : false,
            "action_data" : [],
            "action_entry_const" : false
          }
        }
```
I'm surprised that the `key` is empty, and the `match_type` is exact.

Is the meaning of a `selector` `match_kind` that every value matches the pattern (so there can be only one rule?) That's the only semantics I can think of that's consistent with this behavior.

**Comment by samar-abdi** [comment]
Yes, I can add the details of action selector as well. Essentially, the selector match fields are passed to the action_selector instance as a list. So, they are not actually part of the match key.

Action selectors were actually much cleaner in P4_14 with the use of field lists.

**Comment by samar-abdi** [comment]
Here is an example:

https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/action_selector_shared-bmv2.p4

**Comment by mbudiu-vmw** [comment]
This is a legitimate behavior from the compiler, I don't know if BMv2 supports such tables, though.
Perhaps the compiler should reject the program.

The meaning of selector is the following:
- the fields of the key which have a standard type ("exact", "ternary", etc) are used to find a table entry
- the table entry points to a smaller table
- the fields labeled "selector" compute a key used to index within the smaller table; this gives you the action.

So logically you have a table that is the product of two tables with separate keys.

**Comment by jnfoster** [comment]
I don't think a P4_16 construct should have a semantics that is independent of P4_14 constructs (or documentation in a PowerPoint deck). That, is we should really be able to write this down in terms of P4_16 concepts only. 

In the case of a core feature like a table `key` and `match_kind`, I really think the semantics should be defined in a compositional manner. For example, a table can be thought of as some kind of function that, given a set of entries and the inpu data, executes the actions corresponding to the matching entry on the state of a switch. In this regime, the meaning of the `match_kind` attached to the keys defines which entry is selected, independent of any other properties that might happen to be attached to the table.

Can we formulate such a semantics for `selector`? If we can, great! If not, then I think whatever we are doing to port P4_14's action profiles should perhaps be implemented using some other table property with its own idiosyncratic semantics, and not abusing a core feature like `match_kind`s.

**Comment by mbudiu-vmw** [comment]
I think that the semantics is very clean and it fits very well within the P4-16 framework.
What is missing is documentation.

This feature is needed to model some very special features present in some classes of hardware; that's why there was a special P4-14 construct for this purpose. In P4-16 there is no special construct; it is modeled using the existing language elements.

**Comment by samar-abdi** [comment]
BMV2 would support the table. It would match on all packets.

**Comment by jafingerhut** [comment]
As far as describing the proposed semantics of ActionProfile and ActionSelector, I believe that perhaps the following is true:

+ Any program written using these externs _could_ instead be written using a sequence of 2 (or maybe 3?) P4 tables that did not use those externs.

If that is true, showing a pair of P4 programs that have equivalent behavior, one with the externs, and one without, would be clarifying for me, at least.

**Comment by jnfoster** [comment]
Another thought:

* We have externs that can compute various hash functions.

* We can use a control to compose multiple tables in sequence. In fact, we can implement any DAG of tables -- so two tables can have the same successor.

* So why is this use of action profiles a thing we need to do at all? Wouldn't it be cleaner to compute a hash in a first table, and then execute an action in a second phase using plain old tables and sequential composition in a control? While it's a bit more typing for the programmer, it's *much* simpler semantically.

**Comment by mbudiu-vmw** [comment]
Yes, it would be simpler, but this is a hint for the compiler to use a specific kind of implementation for the target.

**Comment by mbudiu-vmw** [comment]
It also has a very important influence on the control-plane API. The API of a table with selectors is not the same as the API of a pair of tables.

**Comment by jnfoster** [comment]
(I'm typing this from an airplane, which is why my responses are coming all out of order.)

**Comment by jnfoster** [comment]
> the table entry points to a smaller table
> the fields labeled "selector" compute a key used to index within the smaller table; this gives you the action.

I would argue this is not compositional. The meaning of which entry matches is stated in terms of a lookup in another table, as specified in the `implementation` property. So the meaning of a core P4 feature -- tables -- has been changed in a non-compositional way.

**Comment by jnfoster** [comment]
> It also has a very important influence on the control-plane API. The API of a table with selectors is not the same as the API of a pair of tables.

In addition, the meaning of the control-plane API generated from the program can also not be computed compositionally from the tables...

**Comment by jnfoster** [comment]
FWIW, my reading of the wording in the spec is that one would expect the kind of compositional semantics I'm advocating for...
> A key is a list of pairs of the form (e : m), where e is an expression that describes the data to be
> matched in the table, and m is a match_kind constant that describes the algorithm used to 
> perform the lookup (see Section 7.1.3).
> ...
> The match_kind constants serve three purposes:
> 
> They specify the algorithm used to match data plane values against the entries in the table at 
> runtime.
> They are used to synthesize the control-plane API that is used to populate the table.
> They are used by the compiler back-end to allocate resources for the implementation of the table.

If a match_kind doesn't actually affect a lookup in the table where it appears, but computes an index into another object (like an action profile extern), then this text doesn't tell the whole story.

Note that all other kinds of match_kinds I've heard discussed or hypothesized (exact, ternary, lpm, fuzzy, regexp, etc.) are compositional.

**Comment by mbudiu-vmw** [comment]
The term "table" is misused in P4; I attempted to call what is today a "table" a "match-action unit", but for historical reasons they are still called tables. A table has inside a small look-up tables. That is what I am talking about: a table with selectors is implemented as a tree hierarchy of look-up tables, where half the key is used for the first level and half the key (labeled selector) is used for the second half. It is perfectly compositional. It has the exact same API to the data-plane as any other table: all the key fields are used for lookup. The "selector" label is only a hint for the *implementation*. The semantics of key lookup from the data-plane point of view is independent on the key match_kind.

**Comment by jnfoster** [comment]
Okay, this is starting to make some sense for match-action units that are composed of multiple internal tables, as we would have when translating an P4_14 action profile.

But I still don't know what it means for my Bmv2 program with `tbl` above, which really has a single logical (and probably physical) table.

> The semantics of key lookup from the data-plane point of view is independent on the key match_kind.

If I change the match_kind and keep the same control-plane interactions won't I get different hit/miss behavior? I suppose one could say that all of the masking and slotting in of bits gets done as pre-processing but...

**Comment by mbudiu-vmw** [comment]
The control-plane will be different; the control-plane has to populate the two levels of tables separately.
The match-action units only have the same data-plane API, they have different control-plane APIs. That's really the point of the "selector" kind; otherwise we could just use two chained tables.

We could still used two chained tables with a special annotation.

There are also implications on atomicity: insertion of an action in a single table is supposed to be atomic; if you use two tables then you may see intermediate results by packets.

**Comment by samar-abdi** [comment]
A selector match key implies an indirect table. If no implementation is found, I think this should be a compiler error?

**Comment by jnfoster** [comment]
Hi Mihai, Andy, and Samar,

If I understand correctly, the semantics of `selector is as follows: the portion of the key value that is annotated with `selector` does not contribute to the lookup in the top-level table at run-time. Equivalently you could say that matching relation on values and patterns is total -- i.e., for this part of the key, any data plane value will match any pattern installed by the control plane. (In practice, for efficiency, the compiler and control plane would probably simply erase this part of the value / pattern to save resources.) 

It would be natural to ask: if `selector`s essentially denote the total relation, why is it ever useful? The answer is that the value gets "forwarded" to the widget that is attached to the table through the `implementation` property, if it exists.

If all of that is correct then I'm happy. The semantics *is* compositional because we can still define the meaning of each table in terms of data-plane / control-plane schemas and a matching relation on values and patterns. The fact that the second table -- the action profile -- resides in a black-box extern is fine. And the Bmv2 code above is correct (if slightly strange -- modifying the compiler to produce an error or at least a warning as Mihai and Samar both suggested would be sensible.)

Thanks for the good discussion and patient explanations.

-N

**Comment by jnfoster** [comment]
I'm going to close the issue...

**Comment by mbudiu-vmw** [comment]
Nevertheless, this description should show up in the documentation of v1model (which doesn't really exist), and whatever models offer a similar match_kind.
