### ISSUE TITLE
streaming packets through a P4 switch

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4-spec#405]
Yesterday, I made a [post ](https://github.com/p4lang/p4c/issues/869) inquiring about parser state syntax, and Mihai suggested I open issue with the language spec. I agree with pretty much all he said, and don't really care to make the language more C like. The last statement from my example (```pkt.lookahead<H>().f = 1; ```) is really the one I'm interested in here.

First, I guess, a little background is needed. Basically, I've been thinking about how to represent streaming packets through the switch. The current packet_in & packet_out externs work at the header level which, at least for my backend, can lead to a waste of resources. Users extract entire headers, but are really only interested in a few fields. I'm an FPGA guy so streaming has always been in the back of my mind, but recently I've been thinking more about how to better model it in P4_16. The key difference here from packet_in/packet_out externs is that with packet_stream_in/packet_stream_out externs headers would not actually be removed from the packet for ingress/egress. Instead they would just be updated in the deparser.

Ignoring any method nomenclature for now, I imagine a packet_stream_in extern would just be a subset of the packet_in extern, and can be used in a similar way. Maybe something like:

```
extern packet_stream_in {
    T lookahead<T>();
    void advance(in bit<32> sizeInBits);
    ...
} 
```

The interesting case is how to represent the packet_stream_out since the assumption is that headers are still in the packet during deparsing. In this case emit() doesn't make sense any more. Inserting & removing could be done with something like: 

```
extern packet_stream_out {
    void insert<H>(in H hdr);
    void remove<H>();
    ...
}
```

The real challenge is how to allow users to update headers already in the packet stream. One approach is to give read/write methods like:

```
extern packet_stream_out {
    ...
    void read<H>(out H hdr);
    void write<H>(in H hdr);
}
```

This has the advantage of already being supported by the P4_16 compiler. However, it's a bit clunky. First  the user will have to declare header instances. They will have to call 2 methods also when all they need to do is update a field that already exists.

The alternative idea I've been thinking about, and would like to discuss, is allowing some extern methods to be l-values. So the packet_stream_out could have something like:

```
extern packet_stream_out {
    ...
    T update<T>();
}
```

which is much closer to what I'm trying to model, and would have cleaner code. The user could write something like:
```
{
    pkt.update<ipv4_h>().dst = ... ;
}
```
instead of
```
{
    ipv4_h ip;
    pkt.read(ip);
    ip.dst = ... ;
    pkt.write(ip);
}
```

Obviously there would be consequences at other places in the compiler if we assume all extern methods can be l-values. To minimize affect we could update the extern syntax to allow some methods to be l-values. Maybe use the out keyword to mark them ```out T update<T>();``` or some other keyword/syntax.

This is something I've started think more about and  I'd be interested to hear other opinions or suggestions, better ways, etc.

**Comment by mbudiu-vmw** [comment]
If I understand correctly, you want an imperative API to update a packet seen as a byte array instead of a functional API that treats the input and output packets as read-only and write-only streams.

That is quite different from the standard P4 approach (inherited from P4-14).

Hopefully the P4-16 language is rich enough to support this model, but that won't be a standard model - at least the core.p4 APIs won't look this way for a while. 

There is nothing in the P4-16 design that prevents a compiler implementation to support a new abstraction for packets, e.g., ```extern MutablePacket { ... }```. Portability will suffer, but maybe you don't care about that.

What is needed is a design of a complete API that does everything you need. Maybe you can share more details about how your target operates on the packet.

**Comment by rhalstea** [comment]
It is different than the standard P4 approach, and I'm fine with it not being a standard model (not something I was expecting). 

Since you mentioned portability I would like to mention that in this case, no it's not something I'm concerned with. Another thing we're looking into is ways for users to build their own architectures (this hasn't been flushed out enough yet to really warrant a discussion). However, since the P4 language doesn't explicitly say how parser & control interfaces interconnect we will end up losing the connection between parser & deparser.

I'm going to keep back-end details light (Gordon is on vacation and I'd like to discuss it with him first), but at a high level once the parser and deparser connections get decoupled we can no longer reason about what header fields are used where in the data-plane.

Reasoning about a standard portable switch is do able with the packet_in & packet_out externs. Granted it's more difficult now that the parser & deparser are separated in P4_16. This MutablePacket is really aimed at non-standard architectures.

The read-only and write-only streams is something I'd like to keep. From the API level I'd like to have the 2 following externs:

```
extern MutablePacket_in {
	T read<H>();
	void advance(in bit<32> sizeInbBits);
	void advance<H>();
}

extern MutablePacket_out {
	T update<H>();
	void insert<H>(in H hdr);
	void remove<H>();
	void advance(in bit<32> sizeInBits);
	void advance<H>();
}
```

P4 syntax for this is already supported. However, I am assuming ```T update<H>();``` is treated as an l-value.

Other than the extern type nothing really changes at the architecture level for a Parser. However, at the architecture level the deparser would now become a parser container instead of the current control container. Writing to a header would look something like:

```
state deparse_ip {
	pkt.update<ipv4_h>().dst = metadata.forward_dst; // currently invalid syntax
	pkt.advance<ipv4_h>();

	transition select(metadata.proto) { ... }
}
```

Since P4 doesn't allow methods to be l-values it would be my back-ends job to enforce this. Which makes sense because my back-end is currently the only one that wants this. Besides the assignment statement I think P4_16 supports everything else.

**Comment by rhalstea** [comment]
closing

superseded by issue #438
