### ISSUE TITLE
P4_14 (v1.0.4): initial value of registers (and meters)

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#412]
What should be the initial value of registers according to the P4_14 spec?
Should it be 0 or "undefined" (meaning that it might take any value)?
Same question for meters as well.
For counters, I am assuming the initial value should be 0 (that's the only value that makes sense in this context)

I know there is another issue (#324) that discusses this for PSA, but my question is specifically about P4_14 spec.

**Comment by kheradmand** [comment]
Suggestion: explicitly mention that reading an uninitialized register yields an undefined value. The same way reading an invalid header yield undefined value.

**Comment by vgurevich** [comment]
Makes sense.

For meters I'd like to suggest the same approach as in P4_16/PSA (by default they always return GREEN color), but I do not think that's how things are currently implemented.
