### ISSUE TITLE
P4_14 (v1.0.4): can direct meters be referenced in the execute_meter primitive?

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#414]
In P4_14's spec, section 7.2 states that:

> ... meter names declared as direct are not allowed to be referenced in the execute_meter primitive, and a compiler must raise an error if this occurs.

But later in section 9.1, for specification of `execute_meter` primitive action, it is stated that 

>  If the meter is direct, then index is ignored as the table entry determines which cell to reference.

It seems that these to sentences are inconsistent with each other.  Which one is the correct one?

**Comment by kheradmand** [comment]
Suggestion: to make this consistent with counters and registers, allow direct meters to be referenced in execute_meter primitive action. (i.e remove the sentence in section 7.2 that disallows it)

**Comment by vgurevich** [comment]
There is another difference: in case of the direct meters, the result is specified in the meter definition, not in the action (as for indirect meters). 

In P4_16/PSA I believe we came to the conclusion that it is definitely better to have explicit actions always. 

In P4_14, however, I thought that we chose the route where both direct counters and meters do not need a primitive in the action, but the indirect ones do.

This might be an oversight.

**Comment by kheradmand** [comment]
Hi @vgurevich,

So just to make sure I understood your point correctly, you say `execute_meter` should be disallowed for direct meters? Similarly `count` should be disallowed for counters (that is not currently the case in the spec)

**Comment by vgurevich** [comment]
Hi Ali (@kheradmand),

Yes, as the things currently are, `execute_meter()` should be disallowed for direct meters and `count()` should be disallowed for *direct* counters (I think you missed that word).  In other words: direct resources do not use primitives -- all required info is the same and is "baked" into the declaration, while indirect resources do use primitives (the declarations are shorter, especially for the meters and the additional info is supplied by the primitive).

This was previously discussed (probably at the time of 1.0.3 spec) -- I am not sure why it didn't make it into the spec.

Thanks,
Vladimir

**Comment by kheradmand** [comment]
@vgurevich Thanks for clarification

> direct resources do not use primitives 

Just to make sure, this is not the case for direct registers, is it?

**Comment by vgurevich** [comment]
@kheradmand ,

There are no direct registers in P4_14 spec. 

Thanks,
Vladimir

**Comment by kheradmand** [comment]
@vgurevich,

I am bit confused because according to the syntax in the specification, and I know it doesn't make much sense but it is possible to declare direct registers:

```
register_declaration ::=
register register_name {
width_declaration ;
[ direct_or_static ; ]
[ instance_count : const_value ; ]
[ attribute_list ; ]
}
```

Also the specification of `register_read` and `register_write` mention  

```
If the register is direct, then index is ignored
as the table entry determines which cell to reference.
```

**Comment by vgurevich** [comment]
@kheradmand ,

These are the remnants of the things that shoud've been cleaned up long time ago, but haven't.

If we were, however, to allow direct registers, then they would have to use the primitives. That's why in P4_16/PSA we decided to be explicit and use the primitives everywhere. As the "Zen of Python" says: "Explicit is better than implicit" :)

**Comment by kheradmand** [comment]
@vgurevich I see. So would it be a better to just keep things as is or it do you think it would be a better idea to get rid of `[ direct_or_static ; ]` in register declaration syntax (and probably replace it with `[ static_attribute ;]`)

I don't know if the behavioral-model supports direct registers or not.

**Comment by vgurevich** [comment]
@kheradmand 

Hello Ali,

bmv2-simple-switch doesn't support direct registers, indeed. 

However, it doesn't mean that they do not make sense in P4_14. Initially, they made no sense (when the action semantics was parallel), but once it became sequential, they make a lot of sense now. But, in this case, you will have to have primitives (as described in the current spec) :)

There are other platforms that do implement direct registers, though :)
