### ISSUE TITLE
PSA: Scrub PSA metadata for direction

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#425]
Currently psa.p4 has psa_ingress_output_metadata_t as a direction 'out' parameter of the Ingress control block, and it also claims to specify initial values for some of the fields when the Ingress control block begins execution.

This is not possible in P4_16.

One fix: For all fields that we wish to define an initial value, and also let the user's Ingress control block code modify it, put them in a struct with direction 'inout'.

For all fields that we wish to have no defined initial value (i.e. they are initially undefined in the P4_16 spec sense of the word), put them in a separate struct with direction 'out'.

Obviously, if we end up defining initial values for all such fields, there would be no need for a struct with direction 'out'.

**Comment by cc10512** [comment]
Fixed by #434
