### ISSUE TITLE
Variable length length fields

### ISSUE THREAD

**Issue by maufl** [p4lang/p4-spec#426]
Hi, I'm currently looking into programming NDN/CCN routers in P4. There is already [NDN.p4](https://github.com/signorello/NDN.p4) but it's written in P4_14 and they assume some fields to have a fixed size which is not generally true. So started and tried to define headers which capture all possible values. NDN uses variable length fields of the form
```
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 
+----------------+----------------+---
|    TAG         |     VALUE *    |
+----------------+----------------+---
```
If the TAG is smaller then 253 there are no VALUE fields and the value is the value of the TAG.
If the TAG is 253 then there are 2 VALUE fields containing the value, if it is 254 there are 4 VALUE fields and if it is 255 there are eight VALUE fields. The full description is [here](http://named-data.net/doc/NDN-TLV/current/tlv.html).

They in turn use THESE variable length fields to build TLV fields! Meaning, the type and the length part of the TLV field have a variable length!

Now I have defined the following headers, header unions and packets.
```
header onebytenumber_h {
  bit<8> number;
}
header twobytenumber_h {
  bit<8> constant;
  bit<16> number;
}
header fourbytenumber_h {
  bit<8> constant;
  bit<32> number;
}
header eightbytenumber_h {
  bit<8> constant;
  bit<64> number;
}

header_union varnumber_h {
  onebytenumber_h onebyte;
  twobytenumber_h twobyte;
  fourbytenumber_h fourbyte;
  eightbytenumber_h eightbyte;
}

struct TLV {
  varnumber_h type;
  varnumber_h length;
  varbit<MAX_VALUE_LENGTH> value;
}

```
And I have a parser
```
parser VarnumberParser(packet_in b, out varnumber_h number) {
  state start {
    transition select(b.lookahead<bit<8>>()) {
      8w255: eightbytenumber;
      8w254: fourbytenumber;
      8w253: twobytenumber;
      _: onebytenumber;
    }
  }

  state onebytenumber {
    b.extract(number.onebyte);
    transition accept;
  }

  state twobytenumber {
    b.extract(number.twobyte);
    transition accept;
  }

  state fourbytenumber {
    b.extract(number.fourbyte);
    transition accept;
  }

  state eightbytenumber {
    b.extract(number.eightbyte);
    transition accept;
  }
}

parser TLVParser(packet_in b, out TLV p) {
  VarnumberParser() varnumberParser;

  state start {
    varnumberParser.apply(b, p.type);
    varnumberParser.apply(b, p.length);
    transition accept;
  }
}
```
However, I don't know how to use the length encoded in the varnumber_h type to extract a varbit field. I can't use if conditions to check which of the headers in the varnumber_h union is valid.

Apart from that I'm generally unsure what the best approach is to parse NDN packets in P4. I also thought about defining headers for all combinations of possible type and length field lengths. Is there an approach you would recommend?

**Comment by mbudiu-vmw** [comment]
P4 is not very good at this kind of stuff.
You can consider selecting on all valid bits:

```
select(p.length.onebyte.isValid(), p.length.twobyte.isValid(), p.length.fourbyte.isValid()) {
    true, false, false: ...
```

**Comment by antoninbas** [comment]
You could also use a custom enum to keep track of which member of the union was set. Kind of like an explicit tag for your union. You would need to add an extra `out` parameter to your subparser and write the appropriate enum value to it. I believe you should then be able to select on that enum value.

**Comment by maufl** [comment]
Thanks for your feedback, I tried both but selecting on all valid bits seems to be less verbose.
