### ISSUE TITLE
P4_14 (V1.0.4) : is it possible to call {add/remove/copy}_header on metadata?

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#430]
The spec states 

> Metadata is always considered to be valid.

Also the specification `remove_header` primitive action states

> If the header_instance is not an element in a header stack, then the indicated header instance is marked invalid

These two sentences would be inconsistent with each other if it is possible to call `remove_header` on metadata. (similar situation if it is possible to copy an invalid packet header into a metadata)

**Comment by jafingerhut** [comment]
I doubt it was ever intended that those operations could be called on anything other than headers in P4_14.

**Comment by kheradmand** [comment]
My guess was also that `{add/remove/copy}_header` should only be allowed on packet header and not metadata. But I could not find anywhere in the spec that explicitly says so (maybe I'm missing something).

Although I must note that there is a bit of confusion about whether "header instance" means packet header only or both packer header and metadata. Section 2.2 says

> There are two sorts of header instances: packet headers and metadata.

But the BNF grammar is:
```
instance_declaration ::= header_instance | metadata_instance 
header_instance ::= scalar_instance | array_instance
scalar_instance ::= header header_type_name instance_name ;
...
```

**Comment by kheradmand** [comment]
Probably it worth clarification in the spec.
