### ISSUE TITLE
[PSA] Map extern in psa

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#432]
Map extern is somewhat counter-intuitive because we have tables in P4. However, we cannot apply tables in the parser. There may be use cases of parsing a packet differently depending on the ingress port. A common example being a packet from the controller with some controller-defined header. 

However, as we have discussed at length, we cannot rely on the value of the ingress_port in standard metadata, so we need to have a mapping (outside P4) from the ingress_port to some logical notion of a singleton port. If we want to do this mapping in the parser, I don't see any other option except an extern.

So, I would like to propose the following extern:
// BEGIN:Map_extern
extern Map<K, V> {
  /// Create a map with at most size entries.
  Map(bit<32> size);
  /// Get value from key.
  V at(in K key);
}

The map can be populated through P4Runtime API (like we do for action profiles and selectors) or through some other config mechanism. We can discuss the actual control plane API, but it would essential add, modify and remove the key, value pairs.

Targets may implement the map extern using a hardware table, just as they may do for action profiles and selectors.

**Comment by mbudiu-vmw** [comment]
Why not use a register?

**Comment by samar-abdi** [comment]
Good point! I didn't realize we can have an arbitrary index into a register. One minor issue is that ideally, we don't want the dataplane to be able to modify the register. But I suppose this is use case dependent.

**Comment by jafingerhut** [comment]
There is also the ValueSet extern which is defined in the PSA, intended for use in parsers only, which lets the control plane populate a set of values that at P4 forwarding time can be used to determine whether a value (like ingress_port) is in that set or not.  I would have thought that using this for ingress-port-specific modifications to how packets were parsed is one of the prime use cases for this extern.

**Comment by samar-abdi** [comment]
Thanks Andy and Mihai. We can use register to map ingress_port to some controller-defined port number and ValueSet to make parser decisions. I am closing this issue now.

**Comment by samar-abdi** [comment]
Actually, on a closer read of the PSA spec, I noticed that the register extern is intended to be used as a HW register file, with an index range of 0 to size-1. 

"access to an index of a register that is at least the size of the register is out of bounds.  An out of
bounds write has no effect on the state of the system.  An out of bounds read returns an undefined value."

So, at least as per the current spec, we cannot really use register as a map. I am also mildly concerned about the dataplane program being able to modify the register contents.

@jafingerhut @cc10512 are we OK with generalizing the definition of register to be a map in PSA?

**Comment by hanw** [comment]
IMHO, the implementation of value_set provides the mapping mechanism you will need. In addition, this mapping is software-programmed (think hardware MMU managed by the OS, here OS is your controller, MMU is the value_set). Instead of redefining a new primitive, we should think about reusing existing primitive as much as possible.

**Comment by vgurevich** [comment]
+1 on @jafingerhut  and @hanw responses. ValueSet is exactly the extern you need. Please, note that if you define it to take PortId_t as the input, then the APIs/Driver can perform the remapping for you as per our earlier discussion.

**Comment by jafingerhut** [comment]
@samar-abdi If your goal is to have some ingress ports support parsing of some kinds of headers in packets, but those headers should not be parsed in packets received from other ports, and you want that set of ports to be configurable by the control plane, ValueSet alone can do this, without any need to use the Register extern.  One way would be to create a ValueSet instance "supports_protocol_foo", where the 'key' is wide enough to take a PortId_t type.  In the parser code you could do an assignment like "meta.my_meta.foo_supported = supports_protocol_foo.is_member(istd.ingress_port);", then later transition select statements in the parser can use meta.my_meta.foo_supported as the only field, or one of several fields, to select the next parser state.

The latest version of the PSA specifies that the Register extern is only required to be supported in the Ingress and Egress control blocks, and need not be supported in parsers (see the table in Section 4.1 "Restrictions on where externs may be used" -- that text isn't necessarily final, as everything in the latest PSA isn't yet final).

**Comment by samar-abdi** [comment]
Thanks @jafingerhut @hanw. I agree that selective parsing can be done with value-sets. That enables using a table to do the mapping from standard metadata ports to controller-defined ports after parsing.
