### ISSUE TITLE
P4_16: Allow DONTCARE items in list expressions

### ISSUE THREAD

**Issue by gbrebner** [p4lang/p4-spec#438]
Currently, DONTCARE (_) can occur in tupleKeysetExpression, the simple expression lists for key set expressions in select expressions.

The proposal is to allow DONTCARE also to occur in expressionList, the general-use expression lists.

There is a concrete use case in a new core library we are prototyping (more on this in a later "P4_18" issue).  Here, the expression list is for a tuple being assigned to a packet header, where a DONTCARE field value means "don't update" that field.  (Yes, this effect might be achieved by doing individual field assignment but, to improve readability and analyzability, it is desirable to assign a tuple.) 

So suggested grammar change is:
expressionList
    : /* empty */
    | expression
    | DONTCARE
    | expressionList ',' expression
    ;

Associated with this would be wording on contexts where DONTCARE is allowed in an expression list, and on the semantics of its use in each context.

**Comment by gbrebner** [comment]
Since my earlier remarks haven't attracted any feedback, here is some more.

After some further thought, I think a simpler change would be to allow DONTCARE as an expression option (which then means that it no longer has to appear as a simpleKeysetExpression option).

As mentioned in my original, my particular interest is for DONTCARE to be allowed in a list expression.  Recall that list expressions can be assigned to expressions of type tuple, struct or header, and can also be passed as arguments to methods.

For an assignment, the meaning would be that the corresponding element in the l-value is left unchanged (if it had been uninitialized, then it would stay uninitialized).  So, an example of this for a header - extending an example in the spec - is:
    header H { bit<32> x; bit<32> y; bit<32> z }
    H h;
    h = { 10, _, 12 };  // This also makes the header h valid, although it is not fully initialized
    ...
    h = { _, 11, _};  // This means the header is fully initialized (and also continues the header h being valid)
Use cases would be that one really doesn't care about some field and don't want to invent some dummy value or, as in the example, it is convenient to set up a header, tuple, or struct, piecewise.

I am not sure of any particular usefulness yet but, for completeness, an assignment of a single DONTCARE expression would similarly have the meaning of leaving the l-value unchanged.    In general, when DONTCARE appears as an expression, it would have a similar status to, say, an uninitialized header field value, that is, undefined.

My actual direct interest is for arguments to an extern method call.  Where an argument is used for assigning to some internal state, then a DONTCARE argument (or a DONTCARE member of an argument) can be interpreted as leaving that state unchanged.  Of course, this is only if an extern implementation wants to interpret DONTCARE this way - it is perfectly okay for it to interpret DONTCARE in the same way as uninitialized.

**Comment by mbudiu-vmw** [comment]
In general I think that we expect some simple properties from a programming language. For example, the two programs:

`a = b;` and `tmp = b; a = tmp;`

should produce the same value for a (assuming that a, b, and tmp have the same type and involve no casts).

Unless we actually add a runtime value of 'undefined', similar to JavaScript, I don't see how we can achieve this property for the above program.

Another simple property we would like is that for the evaluation of the right-hand-side of an assignment to produce the same result no matter what the left-hand side is.

The compiler relies on these properties when making code transformations. In the absence of these properties it is much harder to reason about programs.

I hope that there is an alternative way to achieve what you want. What is the core use case for this example?  It it is extract, maybe we can have a variant of extract where you supply a supplementary argument which is a bit-mask with the fields that you want not to have overwritten.

**Comment by gbrebner** [comment]
I suspected that the introduction of a don't care / undefined value might not prove too popular, though I thought it worth considering given that DONTCARE already has a couple of uses in the language.

Since you mention it, a supplementary bit-mask argument would indeed do my job, though it would look a bit more clumsy from a cosmetic point of view.

**Comment by cc10512** [comment]
Given that your stated interest was:
> My actual direct interest is for arguments to an extern method call. Where an argument is used for assigning to some internal state, then a DONTCARE argument (or a DONTCARE member of an argument) can be interpreted as leaving that state unchanged. Of course, this is only if an extern implementation wants to interpret DONTCARE this way - it is perfectly okay for it to interpret DONTCARE in the same way as uninitialized.
> 
would it work to have those arguments as optional? There is already support for optional arguments to methods in p4c, although they do impose ordering constraints.

Another proposal that has been brought up is to use named parameters. Using this technique, you can pass only the parameters that you require initialized by name, and the ones that you DONTCARE, are not part of the signature at all. They will get an undefined value and it should be an error to access them -- not sure how the compiler can check that in the case of an extern. However, this seems to match your initial intent -- interpret DONTCARE as it was uninitialized.

--
Thanks, Calin

**Comment by mbudiu-vmw** [comment]
If your scenario is the following:
```pkt.extract<Ethernet>( { _, _, type } )```
then I can see a path to make this work. We only allow `_` in out arguments.
We just need to generalize the language to allow list expressions to be treated as left-values and used as out arguments. That should be doable, but not necessarily trivial. I think I tried to make `_` a left-value and this introduced ambiguities in the grammar. But if we can solve this there are two steps:
- allows lists of left-values to be left-values
- allow underscores in lists which are left-values

**Comment by gbrebner** [comment]
CC> would it work to have those arguments as optional? There is already support for optional arguments to methods in p4c, although they do impose ordering constraints.

My use case is actually a single argument that's a tuple, and I wanted to allow DONTCARE values in the tuples.  So optional arguments wouldn't help (well, not unless I exploded the tuple into separate arguments, but I don't want to do that).

CC> Another proposal that has been brought up is to use named parameters. 

Yes, that discussion has been going on since the earliest days.  For the same reason as above, named arguments wouldn't help.  Though if there were named/numbered members in tuples, that would work.

MB> If your scenario is the following:
MB>   pkt.extract<Ethernet>( { _, _, type } )
MB> then I can see a path to make this work. We only allow _ in out arguments.

It's actually the opposite - it's not for extract but actually for an experimental packet method called update.  It has an in argument, not an out argument.  (Though I can imagine that this extract use case could be handy.)

**Comment by gbrebner** [comment]
I'll withdraw this suggestion, and go with the (more ugly, but less controversial) alternative approach suggested by Mihai.
