### ISSUE TITLE
P4_14 (v1.0.4): semantics of `default` in apply and select block

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#447]
According to the spec:
```
apply_and_select_block ::= apply ( table_name ) { [ case_list ] }
case_list ::= action_case + | hit_miss_case +
action_case ::= action_or_default control_block
action_or_default ::= action_name | default
```

Does `default` here mean "any other action" or "any other action or no action"?
For example in the following code:
```
apply(t){
  a {
    ...
  }
  default {
    ...
  }
}
```
If no match is found in table `t`, and the runtime does not specify a default action for that table, does the default case get selected?

The specification does not directly say anything about this, but there is an example with a comment:
```
apply(routing_table) {
  ipv4_route_action { // IPv4 action was used
    apply(v4_rpf);
    apply(v4_acl);
  }
  ipv6_route_action { // IPv6 action was used
    apply(v6_option_check);
    apply(v6_acl);
  }
  default { // Some other action was used
    if (standard_metadata.ingress_port == 1) {
      apply(cpu_ingress_check);
    }
  }
}
```

**Comment by jnfoster** [comment]
It means "any other action".

See section 12, in particular the sentences:

Note that the two modes (match selection versus action selection) cannot be
> intermixed. They are differentiated due to the fact that hit and miss are
> reserved words and cannot be used as action function names.

**Comment by kheradmand** [comment]
Hi @jnfoster, thanks for clarification :) 

I noted that sentence but I it's hard (for me) to directly infer semantic for default from it. I thought it is merely a syntactic constraint.
