### ISSUE TITLE
PSA: Proposal for metadata packing and unpacking

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#453]
[psa-example-pack-unpack.p4.txt](https://github.com/p4lang/p4-spec/files/1433121/psa-example-pack-unpack.p4.txt)

This proposal is intended to cover all cases I know about in PSA for including metadata with a packet that is staying inside the device.  This includes these cases:

+ normal unicast or multicast packet, just finished with ingress, heading towards egress
+ clone, both ingress-to-egress and egress-to-egress cases
+ resubmit (out of ingress end, back to ingress parser)
+ recirculate (out of egress end, back to ingress parser)

It is explicit in what metadata will be included, but it is a small amount of code to include all metadata, if you want, or selected subsets of it.  If you want to pass all metadata from ingress to egress or vice versa, then the user-defined metadata should be the same for both, but it is straightforward to pass large subsets of the user-defined metadata, too, without requiring that the user-defined metadata for ingress and egress be identical.

It allows arbitrary P4_16 types to be passed, including those that cannot go through today's emit() and extract() calls, such as values of enum, error, or boolean types.

As far as I can tell, it doesn't require anything to be added to the P4_16 language spec.  It does require some kind of special-ness in PSA architecture compilers, but I'll let the professional compiler writers comment on how much it is.  I hope it is relatively straightforward there.

I have attached a sample program that demonstrates what it could look like.

The basic idea is that similar to having the packet_in and packet_out types, you have packed_metadata_in and packed_metadata_out extern objects.

The packed_metadata_out extern object is a new parameter to the ingress and egress deparser, and the packed_metadata_in extern object is a new parameter to the ingress and egress parser.  The idea probably works best with a separate instance for clone metadata vs. other cases (recirculate, resubmit, and normal unicast and multicast ingress-to-egress packets), since in PSA you can create a clone, or not, in addition to the other types of packets.

In the egress deparser, for example, if a clone is to be generated, you do an if-then-else on a 'format id' (Vladimir seemed to be wanting something like this in Han Wang's example programs, so I'm assuming there is a strong use case for this).  In each of these cases, you make exactly one method call like this:
```
// 2 is the format id
clone_metadata_out.pack(2, { meta.foo, meta.bar, meta.baz });
```

In the parser where this packet is next processed (e.g. egress parser for in ingress-to-egress clone packet), you have a parser state that checks whether the packet is a clone, or a normal packet, going to different parser states.  If it is a clone, you have a transition select statement on a value (packed_metadata_in.format_id()) to one of the format id values, e.g. 0, 1, 2, etc.  Each transitions to a different parser state, where the one for format_id 2 would look like this:
```
state unpack_clone_i2e_format_2 {
    packed_metadata_in.unpack({ meta.x, meta.y, meta.z });
}
```

That unpack method call has exactly the same effect as executing these assignment statements:
```
meta.x = meta.foo;
meta.y = meta.bar;
meta.z = meta.baz;
```
except that meta.foo, meta.bar, and meta.baz do not need to be visible in the scope of the place where the unpack() call is made.

The compiler would give an error if meta.x and meta.foo had different types, or either of the other two assignments had incompatible types.  meta.x and meta.foo could be a simple type like `bit<8>`, or a user-defined struct containing sub-structs nested as deep as you wish, or headers, header stacks, etc.

The same approach works for 'bridged metadata', by doing pack and unpack calls for normal unicast or multicast packets sent from ingress to egress.  You don't have to call pack/unpack, so the extra metadata associated with a packet is optional.  If you do the common thing in P4_16 which is to create a struct type that _all_ your ingress or egress metadata field are inside of, you can just pack that one thing, and everything is included, without having to list all of the fields.

The compiler is free to get the data from the packing point to the unpacking point in whatever format it wants, without the programmer having to specify the bit order.

It is a fair amount of code if you want to have multiple formats for all kinds of packets, but since it is optional, you can write the code for only the cases that you want the extra metadata carried along.

**Comment by jafingerhut** [comment]
[psa-example-pack-unpack2.p4.txt](https://github.com/p4lang/p4-spec/files/1435466/psa-example-pack-unpack2.p4.txt)

I have attached a variation of the example code in my previous comment.  It has less 'boiler plate' code, I think making it easier on human readers and writers, and perhaps also making it easier to match pack and corresponding unpack calls up in the compiler.

**Comment by vgurevich** [comment]
Hello Andy (@jafingerhut),

Thank you for the detailed proposal with the code. I only wish we always had these :) They really show both your thinking as well as allow us to estimate the complexity/readability of the code, written in the given paradigm. Thank you!

From what I see in these two examples, the code gets fairly complicated and unless a P4 developer follows a very strict pattern, similar to what you demonstrated, the potential for errors is quite high. This code is asking to be written by a computer, at least in my opinion. 

I have a very simple question: how does it compare to simply passing the metadata structs in and out of the parsers and the controls as in/out parameters instead of explicit serialization? What is the problem doing that?  Why can't we have bridges/clone/resubmit metadata declared as out (or inout parameters to the ingress deparser and as inout parameters to egress parser/control/deparser?

**Comment by hanw** [comment]
There is an example in #448 that is similar to what @vgurevich is asking. One problem is the struct for clone metadata has to be defined by the user program, even though a problem does not use clone at all.

**Comment by mbudiu-vmw** [comment]
You can have multiple versions of the control blocks and parsers, with and without this metadata.
You can choose which version you want to instantiate.

**Comment by jafingerhut** [comment]
[psa-with-bridged-metadata.p4.txt](https://github.com/p4lang/p4-spec/files/1436632/psa-with-bridged-metadata.p4.txt)
[psa-example-bridged-metadata1.p4.txt](https://github.com/p4lang/p4-spec/files/1436633/psa-example-bridged-metadata1.p4.txt)

Following up from today's PSA working group meeting, I created a modified version of the example that just uses structs with new out parameters from deparsers, and new in parameters to parsers, to carry the metadata, one for each of the packet paths/types of resubmit, recirculate, normal (unicast or multicast from ingress to egress), clone_i2e, and clone_e2e.

psa-with-bridged-metadata.p4.txt is the same as the latest master version of psa.p4 checked into the repository as of now, plus the changes required to add these extra parameters.  You can search for the string "new:" to find all of these new parameters.  Everything else should be the same as you find in psa.p4, except I have also removed the externs for clone_out, resubmit, and recirculate that would no longer be needed if this approach is taken.

psa-example-bridged-metadata1.p4.txt is similar to my earlier file psa-example-pack-unpack2.p4.txt attached to an earlier comment on this issue, except it uses psa-with-bridged-metadata.p4.txt and the parameters to copy metadata around.  I suspect it looks nearly identical to the style of example that @hanw created on another issue, but I haven't compared them to each other yet.

They compile cleanly with the latest open source p4test from the p4lang/p4c repository, except for a couple of warnings unrelated to the code relevant to this approach.

**Comment by jafingerhut** [comment]
This is the PR with sample code by @hanw that I was thinking of that is most similar to the code I just added above: https://github.com/p4lang/p4-spec/pull/448

His example combines the user-defined metadata for clones, etc., into the structs with types named psa_*.  My example above keeps those types separate.

**Comment by hanw** [comment]
To respond to @mbudiu-vmw's suggestion, suppose a user does not need recirculate_metadata_t, we might provide an IngressParser definition without the RECIRCM type.

```
parser IngressParser<H, M, RESUBM>(    // new: types RESUBM
    packet_in buffer,
    out H parsed_hdr,
    inout M user_meta,
    in psa_ingress_parser_input_metadata_t istd,
    in RESUBM resubmit_meta,                    // new: parameter
    out psa_parser_output_metadata_t ostd);
```

and the user can instantiate with

```
parser IngressParserImpl(packet_in buffer,
                         out headers parsed_hdr,
                         inout metadata meta,
                         in psa_ingress_parser_input_metadata_t istd,
                         in resubmit_metadata_t resubmit_meta,
                         out psa_parser_output_metadata_t ostd) {}
```

Now another user does not need resubmit_metadata_t, and we provide another IngressParser definition.

```
parser IngressParser<H, M, RECIRCM>(    // new: types RECIRCM
    packet_in buffer,
    out H parsed_hdr,
    inout M user_meta,
    in psa_ingress_parser_input_metadata_t istd,
    in RECIRCM recirculate_meta,                    // new: parameter
    out psa_parser_output_metadata_t ostd);
```

and the user instantiates the ingress parser with

```
parser IngressParserImpl(packet_in buffer,
                         out headers parsed_hdr,
                         inout metadata meta,
                         in psa_ingress_parser_input_metadata_t istd,
                         in recirculate_metadata_t recirculate_meta,
                         out psa_parser_output_metadata_t ostd) {}
```

I am not sure how the compiler can tell the difference between the two instantiations.

**Comment by mbudiu-vmw** [comment]
There is no overloading for parsers, packages and controls. They have to have a different name.

**Comment by hanw** [comment]
then PSA will need to provide 2^N, N is the size of { RESUBM, RECIRCM, CI2EM, CE2EM, NM }, or 32 variants of possible packages?

**Comment by mbudiu-vmw** [comment]
2 may be sufficient, one with none and one with all. Or perhaps a few of the more common ones.
It should also be easy to supply an empty struct as a type for the package that has all of them.

**Comment by jafingerhut** [comment]
In response to hanw's comment https://github.com/p4lang/p4-spec/issues/453#issuecomment-341232690 saying: "One problem is the struct for clone metadata has to be defined by the user program, even though a problem does not use clone at all."

Having all of those metadata parameters for the different paths, but using a type 'struct no_metadata_t { }' for the ones they don't use, seems like a fairly quick way to handle the unused-path cases for particular programs.  They don't even need any assignment statements in their parsers and deparsers that refer to those parameters.

**Comment by jafingerhut** [comment]
[psa-with-bridged-metadata.p4.txt](https://github.com/p4lang/p4-spec/files/1479741/psa-with-bridged-metadata.p4.txt)
[psa-example-bridged-metadata2.p4.txt](https://github.com/p4lang/p4-spec/files/1479742/psa-example-bridged-metadata2.p4.txt)

After the discussion of the PSA working group on 2017-Nov-15, I edited the example program attached to this comment above: https://github.com/p4lang/p4-spec/issues/453#issuecomment-341327037

The only changes (other than updating to base this example on the latest version of psa.p4) are that in the ingress and egress deparser code, all assignments to the new out parameters for carrying metadata with the packets that support them are inside of 'if' statements.  The conditions on these 'if' statements are new proposed PSA extern function with names like psa_clone_i2e, psa_clone_e2e, psa_resubmit, psa_recirculate, psa_normal, that are true exactly when that kind of metadata will be included with the packet currently being processed.  The attached proposed changes to psa.p4, called psa-with-bridged-metadata.p4, includes comments describing the purposes of these new extern functions, and the precise conditions they should evaluate and return with the current PSA draft spec.

I plan to create a PR for the PSA spec with this example program, or one very much like it, which would also describe these things:

+ in the parsers, these new in parameters carrying packet metadata are defined only when they correspond to the packet_path of this packet, e.g. clone_i2e_meta is only defined in the EgressParser if the packet being processed is an ingress-to-egress clone.  Otherwise that in parameter is undefined, and its value should not be used in a portable program to affect the processing of the packet.

+ In the deparsers, a compiler is recommended to give either a warning or an error if the program attempts to assign to one of these new out parameters unless it is guarded by the appropriate if condition, which should be one of the new extern functions added for this purpose.  Rationale: Having these if conditions around such assignments may give some additional freedom to a PSA implementer to optimize the generated code, either in run-time, memory, or both.

**Comment by jafingerhut** [comment]
Created a PR with proposed changes: https://github.com/p4lang/p4-spec/pull/494

**Comment by jafingerhut** [comment]
Closing this issue, since PR #494 was discussed and merged.
