### ISSUE TITLE
PSA Should InternetChecksum extern be guaranteed initialized as if clear() was called?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#458]
That is, should the following code snippet be guaranteed to behave the same even if you remove the call to clear(), if the lines of code shown are the only ones that refer to instance ck?
```
InternetChecksum ck;

ck.clear();
ck.update({ipv4.srcAddr, ipv4.dstAddr});
ipv4.hdrChecksum = ck.get();
```
We do not have any plans in PSA for instances of InternetChecksum to maintain their value from one packet to the next, so guaranteeing they are always initialized as if you had called clear() on them seems reasonable.

**Comment by mbudiu-vmw** [comment]
I think it's safer to leave 'clear' in. It can be always compiled to a noop if the architecture does that.
Otherwise you will have to define what "packet" means, especially when you have packet generation and other odd behaviors.

**Comment by jafingerhut** [comment]
Discussed briefly during the 2017-Dec-06 P4 Arch WG meeting.  Decided to document that every InternetChecksum instance is auto-cleared for each new packet processed.  The clear() method remains, in case one wishes to use the same instance more than once per packet: https://github.com/p4lang/p4-spec/issues/514
