### ISSUE TITLE
PSA Consider adding Register constructor with initial value

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#461]
I happened to notice this example P4 code by Chris Dodd in a pull request, and it seems like a natural option to have for the Register extern in PSA:

https://github.com/p4lang/p4c/pull/1003/files#diff-1a772640e27451786c127b3cbc6c3d9c

**Comment by cc10512** [comment]
Thinking about this more: even if the change to the spec is trivial, this may be a significant burden on some targets. Assuming that you can instantiate a Register for an entire table of large size, do we expect that all entries will get the same value and is that really needed? It seems ... expensive.

**Comment by jafingerhut** [comment]
So right now, I do not think that the PSA spec says anything about the initial contents of Register instances when a P4 program begins.  Does that mean that all P4 programs using Register arrays in a read, modify, then write back fashion will have unpredictable behavior, unless the control plane writes every entry before the data plane reads it?

Counter instances are defined to have initial contents of 0, yes?  Not some random garbage in them?  And Meter instances are defined to have always a GREEN result until and unless the control plane changes that.  Those things seem to require that local agent software associated with the PSA device initialize such instances before the first packet goes through.

Specifying an initial value for Register array contents before the first packet can go through seems no harder than assuring those initial contents for Counter and Meter instances.

**Comment by cc10512** [comment]
I believe that the main difference here is that you can rely on hardware to initialize memories to a certain value, in particular 0, and it so happens that GREEN is usually zero. However, a user provided value will require explicit instructions to set the contents.

I don't think it is as bad as reading undefined values, if we assert that the non-parametrized constructor initializes the values to zero. However, if users want a different initial value, that should be set by the control plane. How likely is that they'd want the same value across all registers? In particular a value that's not zero? You probably have a much better idea on this :)

**Comment by jafingerhut** [comment]
It would be good to have at least a sentence or two giving a requirement, or lack of a requirement, in the Register section about this.

One possibility that makes it easier on PSA implementations: Mention that a PSA implementation need not auto-initialize Register contents, and control plane authors should initialize the contents of any Register array entries that the P4 program is expecting to be initialized for correct operation (there may be some Register arrays defined in a P4 program primarily for writing and recording things, rather than read, modify, and writeback behavior -- those would not need initialization).
