### ISSUE TITLE
PSA example programs to create

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#476]
Whatever mechanism is chosen for including metadata with packets, in the packet paths that support that, should be part of at least one example program, perhaps all paths demonstrated in a single program.

It would be nice to demonstrate the ability of receiving a packet in ingress, sending a normal copy that is multicast-replicated, and a clone created that goes to the control CPU with some extra headers added to it (given the spec so far, those probably have to be added to the to-CPU clone in egress processing, since ingress cloning cannot change the packet contents).  That could be part of a single example program mentioned above, if convenient to combine them.

Also demonstrate a packet that gets a parsing error on ingress, and instead of dropping it in ingress, we use some mechanism to send a copy of the packet to the CPU, with some header indicating that the packet after the header was received on ingress port X and parser error Y occurred while parsing it.  Whatever method is used should ideally ensure that the packet does not experience the same parser error in the egress parser, since Vladimir Gurevich has suggested that some platforms might not leave packet headers with well-defined predictable contents if an error occurs during parsing.

**Comment by jafingerhut** [comment]
The last example program described above is the focus of this issue (in place of this one): https://github.com/p4lang/p4-spec/issues/535

**Comment by cc10512** [comment]
@jafingerhut do we still need to build this example? We have examples of cloning, recirc, resubmit.

**Comment by jafingerhut** [comment]
Yeah, I think we have all of these examples now, except my "multicast plus send a clone to CPU" proposed one.  But the pieces of that functionality exist in already-written example programs now, so not urgent to have a separate example program just for that.  I will close this.
