### ISSUE TITLE
PSA Document any limits on parameter values of Hash extern, and others

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#478]
The Hash extern get_hash method takes a parameter max which is documented to be used to calculate a return value as `base + (hash % max)`.  The main issue is, what is expected of a PSA implementation for this value max?  If an implementation only supports power-of-2 values of max, it is easier to implement, but much less useful.  If it supports arbitrary values of max up to 2^32, that could be more expensive than some implementations would be willing to allow.  Is there some minimum set of supported values of max that we want all PSA implementation to support, so that PSA program writers can rely on that being portable?  e.g. all values 1 through 2^10?  1 through 2^8?

Similarly for restrictions or guarantees of minimum support of combinations of min, max parameter values to the Random extern's constructor.  What can PSA program writers rely on that will work across most/all implementations?

**Comment by cc10512** [comment]
@jafingerhut can we close this issue? We now have the following text:

> Truncation of cloned packets is supported as an optimization to reduce the bandwidth required to send the beginning of packets.  This is sometimes useful in sending packet headers to the control plane, or some kinds of data collection system for traffic monitoring.  Here by "headers" we simply mean "some number of bytes from the beginning of the packet", not headers as defined and parsed in your P4 program.

**Comment by cc10512** [comment]
oops, sorry, wrong issue.

**Comment by jafingerhut** [comment]
Created a PR, saying that PSA implementations need only support power of 2 for hash divisor and random range sizes: https://github.com/p4lang/p4-spec/pull/574

**Comment by jafingerhut** [comment]
PR merged in, so closing this issue.
