### ISSUE TITLE
PSA Rename InstanceType_t ?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#482]
I am hoping that by suggesting this, I am not opening a discussion of every single name chosen in the PSA spec.  If despite that hope, such a discussion does arise, I'd recommend you pick one name that gets under your skin the most, rather than proposing new names for everything :-)

Suggested new names:
+ InstanceType_t -> PacketPath_t
+ instance_type -> packet_path

It seems especially odd in the current naming that for multicast packets arriving at egress, they have an instance_type to tell you it is NORMAL_MULTICAST, and a separate field named 'instance' that is intended so that the value (egress_port, instance) is unique for all copies of a multicast packet.

**Comment by cc10512** [comment]
I've always wondered how did instance come into existence. It is true that you can see multiple copies of the same packet as instances, but once they get resubmitted and reach the parser again, they are packets in their own right.

It would be good to get a bit more input before we rename them from other folks in the WG who have been working on switching for a living! @vgurevich, @skipbooth, @jnfoster, thoughts?

**Comment by jnfoster** [comment]
I am not sure I work on switches for a living, but I like the name PacketPath better than InstanceType.

-N

**Comment by jafingerhut** [comment]
This name change been done via this PR: https://github.com/p4lang/p4-spec/pull/484
