### ISSUE TITLE
Programs can't use tables' .action_run and .hit results simultaneously

### ISSUE THREAD

**Issue by jamescoole-cisco** [p4lang/p4-spec#485]
Because the type returned by tables' `apply()` is synthesized by the compiler and that type isn't nameable, the result of a table apply can't be put in a temporary:

``` p4
T result = someTable.apply(); // what's T?
```

This means programs can either use the result's `.action_run` or `.hit` fields, but not both. It seems like this is just an oversight in the language since it's hard to imagine most implementations have trouble providing access to both pieces of information.

One way to deal with this is to just provide names for those types, ideally using namespacing like is currently done for the error type. For example, the types for a table `someTable` could be:

return struct: `someTable.result_t`
action enum: `someTable.action_t`

**Comment by jamescoole-cisco** [comment]
Extending the capabilities of P4-16 in this way can't cause problems for conversion from P4-14. It may complicate converting some P4-16 programs back to 14, but that doesn't seem like a concern that should drive future versions of the language.

Some targets may be limited in their use of those values, but some interesting ones aren't, including FPGAs and CPUs. So it would be good if using both fields could be expressed cleanly in the language.

**Comment by jnfoster** [comment]
@jamescoole-cisco +1

I wrote a half-baked proposal about a year ago that included something akin to this;
```
enum _t_result { hit : bool; action_run : _t_action }
```
https://github.com/p4lang/p4-spec/issues/58

**Comment by mbudiu-vmw** [comment]
I expect this program should work fine. The compiler will actually translate the t1.apply().hit into an if:
`if (t1.apply().hit) hit = true; else hit = false;`
This is today's implementation for the bmv2 back-end.

**Comment by jnfoster** [comment]
This is an interesting idea, but it seems to be stalled. So marking it as such and closing for now.
