### ISSUE TITLE
PSA: Add something to PSA spec about fast-failover aspect of ActionSelector extern

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#496]
@samar-abdi

Not sure if this is intended only for ActionSelector, or also for ActionProfile, but for whichever ones we want it to apply, even if the PSA does not define all aspects of how this works, we should at least have some description of the fast-failover option that a system can enable for a subset of the ActionSelector instances in a PSA P4 program.  It is OK to defer to the P4 Runtime API spec for the control plane API details, but an example P4 program that takes advantage of this feature would be helpful to understand it, especially if it had two ActionSelector instances (e.g. one L3 ECMP, one LAG load balancing) and how it is expected that the control plane would react in the event of a link failure.

In the example of an L3 ECMP ActionSelector and a LAG ActionSelector, would you expect that the fast-failover mechanism would only apply to the LAG ActionSelector instance, and not the L3 ECMP instance?

If it somehow applied to both, what would you expect the behavior to be on a link failure in the general case?  Easy case is "if a member of a LAG group fails, remove it from any groups it is part of".  If you then want to also say "if all members of a LAG group fail, also remove that LAG from any ECMP groups it belongs to" (or in general any case where there are two ActionSelector instances where one can affect the search key or result of the other), I don't see any general way to automatically infer from a P4 program what the desired fast-failover reaction in the "close control plane" ought to be.

**Comment by jafingerhut** [comment]
Perhaps a document like this, or something more official, could be added as a reference for those unfamiliar with OpenFlow watch ports?

https://floodlight.atlassian.net/wiki/spaces/floodlightcontroller/pages/7995427/How+to+Work+with+Fast-Failover+OpenFlow+Groups

**Comment by samar-abdi** [comment]
@jafingerhut 

I have come to the (painful) realization that PSA is intended to be the architecture of a reconfigurable switching *ASIC*, not the switch as a whole (embedded SW + ASIC). So, the fast failover behavior is outside the scope of PSA for now. It is however in the scope of P4Runtime, which defines a programming interface of the switch embedded software. In P4Runtime, there is a watch port specification in action profile group messages.

**Comment by vgurevich** [comment]
@samar-abdi 

+10!

**Comment by jafingerhut** [comment]
AI @jafingerhut to add a reference to PSA somewhere appropriate, probably in ActionSelector section, to the part of the P4 Runtime API that documents the watch port functionality.  This is not so much a requirement on a PSA implementer as it is a useful pointer to a feature that P4 programmers may ask for, and look for in the PSA spec.  May as well show them where to learn more.
