### ISSUE TITLE
P4_16: Result of `(int<W>) X` right shifted by W or more bits when X is negative?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#506]
Section 8.6 "Operations on fixed-width signed integers" says this about left and right shift operations:

"Arithmetic shift left and right denoted by `<<` and `>>`. The left operand is signed and the right operand must be either an unsigned number of type `bit<S>` or a non-negative integer literal. The result has the same type as the left operand. Shifting by an amount greater than the width of the input produces a result where all bits are zero."

The only part I have a possible issue with is the last sentence.  Suppose X is a value of type `int<16>` and it is two's complement negative, so its most significant bit `X[15:15]` is 1.  Arithmetic right shifts on X of less than 16 bits should do sign extension, effectively copying the most significant bit during the right shifts.

The sentence in the spec seems to imply that the result of `X >> 17` should be 0, whereas from an arithmetic shift I would perhaps expect a result of all 1 bits (-1 in 2's complement) if X was negative.

It appears from this STF test: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/arith5-bmv2.stf#L25-L26

that the combination of p4c-bm2-ss and simple_switch are doing what I would expect in this case: a right shift of a negative `int<32>` value by 255 bits results in all 1's.

It is the P4_16 spec language that I am questioning here.

**Comment by mbudiu-vmw** [comment]
This is a bug, we should fix it.

**Comment by jafingerhut** [comment]
Just to clarify your comment, do you believe it is a bug in the P4_16 language spec, or the current p4c and behavioral-model implementation?

**Comment by mbudiu-vmw** [comment]
it is a bug in the spec.

**Comment by jafingerhut** [comment]
Closing this issue, as PR #526 has made changes to address it.
