### ISSUE TITLE
[PSA] Clarification of Egress Instance

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#517]
@vgurevich @jafingerhut 

My understanding, based on P4_14 documentation, was that we use egress instance to differentiate between different copies of a multicast packet. However, I noticed that we are allowing copies sent to different egress ports to have the same egress instance. It seems that the notion of egress instance is overloaded and I will appreciate some clarification. Thanks!

**Comment by jafingerhut** [comment]
If a target device has enough bits in its egress instance value for a particular control plane's purpose, that control plane can, with that device, choose never to reuse egress instance values.

What we've written in the PSA simply says that the device should allow you to reuse egress instance values, as long as within a multicast group you do not reuse (egress port, egress instance) pairs.

More flexibility in the target device can't hurt you, can it?

**Comment by samar-abdi** [comment]
Thanks @jafingerhut . Yes, I realize the restriction. I am more interested in understanding the semantics of egress instance in switch hardware. Is it tied to a resource in a PRE implementation or just a piece of metadata?

**Comment by jafingerhut** [comment]
One reasonable implementation in hardware would be to have an SRAM near the packet buffer, indexed by multicast_group, which contains an address into another SRAM, where each entry in the second SRAM contains (egress_port, instance, next_ptr), where (egress_port, instance) get associated with the packet, and next_ptr points at another entry in the second SRAM if there are more copies to make for this multicast_group, or 0/NULL if there are no more copies to make.

That implementation would make it easy to have multiple (egress_port, instance) pairs be identical in the same multicast_group.  In such a hardware implementation, the restriction that no pairs can be the same would purely be a software restriction, not one required by the hardware.

I don't have any alternate hardware implementations to suggest that would make it impossible to have multiple pairs be identical in the same multicast_group.

**Comment by jafingerhut** [comment]
I wasn't involved in the P4_14 language spec writing, but I suspect the background here is that there are P4 programs that will want _some_ way to distinguish the different copies in the egress code, to process different copies differently from each other.

If the control plane chooses to make all egress instance values unique within a multicast group, then the P4 program egress code could use (multicast_group, egress_instance) as a key that uniquely identifies that copy.

If the control plane chooses to make all egress instance values unique across the whole chip, i.e. never reuse values between multicast groups, then a P4 program egress code could use (egress_instance) alone as a key to uniquely identify that copy.

If the control plane chooses to reuse egress instance values for different egress_port's in the same multicast_group, then the P4 program must use (multicast_group, egress_port, egress_instance) to uniquely identify a copy across all multicast groups.

It partly depends upon the reason the P4 program is doing the multicast replication, and what copies it needs to distinguish from each other, vs. which it does not.  This can depend on the 'application requirements' for which you are writing a P4 program, where here I don't mean applications running on the host, but in the programmable network devices.

**Comment by samar-abdi** [comment]
Thanks @jafingerhut . It is perfectly reasonable to disallow identical (egress_port, instance) pairs for a multicast group in the PRE API. 

Everything you say makes sense. Just out of curiosity, are there current networking use-cases where we may want to send mutlicast packets to the same port and distinguish them based on egress instance?

**Comment by jafingerhut** [comment]
Depending upon the types of interfaces supported by an IP router, IP multicast routing can require sending multiple packets out of the same egress port for the same input packet, but each with different contents.

For example, if you support VLANs, and trunk port interfaces (i.e. those that allow packets with a configurable set of VLANs to share the same physical port, each tagged with an 802.1Q header containing the VLAN), then a single received IP multicast packet can require replication to multiple L3 interfaces.  (Trunk port #7, VLAN 5) and (Trunk port #7, VLAN 10) can be different interfaces according to L3 software.  (interface here being a logical concept, not necessarily tied one-to-one to a physical port or LAG).

IP multicast where some packets in the replication list are IP tunnel interfaces can lead to a similar situation.

**Comment by samar-abdi** [comment]
Thanks @jafingerhut
