### ISSUE TITLE
[PSA] Should drop override multicast?

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#520]
In the PSA spec, we have made multicast action override a drop (Section 6.3.3). So, if a packet is marked to be dropped in an ingress table, it can still be replicated by setting the multicast group id in a subsequent table. In fact, the action to set multicast group id clears the drop bit. 

I can understand the need to clone and drop original. In fact it is very valuable in many use cases. But for ACLs to work effectively, without over-complicating the P4 program, we should define a relative priority between drop and multicast group.

One reasonable option is that drop should override multicast: i.e. if a packet arrives at the PRE with both drop bit set and the multicast group id set to a valid value, the packet should be dropped and no replicas should be made. Of course, if the multicast group id does not match any entry in the PRE, then no replicas are made.

**Comment by jafingerhut** [comment]
So the actions are explicitly stated as potentially useful, but maybe not what you want to use in your program.

The actual behavior is that no matter how many of those actions you call, in whatever order, what happens to the packet when ingress processing is done is defined by the pseudocode in Section 6.2.

That pseudocode currently has these possibilities, in the order given below as highest priority to lowest priority:
* drop
* resubmit
* multicast
* unicast

So perhaps this is already what you are hoping for, but maybe the actions need some tweaking in their documentation to make this clearer somehow?

**Comment by samar-abdi** [comment]
Thanks @jafingerhut !! This is exactly what I was hoping for. I was thrown off by the action in 6.3.3.

**Comment by jafingerhut** [comment]
No urgency here, but just wanted to check whether it is OK to close this issue, then?

**Comment by samar-abdi** [comment]
Yes, thank you.
