### ISSUE TITLE
PSA Digest extern documentation needs editing

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#530]
There are some notes about things discussed in a P4 Arch working group meeting that should be changed:

+ change the digests from having an id to an instantiation. The instance then can be used as a name to help generate control plane API.
+ add constructor parameter with a struct that captures the data serialized
+ add example that shows more than one instantiation

A more minor formatting issue is that it should be a section number like "7.14", not "7.14.1", achievable in Madoko formatting by replacing "###" at beginning of line with "##"

(Reference: https://github.com/p4lang/p4-spec/wiki/PSA-Meeting-Minutes-Nov-1,-2017 )

**Comment by hanw** [comment]
The first two items are already fixed with the current digest extern definition. Digest is an extern object to create control plane API. It takes <T> as a type parameter to capture the data serialized. I have just created a PR to fix this in the digest example.

```
extern Digest<T> {
  Digest(PortId_t receiver);         /// define a digest stream to receiver
  void pack(in T data);           /// emit data into the stream
}
```

**Comment by jafingerhut** [comment]
The latest master version of psa.p4 has the a constructor parameter "PortId_t receiver".  Maybe I am misunderstanding, but I thought there was conversation that this parameter would be eliminated?  If you think it should remain, what is its purpose?  I would have thought that digests could be gotten out of a PSA device with no association to any port of the device at all, e.g. in some implementations, they might be obtained from an ASIC for PCI express read/write/DMA accesses, within nothing to do at all with Ethernet.

**Comment by hanw** [comment]
You are right, the `PortId_t` should be eliminated since, in PSA, digest always goes to the control plane.

**Comment by jafingerhut** [comment]
The text in the PSA in the digest section also looks like it is incomplete, e.g. sentences that end in the middle with nothing after them.  It could use polishing, too.

**Comment by jafingerhut** [comment]
@hanw @vgurevich @cc10512 

I am making a pass of editing the PSA section on the Digest extern.

Is there any reason in PSA to restrict Digest 'pack' method calls to be in the ingress or egress deparser control blocks?

It seems more convenient to make such `pack` calls in the main ingress or egress control blocks.  If a PSA implementation chooses to carry that digest information to the end of a physical pipeline before it goes to the control plane, that seems to me like an implementation detail of a particular PSA implementation, not something fundamental to how a Digest object must behave.

**Comment by jafingerhut** [comment]
Significant editing that should address all comments above in this PR: https://github.com/p4lang/p4-spec/pull/558

**Comment by jafingerhut** [comment]
Closing this issue now, as everything _except_ having an example program with multiple digest instances mentioned above is addressed in this PR: https://github.com/p4lang/p4-spec/pull/558

That a PSA implementation should allow one to instantiate multiple Digest instances in ingress, and/or in egress, is mentioned in the text of these changes.
