### ISSUE TITLE
The spec does not define equality for tuples or structs.

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#542]
I think we should extend the spec rather than forbid these operations.

**Comment by jamescoole-cisco** [comment]
Makes sense to me. We may also want to consider defining it for headers.

**Comment by jamescoole-cisco** [comment]
The language for structs includes a requirement that their fields be recursively comparable

> Two structs can be compared for equality (==) or inequality (!=) only if they have the same type and all of their fields can be recursively compared for equality.

but this language is missing for headers

> Two headers can be compared for equality (==) or inequality (!=) only if they have the same type.

However, varbits can appear in headers but don't appear to be directly comparable https://github.com/p4lang/p4-spec/blob/54e425a99a387130f946d8a522bd36ac65af1e30/p4-16/spec/P4-16-spec.mdk#L2968-L2981

It seems like we should allow comparing headers that contain varbits, but if we're going to allow that we should probably also define == and != for varbits so they can be directly compared as well.
