### ISSUE TITLE
Add brief and detailed description fields for all code blocks, entities and fields

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4-spec#549]
Please see https://github.com/p4lang/PI/issues/275 additional motivation. In summary, P4 source could  be enhanced via Doxygen-style comments, annotations or first-level language constructs to document each entity, metadata or packet field to provide several benefits:
- This would encourage developers to document the code more thoroughly - most P4 code out there is light on explanation.
- A P4 compiler could extract such information and put it into the P4 Info file being developed the P4 API WG. This info could  be used by controllers and code development frameworks to auto-generate APIs, provide prompt help (e.g. in CLIs), etc.
- DOxygen-style user manuals could be generated
- A potential future IDE (e.g. an Eclipse plugin) could present pop-up help as you develop P4 code

A nice side-effect is that table match fields can automatically inherit the descriptions of the filds' original definition. So, for example, when P4 Info is generated, match fields can acquire descriptions from the original definitions of the matched fields, e.g. in a header or metadata declaration.

I therefore propose some alternative ways to add more documentation in P4 source code.

**Proposal Alternative #1 - Doxygen style comments**
Establish conventions to use DOxygen-style comments in front of any code block (e.g. table, action, control, etc.) and also field-level comments after or above field names. See https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

For example:
```
/**
  * \brief holds inner IPv4 metadata
  * This metadata is filled in with parsed inner IPv4 information
  */
header_type ipv4_metadata_t {
    fields {
        lkp_ipv4_sa : 32; //!< Inner IPv4 source address
        lkp_ipv4_da : 32; //!< outer IPv4 source address
        ipv4_unicast_enabled : 1;      //!< is ipv4 unicast routing enabled
        ipv4_urpf_mode : 2;            //!< 0: none, 1: strict, 3: loose 
    }
}
```

The advantage of this approach is that is simply requires adopting some code commenting conventions, plus it famliar to most coders. The downside of this approach is that it requires p4 compilers (or some other post-processing tool) to recogize special comments while generating P4 info.

**Proposal Alternative #2 - Annotations**
An alternative way to inject comments would be annotations, e.g.:

```
@brief("Brief description")
@description("Detailed description")
header_type ipv4_metadata_t {
    fields {
        @brief("Inner IPv4 source address")
        lkp_ipv4_sa : 32;
...
```
The advatage is we could use existing annotations capabilities; the P4 info generator already has access to these extracted annotation values. (Need to confirm annotations can be applied at any entity or field). We could modify the P4 info generator to emit the descriptions into the respective entity's "documentation" fields. Disadvantage is it will look alittle more clutttered than simple comments.

**Proposal Alternative #3 - New language constructs**
We could establish  some new first-class language contruct like in yang (yang doesn't have brief, just description).
```
header_type ipv4_metadata_t {
    brief "brief desccription";
    description "Detailed description";
    fields {
```
Advantages are it is more formalized as opposed to merely being a convention; disadvantages are it requires new language spec and compiler changes.

Personally I prefer using annotations for now and migrate to Doxygen comments over time. This way the P4 info generator can immediately recognize special annotations and extract as desired, and no compiler  parsing changes are needed in the near term.

**Comment by mbudiu-vmw** [comment]
The spec encourages the use of javadoc comments. That requires no language change and the ability to reuse existing tools.

**Comment by chrispsommers** [comment]
Mihai, thanks for responding. Do existing compilers recognize/extract the comments? The quesiton I have is, how would this documentation make it into the "p4 Info" without writing a new parser?

**Comment by mbudiu-vmw** [comment]
The p4c* compilers discard comments in the lexer. We could build separate tools or fix the compiler. But first we have to have a specification of what we need to achieve.

**Comment by chrispsommers** [comment]
Agreed, hence me posting this issuue to get a discussion going. It's also tied to the objectives of the  P4-API WG. Thanks.

**Comment by chrispsommers** [comment]
The P4 APi WG is moving ahead for now with annotations to add brief and description text, see https://github.com/p4lang/PI/issues/275. This is an expedient and short-term solution; there seems to be agreement that Doxygen comments would be a nicer long-term solution. We'd also like a long-term solution for https://github.com/p4lang/PI/issues/276 as well.

**Comment by jnfoster** [comment]
Would it make sense for you to give a quick update at tomorrow's LDWG meeting? I tentatively added an item to the agenda but we can remove it if not.

**Comment by chrispsommers** [comment]
Yes, certainly. I was expecting to do so based on the agenda item, which is why I added a comment. I may add an Issue about PkgInfo s well since it’ related. Thanks!


  *   chris

**Comment by chrispsommers** [comment]
Note https://github.com/p4lang/PI/commit/afd5831393824228246ea01b26da2f93d38fd20c added P4Info message fields for doc, doc.brief and doc.description, which can appear in PkgInfo, Preamble, match fields and action parameters. Since these fields are not extracted by the compiler yet, I created a simple utility to map annotations into new first-class P4Info fields. See https://github.com/p4lang/PI/tree/master/proto/p4info/xform.

I'd like to propose we standardize on corresponding annotations in P4 source code: `@brief("Brief text"), @description("Longer text")`. Then we can enhance the compiler to extract into P4Info accordingly.

**Comment by mbudiu-vmw** [comment]
The language support has been added, I think that if we still need this issue (e.g., for the PI) it should be filed with the compiler.
