### ISSUE TITLE
Allow enums with specified bitwidths and values

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4-spec#550]
Currently P4 doesn't allow specifying the bit width or values for enums, presumably to decouple from specific architectures. However, there are many code examples of defining constants which are written into metadata fields and used as match action entries, e.g.:

```
/* Egress tunnel types */
#define EGRESS_TUNNEL_TYPE_NONE                0
#define EGRESS_TUNNEL_TYPE_IPV4_VXLAN          1
#define EGRESS_TUNNEL_TYPE_IPV6_VXLAN          2
...

header_type tunnel_metadata_t {
    fields {
...
        egress_tunnel_type : 5;                /* type of tunnel  - can be 0-31 ? */
...

action set_l2_rewrite_with_tunnel(tunnel_index, tunnel_type) {
...
    modify_field(tunnel_metadata.egress_tunnel_type, tunnel_type);
}

table egress_vni {
    reads {
        egress_metadata.bd : exact;
        tunnel_metadata.egress_tunnel_type: exact;   // what are legal values???
 ...
```

The down side is there is know way to declare proper values to program into match fields without reading the code, nor is there any error-checking for unexpected valuesother than maybe bit width truncation.

Instead of using #defines in such cases, I propose we expand on enums, e.g. something like this or whatever the language experts think:

/** Egress tunnel types */
typedef enum bit<5> {
    EGRESS_TUNNEL_TYPE_NONE= 0,  //!< no tunnel
    EGRESS_TUNNEL_TYPE_IPV4_VXLAN=1,  //!< IPv4 VxLan tunnel
    EGRESS_TUNNEL_TYPE_IPV6_VXLAN=2  //!< IPv6 VxLan tunnel
} egress_tunnel_t;

header_type tunnel_metadata_t {
    fields {
...
        egress_tunnel_type :egress_tunnel_t;                /* type of tunnel */
...

Additionally, we'd want to include the type def and type declaration (for the match fields) into the P4 info. This way the control plane API can know what legal values to write into the table because it is defined as a data type with specific size, value and a description. If this were exported into p4 info, this could be used reject illegal values, assist control plane developers, present legal values and descriptions  to user interfaces, appear in debugger output, etc.

**Comment by jnfoster** [comment]
This issue has come up before:
https://github.com/p4lang/p4-spec/issues/394
https://github.com/p4lang/p4c/issues/861
@akeep is leading a small group of people working on a "serializable" modifier for types that would subsume this.

**Comment by chrispsommers** [comment]
Good to hear. Shoud I close this to avoid redundancy?

**Comment by jnfoster** [comment]
I think we can safely close this.
