### ISSUE TITLE
P4_16 questions on atomicity in language spec

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#556]
Question 1:

Section 16 "P4 abstract machine: Evaluation" says this:

"dynamic evaluation: at runtime each P4 functional block is executed atomically, in isolation, when it receives control from the architecture"

Does anyone know what "atomically" is intended to mean in this sentence?  In particular, is it intended to have any relationship to the control plane operations that can be done on tables, or the `@atomic` annotation?  If it was intended to mean "all control blocks should behave as if their entire bodies were annotated with `@atomic`" that seems overly restrictive on implementations, and also makes the `@atomic` annotation unnecessary, so I am guessing some other meaning was intended.

Question 2:

Section 16.4.1 "Concurrency model" contains these two sentences (not right next to each other):

"At the very least there is a thread executing the control plane, which can modify the contents of the tables."

"Execution of an action is atomic—i.e., the other threads can “see” the state as it is either before the start of the action or after the completion of the action."

Am I correct in believing that the statements below follow as logical consequences from the spec?

"Every action should be treated as if it had an `@atomic` annotation on its body, even if the programmer does not put one in the program.  Also, all control plane operations should behave as if they are performed between two action calls, not "during" an action call."

**Comment by cc10512** [comment]
@jafingerhut here's my recollection. A detailed discussion was here: https://github.com/p4lang/p4-spec/issues/48

A1: atomicity is defined entirely w.r.t. data plane. That is, field operations, extern method invocations, register read/write operations (after all they are extern methods) are by definition atomic. Sequences of these operations (and therefore control applies) are atomic only if annotated with `@atomic`.

A2: I'm afraid that action in this context is not intended as a table action, but rather one of the "actions" listed above. @anirudhSK and @mbudiu-vmw should confirm.

**Comment by jafingerhut** [comment]
@cc10512 
Thanks for the comment.

A1: I question whether atomicity is defined entirely w.r.t. the data plane, if this sentence in the spec is supposed to be there: "At the very least there is a thread executing the control plane, which can modify the contents of the tables."

A2: What are the "actions" listed above that you are referring to?  Whatever those actions are intended to be, I would strongly suggest that if they are not P4 actions of tables, that the word "action" there should be replaced with another word where what it refers to is more obvious.

**Comment by anirudhSK** [comment]
@jafingerhut:

A1: I don't know when that piece of text was written and I agree it's very confusing. It wasn't introduced by https://github.com/p4lang/p4-spec/issues/48, which @mbudiu-vmw and I were involved in. My suggestion would be to drop the word atomically from that sentence. If that text is correct, you're right that we won't need an @atomic annotation.

A2: Your interpretation is correct. "Actions" refer to table actions here. If by "control plane operations," you mean invocations of extern methods, then your description of that is correct as well.

Re: @cc10512's point on atomicity being restricted to the data plane, here's what we do and don't specify wrt the control plane.

(1) We do specify that extern method invocations, which are the means for the data plane to interact with the control plane on a per-packet basis (e.g., counters, registers, learning filters, checksums), are atomic.

(2) We do not specify anything about how the control plane interacts with the data plane (e.g., when updating forwarding table entries). All that the concurrency model says in this regard is: "Architecture specifications should describe in detail the interactions between the control-plane and the data-plane."

**Comment by vgurevich** [comment]
@jafingerhut ,

Actually @mbudiu-vmw would be the best person to answer, but I suspect that what he might have meant is that each P4 block (such as ingress/egress control, parser, deparser etc.) is viewed by the architecture (i.e. the outside component that orchestrates the whole processing by passing packets, intrinsic metadata, etc. from one fixed or programmable block to another) as a "unit of processing" that can't be further divided. Again, that's only from the outside point of view. This means for example, that the same packet cannot be processed by multiple components at the same time: it's either in the parser, in the control or in the deparser. I think that's where the word "atomically" might be coming from.

I think that the word "independently" is probably more important here (i.e. ingress control doesn't interfere with egress control and so on).

**Comment by jnfoster** [comment]
I agree with what I think @vgurevich is saying.

For Q1, I think the meaning of "atomically" is simply all-or-nothing in the
sense of database transactions, and not @atomic-like, which as defined in
#48 has richer semantics. The fact that the spec goes on to talk about
isolation, another one of the ACID properties, provides further evidence
for this interpretation. Now, one might argue that since P4 doesn't really
have any notion of exceptions or failure, calling out "atomic" is
redundant. It follows from the way the language is defined that once you
start executing a given block, you will continue executing it all the way
to the end.

Popping up a level, this stuff is really subtle and it's easy to make
mistakes. I think we should consider a formalization effort to make it
precise.

-N

**Comment by jafingerhut** [comment]
So from some of the comments above, it sounds like the following statements added to the P4_16 spec would clarify things for me, at least.  I'm happy to create a PR if others think these would be clearer, too.

1.

Replace "atomically" with "to completion" in the sentence sentence beginning with "dynamic evaluation", so the edited version reads:

+ "dynamic evaluation: at runtime each P4 functional block is executed to completion, in isolation, when it receives control from the architecture"

2.

Replace this sentence:

"Execution of an action is atomic—i.e., the other threads can “see” the state as it is either before the start of the action or after the completion of the action."

with this:

"Execution of a P4 table action is atomic—i.e., the other threads can “see” the state as it is either before the start of the action or after the completion of the action.  That is, every table action behaves as if its body was annotated with the `@atomic`."

**Comment by anirudhSK** [comment]
I think both would help. One concern is that the @atomic annotation shows
up only after the sentence about table actions. So the reader won't know
what we're referring to. We could either leave out the sentence on @atomic
or throw in a forward pointer.

**Comment by mbudiu-vmw** [comment]
Sounds good to me.

**Comment by jnfoster** [comment]
+1

**Comment by jafingerhut** [comment]
Created this PR: https://github.com/p4lang/p4-spec/pull/559

I took your warning into account @anirudhSK by moving the mention about the `@atomic` annotation being redundant on table action bodies to just after `@atomic` is first mentioned.

**Comment by cc10512** [comment]
While I see the attractiveness of defining actions as being atomic, I do want to caution that actions may be quite complex and modify multiple header/metadata fields. Given our current architectures assume one thread per packet and the control plane can't get to these modified fields, it is likely not an issue to make them atomic. However, it does seem to me that in the not too distant future when targets may implement additional processing functionality, this may come to bite us. 

Backing off this requirement may require annotating actions that need to be atomic with `@atomic`. If not actions are not atomic by default, we can annotate blocks within actions to be atomic, and then we should consider what do we say about reads/writes to fields of arbitrary sizes. It is hard to guarantee atomicity for writing a field of 128 bytes in hardware.
To avoid the burden of gratuitously annotating every action we could have a global directive that makes all actions atomic. 

We could also wait for those architecture to appear to impose such requirements on the language and the programmer. However, I wanted to raise this issue to your attention.

**Comment by anirudhSK** [comment]
@cc10512 You make an important point. My hope is that in the common case the programmer would be able to break up a non-atomic table action into smaller atomic table actions that are supported by the target. That said, it's possible that the smallest table action that the programmer can write (without unduly complicating the program logic) still can't be executed atomically. My vote would be to wait until we have more experience with real stateful programs before changing this default rule.

**Comment by jafingerhut** [comment]
It is really only the Register extern method calls that make the use of `@atomic` an issue today, correct?  I realize other externs and their method calls may become an issue later, but at least now in P4_14 and P4_16 PSA, I don't see anything else that makes implementation of `@atomic` challenging.

That said, we could choose to remove the requirement from the P4_16 spec that all action bodies must be `@atomic`, and require the programmer to add such annotations when it is important for correctness (again, I think right now that is only if Register read and write calls are involved -- without those, putting `@atomic` around a block of code makes it no easier or harder than without `@atomic` around that block of code.

**Comment by mbudiu-vmw** [comment]
Initially (P4-14) actions had started as a set of primitive operations that are all executed concurrently.
It seemed natural to expect them to be atomic.
If we don't make actions atomic we will have to say what is expected to be atomic - or to punt all this to the architecture.

**Comment by cc10512** [comment]
Requiring primitives to be atomic would be a good compromise. I would punt to architecture only some sort of hardware guarantee for unit of atomic read/writes to header fields/metadata, which the backend compiler can use to ensure the atomicity of primitives.

Indeed, only operations that maintain state across packets may be an issue, and in PSA these are only Registers. However, IIRC, we did discuss requiring in the language that extern methods are atomic. Externs live outside the language in any case. However, the point I was trying to make earlier, is that the design of the language does allow us to write controls that can run in parallel with the ingress/egress controls -- yes, they will have to be specified in the architecture, and then imposing atomicity on actions can become a significant burden. 

I like @jafingerhut's proposal of not saying that actions are atomic, and if atomicity of a certain action is required for correctness, annotate it with `@atomic`.

**Comment by anirudhSK** [comment]
@cc10512 : Re: "Requiring primitives to be atomic would be a good compromise. I would punt to architecture only some sort of hardware guarantee for unit of atomic read/writes to header fields/metadata, which the backend compiler can use to ensure the atomicity of primitives."

I like this idea, but I am a bit confused by what you mean by primitive here? Do you mean P4-14 primitive actions? I could be totally off, but I thought P4-16 no longer had the concept of primitive actions.

**Comment by jafingerhut** [comment]
Hopefully this doesn't cause too much confusion, but there are now two different PRs proposed to address this issue, the one I created before and a new one:

#559 - Continue to require table actions to be as if their entire body was annotated with `@atomic`

#560 - Eliminate the requirement that table actions be as if their entire body was annotated with `@atomic`.  Add a sentence pointing out that `@atomic` annotations within a block within an action definition are thus sometimes necessary for correct operation, e.g. when the action definition reads, modifies, and writes back a register entry that should be visible to other packets.

**Comment by jnfoster** [comment]
As long as we apply them atomically... #rimshot

-N

**Comment by cc10512** [comment]
Thanks @jafingerhut for indulging us! My vote goes for #560.

@anirudhSK, even though we translated the P4_14 primitives (modify_field, add_to_field, add_header, etc.) we still have them as basic operations in P4_16. I think we should maintain that those operations are considered atomic. This is why I mentioned that we should leave to the architecture the definition of what is the granularity of hardware atomicity (since clearly some of these operations may be quite complex and involve hundreds of bits), but still maintain that the language offers the atomicity guarantee at the primitive/operation level. Our current phrasing in the spec, captures well how to deal with such limitations: 
> A compiler backend must reject a program containing `@atomic` blocks if it cannot implement the atomic execution of the instruction sequence. In such cases, the compiler should provide reasonable diagnostics.

@jnfoster: they are mutually exclusive! ... #ball-bounces-from-rim.

**Comment by anirudhSK** [comment]
I am fine with what Andy has in his pr. I think it's sufficient if the spec
says that table actions are not atomic by default. But if we do decide to
say in the spec that the language guarantees atomicity at the operation
level, I suggest we clarify what operations mean for the purpose of
atomicity.

**Comment by jafingerhut** [comment]
I don't see how to say in the spc that the language guarantees atomicity at the operation level.

I guess for one, I don't see how any of the language operators could cause a violation of atomicity.

Everything you do in P4_16 that doesn't involve externs is invisible to all other packet threads, yes?

And every _individual_ extern call is currently defined to be atomic in the spec (unless we want to remove that, too, but I wouldn't recommend it).

So as I mentioned above, it seems that the only time one should ever need an `@atomic` annotation on anything, is for a sequence of multiple extern calls.

**Comment by anirudhSK** [comment]
@jafingerhut What you say makes sense to me. I think this means that we don't need to specify anything more beyond what #560 already contains.

**Comment by jafingerhut** [comment]
Resolved by merging PR #560, as decided during 2018-Feb-12 P4 language working group meeting.
