### ISSUE TITLE
PSA What should be specified for an empty group in an ActionSelector?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#573]
Attention to: @cc10512 @vgurevich @samar-abdi @antoninbas 

I haven't carefully reviewed the latest PSA draft section on ActionSelector to see if it is explicit about this.  If it already answers this, please just point out a quote to me and we can close this.

Should an ActionSelector group be allowed to be empty, _and_ at the same time active in the state of the data plane?

Possible answers:

1. No, we should not.  The control plane should disallow any operation that would result in this happening, e.g. adding an empty group as the action of a table entry, or removing the last member from a group that is currently in use by any table entry in the data plane.  Advantages - we do not need to define how the PSA data plane behaves in this case, because we never let it happen in the first place.  Yes, this does require a few extra checks in the control plane, but all such checks should be easily implementable in O(1) time given appropriate data structures in the control plane code, e.g. perhaps use ref counts for how many times each ActionSelector group is used by data plane table entries, and disallow removing the last member of a group when its ref count is not 0.

2. Yes, we should.  In my opinion, if we allow this, we should define a behavior in a PSA device for when a table entry is matched that has an empty group associated with it, one that is portable and required across PSA devices.  Anything else dilutes the "P" in PSA.  Antonin Bas suggested that if this is allowed, perhaps requiring the data plane to do a no-op in this case would be reasonable.

My personal preference is for #1, but feel free to comment.

**Comment by cc10512** [comment]
I prefer #1 as well. Here is what I found in our meeting minutes for discussion:

Sept 18, 2017
>- Andy: if a group has no member, then it can not be added (current bmv2 behavior)
>- Samar: group size and member size parameters
>- Vlad: there are APIs that do allow 0-member groups and that do not allow sharing
>- Andy: P4runtime?
>- Andy: what happens when going outside the specified limits? The control plane should provide a clean error message.

**Comment by jafingerhut** [comment]
Created a proposed PSA spec change in this PR to make this explicit: https://github.com/p4lang/p4-spec/pull/575

**Comment by jafingerhut** [comment]
Should we also say the control plane may never remove an ActionProfile member that is used by at least one table entry in the data plane, for similar reasons?  -- then we do not need to define what the data plane might do when matching such a table entry.

**Comment by samar-abdi** [comment]
Option 1 makes sense to me too.

Action profile members cannot be removed if they are referenced by groups or table entries. Similarly, groups cannot be deleted if they are referenced by table entries. P4Runtime should have this requirement in the spec (if not, I will add in next PR).

**Comment by jafingerhut** [comment]
See #659, which is a duplicate, but indicates that there are at least a few people in the P4Runtime API working group who would prefer if there were defined semantics for matching a table entry with an ActionSelector implementation that pointed at an empty group.

**Comment by jafingerhut** [comment]
PR https://github.com/p4lang/p4-spec/pull/662 has been merged in, which addresses this issue.
