### ISSUE TITLE
P4 2016 draft spec: `switch` vs. `select`

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#58]
P4 includes both `switch` statements (Section 12.7) and `select` expressions (Section 13.6). There are real differences in the current incarnation of the language -- expression vs. statement, and the latter must evaluate to a state value. 

This is potentially a big change, but it's worth asking if these should be merged into a single construct. Generally speaking, I think programmers would benefit from having fewer constructs in the language (fewer special cases and more uniformity). In control blocks, it might be useful to discriminate different situations using tuples, which are not available with `switch` statements. In parsers, it might be useful to be able to use statements (`transition select (...) { set1 : state1; ... }` becomes `switch(...) { set1 : transition state1 ... }` which would sometimes be cleaner and more readable).

**Comment by mbudiu-vmw** [comment]
@jnfoster : we should either close this issue or add it to the list of issues to discuss.
There is a mention of this in the spec as well in a section about open issue, which we could probably take out until we resolve the issue.

**Comment by mbudiu-vmw** [comment]
Here is the contents of Appendix G in the spec version 1.2.3:

P416 includes both switch statements [12.7](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-switch-stmt) and select expressions [13.6](https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-select). There are real differences in the current version of the language – expression vs. statement, and the latter must evaluate to a state value.

We propose generalizing switch statements to match the design used in most programming language: a multi-way conditional that executes the first branch that matches from a list of cases.

switch(e1,/* parameters omitted */,en) {
  pat_1 : stmt1;
  /* body omitted */
  pat_m : stmtm;
}

Here, the value being scrutinized is given by a tuple (e1,/* parameters omitted */,en), and the patterns are given by expressions that denote sets of values. The value matches a branch if it is an element of the set denoted by the pattern. Unlike C and C++, there is no break statement so control “falls through” to the next case only when there is no statement associated with the case label.

This design is intended to capture the standard semantics of switch statements as well as a common idiom in P4 parsers where they are used to control transitions to different parser states depending on the values of one or more previously-parsed values. Using switch statements, we can also generalize the design for parsers, eliminating select and lifting most restrictions on which kinds of statements may appear in a state. In particular, we allow conditional statements and select statements, which may be nested arbitrarily. This language can be translated into more restricted versions, where the body of each state comprised a sequence of variable declarations, assignments, and method invocations followed by a singletransition statement by introducing new states.

We also generalize the design for processing of table hit/miss and actions in control blocks, by generating implicit types for actions and results.

The counter-argument to this proposal is that the semantics of select in the parser is sufficiently distinct from the switch statement, and moreover these are constructs that network programmers are already familiar with, and they are typically mapped very efficiently onto a variety of targets.
