### ISSUE TITLE
No appendix 17.8.2 in newest P4-14 spec?

### ISSUE THREAD

**Issue by onlyfly34** [p4lang/p4-spec#596]
In newest P4-14 spec P.12, it says:
> See the proposal in Appendix 17.8.2.......

But there's no such chapter, any ideas?

**Comment by jafingerhut** [comment]
It looks like that sentence is in v1.0.2 and v1.0.3 of the P4-14 spec as well, which are the oldest versions in the p4-spec repository.  I do not know where older versions might be stored that could be examined to see when this line was added.
