### ISSUE TITLE
P4_16: Named parameters

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4-spec#598]

**Comment by jafingerhut** [comment]
@cc10512 One thing that confuses me about the idea as described on the wiki here: https://github.com/p4lang/p4-spec/wiki/Named-Parameters

I think you have said that the proposal is only to allow named parameters for compile-time parameters, e.g. compile-time parameters for controls and parsers, package instantiations, and extern constructor calls.  That makes sense to me.

But one of the examples on the wiki is for the parameters resubmit_meta and recirculate_meta of the PSA IngressParser to be named, with a default value.  Those are run-time parameters to the parser, aren't they?

If you allow those run-time parameters to have default values, what criteria would you propose to distinguish the cases where run-time parameters can have default values, vs. those that cannot?

If you do allow cases where run-time parameters can have a default value of _ as shown in your wiki example, what should happen if that parameter is accessed in the body of the control/parser?  Should that be an error?  If it isn't an error, _what value should that parameter have at run-time if it is not supplied in the call to the parser/control at run time_?

**Comment by mbudiu-vmw** [comment]
We should allow calls to use named parameters everywhere.
We should only allow default values or optional parameters in some kinds of declarations.
