### ISSUE TITLE
Add support for key=value pairs in annotations

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#605]
This would enable annotations like
```
@pkginfo(name="my package", date="2018/3/29", version=2)
```

**Comment by ChrisDodd** [comment]
duplicate of #99 ?

**Comment by mbudiu-vmw** [comment]
Seems to be. But the key=value part does not seem to be implemented...
So we should probably reopen that.

**Comment by ChrisDodd** [comment]
IIRC at the time it was decided that full java-style <identifier> = <expression> annotations were not needed.  But they should be relatively easy to add; the main concern is not impacting existing uses of simple <expression> annotations.
