### ISSUE TITLE
versioning for working version

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#610]
Update Markdown so that working version is not incorrectly tagged as v1.0.0.

**Comment by SantiagoBautista** [comment]
What is the number of current version? 1.0.5 ?

**Comment by jnfoster** [comment]
The released version of P4_16 is v1.0.0. The next (minor) version will be released at the P4 Workshop.

**Comment by SantiagoBautista** [comment]
The version in the Markdown was corrected in #629 , so this issue can be closed :)
