### ISSUE TITLE
Serializable Enums

### ISSUE THREAD

**Issue by akeep** [p4lang/p4-spec#611]
Hey All,

The serializable working group is closing in on a resolution for the serializable enums feature request.

The current write-up of where we are is: https://github.com/akeep/p4-proposals/blob/master/enum.pdf part of the public repository: https://github.com/akeep/p4-proposals

The current potential options are described in the document, but to call out the list here, we have a few questions left to answer:

1. What should happen if a serializable enum is used in a header, but doesn't have a complete set of mappings from integers to symbols (as in the ``etherType_t`` enum example in the proposal), and we then extract from ``packet_in`` into the header.  We discussed a few options:

    1. Avoid the problem by disallowing enums in headers.
    1. Raise a parsing error when the numeric value does not have a symbolic representation in the enum
    1. Allow the operation with the possibility that the result will be undefined.

1. What should happen if a serializable enum is cast to from an integer type, and there is no mapping from the integer value to a symbolic one.  And we talked about a couple of actions.

    1. Avoid the problem by disallowing casts from ``bit<n>`` values to enums
    1. Allow the operation with the possibility that the result will be undefined.
    1. Provide a ``convert`` extern that takes a default value to be used in the case where the supplied ``bit<n>`` value is outside the symbolic list.

    (Note: we cannot necessarily raise an error here, since the cast might happen outside the parser.)

1. What happens when two symbols map to to the same underlying numeric representation?  We didn't have much discussion about this, but I would propose that we should either.

    1. Avoid the problem by disallowing more than one symbol to map to the same numeric value.
    1. Treat these two symbols as aliases for each other, effectively meaning these symbols are interchangeable.

I guess my personal bias is towards 1. iii., 2. ii., and 3. i.  My big concern with 1. i. and 2. i. is that this limits the usefulness of the enums so as to make them somewhat useless.  For instance, I then could not have an enum in the header for ``ether_t``, nor could I cast the ``bit<16>`` representing the ``etherType`` to an enum.  Others have brought up concerns about the expense of implementing 1.ii. and 2. iii..  One way to possibly mitigate this is to only allow these in cases where the symbol values are densely grouped within a numeric range, requiring only a less than or less than and greater than checks to determine if it is in range.

At the same time, there is no question that 1.iii. and 2.ii. do trade off a bit of safety, because after an extract or cast, we cannot assume the enum will have a value that matches one of the symbolic values.  Arguably, this is also true when we choose to simply represent the same information as a ``bit<n>`` type.

**Comment by antoninbas** [comment]
I'm also in favor of the the less-constrained and cheaper to implement approach (1.iii, 2.ii and 3.i) because I believe it will be much more useful in practice.
I would like to add the following though (for 1 and 2): when casting from an integer value to an enum, if there is no mapping from the integer value to the symbolic one, then the resulting enum value should never test equal to any valid symbolic value.
If I try to formalize it:
Given `E` an enum type, `S` the set of symbolic value for `E` and `N` the set of valid numerical values for `E`: if an integer `x` does not belong to `N` then `(E)x` != `e` for all `e` in `S`.

**Comment by mbudiu-vmw** [comment]
This last requirement does not exist in other languages, and it has important consequences, e.g., if all possible cases are covered by a set of if statements. Maybe we need two kinds of enums: safe and unsafe. There are many benefits of safe enums, and it is not good to loose all of them because we sometimes want unsafe enums. Perhaps there could be an annotation `@safe` to describe the difference.

**Comment by antoninbas** [comment]
@mbudiu-vmw I think that could work, but using two different keywords (`enum` and `safe_enum`) would probably be better than an annotation. `safe_enum` would have the same definition & properties as the current P4_16 enum.

**Comment by mbudiu-vmw** [comment]
That is certainly doable. We can disallow casts on safe enums altogether.
We can still have a "safe cast" function for unsafe enums, with a default value, but people would not be forced to use it.

We should also consider that if we add namespaces we can have something like this:

```
namespace EthTypes {
   const bit<16> ipv4 = 0xd00;
   const bit<16> ipv6 = 0x86dd;
}
```

Then we can just use EthTypes.ipv4 - it looks like an enum, but it is in fact a `bit<16>`. This may be a better way to address such a use case.

**Comment by antoninbas** [comment]
@mbudiu-vmw I think one advantage of enums is that we have symbolic values to expose to the control-plane.
If I define a table which matches on the ethertype, and ethertype is of type `enum EthType`, the application can (must?) populate the table using `"EthType.IPV4"`, `"EthType.IPV6"`. That's easy to do with enums, I'm not sure how easy it would be with the constants approach.

**Comment by akeep** [comment]
Thanks for the conversation on this, guys.

If we went with an approach like `safe_enum` vs. `enum` would the idea be that a `safe_enum` is the current-style symbolic only `enum`? and `enum` is allowed to be the serializable enum that has a related backing numeric type and values, or would `safe_enum` also permit serializable enums that completely cover the space of their backing numeric type?  In other words would the following be considered a safe `enum`?

```p4
enum bit<2> Example {
  A = 0,
  B = 1,
  C = 2,
  D = 3
}
```

Also, @antoninbas it sounds like you are still in favor of doing this as a `enum` in stead of trying to do namespaces with constants as @mbudiu-vmw suggested, @mbudiu-vmw is there a strong preference for what you namespaces + constants over serializable enums?

I'd like to try to write up a pull request for the spec on this, if we feel like we've sort of settled on a solution for this stuff.  If I don't hear back to the contrary I'll write up the `enum` and `safe_enum` idea this evening and I'll add you both as reviewers, so we can work through the details.

**Comment by mbudiu-vmw** [comment]
Perhaps the safe enum should not be serializable at all. Or it could be serializable in only one direction: you can write it, but cannot read it. A third alternative is for safe enums to only be readable using the safe version of the conversion function, which always has a default value.

@akeep: we could also have a special case for an enum like yours which covers all 2^k possibilities, and thus will always be safe.

**Comment by antoninbas** [comment]
I think `safe_enum` should be exactly the same as the current enum, with the same guarantees and supported operations.
One thought: maybe we do not need a different keyword for `safe_enum` vs `enum`. Maybe specifying an underlying primitive type makes an enum "unsafe" / serializable / "castable":
```
// safe enum (same as today)
// cannot assign numerical values to members
enum Enum1 {
  A
  B
}
```
```
// "unsafe" enum
// can be serialized / deserialized
enum bit<4> Enum2 {
  A = 0
  B = 1
}
```
And once again I do think we should have the following properties if we want this unsafe enum to be useful.
Given `E` an enum type, `bit<W>` its underlying type, `S` the set of symbolic value for `E` and `N` the set of valid numerical values for `E`:
  1. if an integer `x` does not belong to `N` then `(E)x != e` for all `e` in `S`
  2. for every integer `x` in `[0, 2^W[`, `(bit<W>)(E)(x) == x`
  3. for every enum member `e` in `S`, `(E)(bit<W>)(e) == e`
I think these are all pretty trivial and I don't see how an implementation would not be able to guarantee them.

**Comment by akeep** [comment]
@antoninbas That sounds good to me, by their nature the old `enum` is not cast-able (meeting @mbudiu-vmw last comment about `safe_enum`) and I agree with you on the properties we want on this.  Thinking of how I would implement this in software, these properties feel very natural to me.

@mbudiu-vmw I think it is fine not to special case the `enum` from my example.  Did you want to add an optional 'safe_cast' for the serializable `enum`.

**Comment by jamescoole-cisco** [comment]
I don't see any harm in providing a `safe_cast`, but the current definition of `convert` with a single output parameter is awkward. Is there a reason it can't look more like a normal cast operator?:

``` p4
extern E safe_cast<E, D>(in D data, in E forInvalid);
```

It might also be useful to expose the range check separately, like:

``` p4
extern bool can_cast<E, D>(in D data);
```

One argument in favor is that writing equivalent code is laborious and fragile. Implementations are always free to warn or error when performing this check for a given `enum` is expensive.

**Comment by mbudiu-vmw** [comment]
@antoninbas makes a very good suggestion; so if you specify a width it's no longer safe.
@jamescoole-cisco : what you wrote is still a function. Calling it 'cast' will probably be confusing.

**Comment by jamescoole-cisco** [comment]
@mbudiu-vmw I don't have a preference for these being provided as externs. I was just tweaking the proposed declaration to have a return value instead of an out parameter. This way, calls can be used more like the cast operator, e.g. appearing in expressions. I removed the word cast in the examples to be less confusing.

**Comment by mbudiu-vmw** [comment]
Even if the value is undefined, we can ask for it to be equal to one of the legal values. in other words, if you have something like `if (value == EnumA) ... else if (value == Enum.B) ... else ...` and if we list all the values of the Enum, then we know that the last `else` will never be reached.

**Comment by akeep** [comment]
Hey All,

Unfortunately, it doesn't look like I can add reviewers to a PR, but #615 has been created.  Sorry for the delay getting this out, I got sucked into team demo prep at work and lost about a week to it and I'm just digging out now.

Let me know what you think.
-andy:)

**Comment by jafingerhut** [comment]
I wanted to correct a comment I made earlier in this discussion, here: https://github.com/p4lang/p4-spec/issues/611#issuecomment-385302293

My comment is all the more weird because I was the one that wrote the change to the P4_16 spec (after v1.0.0) that says this: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L3354-L3366

So the language _does now_ explicitly say that uninitialized values with type enum and error might not be equal to any of the named members of the type.

**Comment by mbudiu-vmw** [comment]
I think this can be closed now.
