### ISSUE TITLE
PSA numerical translation of PortId_t etc. in data plane

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#622]
PSA v1.0 and P4Runtime v1.0 define types like PortId_t and ClassOfService_t that are expected to use different numerical values in the data plane vs. in the P4Runtime control plane messages between controller and agent software.  The agent software will perform numerical translation for these values whenever they appear in P4Runtime messages.

We may want to discuss the possibility of defining "PSA standard" ways for a data plane to do such numerical translation.  The primary use case I can think of would be including these values in packets that will not go through the agent software, such as:

+ packets directly to/from other P4 target devices, e.g. in INT headers
+ packets to/from the controller (without going through the P4Runtime gRPC TCP connection, perhaps desired in other cases), or to any other entity that is not the agent (e.g. a Netflow / INT data collector)

**Comment by samar-abdi** [comment]
If a switch wants to support such translation in the dataplane, it can easily add twoP4  tables (one in the beginning of ingress and another at the end of egress) to do the translation back and forth. The P4 tables can be programmed over P4RT by the switch config handler (which will get the translation data as part of the config). It's just that this translation is possibly expensive and not viable for most fixed function devices. So, defining it as a PSA standard might be tricky from a portability point of view.

BTW, the emitters and  collectors of such packets can also do the translation, no (assuming they know the topology)?

**Comment by jafingerhut** [comment]
Agreed with everything you said, Samar.  I created this issue primarily as a reminder to bring up the topic at a future P4 Arch work group meeting, to see if there was any interest in standardizing such a mechanism.  For the reasons you describe, and perhaps others, there may not be.

**Comment by mbudiu-vmw** [comment]
Is this issue still open?

**Comment by jafingerhut** [comment]
We had several meetings on it in spring/summer 2018, and there is a PR to update the PSA spec with what we came up with then.  I am happy to close this issue after it all lands in the specs, which might be soon or not so close, depending on how review of that PR goes.

**Comment by jafingerhut** [comment]
Closing this issue as PR https://github.com/p4lang/p4-spec/pull/678 has been approved and merged in.  The implementation in p4c and p4runtime still has a few pieces left to do, created as separate issues.
