### ISSUE TITLE
P4 module system

### ISSUE THREAD

**Issue by ppenzin** [p4lang/p4-spec#628]
Hi,

After compiling a few mid-size examples I've ran into a couple issues with using preprocessor within single compilation. I am highly suspicious that this can come up much more often in really large codes.

First is that that it is impossible to know if all files `#include` everything necessary or just piggy-back on includes from above, like this:
```
// define control A
#include a.p4
// define control B that depends on control A
#include b.p4
...
```
If `b.p4` is missing `#include a.p4` this would still compile, because preporcessed source would have everything in correct order. This leads to errors after switching order of `#include` directives. The solution is to guard the entire source with `#ifndef` in a way done in C or C++ headers, but it requires a bit more discipline than in case of C family, since it has to be done for every source file (versus only header files).

Second is name conflicts in preprocessed source. Because all files that are `#include`'d into a single .p4i file every exposed name needs to be unique. It is also fixable by prepending names with something contextual (like `ingress_A` instead of `A`), but that can affect core reuse, since names like this can go out of date when the code is incorporated into a different application or even a different part of the same application.

Looks like there was some [discussion][c] about this in #30. I am wondering if this is something that would be addressed in future revisions of the standard. One way to address this would be some form of non-transitive 'import' keyword (meaning that it would pull in only one level of imported files), which would provide some form of name hiding and would ensure that every source includes its own dependencies.

[c]: https://github.com/p4lang/p4-spec/issues/30#issuecomment-252094092

**Comment by ppenzin** [comment]
I was thinking of Python and Haskell as well. But in spirit of P4's simplicity explicit module definitions might not be necessary. Maybe have "import" add all symbols (besides ones imported from into it) from imported file to the current symbol table. There can be limitations on where such "import" statement can be placed in the source file (probably top level only, may be before all declarations).

Let me know if I can do anything to help -- with prototyping or write up.

**Comment by mbudiu-vmw** [comment]
If you or your organization is a member of p4.org you should consider joining our design discussions for the modularity constructs in P4. If you are not perhaps you should consider joining - there is no cost, you just have to sign a CLA form. We have some online meetings roughly every two Mondays. 

Any other contributions are encouraged, including a design proposal or even code prototyping. If you have a proposal for an 'include'-like construct design the right solution is to submit a pull request against the spec with your changes. (For us to accept the pull request you may need to be a member of p4.org.)

**Comment by mbudiu-vmw** [comment]
Personally I think we should give a high priority to a nice 'import' mechanism; it should be relatively simple and it should not take too many resources to design and implement, but the payoff may be substantial.
So thank you for bringing this up.

**Comment by jnfoster** [comment]
+1.

Having namespaces and import would be a win and is easier technically than
some of the issues we've been dealing with in the modularity group so far.

We should fork off a parallel thread to explore this.

-N

**Comment by ppenzin** [comment]
I think I will be able to join, I'll try to follow the instructions on https://p4.org/join/

**Comment by ppenzin** [comment]
I have submitted the CLA form, but not able to join mailing lists for some reason. Let me know if you want me to be part of any of the meetings. In the meantime, I will try to put a PR together.

@jnfoster, what is the best way to start a thread? Another issue?

**Comment by mbudiu-vmw** [comment]
We haven't had any meetings lately.
Have you followed the directions here for joining the mailing list?
http://lists.p4.org/mailman/listinfo/p4-design_lists.p4.org

**Comment by ppenzin** [comment]
I got through, thank you! I am not on p4-dev yet though, not sure if that is important.

**Comment by jnfoster** [comment]
Petr, can you send me an [email](mailto:jnfoster@cs.cornell.edu)? I'll send you the info for the P4 Modularity meetings.

**Comment by jnfoster** [comment]
Marking this as stalled.
