### ISSUE TITLE
Let annotations take an argumentList rather than `expressionList | keyValueList `

### ISSUE THREAD

**Issue by SantiagoBautista** [p4lang/p4-spec#633]
Currently in the P4-16 grammar, annotations can take either an expression list or a keyValuePair List for their arguments and this allows arguments to annotations to be named:
```
annotation
    : '@' name
    | '@' name '(' expressionList ')'
    | '@' name '(' keyValueList ')'
    ;
```
But this makes the grammar ambiguous, because there is no way of telling whether the empty list is an expressionList or a keyValueList.

There is a non-ambiguous and nicer way of achieving exactly the same behavior:
there is a non-terminal in P4-16 grammar called argumentList , and each argument can either be an expression or a `name '=' expression` (i.e. a keyValuePair).

So if annotations took an argumentList, instead of either an expressionList or a keyValueList, we would have exactly the same behavior, but without introducing ambiguity to the grammar.

I will open a Pull Request implementing this solution.

**Comment by jnfoster** [comment]
I guess the one difference is "_".

But generally, yes, this seems like a nice simplification.

On Thu, May 31, 2018 at 4:40 PM, Santiago Bautista <notifications@github.com

**Comment by SantiagoBautista** [comment]
To be precise, there is another difference: if annotations take argumentList, then one single annotation can take both key-value pairs and expressions; whereas with the current grammar one annotation can either only take expressions or only take key-value pairs.

But this extra flexibility can, I guess, be useful, and AFAIK it doesn't introduce any problems.

**Comment by SantiagoBautista** [comment]
For information:
This issue is related to #605 and #625 .

**Comment by chrispsommers** [comment]
@SantiagoBautista I like this, good catch!

**Comment by SantiagoBautista** [comment]
Thank you @chrispsommers !

**Comment by mbudiu-vmw** [comment]
This is no longer relevant, since we now have free-form annotations.
