### ISSUE TITLE
parser_value_set equivalent

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#65]
P4-14 has a parser_value_set construct that encapsulates a set of values that can be specified at run-time by the control plane and used to choose parser state transition (Section 5.3 page 38 in P4 spec v1.0.2)

For example, for programmable TPIDs one would do something like this:

parser_value_set tpids;

parser parse_ethernet {
    extract(ethernet);
    return switch(ethernet.ethertype) {
        0x0800: parse_ipv4;
        0x86DD: parse_ipv6;
       tpids: parse_vlan_tag;
       default: return ingress;
}

and then the assumption is that the compiler will generate appropriate control plane APIs to manage the parser_value_set "tpids" (could be a list of values, a list of cubes, or whatever).

It is not quite clear how to achieve the equivalent functionality in P4-16. Intuitively, an extern must be the right mechanism, but based on the grammar we need to be able to declare an extern with a method that returns a set (see section 13.6 on p. 65 in P4-6 draft). I do not think the grammar allows this.

**Comment by jnfoster** [comment]
Closing this issue, as discussed above.
