### ISSUE TITLE
PSA - define behavior for empty ActionSelector groups?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#659]
In a P4Runtime working group meeting, some people expressed a desire that PSA have well-defined portable behavior in the case where a table entry pointed at a group that had 0 members.  This could simplify control plane software in some cases, e.g. removing the last port in a LAG, where OpenFlow currently defines behavior of dropping the packet (so it was said in the meeting -- I do not have deep knowledge there).

One possibility would be to treat the case where a match occurs, but it points at an empty group, similar to a miss, in that the table will execute its default action.

An alternate approach to consider - leave the behavior of empty groups undefined (i.e. it might be non-portable behavior across implementations), and require software, when it wants to change a group from the state '1 up port to use' to 'no up ports to use', to first add a 'drop' action to the group, then remove the last '1 up port to use' action from the group.  The group remains non-empty at all times, and ends in a state where all packets using that group are dropped.

**Comment by antoninbas** [comment]
@jafingerhut I think you already opened an issue in the past: https://github.com/p4lang/p4-spec/issues/573

**Comment by jafingerhut** [comment]
Closing as duplicate of #573.
