### ISSUE TITLE
bitslicing signed bitstrings

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4-spec#668]
I ran into an underspecified hole in the type system specification around slicing one bitstrings.  Section 8.5 talks about bitstring extraction operations `[m:l]` but only talks about the relations between the sizes of the of the source and resulting bitstring, and never mentions signedness (`bit` vs `int`).  Obviously an extraction from an unsigned `bit<n>` bitstring should be an unsigned `bit<k>` bitstring, but what about an extract from a signed `int<n>` bitstring?  There are arguments either way.

The p4c implementation preserves the signedness, so an extract from a signed `int<n>` bitstring is always a signed `int<k>` type, but this has an unfortunate corollary:  you can't extract a single bit from a signed bitstring as that would have the disallowed type `int<1>` (7.1.6.3).

We should clean up the hole, but there are a number of ways we could do it

1. Codify the p4c behvior of preserving the signedness, and note the odd effect that you cannot extract a single bit from a signed `int<n>` value

2. Codify a different behavior (and change p4c to match)

    1. bitstring extracts always result in unsigned `bit<k>` values

    2. single bit extracts result in `bit<1>` but multibit extracts from `int<n>` result in `int<k>`

    3. Extracts from `int<n>` result in `int<k>` values iff `m` is the msb and `l < m`, and `bit<k>` values otherwise (k = m - l + 1 as always)

Alternately we could also (or independently) relax the prohibition on `int<1>` -- this type is weird (a bare sign bit), but does have a reasonable meaning (can only contain the values 0 and -1)

**Comment by cc10512** [comment]
From the alternatives you suggest, I prefer 2. Although supporting int<1> sounds quite reasonable, extracting a single bit from an int<n> and ending up with sign bit seems wrong. Getting a bit<1> is much more inline with what's likely to be the programmer's intention.

There is another alternative: prohibit slices on signed int altogether. Likely too big of a hammer, but I thought I would put it out there.

**Comment by jafingerhut** [comment]
No strong opinion here, but out of alternatives mentioned, these sound most reasonable to me:

+ prohibit slices on `int<W>` types completely.  We could point out that `int<W>` can be type cast to `bit<W>` first (which does not change the sequence of bits at all), then bit slicing is available on the result.

+ allow slices of any width, even down to only 1 bit wide, on `int<W>` types, with the result being `int<X>` for X <= W.  Allow `int<1>` type.

**Comment by mbudiu-vmw** [comment]
Users can also cast to unsigned. Before slicing. We should not change existing semantics.

**Comment by jnfoster** [comment]
I like Mihai's suggestion.

**Comment by vgurevich** [comment]
@mbudiu-bfn , ouch... I can't wrap my head around 1-bit signed integers, really.... In that sense unsigned-only bit-slices look more plausible. What's your idea bout signed 1-bit integers?

**Comment by mbudiu-vmw** [comment]
@ChrisDodd explained it above: they can only have the values 0 and -1.

**Comment by mbudiu-vmw** [comment]
Interestingly, the spec does not say anything about slices from `int<>` values. I will submit a PR which adds slices for `int<>` with a result which is `int<>`. I think the result should probably be `bit<>`, but if the implementation has been this way we should perhaps preserve it. That's something we should discuss during the design meetings.
