### ISSUE TITLE
PSA Consider removing control plane API portions of PSA spec?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#669]
Instead leaving it up to the P4Runtime API group to define completely?

I know that PSA doesn't _require_ that you use P4Runtime with it, but it seems like pretty low value to try to define a "low level control plane API" in PSA that P4Runtime is implemented on top of, with the idea that this same "low level control plane API" would also be used as defined in the PSA spec by some alternate to the P4Runtime API.

**Comment by jnfoster** [comment]
As a general principle, I think it makes sense to have "definitional" things in just one place. The P4 Language Spec already mandates some of this, but leaves certain decisions to architectures. P4 Runtime might provide further guarantees and specific architectures like PSA might tighten things down further. 

So perhaps the way to go is: provide a brief summary of what's mandated in the P4 Language Spec and P4 Runtime, with a pointer to those documents. Then spell out what's more specific in PSA?

**Comment by jafingerhut** [comment]
Closing this older issue as a duplicate of the newer one here https://github.com/p4lang/p4-spec/issues/940
