### ISSUE TITLE
P4_16 addition of functions should cause other parts of spec to be updated?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#680]
In particular, Section 7.2.8.2 "Function types" seems to predate the addition of functions, and seems very misleading now:

"Currently function types cannot be created explicitly in P4 programs; they are created by the P4 compiler internally to represent the types of functions, procedures, and methods during type-checking. We also call the type of a function its signature. Libraries can contain extern function declarations."

There may be other parts of the spec that could similarly use updating.

Perhaps the only update needed here might be to qualify the first sentence with "Currently extern function types ..."

**Comment by mbudiu-vmw** [comment]
If we haven't done this we have a bug in the spec.

**Comment by mbudiu-vmw** [comment]
Actually the statement is still correct - the user cannot write down a function type, but they can write functions and extern function declarations.
