### ISSUE TITLE
P4_16 proposal to make type casts "more powerful" if `type` types are involved

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#682]
In reviewing the proposed mechanisms for PSA to identify types requiring numerical translation between control plane and data plane among @cc10512 @jnfoster and myself, one of them mentioned the following idea for a change, which would make some kinds of type casts required in that proposal reduce from 3 down to 1.

Example:

```
type bit<9> PortId_t;
typedef bit<9> PortIdUint_t;
typedef bit<32> PortIdInHeaderUint_t;
type bit<32> PortIdInHeader_t;

PortIdInHeader_t x;
PortId_t y;

// This is required today to assign the value of x to the variable y.
// Truncation from bit<32> down to bit<9> done using the middle of the 3 casts.
// The other 2 casts are there only to get between a custom `type` and its "base type",
// but do not otherwise change the value at all.

y = (PortId_t) ((PortIdUint_t) ((PortIdInHeaderUint_t) x));

// With today's language spec and p4c implementation, the assignment below is a compile-time error.
// With the change proposed in this issue, the assignment below would be correct, and the compiler
// would effectively auto-generate the above from the single cast in the source code.

y = (PortId_t) x;
```

**Comment by mbudiu-vmw** [comment]
This looks easy, but this is because both `type`s are for types that can be directly cast to each other.
Can you write a general rule which describes when casts between `type` types are allowed?

**Comment by jafingerhut** [comment]
Maybe this?

For every type defined via a statement `type A B;`, define the "transitive underlying type" (or TUT) of B to be A, if A is not defined via a `type` statement, or the underlying type of A, if A is defined via a `type` statement.

The cast expression `(A) expression` is legal if the cast `((TUT_of_A) ((TUT_of_expression) (expression)))` is legal.  It is equivalent to that expression, if you also add in all of the intermediate casts needed to convert `(expression)` to type `(TUT_of_expression)`, and to convert a value of type `(TUT_OF_A)` to type `A`.

**Comment by mbudiu-vmw** [comment]
The situation is harrier if you consider tuples that have multiple fields each of which could have some different type. Technically structs cannot be cast, but we do allow casts when the `type` refers to a struct. We also have the problem that list expressions can be implicitly cast to struct types that have the suitable fields.

**Comment by jafingerhut** [comment]
Maybe I am thinking too small here, but with my proposed behavior in my last comment above, it seems that in most or all of the cases you describe, these new rules would not apply, and so the new style of cast wouldn't be useful in such cases?  Or if I am wrong on that, perhaps you have a specific example of two types and a cast from one to the other where my definition would raise questions?

If the biggest criticism of my proposal is that it doesn't recurse into structs/list members/header fields, that seems like potentially a good property of it, that it is easier to understand because it _doesn't_ do those things.

**Comment by mbudiu-vmw** [comment]
@jafingerhut : should we promote this into a discussion item for the LDWG?

**Comment by jafingerhut** [comment]
We can discuss it in the LDWG if people want to.  It looks like the history of this idea is explained pretty well, and since @konne-google has an interest in using `type` in P4_16 for some of his work, perhaps he may have an opinion about this issue, too.

I mainly created the issue because it came up in a discussion when coming up with the original proposals for `type` and P4Runtime translation, and I didn't want to forget it.  It isn't personally high priority for me to push it through, or I would have brought it up before now. :-)

**Comment by jnfoster** [comment]
In the interest of tidying up our list of issues, I'm going to mark this as "stalled." Please fell free to speak up if it should be resurrected.
