### ISSUE TITLE
select vs. switch: ordering of cases

### ISSUE THREAD

**Issue by liujed** [p4lang/p4-spec#692]
This is perhaps related to #58, but I am opening a new issue for a more focused discussion.

In `select` expressions, the order of the cases matters: any cases that appear after a `default` case are [considered unreachable](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L4751). One might expect the analogous to be true for `switch` statements, but this is [not specified](https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L4468). In fact, the spec doesn't explicitly specify the semantics of `default` in `switch`.

The spec should clarify the semantics of `default` with regards to `switch`, and be explicit about whether the order of cases in `switch` matters.

**Comment by mbudiu-vmw** [comment]
In a switch statement the labels are always exclusive, so the semantics is less ambiguous: i.e., the order should not matter. We should say that default is always executed last; we may in fact enforce the fact that default has to be written last.

**Comment by liujed** [comment]
In most languages, `default` can be thought of as a case that matches everything. If we adopt this same thinking (as we do for `select`), then order in `switch` matters exactly when `default` is used.

My personal preference would be to bring `switch` closer to `select` by specifying that it is a compile-time error (or at least a compile-time warning) when `default` does not appear last.

**Comment by jafingerhut** [comment]
It does sound like a nice idea to require the 'default' case to be last, if it is present, mostly for the sake of the human reader understanding the code.

**Comment by jafingerhut** [comment]
Closing this issue as changes have been committed to both p4c and the P4_16 language spec addressing this, making it a warning in p4c, and saying that the 'default' label, if present, should be last.
