### ISSUE TITLE
save state between packets

### ISSUE THREAD

**Issue by cbolson1** [p4lang/p4-spec#694]
I believe I have a model where the processing of packet 0 may change some state, which in turn should affect the processing of packet N (assume N >> 0).  Does P4 have a notion of remembering this state between packets?  Or are all packets treated as independent?

**Comment by mbudiu-vmw** [comment]
The core P4-16 language does not have such a construct. 
P4-14 had a notion of a "register" that does that.
This has now been moved into a target-specific library. If the target you are compiling for has registers, then you can use them. For example, if you compile for the v1model target, when you 
`#include <v1model.p4>` you will get a declaration for `extern register`.

**Comment by cbolson1** [comment]
I am using the v1model target.  Can you point me to an example that does this?

**Comment by mbudiu-vmw** [comment]
https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/flowlet_switching-bmv2.p4

**Comment by cbolson1** [comment]
Looks like that example uses it in a control block.  Can you also use that in a parser block?

**Comment by mbudiu-vmw** [comment]
v1model is a model of the P4-14 switch architecture, which seems to imply that registers can only be accessed from actions. BMv2, being a software switch, may not have this restriction, but I don't know. 
If you compile for a real hardware device it may have different constraints than BMv2.
So it depends on your target. The language itself does not put any restrictions.

**Comment by jafingerhut** [comment]
Just a suggestive question: Is there a way you can think of to move the use of registers from the parser code into the ingress control block instead?

For example, if your goal is to check a sequence number in a packet header to see if it is one more than the previous sequence number, or simply "greater than", that can be done after parsing is complete in the ingress code.

I can't off hand think of a reason why you would _need_ a register in the parser code, but I could be lacking imagination of possibilities here.

**Comment by jnfoster** [comment]
Aha. This is a cool intellectual problem I'd never thought of before.

One possible workaround: if you have point-to-point traffic flows, could
you serialize the state that determines how the next packet will be parsed
and then copy it over to the next packet at the end host?

-N

**Comment by cbolson1** [comment]
I'm actually working off some existing code (and porting to P4), so I don't think I'm at liberty to make such an architectural change.

**Comment by jafingerhut** [comment]
Here is a thought for what I would consider a workaround for devices that don't let you update registers during parsing, not necessarily the ideal solution you would wish for:

When the packet first arrives, parse it as well as you can without access to register state.  During ingress, identify whether it is one of the kinds of packets that needs state to parse it correctly, using the parsing results you have (perhaps only partial compared to what you want in the end), and accesses to registers.

Then recirculate or resubmit the packet, with saved metadata that can be used by the parser on its second time parsing the packet, to cause it to parse in the way that you want, using both the packet contents _and_ the preserved metadata.

**Comment by jnfoster** [comment]
👍

**Comment by jnfoster** [comment]
One follow-on thought: it's useful to have keep parsers stateless. If one allowed register read/writes from within the parsers, then things could get really complicated in the presence of concurrency. I'm not a hardware expert, but I understand it's fairly common to replicate the circuits that implement parsers at the hardware level to be able to maintain line rate.... Alternatively, you could change the concurrency model to something weak or perhaps sequential but only per-flow (which might be feasible to implement) but that also gets complicated fast. 

In contrast, @jafingerhut seems pretty easy to implement and practical on today's P4 targets.

**Comment by mbudiu-vmw** [comment]
I think we can close this issue, since it's not really about the spec.
