### ISSUE TITLE
Is error allowed in header field?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#726]
P4-16 v1.1.0 spec has a sentence in section 8.14.

>For a field with a type of enum or error, the unspecified value that is read might not be equal to any of the values defined for that type. 

Is error allowed in a header?

The following code currently has a type error
```
#include <core.p4>
#include <v1model.p4>

enum bit<8> e_t {
  e0 = 8w0
};

header h {
    e_t algo;
    error err;
}
```
```
../testdata/p4_16_samples/enum_field.p4(10): [--Werror=type-error] error: Field err of header h cannot have type error
    error err;
          ^^^
```

We should probably change the sentence to 
> For a field with a type of serializable enum, ...

or fix the compiler.

**Comment by jafingerhut** [comment]
I agree that sentence is confusing, given that values of those types are not allowed inside of headers.

I think those sentences are intended to be true for uninitialized variables of those types, wherever they appear, e.g. inside a struct or as the out parameter of a control or function that was not initialized inside of that control/function, so those sentences seem like they ought to be kept somewhere in the spec, even if not in the section on headers.

**Comment by hesingh** [comment]
The compiler is correct to not allow an error inside a header.  One does not know yet how to serialize an error.

**Comment by jafingerhut** [comment]
Another data point: section 7.2.7 "Type nesting rules" says that `error` and non-serializable `enum` types are not allowed in a header.

**Comment by jafingerhut** [comment]
The change moving that text into its own section has been merged into the spec now, so closing this issue.  Hopefully with these changes, with no mention of fields of type `error` or `enum` (serializable or otherwise) inside of the section on headers, it is clearer.
