### ISSUE TITLE
Clarify whether emit is supported on varbit values

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#733]
Section 8.8 "Operations on variable-size bit types" of P4_16 language spec v1.1 says:

"Variable-length bit-strings support a limited set of operations:"

followed by a bullet item:

"The emit method of a packet_out extern object, which inserts a variable-sized bit-string with a
known dynamic width into the packet being constructed"

There seem to be at least two ways this could be interpreted (or misinterpreted):

(a) If `v1` is a variable of type `varbit<W>`, it is legal to do the operation `packet.emit(v1);`
(b) The previous scenario is _not_ supported.  It is supported to have a `varbit` type field inside of a header, and call `packet.emit(h1);` on a header, header stack, or header_union that contains a `varbit` field.

I think (b) is what is intended, but if so, it seems easy to misinterpret it as (a), given that this section is for operations _on the `varbit` type_, and all other operations in the other bullets can be performed directly on values of type `varbit`.

If (b) is the intended meaning, I am happy to suggest some changes that make this clearer, e.g. taking the extract and emit bullet items in Section 8.8 and discussing them separately than the operations that can be done directly on a value of type `varbit`.

**Comment by jafingerhut** [comment]
Note: the latest version of p4c as of 2019-Feb-17 gives the following error if you attempt to make a call like `packet.emit(v1);` where `v1` is of type `varbit<W>`.  This error message is from `p4test`, so not specific to any architecture, I would think:
```
$ p4test checksum-ipv4-with-options.p4
checksum-ipv4-with-options.p4(215): [--Werror=type-error] error: packet.emit: argument must be a header, stack or union, or a struct or tuple of such types
        packet.emit(hdr.ipv4.options);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ChrisDodd** [comment]
As you might guess from the error message, you'll get the same error if `v1` is a `bit<N>` -- its not just varbits that are disallowed.

**Comment by hanw** [comment]
Yes. emit should not be allowed on bit<N>, int<N> or varbit<N> directly. Spec is clear in section 8.5 and 8.6 that 'emit' is not a the supported operation. What is confusing is 8.8, where spec mentions 'emit' is a supported operation on varbit. @jafingerhut has pushed a PR to fix the confusion in spec.

**Comment by jafingerhut** [comment]
Spec clarification has been merged in, so closing this issue.

**Comment by jafingerhut** [comment]
Spec clarification has been merged in, so closing this issue.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Sorry for the bother.  I tried closing this issue, but on Github it still shows up on the open issues list right now.  What do you see for its status?  Hopefully this is a short-term delay in Github updating things, but notifying you in case it isn't.

**Comment by mbudiu-vmw** [comment]
It says here that the issue has been closed 1 hour ago.
