### ISSUE TITLE
changing hdr.setValid() to hdr.setValid(bool).

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#742]
Currently, p4c does not support changing the validity bit of a header through action parameter. The following code is not possible without multiple actions.

```
action act(bool valid) {
    hdr.setValid(valid);
}
```

```
action act() {
    hdr.setValid(hdr2.isValid());
}
```

**Comment by hanw** [comment]
The proposal is to change the setValid() method on header to setValid(bool).

**Comment by hanw** [comment]
and possibly remove setInvalid().

**Comment by mbudiu-vmw** [comment]
The current design is made on purpose. In p4-14 these are different operations: add_header, remove_header. We assumed these match the hardware capabilities. To support dynamic values for setValid we would have to insert lots of if statements everywhere in the program.

**Comment by hanw** [comment]
Just to confirm, the dynamic value for setValid is not supported because we would have to translate
the following code in P4-14. 
```
action a() {
  add_header(hdr);
}
```
 
into the following code in P4-16.
```
action a() {
  if (!hdr.isValid())
      hdr = 0;
  hdr.setValid(true);
}
```

AND, because we disallow if condition in an action, therefore we cannot support setting valid bit directly?

**Comment by mbudiu-vmw** [comment]
These are target-specific limitations really. But in P4-14 you could not do this, so we assumed it reflects limitations of many important classes of targets, such as Tofino. We didn't want to assume more about targets in P4-16.

**Comment by zma-barefoot** [comment]
```
  if (!hdr.isValid())
      hdr = 0;
```

This can be simply implemented as a conditional move instruction in HW. x86 has `cmov`, so does Tofino in its ISA. So I don't agree it "reflects limitations of many important classes of targets".

**Comment by hanw** [comment]
let's start a thread offline to talk about this limitation.

**Comment by jafingerhut** [comment]
If this does go forward, I would ask you to consider that perhaps there are already existing programs with setValid() and setInvalid() calls, so leaving them in with the existing behavior seems like a good move for backwards compatibility

If overloading is possible between the existing setValid() and a new setValid(bool x), then great.  If not, then introducing a new name, e.g. assignValid(bool x) would be better than breaking backwards compatibility, it would seem to me.

**Comment by mbudiu-vmw** [comment]
Perhaps the addition of the invalid literal will make this less useful.
