### ISSUE TITLE
externs as a constructor parameter to other externs

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4-spec#744]
Per the LDWG discussion on 3/4, here is the full example of the code for passing externs as constructor parameters to other externs. Details of the proposal are https://github.com/p4lang/p4-spec/wiki/Externs-as-constructor-parameters and included below for your reference.

# Problem
We encountered several instances in which the state of an extern needs to be manipulated from the control plane. For example hash functions that compute the hash on a field list specified by the control plane.

# Current state
The current language specification requires that all the constructor parameters are compile time constants. While we can ask the user to enumerate all the possible field lists that are available as candidates for computing the hash, because lists and tuples are internal compiler data structures, we have no means of identifying the selected list from the control plane. Moreover, the elements should not capture the values at construction time, but rather use the values that are in the fields when the `get` method is invoked.

# Proposed solution
## Pass an extern as a constructor parameter to another extern
By passing an extern as a constructor parameter to another extern we can:
  - use the name of the extern instance or constructor parameter in the control plane to identify a particular encapsulate state, in our case a field list
  - since the semantics of the extern is entirely decided by the compiler, we decide what should happen to the state of the argument passed as a constructor parameter. In our example, the extern instance is passed as a reference and values are captured only when we invoke the method that needs them. Think of the same semantics as a match key for a table.

### Issues
What happens if the same instance is passed to multiple externs? We can let the programmers to express what should be the semantics using parameter labels. `in` will continue to act as a read-only, copy-in parameter. No direction or `ref` can specify a parameter that is acted upon by the control plane and is called by reference.
### Code changes
Trivial -- require removing 4 lines of code that check parameters

# Example

```
#include <core.p4>

header hdr1 {
    bit<8> f1;
    bit<8> f2;
    bit<16> res;
}

header hdr2 {
    bit<8> f3;
    bit<8> f4;
    bit<8> f5;
    bit<8> f6;
}

@metadata @name("standard_metadata")
struct standard_metadata_t {
    bit<9>  ingress_port;
    bit<9>  egress_spec;
    bit<9>  egress_port;
    bit<1>  drop;
}

struct hdrs {
    hdr1 h1;
    hdr2 h2;
}

/// Field list extern -- identifies a set of fields
extern FieldList<W> {
   FieldList(W field_list);
};

extern FieldLists<T> {
   FieldLists(T fls);
};

enum HashAlgorithm_t {
  IDENTITY,
  CRC32,
  CRC32_CUSTOM,
  CRC16,
  CRC16_CUSTOM,
  ONES_COMPLEMENT16,  /// One's complement 16-bit sum used for IPv4 headers,
                      /// TCP, and UDP.
  TARGET_DEFAULT      /// target implementation defined
}

/// An extern that requires the control plane to choose which field list is
/// participating in the hash computation
extern DynamicHash<W> {
    DynamicHash(HashAlgorithm_t algo, FieldLists<_> fls);
    /// the control plane needs to select the FieldList.
    W get();
    W get(in W base, in W max);

    /// LDWG discussion proposed to pass the field list to the get method
    /// However, again, the goal here is for the control plane to set
    /// which one of the lists is desired, so it is not clear to me
    /// why get with the whole set is more intuitive.
    /// W get(FieldLists<_> fls);

    /// the data plane may want to set a default
    void setDefault(FieldList<_> fl);
}

control c(inout hdrs h, inout standard_metadata_t std_meta) {
    /// Declare several filed lists
    FieldList<tuple<bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h1.f2, h.h2.f3 }) fl0;
    FieldList<tuple<bit<8>, bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h2.f4, h.h2.f5, h.h2.f6 }) fl1;

    /// construct a dynamic hash extern
    DynamicHash<bit<16>>(HashAlgorithm_t.CRC16, FieldLists<_>({fl0, fl1})) hash0;
    action a () {
        h.h1.res = hash0.get();  // correct.
    }
    action dropIt() {
        std_meta.drop = 1;
    }

    table t {
        key = {
            h.h1.f1: exact;
            h.h2.f3: exact;
        }
        actions = {
            a;
            dropIt;
        }
        default_action = dropIt;
    }

    apply {
        t.apply();
    }
}

control proto(inout hdrs h, inout standard_metadata_t s);
package top(proto p);

top(c()) main;
```

### Compiler output
```
/p4test ~/dyn_hash.p4
/Users/cascaval/dyn_hash.p4(62): [--Werror=type-error] error: ListExpression: cannot evaluate to a compile-time constant
    FieldList<tuple<bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h1.f2, h.h2.f3 }) fl0;
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/cascaval/dyn_hash.p4(63): [--Werror=type-error] error: ListExpression: cannot evaluate to a compile-time constant
    FieldList<tuple<bit<8>, bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h2.f4, h.h2.f5, h.h2.f6 }) fl1;
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jafingerhut** [comment]
So one way to change the language spec is to just bite the bullet and add a field_list construct to the language, and define reference semantics.  A field list name could become a 'compile time constant' that could be passed to an extern constructor (the reference is compile-time constant, even if the values of the header fields are not).  Then change Section 6.7.1 to explicitly allow passing of field_list names to externs, and let extern method calls read the values of all referenced fields whenever they are called, even if they are not part of the parameter list.

I am sure there are other ways, but it takes more than merely allowing externs to be passed as constructor parameters to other externs to make this proposal behave as you want at run time.

**Comment by mbudiu-vmw** [comment]
This kind of change has a huge impact on the language design and implementation. It may require us to rewrite significant parts of the compiler. Why not adopt a solution that is not more expensive in terms of p4 lines of code and could be done today with no changes to the language and compiler?

**Comment by jafingerhut** [comment]
So I think there is a big disconnect on thinking here.  Mihai thinks this is a large change to the compiler (and for reasons I have tried to describe in comments above on the changes required to the spec, which seem fairly deeply rooted in p4c as assumptions, I have a small idea why it might be a big change), and you believe it is removing one check.

Do any of my comments on assumptions made by p4c from the spec make it seem reasonable that perhaps eliding one check in the compiler will not necessarily give a correct compiler for your proposed language changes?

**Comment by jnfoster** [comment]
Are we talking about Calin's constructor change or adding field lists with
call-by-reference semantics?

I'm pretty sure Mihai is referring to the latter.

**Comment by jafingerhut** [comment]
Calin's constructor change is what I was referring to.

If Calin's proposed change is: allow lists of fields as constructor parameters, even though they are not compile-time constants...

then it seems to me he wants later calls to _other_ extern object methods (`hash0.get()` in his code example) to get run-time access to that list of fields, the current value of them at the time of that extern method call.

Section 6.7.1 of the spec explicitly disallows that, and I think for fairly deep assumption reasons in the compiler, not just because someone felt like writing more words in the spec.

**Comment by mbudiu-vmw** [comment]
@jafingerhut is right: if you pass these expressions to the constructor it cannot do anything with them unless it can save references for later. So references are needed in the language.

**Comment by cc10512** [comment]
I will type a summary of my understanding of the discussion later today.

**Comment by jafingerhut** [comment]
As I have mentioned before in a similar discussion, the kinds of references you would need to do this, are _not_ nearly as general as references in Java or other languages, for example.  You only need a "constant reference", i.e. one like a P4_14 field list, where the name given to the field list always and forever refers to a particular list of fields, never any others (unless you change the code and recompile).  Such a "const reference" is much easier to reason about than a run-time variable reference.

Mihai and Chris have had discussions on having some kinds of annotations that limit the "power" of "virtual functions" that could be similarly used to limit the power of extern methods, to make it possible for the compiler to reason about them.

For example, while the P4_16 language spec says that externs have arbitrary power of starting up threads, colluding with each other, sharing data between them, etc., you do not need all of that power here.  If there were a way to inform the compiler "No, no, this isn't one of those powerful beasts of an extern, this one can only do some calculations after I call one of its methods, and completes all of its activities when it returns back to the P4 program." then again, it becomes much easier to reason about such a call than the generality of a full extern.

**Comment by cc10512** [comment]
Sorry for the long message and the long time it took to put this together. I have collected more feedback (thanks everyone for your input!) and in retrospect, none of the proposed solutions work. So, let me first restate the problem, then point out the shortcomings of the proposals that were circulated, and finally put out a new proposal that we believe does address the problem and solves it in an elegant fashion.

We are looking to:
1. Gather a collection of field references into a single, named, P4 object. At least the name of the P4 object should be available to the control plane through auto-generated APIs. Ideally the names of the fields in the object are available in the generated APIs.
2. Bind that object to a P4 extern

Our proposed solution expanded on the P4 language notion that externs are **the mechanism** of extending the language. The particular extension that we were asking for is to allow externs to be passed as constructor parameters to other externs. Externs are already passed by reference in the language, and the semantics of externs is already known to the (backend) compiler. In our particular case, we proposed that the DynamicHash extern captures the FieldList externs as references, the control plane selects one at runtime, which is dereferenced at the get call site. The behavior of the extern is similar to tables defining a set of match keys and dereferencing them at runtime -- table.apply() has no parameters, and the key accessed is defined at table construction time. Note that we did not propose that these references be allowed anywhere else but in externs, where the backend compiler understands the semantics and the user has no additional control. It turns out that this proposal is not sufficient: in particular, the following statements break requirement #1:
```p4
/// Declare several filed lists
FieldList<tuple<bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h1.f2, h.h2.f3 }) fl0;
FieldList<tuple<bit<8>, bit<8>, bit<8>, bit<8>>>({ h.h1.f1, h.h2.f4, h.h2.f5, h.h2.f6 }) fl1;
```
The tuples provided as constructor parameters follow copy-in semantics rather than field reference semantics, so the FieldList ends up containing a set of values rather than references to fields. While the object can be named, it does not contain a collection of field references.


The objections raised are related to the fact that the get call site does not fully specify what is being accessed in a runtime packet. The alternative proposal is to define multiple get methods for each type of list, and call the appropriate get method with the desired field list. This proposal has the following shortcomings:
- the field list is not selectable by the control plane, as there are no names, and no field references.
- there is no finite set of field lists that the user can chose from. In particular, there can be multiple calls to get with different field lists of the same type. For example:
```p4
extern MuxHash<T> {
    MuxHash();
    extern T get<T1, T2>(in T1 list1, in T2 list2);
    extern T get<T1, T2, T3>(in T1 list1, in T2 list2, in T3 list3);
}

MuxHash<bit<16>> mh();
mh.get( { f1, f2 }, { f3, f4 } );
```
one can call 
`mh.get ( {f1, f2}, {f3, f4} );`
or
`mh.get ( {fa, fb}, {fc, fd} );`
with lists that have the same type and contradict what the control plane may have set. Similarly for Andy's example where the hash.get is buried into actions. It is also not clear how do we solve the problem when the architecture defines the extern with a fixed number of get signatures, rather then letting the user define how many choices should be provided.

Note that we had explored before the use of tables, overlays, and annotations to solve this problem and each one has one or more of the following shortcomings:
- Can not associate the control-plane name with the data-plane name, e.g., when lists are passed directly on the get call.
- No support for multiple lists, unless they are all merged into a gigantic list and down-select from it, that is a significant waste of resources.
- Not possible to guarantee the proper ordering of elements in the list, e.g., when using annotations to collect fields from different structs.

After a bit more thought, there are two options that we think can solve the problem:
### 1. FieldLists as references
Introduce FieldList as a first-class object in P4 to represent a list of field references. In its favor is the fact that this is a concept familiar to P4-14 programmers. However, it introduces references in the language without much control over how are they used. It is fair to assume that this will require significant discussion and argumentation in the LDWG -- likely beyond each of us are comfortable with.
### 2. Overlays
Introduce a solution based on @mbudiu-vmw's overlay proposal (thanks @antoninbas for working out the kinks!)  as follows:

```p4
struct Hdr { } // my program headers
struct Meta { } // my program user-defined metadata

struct FieldList1_t {
  bit<8> a;
  bit<16> b;
}

struct FieldList2_t {
  bit<16> a;
  bit<16> b;
  bit<32> c;
}

struct FieldLists_t {
  FieldList1_t fl1;
  FieldList2_t fl2;
}

// extension to Mihai's proposal (the overlay can be built from multiple sources)
overlay FieldList1_t Overlay1 (Hdr hdrs, Meta meta) { 
  a = hdrs.ipv4.dstAddr[32:24];
  b = meta.f1;
}

overlay FieldList2_t Overlay2 (Meta meta) {
  a = meta.f1;
  b = meta.f5;
  c = meta.fb;
}

Hash<bit<16> /* output */> hash1;
hash1.get<FieldLists_t<_>>(Overlay1(hdrs, meta), Overlay2(meta));
```

What are the advantages of this proposal:
- builds upon a desirable feature (overlays) that we already discussed and has been on our backlog for implementation for some time
- takes care of naming: fl1 and fl2 are field list names that uniquely identify the lists and can be generated for the control plane. Also, the overlay field names (a, b, c) are available.
- the overlays are defined as left-values, so the fields assigned to overlays provide the reference semantics
- it is clear what is accessed in the get method so the compiler can fully analyze the behavior. In addition, we can use the current directional 'in' parameter to further specify that the field list is read only
- it can be directly bolted to an extern without any additional language changes.

**Comment by jafingerhut** [comment]
On your last proposal using overlays for this, it seems to slightly generalize the current overlay proposal, in that you propose that an overlay 'function' can take multiple struct/header parameters, rather than only one, but that does not seem like a problem, that I can think of.

The names fl1, fl2 in your code example definitely appear, and it will likely require a tiny bit of care in p4c getting those names into the P4Runtime P4Info file, and/or other auto-generated control plane API description formats, but it definitely looks doable.

Overlays do seem in effect to be a kind of named reference with heavy restrictions on its use, so it makes sense that they would help achieve the goals you have set out here.

**Comment by mbudiu-vmw** [comment]
We could say that `f(overlay(x))` is the same as
```
tmp y = overlay(x);
f(y);
```

**Comment by mbudiu-vmw** [comment]
There are some restrictions for an overlay to be a left-value. But in your example get seems to require only a value, not a left-value.

**Comment by cc10512** [comment]
In this example, yes. However, if you want to consider using the same approach for recirculation, you may pass an `out` field list to the `recirculate_receive()` method, then it will need to be an l-value.

**Comment by jnfoster** [comment]
Chiming in late, provided we work out these details, the Bas/Cascaval
overlay solution looks super elegant to me.

**Comment by antoninbas** [comment]
I just want to confirm that the following is true:
```
overlay S MyOverlay(X x) { 
  a = x.f;
}
X x;
x.f = 1;
S o1 = MyOverlay(x);
S o2 = o1;
o2.a = 2;
assert(o1.a == 2);
assert(x.f == 2);
externCall(o2.a);
```

I'm curious about how hard overlays will be to implement in the compiler. It seems that very few changes would need to happen in the frontend. The type checker would just treat the overlay object has a regular struct, and the frontend would just need to validate uses of the overlay as an l-value.

What I'm confused about is how the compiler would eventually "eliminate" overlays.
If I have the following code:
```
S o1 = MyOverlay(x);
S o2 = o1;
o2.a = 2;
externCall(o2.a);
if (<some non compile-time condition>)
  o2.a = 3;
else
  o2.a = 4;
externCall2(o2.a);
```
What do you think this code would look like after the frontend and after the midend (let's say the bmv2 midend)?
Ideally, by the end of the midend (at least for bmv2), the code above was transformed into:
```
externCall(2);
if (<some non compile-time condition>)
  x.f = 3;
else
  x.f = 4;
externCall2(x.f);
```
Is my understanding correct? How does the compiler get to that result?

**Comment by mbudiu-vmw** [comment]
The overlays would be eliminated in the front-end.
For assignments to an overlay you need to revert the operation and generate assignments to the original fields. You would use slicing and concatenation for that purpose.

Overlay fields are always bitstrings. The compiler builds a bidirectional map at the bit level, mapping source-bit <=> destination-bit (the map must be onto: each destination bit must have a unique definition). Then is uses this map to convert operations on overlay fields to operations on source fields. Reads on overlays become reads of slices of the sources; writes to overlays become assignments to slices of sources.

In your example, if the f field of the overlay maps exactly to the a field of o2 then the compiler should generate similar code (probably with widths for the constants). We assume that the externCall has an in parameter. The copy propagation pass would be responsible for propagating the constants into the calls.

**Comment by jafingerhut** [comment]
In Antonin's example that I am copying here to make it clear which one I am talking about:
```
overlay S MyOverlay(X x) { 
  a = x.f;
}
X x;
x.f = 1;
S o1 = MyOverlay(x);
S o2 = o1;
o2.a = 2;
assert(o1.a == 2);
assert(x.f == 2);
externCall(o2.a);
```

I do not see why modifying `o2` would change `o1` or `x`.  I would have thought that `o1` and `x` are aliased, but `o2` is a separate variable from either of those, with no overlay or aliasing going on.  Certainly that is the case in any other P4_16 program containing the statement `S o2 = o1;`, but maybe the idea is that somehow in this context `o2` is created as yet another alias?

What if you _didn't_ want another alias?  Could you do it, and if so, with what P4_16 source code?

**Comment by jafingerhut** [comment]
By the way, in case it wasn't clear, the following seems like it should be true to me, i.e. you can make as many overlays of an original value as you want, and they all alias the same original values:
```
overlay S MyOverlay(X x) { 
  a = x.f;
}
X x;
x.f = 1;
S o1 = MyOverlay(x);
S o2 = MyOverlay(x);   // this line is very different than Antonin's example, which has o1 as initial value
o2.a = 2;
assert(o1.a == 2);
assert(x.f == 2);
externCall(o2.a);
```

**Comment by mbudiu-vmw** [comment]
Yes, assigning to o2 just copies the fields of o1.

**Comment by jafingerhut** [comment]
I know adding syntax is bad if it is just for the sake of adding syntax, but it seem that the currently proposed syntax:
```
S o1 = MyOverlay(x);
```
is a potential source of confusion.  That statement is completely different than this one in its proposed effects:
```
S o2;
S o1 = o2;
```
If the first line of code above were instead something like this:
```
S o1 overlays MyOverlay(x);
```
with no `=` sign anywhere, then it doesn't look as much like a normal P4_16 assignment statement any more (which is good if it isn't like a normal P4_16 assignment statement).

**Comment by jafingerhut** [comment]
Antonin, out of curiosity, Calin's original code snippet that used overlays was, copying just the final two lines, this:
```
Hash<bit<16> /* output */> hash1;
hash1.get<FieldLists_t<_>>(Overlay1(hdrs, meta), Overlay2(meta));
```
which I believe the compiler would treat like this:
```
Hash<bit<16> /* output */> hash1;
FieldList1_t compiler_gen_tmp1 overlays Overlay1(hdrs, meta);  // using 'overlays' in place of '=' to emphasize difference in behavior from '=' of this line
FieldList2_t compiler_gen_tmp2 overlays Overlay2(meta);
hash1.get<FieldLists_t<_>>(compiler_gen_tmp1, compiler_gen_tmp2);
```
If for this comment I continue to only use `=` to represent "copying assignment", never "create a new alias", then it seems you are concerned that the compiler might insert additional temporaries like in the following version?
```
Hash<bit<16> /* output */> hash1;
FieldList1_t compiler_gen_tmp1 overlays Overlay1(hdrs, meta);  // using 'overlays' in place of '=' to emphasize difference in behavior from '=' of this line
FieldList2_t compiler_gen_tmp2 overlays Overlay2(meta);
FieldList1_t tmp3;
FieldList2_t tmp4;
tmp3 = compiler_gen_tmp1;  // this copies the values to tmp3, it does _not_ create another overlay
tmp4 = compiler_gen_tmp2;  // same here -- copying
hash1.get<FieldLists_t<_>>(tmp3, tmp4);
```
I do not know of a reason the compiler would introduce tmp3 and tmp4 here, but the _values of the bits_ passed to hash1.get is the same in the previous two code snippets, in all cases.

For the purposes of hash calculation, this should all work correctly, I think?  Do you see a problem?

It seems like it could be a problem for another method call that had 'out' or 'inout' direction parameters, and you expected the extern call to change the values of the original storage through the overlays when the copy-out of the out/inout parameters occurred.  It isn't clear to me in such a case whether the compiler transformation of adding tmp3 and tmp4 is correct, then, unless it also then copied the value of tmp3 back into compiler_gen_tmp1.  That doesn't seem to me to change with the introduction of overlays, though.  The compiler needs to preserve the original data flow.

**Comment by antoninbas** [comment]
Sorry for the delay, I am just catching up on this thread. I really like Andy's idea of not using the assignment operator for creating an overlay, but instead using something more constructor-like. It makes everything easier to understand.

There is one case I am still concerned about. If we set aside the hash use case, and consider a similar extern method, but which takes an `inout` parameter instead of an `in` parameter, what would be the semantics of this:
```
method<FieldLists_t>({Overlay1(hdrs, meta), Overlay2(meta)});
```
Obviously my intention here is that the overlaid fields can be modified by the extern function. In other words, I want my extern implementation to "see" overlays, not struct copies. It seems to me that something like this (overlays as members of a `FieldLists_t` struct) is a strong motivating use case for introducing overlays.

BTW, if one is just looking at the hash use case (with an `in` parameter), and **if the compiler frontend is going to eliminate overlays early**, I may as well use structs myself in my program, it's not more verbose. What would be the advantage of using overlays then? It seems that either way, my compiler backend needs to rely on copy elimination.

**Comment by mbudiu-vmw** [comment]
This does not change the semantics of in/out/inout. It just adds a new mechanism that may be convenient for viewing the same data structures in multiple ways. This is motivated by some use cases suggested by external third-parties. This is also a safe replacement for C-style unions, which we have considered in the past.

**Comment by antoninbas** [comment]
I'm not sure where in my previous comment I suggested changing the semantics of in/out/inout. The fact that an overlay and a struct have the same type is very confusing to me, which is why I ask a lot of questions. I'm essentially trying to figure out compelling use cases for overlays, and failing. In the hash use case presented above, my assumption (apparently incorrect) was that overlays would not be eliminated by the frontend, which would have possibly made the job of the backend easier. If overlays are eliminated early, I can just use structs directly in my P4 program to encapsulate fields. It doesn't make the P4 program more verbose or more complicated.

Considering the following code:
```
extern void func<T>(in T t);

overlay S MyOverlay(X x) { 
  a = x.f1;
  b = x.f2;
}

X x;
...
func(MyOverlay(x));
```
If the compiler frontend freely re-writes the `func` call as this:
```
func<S>({x.f1, x.f2});
```
or this:
```
S tmp = {x.f1, x.f2};
func<S>(tmp);
```
and I lose the overlay "information", there is no value in me using an overlay in the first place.

**Comment by jnfoster** [comment]
This seems interesting, but in the interest of tidying up our list of active issues, I'm going to mark this as "stalled."
