### ISSUE TITLE
Add access to table keys

### ISSUE THREAD

**Issue by telmich** [p4lang/p4-spec#745]
Whening defining a table like the following

```
    table v6_networks {
        key = {
            hdr.ipv6.dst_addr: lpm;
        }
        actions = {
            nat64_static;
            NoAction;
        }
        size = ROUTING_TABLE_SIZE;
        default_action = NoAction;
    }
```
And the sample action nat64_static:
```
    /* nat64_prefix is the same as the matching key, but without the mask */
    action nat64_static(ipv6_addr_t v6_network, ipv4_addr_t v4_network, ipv6_addr_t nat64_prefix) {
        ipv6_addr_t src_offset = hdr.ipv6.src_addr - v6_network;
        ipv4_addr_t src        = v4_network + (ipv4_addr_t) src_offset;

        ipv4_addr_t dst        = (ipv4_addr_t) hdr.ipv6.dst_addr - nat64_prefix;

        nat64_generic(src, dst);
    }

```

The controller configures the table as follows:

```
        self.controller.table_add("v6_networks", "nat64_static", [nat64_prefix], [net_ipv6, net_ipv4], nat64_prefix])

```
As can be seen the argument nat64_prefix is redundant, but necessary to be redundant.
It is necessary to be redundant, because the action nat64_static cannot retrieve the original key nat64_prefix from the table. Neither is it possible to retrieve the mask of the LPM match.

I suggest to add support for retrieving all configured keys of a table in the actions.

**Comment by jnfoster** [comment]
Just a clarification, do you want to retrieve *all* keys? Or just the one that matched (if it exists)?

**Comment by telmich** [comment]
@jnfoster For my application the matched key would be enough. The reason why I wrote all keys is that I do see other actions that might need access to all keys. 

I shortly discussed with @cedgar (in slack) that something on the line of tablex.key[0], tablex.key[1], ... would be very intuitive, as the keys are possibly a list.

It is also important to note that what I am looking for is not the actual matched value, but the original key, for instance:

- table key = 2001:db8::/32
- actual match = 2001:db8::f00

So in the action it would be good to retrieve 2001:db8::/32, as the exact match will be found in the header anyway (in my case in hdr.ipv6.dst_addr).

**Comment by jnfoster** [comment]
Returning a large collection (e.g., [tens of] thousands of keys) is unlikely to be practical on many hardware targets.

**Comment by mbudiu-vmw** [comment]
There are no lists or vectors in P4, and there are no loops to iterate over these anyway.
There are also no runtime values whose type is match_type, so one cannot represent a key value in P4.
Also, as @jnfoster points out, many architectures may be unable to provide access to the key that has been matched.
In general, it looks like quite expensive to provide in full generality. Specific architectures may be able to perhaps provide an extern that can be invoked in an action to retrieve (parts) of the matched keys.

**Comment by mbudiu-vmw** [comment]
I will close this issue, since I don't see what we can currently do about it. Feel free to reopen if you think I am wrong.
