### ISSUE TITLE
P4_16 spec - Madoko cross-ref label bug

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#749]
There are two sections with the Madoko label/tag `{ #sec-optional-parameters }`.  This causes page number in table of contents of one of these sections to be quite far wrong in the generated PDF file.  There is one cross reference to this thing, and I am not sure yet which is the correct one it should refer to.

**Comment by mbudiu-vmw** [comment]
I have committed a fix directly to master.
