### ISSUE TITLE
Tuple expressions cannot be left values.

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#752]

**Comment by jnfoster** [comment]
@mihaibudiu can you provide a bit more detail here? Otherwise, let's close it...

**Comment by mihaibudiu** [comment]
You cannot do `{a,b} = {2,3};`

**Comment by jnfoster** [comment]
Ok. In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
