### ISSUE TITLE
Documenting v1model more fully

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#756]
Nate Foster asked a question at a recent LDWG meeting about whether the P4_16 v1model architecture should be documented more fully, perhaps at a similar level of detail as the PSA specification has been.

I have been documenting some things about v1model over time.  The results so far are in the p4c v1model.p4 include file [1] and the BMv2 simple_switch documentation [2], and I would encourage people to read those and suggest additions or ask questions about gaps that exist there (there are some big ones, I know, some mentioned below).

[1] https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4
[2] https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

Some high level questions I have:

+ Is v1model defined primarily by the p4c and BMv2 simple_switch implementations of it?
+ Are there any other implementations of v1model that should be considered, and their developers consulted, when making changes to the v1model definition?  Are all of the interested parties already attending P4.org working group meetings?

All of the rest of this comment are a bit more nitty-gritty details on more things that could be documented more fully.

One issue that is being actively discussed in the LDWG is how the definition of resubmit, recirculate, and clone operations, and their preservation of metadata, should be changed so that they fit within the P4_16 language specification rules (or whether the language spec should be changed).  There are other Github issues recording some of that.

Another is a more precise definition of which standard metadata fields are allowed to be read and/or written in each of the 6 "blocks" (parser, verifyCheckum, ingress, egress, updateChecksum, deparser), and which are allowed to be written, and whether the compiler should be giving warnings or errors about violations of such restrictions.  Right now the open source tools allow you to read egress_port in ingress, and write it in egress, even though those things are documented as "you should not do that".  I am pretty sure they let you modify egress_port in egress, and it actually will send the packet out of the modified port, which is definitely not allowed in some high speed ASIC implementations, for reasons described in a PSA spec appendix.

Also, exactly how are all standard metadata fields defined to be filled in, not only for new packets, but also for recirculated, resubmitted, and the 2 kinds of clone packets?  Something as precise as the PSA in this regard could be useful for developers.

I think it would be good to say explicitly, if it isn't already somewhere, that when egress processing begins, _everything_ except a few standard metadata fields is in exactly the state it was when the packet last ended egress processing (if it is a normal ingress-to-egress unicast or multicast packet), including the validity of all headers, and the values of all user-defined metadata fields.  Is that also true for ingress-to-egress cloned packets?

There is no egress parser in v1model.  What is the state of headers and user-defined metadata when egress processing begins for egress-to-egress cloned packets?  Is it whatever BMv2 simple_switch happens to do right now?

**Comment by jafingerhut** [comment]
Expanding on one of the topics I mentioned in the original issue, regarding what the state of the headers and user-defined metadata is when egress processing begins.

I will call today's open source p4c plus behavioral-model simple_switch the "BMv2 v1model" implementation.

Consider a different implementation, which I will call "v1model+ID+EP".  (ID=ingress deparser, EP=egress parser).  It handles the exact same source programs that BMv2 v1model does, but under the hood it actually has an ingress deparser, which operates by the same code as the (egress) deparser in the user's program.  It also has an egress parser that operates by the same code as the (ingress) parser in the user's program.

Suppose I write a v1model program that calls `hdr.funky.setValid();` in ingress code, where `hdr.funky` is not mentioned anywhere in the parser or deparser code.  When I send packets via normal unicast forwarding from ingress to egress processing in the BMv2 v1model implementation, `hdr.funky` will be valid at the beginning of egress processing.  Why?  Because the BMv2 v1model implementation preserves the state of all header variables from the end of ingress to the beginning of egress for unicast packets (also for multicast, and I believe also for ingress-to-egress cloned packets).

That same source code, when compiled for the v1model+ID+EP implementation, will behave differently.  When the egress parser begins, all headers will be invalid, and the only ones that become valid will be ones that the parser code successfully extracts, and it never does this for `hdr.funky`.  Thus when egress processing begins, `hdr.funky` will be invalid.

This raises some questions about what it means to be an implementation of the v1model architecture.

(a) Should both of the implementations described here be considered implementations of the same v1model architecture?

(b) If the answer to (a) is "yes", are there any other significantly different implementations than these two that should also be considered implementations of the v1model architecture?

(c) Should BMv2 v1model be considered a correct implementation of the v1model architecture, but v1model+ID+EP is not, because of the data plane behavior differences?

**Comment by ChrisDodd** [comment]
The original purpose of v1model was to provide an interim architecture for translated P4_14 programs, until we could define a 'proper' standard P4_16 architecture (PSA).  As such its not clear if we need to define the semantics of things that can't be expressed in P4_14 (or are illegal in P4_14) in the v1model architecture, though leaving some things undefined does potentially lead to confusion.

Ideally v1model should eventually go away and we should support P4_14 by translating it to PSA.

**Comment by mbudiu-vmw** [comment]
Let's generalize your question, replacing v1model with any model. The answer then is clear: the P4 model file is not a complete specification of the target architecture; it should always be used in tandem with the architecture specification. Think of the P4 model file as being just a set of interfaces between P4 and the environment in which it runs. Many different environments can implement the same interfaces, but this does not mean that the environment behaves in the same way.

Moreover, consider the XDP model file; it includes the EBPF model file entirely. So that's an architecture which can expose multiple different interfaces to the P4 program, and the user can choose any of them.

**Comment by jafingerhut** [comment]
@ChrisDodd Thanks for the response.  I agree that having auto-translation from P4_14 to P4_16+PSA would go a long way to eliminating some of these kinds of oddities/confusions.

I should really take a big step back and realize all of the things in P4_14 -> P4_16+v1model that _are_ working and precise today.  I can too easily focus on what's missing or weird. :-)

**Comment by jnfoster** [comment]
Haven't we done this now? Should we close this issue?

**Comment by jafingerhut** [comment]
Short answer: I think this issue is as done as it is likely to ever get, and am fine if this issue is closed.

Gory details:

The most complete definitions I know of for v1model are the ones given in the original comment of this issue:

[1] https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4
[2] https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

I have been adding details to those over the years.

I would not call them 100% complete, e.g. I honestly don't even know what happens in various cases such as what happens with user-defined or v1model standard metadata when you do an ingress-to-egress or egress-to-egress clone operation.  As far as I am concerned, I am content if we say "those details are defined by the BMv2 implementation of v1model, which me might change in the future if we think it is really broken somewhere, and someone wants to go to the trouble to change it".  I don't think such details are addressed in the P4_14 specification today, and do not personally care to try to update the P4_14 spec so that it does address them in any more precise way than it does now.

**Comment by jnfoster** [comment]
Ok. Let's close this then...
