### ISSUE TITLE
Type nesting rules

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#759]
[Section 7.2.7](https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-type-nesting) of the spec says that headers cannot be nested inside of other headers, but header unions can be. This seems strange. Is it intentional?

H/T @vgurevich for pointing this out.

**Comment by vgurevich** [comment]
@jnfoster , Actually, after re-reading that section I realized that due to the table layout, I got things transposed in my mind. In reality it says that headers are allowed in header unions, but not otherwise :)

**Comment by jnfoster** [comment]
Whoops!
