### ISSUE TITLE
Add miss to the list of apply() results

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#761]
In the course of P4_16 programming I find that whenever I use `table.apply().hit` I always use it as follows:
```
    if (!ipv4_host.apply().hit) {
        if (!ipv4_route.apply().hit) {
            last_resort.apply();
        }
    }
```

It looks to me that adding an opposite of `hit`, i.e. `miss` will allow the code to be more readable, i.e.:
```
    if (ipv4_host.apply().miss) {
        if (ipv4_route.apply().miss) {
            last_resort.apply();
        }
    }
```

**Comment by vgurevich** [comment]
https://github.com/p4lang/p4-spec/pull/778

**Comment by mbudiu-vmw** [comment]
Can we close this issue?

**Comment by vgurevich** [comment]
Absolutely. I think it is all done.
