### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#762]
I wonder:

- Why isValid() (with parentheses), but hit (without)
- Why isValid(), but action_run (naming and parentheses)?

**Comment by mbudiu-vmw** [comment]
The right question is not "why", but whether there is anything you would like to do to change this state of affairs.

**Comment by vgurevich** [comment]
@mbudiu-vmw 

So, in terms of "case consistency", since the majority of the standard names use camelCase (with the initial lowercase), let's define actionRun and gradually deprecate action_run.

In terms of a "member" vs. "method": if something can be modified (via an assignment or otherwise), then let's use a "member", otherwise let's use a method. In that sense, it should be hit() (plus I'd also want to see a more useful miss()) and actionRun().

**Comment by jnfoster** [comment]
These are good concrete suggestions as well as being good general principles. Let's implement them (and deprecate the old names, as suggested).

**Comment by jnfoster** [comment]
Closing this as it seems to have stalled, and actually is difficult to fix in a backward-compatible way at this point...
