### ISSUE TITLE
Deep packet inspection in P4

### ISSUE THREAD

**Issue by nniranjhana** [p4lang/p4-spec#763]
I understand P4 is unsuitable for deep packet inspection as given in doc

> In general, due to the absence of loops P4 programs cannot do any interesting processing of the packet payload.

But suppose I want to use P4 to detect attacks at the data plane level, how feasible is this and what would be the best way to do so?

Would it be by using `extern` or [pcube](https://www.cse.iitb.ac.in/~mythili/research/papers/2018-pcube.pdf) primitives, or other methods?

**Comment by mbudiu-vmw** [comment]
This is not the best forum for discussion limitations or capabilities of P4; I believe that the p4 mailing lists are a better place: https://p4.org/join/

"externs" are just a language mechanism which allows a specific target (switch, router, NIC) to extend the capabilities of the core language. So if you want to build a device for deep packet inspection and to program that device in P4 the only solution is indeed to use some extern with a suitable API. The same answer is true if you want to write a P4 compiler for a device which is programmable and can do DPI.

**Comment by nniranjhana** [comment]
Ah I see. Thanks for the info!

**Comment by sahilgupta221** [comment]
Nate Foster and his team have written paper in ACM SOSR 2019. Title is "Fast String Searching on PISA". Any thoughts on if after that compiler DPI is possible or in P4? Have a read.

**Comment by jnfoster** [comment]
@theojepsen is the lead on that work. It was a general take on string matching, not specifically what's usually called DPI.
