### ISSUE TITLE
configure a true switch

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/p4-spec#764]
How do I configure a switch to support p4?Are there any requirements for switch hardware?Which switches currently support p4 configuration.I'm just running simulation projects on a virtual machine right now, and I want to experience p4 on an actual switch.

**Comment by mbudiu-vmw** [comment]
This is not the right forum for such a question; this repository is about the language specification.
I think that one of the P4 mailing lists would be the right place to ask such a question.
https://p4.org/join/

**Comment by jafingerhut** [comment]
There was a recent discussion on the p4-dev email list about this.  You can see the beginning of it here:

http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2019-May/003944.html

and more follow-up discussion here:

http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2019-June/003953.html
