### ISSUE TITLE
Write document on P4_16 language issues around externs that seem most naturally written with named field references

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#766]
There may be a better name for this issue, but what I mean here are all of the discussions around defining P4_16 externs that seem more natural to write if one had named field references in the language, similar to how P4_14 has a field_list construct.

Most of the discussion that I know of has involved:

* Can proposed language construct X help solve this problem?  e.g. structure overlays, struct initializers with named fields, abstract/virtual functions, etc.
* Use cases of externs that are not easy to see how to define with the current P4_16 language spec, simultaneously satisfying the goals of:
(a) lives within restrictions of P4_16 language specification, where P4_16 program run-time variables may only be accessed through extern function/method calls as parameters
(b) is reasonably convenient for a user to write and understand
(c) can be used to auto-generate the desired kinds of control plane APIs from the code
(d) doesn't require difficult-to-implement compiler optimizations to generate efficient code for targets of interest.

The hope is that such a document might clarify and collect together most or all of the use cases, example code, and discussions around the topic called "Abstract methods in extern objects" in the LDWG's list of issues here: https://github.com/p4lang/p4-spec/wiki/Language-Design-Working-Group

Right now my hope is simply to collect together relevant links.  Feel free to add more if you want.  I do not know exactly when I might find time to write such a document, but the intent is that it would be a public document, perhaps a Google doc.

* https://github.com/p4lang/p4-spec/issues/561
* https://github.com/p4lang/p4c/issues/1175
* https://github.com/p4lang/p4c/pull/1468
https://github.com/p4lang/p4c/pull/1284
* https://github.com/p4lang/p4-spec/pull/717#issuecomment-480928056

**Comment by jafingerhut** [comment]
Another relevant link: https://github.com/p4lang/p4-spec/issues/51

**Comment by jnfoster** [comment]
This seems interesting, but in the interest of tidying up our list of active issues, I'm going to mark this as "stalled."
