### ISSUE TITLE
switch cache packets

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/p4-spec#768]
Can I use switches to cache packets?Is register ok?Or maybe there's some other data structure that does it

**Comment by jafingerhut** [comment]
There is no mechanism that is part of the base language that enables this.

Most switches have a packet buffer, which can store packets in FIFO queues that can have one of several kinds of packet schedulers for dequeuing them, but that does not give you random access to the packets.

You could use a register to store part of a received packet, but how many bytes of each packet you could store with this mechanism would be implementation-dependent, perhaps anywhere from several dozen bytes of a packet up to hundreds.  It would likely not be an effective way to store all of a packet's contents.

An FPGA implementation would have the flexibility to implement a random access packet buffer at relatively low cost per port vs. a general CPU implementation, but I would be surprised if any ASIC implementations provide such a feature.

You may want to consider using the p4-dev email list for such questions: http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org

**Comment by jnfoster** [comment]
The P4 email lists or P4 Slack are good places to have this discussion. Closing this issue.
