### ISSUE TITLE
extern register does not have method matching this 

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/p4-spec#770]
i use regitser but it is wrong when i run sudo make,i write like this:

`register<bit<3>>(256) pit_r;
bit<3> tmp = pit_r.read((bit<32>)index);
`

but its output shows  the read() method is wrong,   like below
![pic](https://user-images.githubusercontent.com/30151004/60886335-46e05300-a284-11e9-8670-6514ea90fee9.png)

**Comment by jnfoster** [comment]
Please consult [v1model](https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L266) for the signature of the `read` method. It takes two arguments, not one.
