### ISSUE TITLE
Easier conversions for serializable enums

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#774]
Given the strong-typed nature of the language, it is often required to do conversions from serializable enums to the underlying bit<N> type just to make the compiler happy. 

Doing these conversions typically requires being able to declare a variable of the underlying type and then using the cast. In both cases, one must know the underlying type width and if it changes, someone has to go and change it throughout the program. Yes, I know, that can be further modularized by using a constant for the width, but still, it is getting difficult to read, e.g.

```
const int ETHER_TYPE_WIDTH = 16;
typedef bit<(ETHERTYPE_WIDTH)> ether_type_b;
enum ether_type_b ether_type_t {
    TPID = 0x8100,
     IPV4 = 0x0800,
     IPV6 = 0x86DD,
     ...
}
...
ether_type_b ether_type_bits = (ether_type_b)hdr.ethernet.ether_type;
```

I think it would be nicer if we:
  1. Allow automatic conversion from "enum bit<n>" into bit<n> (but not otherwise)
  2. Provide a construct that would allow us to declare a "base type" for 
     a. A given serializable enum type
     b. A given variable of a serializable enum_type

For (1) nothing special is required -- we simply will allow people to omit the casts
For (2) we can define some syntactic sugar, e.g. 
```
BaseType<ether_type_t>
```
or
```
BaseType(hdr.ethernet.ether_type)
```
or even
```
bit<ether_type_t>
```
or something along those lines.

**Comment by mbudiu-vmw** [comment]
I don't understand (2). Can you elaborate with a small example what you want to do?

**Comment by vgurevich** [comment]
@mbudiu-vmw I think if we do(1), most of the problems will be addressed actually. The problem that prompted me to file this issue was the desire to write the parser that deals with the following Ethertypes:
```
const int ETHER_TYPE_WIDTH = 16;
typedef bit<(ETHERTYPE_WIDTH)> ether_type_b;
enum ether_type_b ether_type_t {
     TPID_INNER = 0x8100,
     TPID_OUTER = 0x9100,
     IPV4 = 0x0800,
     IPV6 = 0x86DD,
     ...
}
```

Currently, I could only do the following:
```
     parse_state parse_ethernet {
        pkt.extract(hdr.ethernet);
        transition select((ether_type_b)hdr.ethernet.etherType) {
            (ether_type_b)ether_type_t.TPID &&& 0xEFFF: parse_vlan_tag;
            . . . 
        }
     }
```

Automatic conversion to the "base type" will solve this problem, but I also thought that it would be nice to be able to get the base type for a given enum without knowing its name, since it would allow more transformations done using, say, C preprocessor.

**Comment by jnfoster** [comment]
I spoke to @antoninbas. 

A few facts that are relevant to this issue:

1. The P4Runtime [specification](https://s3-us-west-2.amazonaws.com/p4runtime/docs/v1.0.0/P4Runtime-Spec.html#sec-enum-serializable-enum-and-error) already uses bit strings rather than labels for serializable enums. Here is the relevant text:

> Serializable enum types have an underlying fixed-width unsigned integer representation (`bit<W>`). All named enum members must be assigned an integer value by the P4 programmer, but not all valid numeric values for the underlying type need to have a corresponding name. `P4TypeInfo` includes the mapping between entry name and entry value. When providing serializable enum values through `P4Data`, one must use the assigned integer value (`enum_value` bytestring field). P4Runtime does not provide a way for the client to use the name — even when the enum member has one — instead of the value, as it makes it easier for the server to respect the read-write symmetry principle. 

2. The specification of how to "read off" the types of the operations in the P4Runtime API is indeed scattered across a few documents. But essentially, from the P4Runtime perspective, `P4Info` which is generated by an "early" compiler pass is ground truth. Currently it does *not* treat a serializable enum as equivalent to its underlying bit type. So a table with an expression whose type is a serializable enum were used as a key, the name of that serializable enum would be in the API, but the matches would be populated using bitstrings.

Just as a thought experiment: if we were to change things so the types were truly equivalent, and we also modified compiler so the types in the `P4Info` were also identified, this could break existing control-plane applications, but the API WG has a mechanism for accommodating this change in a graceful way.

Lastly, Antonin and I observed (probably as others have) that if we make a serializable enum equivalent to a bit type, then serializable enums are equivalent to a `typedef` plus a bunch of `const` declarations.

For example and program with this declaration,
```
enum bit<8> my_enum_t {
  A = 0x00;
  B = 0x01;
  C = 0x02;
  D = 0x04;
}
```
and this declaration
```
typedef my_enum_t bit<8>
const bit<8> A = 0x00;
const bit<8> B = 0x00;
const bit<8> C = 0x00;
const bit<8> D = 0x00;
```
behave exactly the same. The front-end of the compiler could even desugar the former into the latter (because we don't use types to disambiguate overloading, for example, so the fact that the latter does not generate a new type is unimportant.)

This last observation is worth pondering... having multiple ways of doing the exact same thing is sometimes considered poor language design (e.g., Perl suffers from this IMHO).

**Comment by antoninbas** [comment]
I think Nate meant to write:
```
typedef my_enum_t bit<8>
const my_enum_t A = 0x00;
const my_enum_t B = 0x01;
const my_enum_t C = 0x02;
const my_enum_t D = 0x04;
```
One difference is that when using an enum, the members are still logically grouped together, and you need to refer to them using their full name, i.e. `my_enum_t.A` instead of just `A`.

**Comment by jnfoster** [comment]
Sure, fixed. (But if `typedef`'d, it doesn't matter, right?)

**Comment by jafingerhut** [comment]
So I believe that if `typedef`s were not erased in the compiler's intermediate phases before control plane API generation, it is possible that we might not have had any motivation to introduce `type`.

Also, agreed that serialized enums are darned close to a typedef plus some const definitions.  This was pointed out by Vladimir around they time they were added to the language spec.

If serialized enums are made completely equivalent to the underlying `bit<W>` type in all ways, _and_ you can still guarantee that they somehow show up wherever you want them in the auto-generated control plane API, then I am curious to know how that can happen, if we couldn't get `typedef` types to show up in the control plane API.

**Comment by vgurevich** [comment]
I think that making the serializable enums full equivalent to the underlying type is not a very good idea. 

Let's imagine this code:
```
enum bit<16> foo_t {
   VAL_1 = 3,
   VAL_2 = 5
}

enum bit<16> bar_t {
   VAL_1 = 7,
   VAL_2 = 9
}

foo_t foo;
bar_t bar;
bit<16> baz16;
```

If we make the types fully equivalent, then one can argue that things like:
```
foo = foo_t.VAL1;
bar = foo;
```
will become possible and I think this is a little too dangerous.

I think that while we should allow automatic casting from the serializable enum to the underlying type, i.e. 
```
baz16 = foo;
```

The reverse should not be true, i.e. the only acceptable form will be:
```
foo = (foo_t) baz16;
```

The reason is that if we allow that, then things like:
```
foo = bar;
```
become possible (i.e. bar is automatically casted to bit<16> and then bit<16> is automatically casted to foo_t) and in my view this kind of an assignment must use casting.

PS: Totally agree with @jafingerhut's first paragraph -- I for once never thought that the equivalency would be taken that far, unless I got to experience it.

**Comment by jnfoster** [comment]
Ahh. We don't have subtyping in the languagee, but morally, it seems that what you want is for serializable enums to be subtypes of their underlying bit type.

**Comment by mbudiu-vmw** [comment]
typedef is different from type because type does not inherit any operations from the underlying type.
So even if you don't "erase" typedef, it's still not the same.

**Comment by vgurevich** [comment]
While updating the spec I also noted that it talks about the "underlying fixed-width **unsigned** integer type". I am not sure what's wrong with defining a serializable enum on top of a fixed-width signed type, e.g.
```
enum int<2> sign_t  {
    MINUS = -1,
    ZERO   = 0, 
    PLUS   = 1
}
```

If there are no objections, I can remove "unsigned" from the spec as well.

**Comment by jafingerhut** [comment]
My guess is that restriction was put there for simplicity, and not having a compelling use case to add the option to make the underlying type signed.

**Comment by vgurevich** [comment]
@jafingerhut, would you agree that we should remove "unsigned" or you'd prefer to leave it there. Note, but the way, that the underlying type for all enums in C is `int` and not `unsigned int`

**Comment by jafingerhut** [comment]
I can't think of a reason that I have a strong preference one way or another.  At least for P4Runtime v1.0 and likely v1.1, there is nothing in the data model for table search key fields, action parameters, and PacketIn/PacketOut header metdata fields that even knows about the enum type name, let alone whether it is signed or not.

That should not restrict the P4_16 language specification -- I point it out primarily to point out other limitations end-to-end that you might want to push for generalizing, too, in order for your grand vision to come to fruition :-)

**Comment by jafingerhut** [comment]
Minor addendum to previous comment: there is a `type_name` field in P4Runtime to describe table search key fields, but the comment near it says that it is for user defined types, which I think is intended to mean `type` definitions in the P4_16 program.  It isn't clear to me whether it would also be reasonable to use that same field to give a name of an `enum` type -- perhaps.  I haven't tried yet to think through whether there are issues with doing that.

https://github.com/p4lang/p4runtime/blob/master/proto/p4/config/v1/p4info.proto#L171-L172

**Comment by vgurevich** [comment]
https://github.com/p4lang/p4-spec/pull/777

**Comment by jnfoster** [comment]
Closing this as it seems to have been at least partly addressed and/or moved to other issues.
