### ISSUE TITLE
Unclear if table properties are ordered or not

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#779]
The spec [says](https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-default-action) that "If present, the default_action property must appear after the action property," but it doesn't impose a similar requirement on the `const entries` list. It seems like the spec should be requiring constant entries to come after the keys and actions of the table so that a typechecker can process the properties in order.

I noticed this because I ran into a related p4c bug: p4lang/p4c#2033

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
