### ISSUE TITLE
Structured annotations to represent properties (kv-pairs, lists of values, etc)

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4-spec#789]
The P4 Runtime WG has identified the need for annotations which declare kv-pairs, expressions, etc. which will get transformed into P4Info. We made some starts at this (https://github.com/p4lang/p4runtime/issues/234, https://github.com/p4lang/p4runtime/pull/238) but the recent change to unstructured annotations in p4-16 1.2 stymied that. We'd like to begin discussing P4-16 enhancements to support this in a uniform way. Below are recent minutes of the P4 API WG which summarize the status to date. Structured annotation are appearing in many venues both open and proprietary and we should define a uniform mechanism before too many ad-hoc conventions get entrenched.

Update on discussion with LDWG regarding annotations support:

* Reluctance from the LDWG to change anything before the P4_16 1.2 release, they wish we had brought it up to them sooner
* Justification for moving to totally unstructured annotation bodies: “Because annotations are used for extensions, they tend to go beyond what can be recognized by the lexer/parser. So minimizing the syntactic requirements maximizes flexibility. We could put them into strings, but then any annotations dealing with strings would need to be escaped.” - Nate Foster
* The P4Runtime WG recognizes this but we also think that our desire for structured annotations support is justified, based on past feedback from members of the WG.
Nate’s proposal to provide support for structured annotations: use a different syntax for different types of annotations.
```
@annot(...) -> parsed uninterpreted, as now
@annot{k1=v1, k2=v2, ...} -> parsed as list of key-value pairs
@annot[v1, v2, ...] -> parsed as list of values
```
The proposed syntax is reminiscent of dictionary / list syntax in other common programming languages such as Python
The same annotation can combine lists and key-value pairs but one needs to repeat the annotation:
```@foo{k1=v1, k2=v2} @foo[v1, v2] my_table { … }```

Vladimir: there is consensus in the LDWG that we should try to rely less on annotations and more on language-native constructs. We also discussed being able to define the runtime APIs for different P4 objects (such as extern types) directly in the P4 program (architecture). We could have some built-in way to attach properties to all P4 objects. There are also some inconsistencies: for some objects the annotations come before the declaration and for other they come after.

Chris: this is true but annotations are definitely needed, being able to specify custom extensions is a must and it has been demonstrated multiple times in this WG. For common scenarios, we should try to uniformize at the language level.
Vladimir: annotations are clunky when you need to refer to other P4 objects such as fields

Antonin: agreed, but this is not the problem we are trying to solve here. If an annotation refers to P4 objects, then it probably means that it is a good candidate for “native” support. But we have not really dealt with such annotations in this WG.

Decision: table Chris’ proposal for now and release P4Runtime v1.1.0 without improved annotation support. Nate’s proposal is a good starting point and we should keep collaborating with the LDWG for the next version of P4_16 (1.3) and the next version of P4Runtime (1.2).

**Comment by liujed** [comment]
Having explicit syntax for annotations that only take key-value pairs or expression lists seems fine to me.

* @ChrisDodd points out that `@annot{k1=v1, k2=v2, ...}` is ambiguous with bodyless annotations on block statements.
* @jnfoster suggests `@annot({k1=v1, k2=v2, ...})` and `@annot([v1, v2, ...])`

Other possibilities:
* `@annot:{k1=v1, k2=v2, ...}` and `@annot:[v1, v2, ...]`
* `@annot={k1=v2, k2=v2, ...}` and `@annot=[v1, v2, ...]`

Would lists only have values, or would general P4 expressions be allowed?

**Comment by chrispsommers** [comment]
@liujed Thanks for responding. I'd expand your question - should general expressions be allowed for values in either kv-v or list forms?

**Comment by konne-google** [comment]
I understand the need to have uniform standard annotations, e.g. one standard annotation shouldn't take a map that looks like {a:b, c:d} where another uses {a=b; c=d}. However, I don't understand the need to change the annotation language. The desired key-value maps are already expressible in the language as is, and we can just make sure that in the standard we define annotations uniformly. 

All the suggested formats seem to have some undesirable properties:
- @annot{k1=v1, k2=v2, ...} is ambiguous with bodyless annotations on block statements.
- @annot({k1=v1, k2=v2, ...}) is ambiguous with the generic annotation
- @annot:{k1=v1, k2=v2, ...} and @annot={k1=v2, k2=v2, ...} seems like it would confuse users that aren't intimately familiar with the standard about why there are multiple ways to write annotation. I also personally feel that these aren't very pleasant to look at.

**Comment by liujed** [comment]
Ah, good point, @konne-google. I think the concerns raised by the Runtime WG could be addressed without any language changes, by having a slightly more complicated implementation. The annotation-parsing pass in the compiler could by default try to parse each annotation body as a list of expressions (or values) or as a key-value list. If either of those succeed, we could put those representations in the AST and emit those representations in the P4Info.

What do you think, @chrispsommers?

**Comment by stefanheule** [comment]
That also doesn't seem great, that will lead to the compiler incorrectly thinking an annotation is a list, when it is not, and then output a "parsed" representation that's completely meaningless.

**Comment by liujed** [comment]
Is the concern that an annotation body might happen to conform to the syntax of a list, and get parsed and output as such? I can see this happening for things that look like singleton lists, if the entire body of the annotation happens to look like a P4 value or expression.

In what sense would the parsed representation be meaningless, if it includes all the information present in the annotation? What is the expected output for annotations that are neither expression/value lists nor kv lists?

I'm afraid I don't have enough context here about P4Info to know how it is used, or the consequences of its having extraneous annotation output.

**Comment by stefanheule** [comment]
Yes, that's right, it seems undesirable to accidentally parse something as a kv-list or list just because it happens to confirm to whatever heuristic the compiler implements to decide what makes a sequence of tokens a kv-list or list.  The result is meaningless in the sense that the annotation wasn't meant to be a kv-list or list, so parsing it as such wouldn't make sense.

**Comment by chrispsommers** [comment]
Per the P4-API WG (minutes: https://docs.google.com/document/d/1qzeAnKDDOIgBzq3sLS1C1CacunTtrV5x5T5xPXUFRGM/edit#heading=h.6cu268h4l7cr) we arrived at a consensus proposal:

Add structured annotations. The "square brackets" form was settled on to avoid conflicts with brace notation as mentioned above. This new syntax can be parsed by the `p4c` front-end to generate `P4info` with structured annotations (e.g.  k-v pairs) which has many demonstrable use-cases in practice.
```
@foo[k1=v1, k2=v2], @bar[v1, v2], @foobar[1 << 10]
```
We'd limit values to literal constants and compile-time integers.

Classic annotations e.g. `@annot(...)`, or `@annot`, are processed per most recent 1.2 spec, i.e. the bodies are not parsed, to allow arbitrary content.

Open question: Should we allow mixing key-value pairs and plain values?
*Discuss ...*

**Comment by jnfoster** [comment]
Let's discuss this at the December 16th LDWG. If you or someone else wants
to formulate an update to the specification (i.e., as a GitHub PR), things
can move faster.

-N

**Comment by chrispsommers** [comment]
Thanks Nate! - chris

**Comment by jnfoster** [comment]
I believe this feature has been added to the specification. Shall we close this issue?

**Comment by smolkaj** [comment]
Sorry if this is derailing the discussion, but on a related note, is there a feature request yet to support nested kv pairs?
We have occasionally had a need for it at Google.

**Comment by jnfoster** [comment]
I don't believe so. But for hygiene, I'd like to close this one. If you or Google wants to open up a new issue to track the new feature, that'd be great!
