### ISSUE TITLE
Unification between lists and tuples

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#792]
This is from this PR: https://github.com/p4lang/p4c/pull/2085

The question is whether the list expression `{x,x}` in the select should be unifiable with both a tuple t and a struct s, or this example should be illegal. 
```
#include <core.p4>

struct S {
    bit<8> f0;
    bit<8> f1;
}

parser p() {
    state start {
        bit<8> x = 5;
        S s = { 0, 0 };
        tuple<bit<8>, bit<8>> t = { 0, 0 };

        transition select(x, x, {x, x}, x) {
            (0, 0, {0, 0}, 0): accept;
            (1, 1, default, 1): accept;
            (1, 1, s, 2): accept;
            (1, 1, t, 2): accept;
            default: reject;
        }
    }
}

parser s();
package top(s _s);

top(p()) main;
```

**Comment by vgurevich** [comment]
I think the main problem in this particular example is that `s` and `t` are variables and not compile-time known values neither  are they value sets. 

Perhaps we should use some other context, since in this one unification is not going to help much.

**Comment by jnfoster** [comment]
@vgurevich, does the spec say that `keySetExpressions` used in `select` statements must either be compile-time known or parser value sets?

The only places I could find mention of such restrictions are in Section 12.6,

> Some targets may require that all keyset expressions in a select expression be compile-time known values.

and in Section 8.2.13:

> P4 architectures may impose additional restrictions on the expressions on the left and right-hand side of a mask operator: for example, they may require that either or both sub-expressions be compile-time known values.

**Comment by vgurevich** [comment]
@jnfoster , I might certainly be somewhat biased towards some more restrictive targets, but I am not sure we intended to allow things like:

```
     transition select (hdr.ethernet.dstAddr) {
          hdr.ethernet.srcAddr : bad_packet;
          default : continue_parsing;
     }
```

Did we?

Note, that in that case we could've implemented `value_set` using a variable-like extern
```
    ValueAndMask<bit<16>(4) tpid;
    
    transition select(hdr.ethernet.etherType) {
        tpid.value_get() &&& tpid.mask_get() : parse_vlan_tag;
        0x0800: parse_ipv4;
        . . . 
        default: accept;
    }
```
without adding a new specialized construct into the language.

**Comment by jnfoster** [comment]
Closing this issue as it seems to have stalled. Moreover, we'd rearranged our data types for collections, so it probably needs an update anyway...
