### ISSUE TITLE
Notes on pure/noSideEffect annotations on extern methods/functions

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#800]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @ChrisDodd 

## Design
- [x] **Document**: https://github.com/jafingerhut/p4-guide/tree/master/extern-annotations

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/issues/802
- [ ] **`p4c`**: 

## Process
- [x] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

I threw in several more annotations, which I don't know whether they would be useful for a compiler to know, but seem to represent fairly common restrictions on the existing extern methods/functions in the v1model and PSA architectures.

https://github.com/jafingerhut/p4-guide/tree/master/extern-annotations

@ChrisDodd Feel free to focus on my proposed definitions of @pure and @noSideEffects here to see if they match your expectations, and I am happy to add a section describing what kinds of compiler optimizations are enabled by these annotations, and/or which are not enabled by them.

**Comment by ChrisDodd** [comment]
I'm not sure I agree with some of the functions you've marked `@pure` -- things like `mark_to_drop` are not pure as they do have side effects, its just that those side effects are not visible in the P4 program in which they occur.  Eliminating a call to such a function if its return value/out params are not used would change the behavior of the program.

**Comment by mbudiu-vmw** [comment]
Actually mark_to_drop has an out argument, so it is pure. The out argument that you are supposed to supply should be part of the standard_metadata, so it's used by the architecture. But if you supply a temporary as an out argument then it's safe to remove it.

**Comment by jafingerhut** [comment]
@ChrisDodd I can try to answer any you think are incorrectly marked on a case by case basis -- I have tried to be very careful in my markings, but could have gotten some of them incorrect.

In general for everything named in the table, you can search for that name later in the document, and find more comments that should hopefully explain the rationale for how I have categorized the method/function.

Ever since `mark_to_drop` takes standard_metadata as an inout parameter, it behaves like the function that I added in the more detailed section later:
```
function mark_to_drop(inout standard_metadata_t standard_metadata) {
    standard_metadata.egress_spec = TARGET_SPECIFIC_DROP_PORT_NUMBER;
    standard_metadata.mcast_grp = 0;
}
```
That is all it does.  Later, after the packet is done with ingress processing, other things might happen, but does the compiler care what happens after ingress processing is done for these annotations?  I thought "no".

**Comment by jafingerhut** [comment]
In the mark_to_drop case, standard_metadata is `inout` to the ingress control as a whole in v1model.  So effectively anything that modifies any field of standard_metadata during ingress cannot be considered dead code, unless the compiler somehow knows that some individual fields are ignored by the architecture?

**Comment by jnfoster** [comment]
This seems to have stalled... feel free to resurrect if it should be kept active.
