### ISSUE TITLE
Global variable 

### ISSUE THREAD

**Issue by SanaaComp** [p4lang/p4-spec#810]
Hi,
In some programming languages, such as Java, I can define a global variable that can be used in all functions within my code.
Is it possible to do that in P4? If yes, how?

**Comment by mbudiu-vmw** [comment]
You can have top-level instances of arbitrary extern objects.
However, some targets may not supports such constructs.
Some switches are truly distributed, and have no shared memory between multiple pipelines.

**Comment by jafingerhut** [comment]
And in some cases "truly distributed" means that ingress and egress are on the same physical chip, but they don't "talk to each other" except though the packet buffer and recirculated packets.

Some more details about why high speed devices often do not have shared state between ingress/egress, or between all ports of a many-port device, can be found here: https://p4.org/p4-spec/docs/PSA-v1.1.0.html#appendix-multi-pipeline-psa-devices

**Comment by SanaaComp** [comment]
> You can have top-level instances of arbitrary extern objects.
> However, some targets may not supports such constructs.
> Some switches are truly distributed, and have no shared memory between multiple pipelines.

@mbudiu-vmw  I'm new to P4, so I appreciate if you show me how to create a top-level instance.

**Comment by jafingerhut** [comment]
Here is a demo program that compiles and works as intended just fine using the BMv2 simple_switch software switch target, where there is a register extern object instantiated at the top level of the program.  I have verified that it compiles and executes as intended on the simple_switch target.

As the comments try to indicate, it is target-specific whether this program will work on any particular P4 target device.

https://github.com/jafingerhut/p4-guide/blob/master/demo6/demo-global-register.p4_16.p4#L36-L55

**Comment by SanaaComp** [comment]
Thank you.
