### ISSUE TITLE
Should struct initializer expressions be compile time constants (if their field values are)?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#816]
Section 17.1 "Compile-time known values" does not explicitly list struct initializer expressions, e.g. an expression like the right hand side of the assignment below:
```
struct mystruct1_t {
    bit<16> f1;
    bit<8>  f2;
}

    mystruct1_t s1;
   s1 = {f1=2, f2=3};
```
Should a struct initializer expression be considered a compile-time known value, if all of the values inside of it are themselves compile-time known values (perhaps even nested compile-time known struct initializer expressions)?

If so, I can create a PR that mentions this explicitly in the bullet list of items in Section 17.1.

**Comment by mbudiu-vmw** [comment]
Yes, it should be a compile-time known value.

**Comment by jafingerhut** [comment]
Closing this issue, as the corresponding PR has been merged into the spec.
