### ISSUE TITLE
P4 spec terminology for extern functions, methods, non-extern functions

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#824]
I am not necessarily using 'standard' or 'specification' language in this question.  I am asking specifically because I wonder whether there is official 'specification' language that distinguishes these things.

P4_16 lets you define:

(a) an extern object, with one or more constructors, and zero or more methods.  The keyword 'extern' must be used when defining such an object.  Such an object must be instantiated before you can call methods defined for it.

(b) something that I have been calling an 'extern function', but maybe that is just me.  An example is the `hash` function in v1model.p4: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L326
```
extern void random<T>(out T result, in T lo, in T hi);
```
There is no object to instantiate that is involved here at all, so it is not identical to (a) above.

(c) something that I have sometimes called a 'normal function', which is like (b), except there is no 'extern' keyword, and the body of the function is specified using the P4_16 language.

Questions:

Sometimes the spec mentions "methods".  Is it intended that those include the things for (a) only, or also (b)?

Sometimes the spec mentions "functions".  Is it intended that those include both (b) and (c) in all cases, or perhaps since (c) was added to the language more recently, some of those mentions should be specifically for case (b) and not apply for (c)?

Sometimes the spec mentions "externs".  I wrote some of those in appendix F, and I believe I was intending those to refer to (a) only, not (b), but not sure right now.

Is this an area that could maybe stand some tightening up of the specification language?  Perhaps with a glossary somewhere in the spec for the terms used?

Having 'compile-time known value' in such a glossary might be helpful, too, where its explanation might mention that in the specification that 'compile-time known value' is a spec-preferred term, and other similar terms should be avoided, e.g. 'compile-time constant'.

**Comment by mbudiu-vmw** [comment]
I OO parlance methods are functions that are fields of objects; with this terminology they would apply only to extern objects. However, the P4 grammar uses a single production for methods and functions, where the name is different (a path or an identifier). That's what produces some confusion.

**Comment by jnfoster** [comment]
I don't see an action item here, so proposing that we close this...
