### ISSUE TITLE
Probably out-of-date text in Section 8.9.2 "Implicit Casts"

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#825]
The first sentence says "To keep the language simple and avoid introducing hidden costs, P4 only implicitly casts from int to fixed-width types."

That was probably written before the following text in Section 8.3 "Operations on enum types":

"Because it is always safe to cast from an enum to its underlying fixed-width integer type, automatic casting from an enum to its fixed-width (signed or unsigned) integer type is also supported:"

Would it be more internally consistent if the text in Section 8.9.2 was updated a bit?

Or is there a technical difference between "automatic casting" and "implicitly cast" that is significant here?

**Comment by mbudiu-vmw** [comment]
There is no "automatic casting", only implicit casts.

**Comment by jnfoster** [comment]
Closing this as it seems out of date. But feel free to resurrect if I've been too eager to close.
