### ISSUE TITLE
Redundant text in Section 8.15 "Operations on headers"?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#826]
These two consecutive paragraphs appear to be saying very similar things, with somewhat different wording.  Given that the second one has more details and was clearly added after structure initializer expressions were introduced, maybe the second paragraph was intended to replace the first?

"A header object can be initialized with a list expression, similar to a struct—the list fields are assigned to the header fields in the order they appear. In this case the header automatically becomes valid:

Similar to a struct, a header object can be initialized with a list expression 8.11 — the list fields are assigned to the header fields in the order they appear — or with a structure initializer expression 8.13. When initialized the header automatically becomes valid:"

**Comment by mbudiu-vmw** [comment]
For this kind of fix feel free to submit directly a PR.

**Comment by jafingerhut** [comment]
Closing this issue, since it was resolved by merging this PR: https://github.com/p4lang/p4-spec/pull/828
