### ISSUE TITLE
Side-effects in table keys and select labels

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#830]
The spec does not say when the side-effects that may occur in table keys and select labels occur.
One simple solution would be to forbid function and method calls in these places.

**Comment by jafingerhut** [comment]
I don't think you want to forbid `hdr.isValid()` method calls in table key expression, do you?

Perhaps the most precise way to express the restriction is something like "key expressions may only contain pure function and method calls, and even among those, only ones that have no direction `out` or `inout` parameters"?  This is assuming the definition of `pure` proposed in this article: https://github.com/jafingerhut/p4-guide/tree/master/extern-annotations

Given the contents of that article, it would be correct for the built-in method `hdr.isValid()` to be annotated with the `@pure` annotation, and it has no direction `out` nor `inout` parameters.

**Comment by jafingerhut** [comment]
I believe that all P4_16 functions, by which I mean the ones written in P4_16, not an extern function, must be 'pure' in the same sense as in that linked article in my previous comment, and might be reasonable to call inside a table key expression, as long as they have no  direction `out` nor `inout` parameters.

**Comment by mbudiu-vmw** [comment]
Indeed, the implementation allows "built-in" functions, like isValid.
Still, the question is "when are these functions evaluated", and in what order.
For tables it's perhaps easier to answer this question, but for select labels the situation is trickier. There is no obvious place to lift the function evaluation, esp. if you want to evaluate only as many labels as necessary.

**Comment by jafingerhut** [comment]
If they are pure functions with neither `out` nor `inout` direction parameters, isn't the order of evaluation unimportant, and their time of evaluation the only thing that matters is "before the value is needed"?

**Comment by mbudiu-vmw** [comment]
There is the semantics, but there is also the cost of evaluating the function, that some of the people may care about. Perhaps we should not worry too much about this in the spec; I maintain, however, that these restrictions won't surprise too many people.

**Comment by jafingerhut** [comment]
So are you proposing for the spec to say something like "table key expressions may not contain any function or method calls, except the following list of built-in ones: ...", where that list of allowed ones includes `hdr.isValid()`?

**Comment by mbudiu-vmw** [comment]
Something to that effect; I put this on the agenda for the next design meeting.

**Comment by mbudiu-vmw** [comment]
But there's no PR yet...

**Comment by jafingerhut** [comment]
I am asking because I started to write a PR, and had questions about what it should say.  May create a proposed one soon.

**Comment by jafingerhut** [comment]
See also discussion on this p4c PR: https://github.com/p4lang/p4c/pull/2259

especially the discussion beginning with this comment: https://github.com/p4lang/p4c/pull/2259#issuecomment-605543708

**Comment by jafingerhut** [comment]
There are two different proposed PRs for this issue: #831 and #834 

See this comment for a brief description of the differences between them: https://github.com/p4lang/p4-spec/pull/834#issuecomment-608999089

**Comment by jafingerhut** [comment]
PR #834 addressed the table keys portion of this issue.  I will close this one and create a separate one to remind us to address the `expr` part of `select (expr) { ... }` expressions.
