### ISSUE TITLE
Question on .next in header stacks

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4-spec#832]
Not sure if this was discussed before.

According to the spec for header stacks `.next`, `.last`, and `lastIndex` are computations but they are implemented as attributes. Consequently, accessing these values is represented as `Member` expression in the IR, not `MethodCallExpression`. On the other hand, `isValid()`, which just returns header validity, is a method and results in a `MethodCallExpression`.  

Is there a specific reason for this? I am asking because while developing an interpreter, implementing `.next` has caused a minor inconvenience for me. 

Another question:  `.nextIndex` is only advanced in `pkt.extract`, correct? There are no other calls that could potentially increment the `next` pointer in a header stack?

**Comment by mbudiu-vmw** [comment]
I would not say that they are computations. They are really references to elements within the stack, and they advanced by the same operations which change `nextIndex`. `a.next` is the same as `a[a.nextIndex]`.

**Comment by jafingerhut** [comment]
`.nextIndex` can be modified when `push_front` or `pop_front` methods are called on a header stack, too.

**Comment by fruffy** [comment]
Ah okay, sounds good, thanks for the clarifications. I was mostly concerned because they were referred to as computations in section 8.16.
