### ISSUE TITLE
[Proposal] Structural iteration

### ISSUE THREAD

**Issue by akeep** [p4lang/p4-spec#84]
One of the patterns I've noticed in some of the P4 14 examples is to use a C-pre-processor define to specify the length of a header stack.  This is a convenient way to declare header stacks, but it means that code that needs to operate over explicit indexes within the header stack need to be protected by C-pre-processor `#if/#elif/#endif` constructs, or the C-pre-processor definition for the length of the header stack is inconvenient.

I was thinking it might be nice to have a `foreach` style iterator for operating over header stacks.

For example, you could imagine something like:

```
foreach hdr in hdrs {
  ... operations over HDR ...
}
```

Since the stacks are always known statically (at compile-time), the compiler could elaborate the `foreach` form into the replicated code with explicit index references at compile-time.  This has the advantage of allowing the code to be written without regard to a parameterized header stack length.

Since the compiler can statically determine the number of operations that would result from the `foreach` it can also reject a program if the result requires more action resources than are available, or can split the action code up to fit available resources as needed.

**Comment by jnfoster** [comment]
Discussed at 11/5/2018 LDWG. @jafingerhut volunteered to own this issue, and identify some examples for further design discussion.

**Comment by jnfoster** [comment]
This old issue might be relevant to #1261.
