### ISSUE TITLE
Division with bit<w> arguments

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#844]
p4c permits division and modulo between bit<w> values but the specification restricts those operations to positive `int` values. I think this is probably the spec being too restrictive rather than p4c being too permissive.

**Comment by mbudiu-vmw** [comment]
These operations do not have an unambiguous definition for negative values.

**Comment by jnfoster** [comment]
And what about the fact that it can be used with `bit<_>` too?

**Comment by mbudiu-vmw** [comment]
Some targets may reject some run-time divisions statically (but may accept, e.g., divisions by constants). But otherwise I think it's fine.

**Comment by apinski-cavium** [comment]
I just came across this today too.
Maybe in the next spec meeting just get a vote up or down to allow them for bit<...>.
We could even add saying some P4 target architectures may optionally support runtime division and mod (just like the section about saturating arithmetic).
If I get time over the weekend, I will submit a pull request so we can just vote on it.

**Comment by QinshiWang** [comment]
I agree that whether or not to allow runtime division depends on the target. And in the case of divided by zero, it should return an unspecified value rather than a runtime error. I think every non-zero division and mod has a well-defined result (dividing by the absolute value and rounding down). But it's okay if you have a different opinion.

**Comment by blp** [comment]
C mandates that integer division rounds toward zero, so I'd be surprised to see other behavior if this gets standardized at all.

**Comment by vgurevich** [comment]
@blp -- if everyone ends up implementing things the same way, it will be very easy to reach an agreement :) But let's see these extern-based implementations first, so that we can have a concrete set of details to discuss.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
