### ISSUE TITLE
Possible clarification for initialization of direction out parameters?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#846]
A quote from version 1.2.0 of the language spec, Section 6.7 "Calling convention: call by copy in/copy out" https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-calling-convention:

'out parameters are uninitialized (parameters of type header or header_union are set to “invalid”) and are treated as l-values (See Section 6.6) within the body of the method or function.'

The v1model architecture parsers have a direction `out` parameter with type `H` that is a struct containing fields that may be any header, header union, or header stack type, and no parser definition I have ever seen explicitly initializes these headers, header unions, and header stack elements to invalid.  It is assumed by the code that they are initially invalid, and the quote above is probably the reason why.

Assuming that is all true, it seems the quote above could be made more explicit, e.g. something like this:

out parameters are uninitialized and are treated as l-values (See Section 6.6) within the body of the method or function.  There are several exceptions where out parameters are explicitly initialized, at least partially:

+ If an out parameter is of type header or header_union, it is set to "invalid"
+ If an out parameter is a header stack containing either header or header_union elements, all elements of the header stack are set to "invalid", and its `nextIndex` counter is initialized to 0, as discussed in 8.16
+ If an out parameter is a compound type such as a struct or tuple, and any of its members is any of the types above, they are initialized as described there.  If any of its members are a compound type, then recurse into those elements.

**Comment by vgurevich** [comment]
Yes, most of the code relies on this rule pretty extensively, so the proposed clarification would be nice. 

For the compound types I would only add that if they have non-header elements, those will remain uninitialized and the compiler is free to produce warnings about those (if they are not assigned by the end of scope).

**Comment by jafingerhut** [comment]
See PR #848 for proposed clarifications to the spec

**Comment by jafingerhut** [comment]
Closing as resolved, since PR #848 was merged.
