### ISSUE TITLE
Reducing requirements for initializing headers

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#849]
In the 2020-May-04 LDWG meeting, issue https://github.com/p4lang/p4-spec/issues/846 and its associated PR https://github.com/p4lang/p4-spec/pull/848 were discussed, as well as the related issue https://github.com/p4lang/p4-spec/issues/845

It was decided that for version 1.2.1 of the language spec, for both `out` parameters and local variables, it would be made explicit that all headers, header unions, and header stacks that are in these places of a P4_16 program, or within a struct or tuple in one of these places, would be mandated to be initialized as invalid, as opposed to the main alternate proposal, which was allowing implementations to leave the valid bit of such headers to remain uninitialized and undefined, i.e. it would be unpredictable whether hdr.isValid() would return true or false for such headers.

It was also decided to create another issue for future discussion that in a future version of the language spec, these requirements should be eliminated, i.e., an implementation would be allowed to leave the valid bits of such headers undefined.  This is that issue.

A concern was raised that at least for `out` parameters, but perhaps also for local variables, writing the spec such that the valid bits could be undefined would be a backwards-incompatible change, requiring existing P4_16 programs that rely on such initialization to be changed in order to continue working as they did before.  If we were strict about following the rules of semantic versioning, it seems that such a change in the language spec should cause the language specification to increase the major version number, e.g. from 1.2.1. to 2.0.0.

**Comment by jnfoster** [comment]
With recent improvements to the specification, I think this can effectively be closed.
