### ISSUE TITLE
Make a list of all places that expressions can appear, and whether they allow side effects

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#855]
Given the recent discussions about table key expressions, select expression lists, select expression key set expressions, and actions with expressions as parameters in an `actions` table property, and whether each of those places should allow expressions with side effects, it seems worth scrubbing all places in the language that allow expressions, and consider for each one this same question.

**Comment by jnfoster** [comment]
In the interest of reducing the set of open issues, I'm going to mark this as stalled. But it's a good idea if you want to pick it up again...
