### ISSUE TITLE
Consider whether `exit` should be allowed in actions called from table T where T.apply() is used in expressions

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#856]
Consider an expression like `some_table.apply().hit`, or `.miss`, or `some_table.apply().action_run` in a `switch` expression.

If one or more of `some_table`'s actions can execute an `exit` statement, is that something we want to define and support in P4_16?

If we prohibit this combination, then this might be the only current way in the P4_16 language spec that evaluating an expression can cause an `exit` statement to be executed.  If so, that seems like a potentially nice thing to rely upon in legal P4_16 programs.

If we allow this combination, or any others where evaluating an expression can cause an `exit` statement to be executed (are there any others?), it seems worth a sentence or three somewhere in the spec mentioning this possibility, and how such a program behaves.

**Comment by jafingerhut** [comment]
Note that a potential disadvantage of allowing `some_table.apply().hit` to execute an `exit` statement during its evaluation: Any kind of analysis tools for P4 programs that wanted to exhaust all possible flows of control through a program in some way would need to consider not merely that the expression could evaluate to `true` or `false`, but also that it could cause an `exit` to occur.  I know I never considered that possibility when working on the `p4pktgen` tool, and it seems a subtle enough point that I would guess a lot of people might not consider it.

**Comment by jnfoster** [comment]
I am not in favor of adding a restriction. A good language design is compositional and uniform wherever possible. We can eliminate side effects in a compiler pass, as @mbudiu-vmw suggested in the other thread. This is a bit more work for the compiler and analysis tools that want to consume the initial IR and not the partially-processed IR. But it keeps the overall design simple and uniform, which is a win for developers.

**Comment by jafingerhut** [comment]
If we allow such programs in the language, then statements similar to the following would make sense to me to include in the language spec:

+ If the conditional expression of an `if` statement is evaluated that causes an `exit` statement to be executed, then neither the `then` nor `else` branch of the `if` statement is executed.
+ If the expression of a `switch` statement is evaluated that causes an `exit` statement to be executed, then no branch of the `switch` statement is executed.

A place where I am less clear how it should be defined is if a table key expression evaluation causes an `exit` statement to be executed, as shown in this issue: https://github.com/p4lang/p4c/issues/2362

I will copy the code snippet below for reader convenience:
```
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {

    table sub_table {
        key = {
            h.eth_hdr.eth_type: exact @name("dummy_name") ;
        }
        actions = {
        }
    }

    table simple_table {
        key = {
            sub_table.apply().hit: exact @name("dummy_name") ;
        }
        actions = {
        }
    }
    apply {
        simple_table.apply();
    }
}
```
Suppose an action of `sub_table` executes an `exit` statement.  How should the behavior of the `simple_table.apply()` call be defined?

One possibility is: it behaves as if the `exit` statement was executed before any later key expressions of `simple_table` were executed, and without doing the lookup or action execution for table `simple_table` at all.  At least, that would be consistent with the spec clarification made with this PR: https://github.com/p4lang/p4-spec/pull/834

**Comment by jafingerhut** [comment]
Here is another example code snippet for consideration.  Suppose during the ingress control of the v1model architecture, where standard_metadata.egress_spec chooses the output port a packet will be sent to, if it is unicast, this code is executed:
```
    standard_metadata.egress_spec = 5;
    standard_metadata.egress_spec = simple_table.apply().hit ? 7 : 8;
```
If the evaluation of `simple_table.apply().hit` causes an `exit` statement to be executed by the selected action, what should the final value of `standard_metadata.egress_spec` be?  One answer that makes sense is 5, since the `exit` causes the second assignment not to occur.

Allowing `exit` in an expression that has subexpressions that can have side effects, too, seems to require (for a precise specification of the behavior) that the order of evaluation of all subexpressions must be explicitly defined, and that order may not be changed by any optimization passes of a compiler, at least when some subexpressions might cause `exit` to be executed.  A compiler has more freedom if it knows that no subexpressions can cause `exit` to be executed, and/or subexpression evaluations cause no side effects.

**Comment by jnfoster** [comment]
Yep. If expressions have side effects, then we need to specify evaluation order, or we say it's unspecified (so a compiler can do anything.)

**Comment by mbudiu-vmw** [comment]
This is already in the spec: https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-expr-eval-order

**Comment by jafingerhut** [comment]
If no restriction is added to the language for this combination of features, then this PR is a proposed way to make the effects of this combination more explicit: https://github.com/p4lang/p4-spec/pull/860

**Comment by jafingerhut** [comment]
PR https://github.com/p4lang/p4-spec/pull/860 has been merged into the spec, so closing this issue.
