### ISSUE TITLE
Understanding PVS Matches

### ISSUE THREAD

**Issue by CommitThis** [p4lang/p4-spec#857]
I've been trying to understand Parser Value Sets, specifically as the are described in P4 16 spec v1.2.0 (Page 90). As per the example, a struct (vsk_t) is defined with a single bit<16> "port" field that is annotated with "@match(ternary)" which is then used (AFAIUI) to describe a value set with 4 entries by default. My understanding was that ternary matches require some of the bits in the match to be ignored in order to match on multiple entries. However, in this example, I don't understand where these bits are. Why is the match in this example ternary, and what would the implication if the match was exact? I'm guessing the fact that the match is applied to a field by an annotation as opposed to the entire type is irrelevant.

I had also been reading the #2188 which covers use of masks in a select expression and so far I have been able to glean:

- Masks in select expressions are ignored in P4 16;
- PVS matches are ternary by default;
- BMv2 doesn't support ternary matches

All in all, a bit confused. Thanks in advance.

**Comment by mbudiu-vmw** [comment]
From the point of view of P4 a parser value set is just a set of values, which can be changed dynamically. Matching a concrete value against it returns 'true' if the value is in the set.

The annotation `@match{ternary}` is just a hint to the compiler on how to *implement* the parser value set. Since the compiler has no idea about what kinds of values will be in the set at runtime it has no way to choose a good implementation otherwise.

**Comment by CommitThis** [comment]
Thankyou for you response. So if it is labelled exact, it doesn't really matter at the point of use, it's just describing an implementation detail?

**Comment by mbudiu-vmw** [comment]
yes. this also has an important effect on the control-plane API that is used to modify the PVS.

**Comment by CommitThis** [comment]
Ok, thank you very much.

**Comment by jafingerhut** [comment]
I do not believe the open source P4 development tools implement this functionality yet, but the intent is that a parser value set with match_kind `exact` (the default if you do not specify one) is a set of individual values of the type indicated in the P4 source code, e.g. a value set with elements of type `bit<16>` and match_kind `exact` would allow the control plane to add zero or more exact values of type `bit<16>` to the set, e.g. the 3 values 0x0855, 0xfade, and 0x8998.

If the match_kind is `ternary`, then the control plane is allowed to add value/mask pairs as individual items to the parser value set, e.g. one element added could be value=0x0805 with mask=0xff0f, and that one entry added to such a parser value set could match any of the 16 values V such that (V & 0xff0f) == (0x0805 && 0xff0f).

**Comment by jafingerhut** [comment]
Clarification to my previous comment: I believe the open source P4 dev tools implement the exact match kind for parser value sets.  They do not yet implement any other match kinds, such as ternary, for parser value sets.

**Comment by CommitThis** [comment]
@jafingerhut Thank you, that also helps.
