### ISSUE TITLE
Specify Enumeration Initialisation Behaviour

### ISSUE THREAD

**Issue by CommitThis** [p4lang/p4-spec#858]
I wanted to get clarification on the following point. Reading Section 7.2.1 (Enumeration Types), It is very clear that an identifier can only be specified once (quite rightly), however I can't see how initialisers are specified in terms of whether it is legal to have the same initialiser repeated. A real world example of this would involve ICMP type codes, where the message type determines how the code is used:

```
enum bit<16> ICMPCode {
    DEST_NET_UNREACHABLE = 0,
    // ...
    REDIRECT_DATAGRAM_NET = 0, // Is this legal?
}
```

The wording implies that it is:

> ... the mapping of symbolic to numeric values defined by the enum are effectively constants defined as a part of this type

I ask because in C/C++, this would be a perfectly legal thing to do [(see cppreference)](https://en.cppreference.com/w/cpp/language/enum) however it appears as though languages such as [Rust](https://doc.rust-lang.org/reference/items/enumerations.html) (although i'm not terribly familiar with that language) do not permit this -- but in any case the behaviour is explicitly specified.

P.S. I noticed a small spelling mistake in the card suite example, "Hearts" is spelt "Hearths". Might be difficult playing a game of cards with that.

**Comment by mbudiu-vmw** [comment]
Section 8.3 answers this question in the positive:
https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-enum-exprs

**Comment by CommitThis** [comment]
Ok, thankyou.
