### ISSUE TITLE
"ReadRegisters" function

### ISSUE THREAD

**Issue by brunofraga-rs** [p4lang/p4-spec#862]
Hello, everyone.

I'm new in p4 language and I was wondering if anyone could give me a tip.

On **p4runtime_lib** we have switch.py which presents the functions **ReadTableEntries** and **ReadCounters** but I didn't find anywhere else a function for the controller to read data plane registers from the switches.

Is there such a library that does it in python ? I mean, did someone implement a .py code defining a "ReadRegisters" function ?

Thanks in advance.
Bruno Fraga

**Comment by jnfoster** [comment]
This is the repository for the P4 language specification. I'm not totally sure where you got `p4runtime_lib` (maybe the tutorials repository?) but can you ask your question there?

**Comment by brunofraga-rs** [comment]
Ok.

Sorry. I realized now I posted the question in the wrong place.
