### ISSUE TITLE
Assigning an invalid header

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4-spec#863]
Quick question. After executing the following assignment:

```p4
struct Headers {
    ethernet_t eth_hdr;
    H     h;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
            H tmp_0;
            h.h = tmp_0;
    }
}
```

Is h.h now invalid or valid? I would tend to say invalid. Otherwise it might conflict with the inlining of function calls like this one?

```p4
void reset_function(out H tmp) {}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {

    apply {
        reset_function(h.h);
    }
}
```

**Comment by jnfoster** [comment]
I think this is clarified by #850 (now merged), which makes it clear that `tmp_0` will be invalid and the line from Section 11.1 discussing assignment on headers:

> all components of headers are copied, including “validity” bits
