### ISSUE TITLE
Consider clarifying what is meant by "same type" in the language spec

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#875]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @jnfoster 

## Design
- [ ] **Document**:

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

In particular, this issue: https://github.com/p4lang/p4c/issues/2230 seems to indicate that for structs and headers, "same type" means "two structs with the exact same type name", or "two headers with the exact same type name".  That is, the following two structs are NOT the same type, even though their field names and corresponding field types are the same, because their type names are different:
```
struct s1_t {
    bit<8> f1;
    bit<16> f2;
}

struct s2_t {
    bit<8> f1;
    bit<16> f2;
}
```
Similarly, two header types with different names are not the same type, even if their field names and field types are identical.

If that is the case, it seems worth mentioning explicitly in the language spec somewhere.

I do not have any current guesses what "same type" might mean for control types, parser types, or package types.  I will leave that up to others to attempt to define, perhaps with a separate issue.  I do not even know if the question makes sense in that case, or needs answering.

**Comment by hackedy** [comment]
Type equality for controls, parsers, and packages comes up (in Petr4's type system, at least) when we typecheck constructor invocations.
```
control C();
package Pkg(C c);
control MyC() { apply { } }
MyPkg(MyC()) main;
```
Here the instantiation `MyC()` of a control declaration has a control type `t = control()` and the type declaration `control C()` defines a type `C = control()`. In the instantiation of `MyPkg`, the typechecker checks that `t` and `C` are equal types.

**Comment by jafingerhut** [comment]
Another question I will guess the answer to: Are two types "the same type" if one is a struct, and the other is a typedef name for that struct?  I would guess "yes".

Are two types "the same type" if one is a struct, and the other is a type name based on that struct?  I believe the answer is "no", since the "type" keyword is intended to introduce distinct new types.

**Comment by jafingerhut** [comment]
And yet another question: What about `tuple<t1, t2>` and a typedef name whose base type is `tuple<t3, t4>`?  Seems likely that perhaps it should be the same type, as long as t1 and t3 are the same type (including perhaps typedef aliases for each other), and t2 and t4 are the same type.

**Comment by jnfoster** [comment]
Nice examples. 

(Just watch out or you'll be doing [Homotopy Type Theory](https://en.wikipedia.org/wiki/Homotopy_type_theory#Equality) soon! :-)

**Comment by jafingerhut** [comment]
If I am doing "Homotopy Type Theory" soon, I will only know that I am doing it because you told me that is what I was doing, using many more words and examples to describe it :-)

**Comment by jafingerhut** [comment]
Note that this issue perhaps becomes more involved with the introduction of generic structs: https://github.com/p4lang/p4-spec/issues/892

Perhaps the only aspect of generic structs that affects this issue is the particular way that generic structs have been implemented in p4c, which involves introducing new type names.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
