### ISSUE TITLE
Legal to form header stacks of header unions?

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#876]
I'm having trouble telling if header stacks `H[n]` require `H` to be a header only or if they also allow header unions. The p4c typechecker allows unions, and the original proposal #139 said unions were ok. Maybe this should be an additional column in the type nesting table?

**Comment by jafingerhut** [comment]
I have thought that the intent was that header stacks where the elements are header unions were intended to be supported in the spec, but at least right now do not see anything explicitly saying so in the spec.  It does seem worth mentioning it explicitly.

**Comment by apinski-cavium** [comment]
I actually found the same issue plus the p4c is getting many new testcases for header stacks with header unions so this gets more important to fix the specifications if we want to allow it.

**Comment by apinski-cavium** [comment]
There is a testcase in the p4c already for header stacks of header unions. ./p4_16_samples_outputs/spec-ex09.p4 and p4_16_samples/spec-ex19.p4 which were added with https://github.com/p4lang/p4c/commit/bb47b71882 (well it was moved to the p4_16 directory later on).

**Comment by jnfoster** [comment]
Closing as this seems to have been fixed.
