### ISSUE TITLE
Rationale for default arguments in types

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#878]
It's grammatical to write something like this in p4.
```
control C(in int<8> x = 77);
package Pkg(C c);
control MyC() {
  apply {
  }
}
Pkg(MyC());
```
I'm trying to understand what the meaning of a default argument is in a situation like this. The 77 isn't actually used anywhere, since MyC doesn't accept arguments. Does this accomplish anything that an `@optional` annotation wouldn't do just as well?

**Comment by mbudiu-vmw** [comment]
This indeed seems useless, we could at least give a warning.

**Comment by hackedy** [comment]
Oops, sorry. Anyway what I was going to say is that even `@optional` parameters complicate things, but it's probably worth it. Having `@optional` parameters in type declarations means that argument and parameter types aren't checked for type equality but for a "subtyping" relationship. In the example above that means checking `control() <: control(@optional in int<8> x)`. So this is a complication to be aware of in #875.

**Comment by mbudiu-vmw** [comment]
You could also call it overloading. I think of @optional as a short-cut to declaring several overloaded methods.

**Comment by ChrisDodd** [comment]
> It's grammatical to write something like this in p4.
> 
> ```
> control C(in int<8> x = 77);
> package Pkg(C c);
> control MyC() {
>   apply {
>   }
> }
> Pkg(MyC());
> ```
> 

This seems to me like it should be a type error, as MyC doesn't match C (so can't be passed as an argument to Pkg).  If you had

    control C();
    package Pkg(C c);
    control MyC(in int<8> x = 77) {

then it should be type-compatible?

**Comment by hackedy** [comment]
p4c accepts this example, with the default argument changed to an @optional parameter.
```
control C(@optional in int<8> x);
package Pkg(C c);
control MyC() {
  apply {
  }
}
Pkg(MyC()) pk;
```

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
