### ISSUE TITLE
Should types on which `lookahead` is supported by specified more precisely?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#879]
The latest spec as of this writing says of the type `T` on which `lookahead` operations are performed: "T must be a type with fixed width".

There are code examples in the spec that show `lookahead` operands being a struct containing two fields, both type `bit<W>`.

If that satisfies "must be a type with fixed width", then it seems inconsistent with the resistance to defining operations like minSizeInBits on structs.  I am not here suggesting that we do define minSizeInBits on struct types, just pointing out that this view, plus the spec implying that structs are types "with fixed width", seems inconsistent.

**Comment by mbudiu-vmw** [comment]
Perhaps; anything that can be in a header, essentially.

**Comment by jafingerhut** [comment]
I created this issue due to discussion on this one: https://github.com/p4lang/p4-spec/issues/864

As Vladimir points out there, if this use of `lookahead` is considered reasonable, one could argue that it justifies that structs should be emit'able and extract'able, too, or at least structs that contain only members that are all emit'able and extract'able.

**Comment by jafingerhut** [comment]
Also note that if structs can be used for lookahead, emit, and extract, that implies absolutely nothing about how an implementation lays them out internally in memory, just as the current spec implies absolutely nothing about how an implementation lays out headers or header_union values in memory.  It only requires that emit puts bits from memory into a packet in a particular order, and extract takes bits from the packet in a particular order and copies them to the corresponding places in memory.

**Comment by vgurevich** [comment]
I think that we currently support this (very useful):

```
struct l4_lookup_t {
    bit<16>  word_1;
    bit<16>  word_2;
}

struct ingress_metadata_t {
    l4_lookup_t   l4_lookup;
    bit<1>        first_frag;
}

parser IngressParser(packet_in        pkt,
    out ingress_headers_t             hdr,
    out ingress_metadata_t            meta,
    out ingress_intrinsic_metadata_t  ig_intr_md)
{
     . . . 
     state parse_ipv4 {
        pkt.extract(hdr.ipv4);
        meta.l4_lookup = pkt.lookahead<l4_lookup_t>();
 
        transition select(hdr.ipv4.frag_offset,
                          hdr.ipv4.protocol,
                          hdr.ipv4.ihl) {
            ( 0, ip_proto_t.ICMP, 5 ) : parse_icmp;
            ( 0, ip_proto_t.IGMP, 5 ) : parse_igmp;
            ( 0, ip_proto_t.TCP,  5 ) : parse_tcp;
            ( 0, ip_proto_t.UDP,  5 ) : parse_udp;
            ( 0, _             ,  5 ) : parse_first_fragment;
            default : accept;
        }
    }
```

So, we support lookahed() with structs and this is super0-convenient.

On the other hand, the compiler crashes with the following construct:
```
    bit<1> bos0;
    bit<1> bos1;
    bit<1> bos2;

    state parse_mpls {
        bos0 = pkt.lookahead<mpls[3]>()[0].bos;
        bos1 = pkt.lookahead<mpls[3]>()[1].bos;
        bos2 = pkt.lookahead<mpls[3]>()[2].bos;

        transition select(bos0, bos1, bos2) {
           (1, _, _) : parse_one_label;
           (0, 1, _): parse_two_labels;
           (0, 0, 1): parse_three_or_more_labels;
       }
}
```

**Comment by mbudiu-vmw** [comment]
If the compiler crashes please file an issue with the implementation.

**Comment by vgurevich** [comment]
@mbudiu-vmw -- will do. I just wanted to make sure we discuss the issue of lokahead on a header stack -- it is not mentioned anywhere explicitly, but seems very useful and convenient.

@jafingerhut -- structs are already emit()-able as long as they contain only headers. Haven't tried anything else, though :)

Not sure about extracts, but I agree with the logic. That's why I think that structs are not unordered collections  (as I mentioned in the comment #864 )

**Comment by jafingerhut** [comment]
@vgurevich I think that at least one property that some people think of when they think of structs as unordered is that the implementation need not store things in memory in any particular arrangement.

There are C compilers that promise memory layouts of structs, so that you can do union/pointer-cast-between-different-type tricks for efficiently treating one sequence of bytes as another.  I don't think I have heard anyone propose _that_ in P4, or at least not recently.

P4 does not require particular layouts in memory for *any* types, that I am aware of.  It requires that emit, extract, and lookahead pay attention to the order that fields are defined within header types, and as I would say kind of an oddball case added in for convenience, for structs containing only headers (but not yet for any other kind of struct).

So there seems to be more than one shade of meaning to whether a collection is considered "ordered" are not:
(a) can you do extract/emit/lookahead on it?  That has often been called serializable in the P4 LDWG and spec.
(b) is there any promise to how things are laid out in memory -- Nothing in P4 has this requirement, not even headers.

**Comment by mbudiu-vmw** [comment]
Because there is no "reinterpret cast" construct in P4 the notion of memory order is not really well-defined. There is no experiment that you can do in the language to distinguish the ordering of fields in the implementation. Indeed, extract/emit/lookahead convert from a bit stream to P4 data structures, and there the layout in the bitstream is important.

**Comment by vgurevich** [comment]
@jafingerhut -- I agree. Fortunately, P4 does not have pointers, so the notion of "memory layout" doesn't exist :)

That's precisely why I think we can do a lot more with structs without breaking anything. 

I think it should be possible to extract a struct that contains multiple headers and/or even ANY serializable types. Frankly, if you do not emit a header and do not check/modify its validity, it can be safely reduced to a struct anyways.

**Comment by vgurevich** [comment]
@mbudiu-vmw Filed #2465 in p4c

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
