### ISSUE TITLE
Be consistent about `miss` in `apply_table(T)`

### ISSUE THREAD

**Issue by blp** [p4lang/p4-spec#885]
In `#sec-invoke-mau` and `#sec-mau-semantics`, the `miss` field in `apply_table(T)` is inconsistently included in the discussion. The attached patch should make what I mean clear (and possibly fix it).
[0001-P4-16-spec-Consistently-consider-the-miss-field-in-a.txt](https://github.com/p4lang/p4-spec/files/5037541/0001-P4-16-spec-Consistently-consider-the-miss-field-in-a.txt)

**Comment by jnfoster** [comment]
Nicely spotted. Do you want to go ahead and make a proper PR on the p4-spec repository?

**Comment by blp** [comment]
> Nicely spotted. Do you want to go ahead and make a proper PR on the p4-spec repository?

Done: pull #886
