### ISSUE TITLE
Does anything in current P4_16 spec prevent an extern from adding entries to a table?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#889]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [ ] **Document**:

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

I will think about where to record an answer to this later, for future reference, but for now I wanted to double-check my understanding.

If one wanted to create an extern function for an architecture that could, from within the P4 program, cause entries to be added to a P4 table, I do not believe that this would violate anything in the P4_16 language spec that I can see.

Some justification for this belief:

Section 6.7.1 "Justification", explaining what extern functions cannot do, pretty much lists the only things that an extern CANNOT do is: read or write P4 program variables, except via parameters to the extern function call.

It explicitly does say that externs can have these kinds of side effects (in version 1.2.1 of the spec, in case this text has changed across spec versions):

"In general, extern functions are arbitrarily powerful: they can store information in global storage, spawn separate threads, “collude” with each other to share information — but they cannot access any variable in a P4 program. With copy-in/copy-out semantics the compiler can still reason about P4 programs that invoke extern functions."

It does not explicitly say "an extern can add entries to a table", but I it seems unwise to attempt to explicitly list everything possible for a construct that is "arbitrarily powerful".

In particular, adding entries to a table via an extern call would not modify any P4 program variables, nor read them, except any passed as parameters to the extern call.

Happy to hear of any dissenting views on this, in case I have missed something.

**Comment by jafingerhut** [comment]
Note: The questions raised in this issue do not say anything about whether a P4 target should be required to support such a feature.  That is properly left to particular target implementations to decide.  There are devices that can add entries to tables without involving the control plane for every such addition.

The point of the question is whether the P4 language spec would need to be modified in order to make this legal according to the spec.

**Comment by vgurevich** [comment]
@jafingerhut -- I think your understanding is correct. I do not see anything in the spec that would prohibit that and I also think that it was intentional.

**Comment by mbudiu-vmw** [comment]
Indeed, in the ebpf back-end we allow programs to write directly to tables.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Out of curiosity for the API you have created for this capability, do you happen to have an ebpf test program handy that exercises this feature?

**Comment by mbudiu-vmw** [comment]
You may be unsatisfied with this answer, but counters in ebpf are implemented as regular tables, but which are mutated by the dataplane directly. In ebpf_model.p4 the CounterArray extern has 'increment' and 'add' methods. So we have not implemented mutation for proper P4 tables, but CounterArray tables use really the same underlying construct. The count_ebpf.p4 program from p4_16_samples uses increment, and there is a count_ebpf.stf file.

**Comment by jafingerhut** [comment]
It wasn't what I was hoping for, which was an implementation of a P4 data plane adding new entries to a P4 table, but I do appreciate knowing the differences between what you have done, and that.  Thanks.

**Comment by mbudiu-vmw** [comment]
There would be no difficulty to create an 
```
extern TableWriter<K,V> {
   TableWriter(string table);
   void insert(k v, V v);
}
```
that is attached to a specific table (specified by name; let's assume that has exact keys), and which can insert an entry at a specified key. You would have to somehow encode in the value the data describing an action and its directionless arguments; perhaps you will also use a string for the action name. Both K and V will in general be tuple types. At runtime, calling 'insert' would overwrite the entry with the specified key with the specified tuple.  In the ebpf back-end the implementation of this method would be exactly the same as for CounterArray.insert. 

Of course, this has no type-checking as written, and in general, if you can have multiple actions, you will need one of the unions that you proposed for the V values.

**Comment by mbudiu-vmw** [comment]
Or, perhaps to accommodate multiple actions the signature can be:
```
extern TableWriter<K> {
    TableWriter(string table);
    void insert<V>(K v, V v);
}
```
This way you can have multiple `insert` methods with different signatures.

**Comment by jafingerhut** [comment]
I want to describe a restricted form of such an insert extern function.  I am not opposed to the more general one that you proposed here https://github.com/p4lang/p4-spec/issues/889#issuecomment-683137478 but the restricted variant is one that I know has multiple use cases, and I've seen multiple high speed data planes with this restricted capability.

The common case is enough to implement a feature like Netflow, where the only time that you ever want to add an entry to a table from the data plane is because you just did an `apply()` call on the table and got a miss.  You want future packets with the same key to get a hit.

For this use case, a restricted `insert` operation that is only allowed to be called from the default action of a table is enough.  Besides being easier for a target device to implement, it also suggests that the target table of the `insert` can be understood from the context -- it must be the table whose default_action is being executed right now.

Also, the key one wants to insert is the key that was just looked up and not found.  This suggests that we don't need to provide a key as a parameter, because the key would be understood from the context.  If this seems to violate the restriction that externs cannot read P4 variables that are not given as parameters, I think one could argue that the extern can access the key that was just looked up as internal state of the architecture.  To me, this looks similar to how action selector externs like those in v1model, PSA, and other architectures can access the values of table search keys with match_kind `selector`.

So, the only parameters needed for a restricted `insert` are an action name, and values for the action's directionless parameters.  As you point out, a string for the action name doesn't require anything new in the language spec.

It seems useful for readability to allow a struct type to specify the directionless action parameters, as in the code snippet below that uses a structure literal expression with a type cast at its beginning.
```
// This code snippet looks like it requires nothing new in the P4_16 language spec
action t1_act1 (bit<8> p1, bit<16> p2) {
     // code for action here (details not relevant for example)
}

struct t1_act1_params_t {
    bit<8> p1;
    bit<16> p2;
}

action t1_missed () {
    insert("t1_act1", (t1_act1_params_t) {p1 = 17, p2 = 35});
}
```
If that is reasonable, we could consider the convenience of some kind of syntactic sugar that creates a struct type like `t1_act1_params_t` from the definition of action `t1_act1`.  The field names and types would be the same as the parameter names and types of the directionless parameters of the action.  I don't have good proposed syntax for such a thing, but if the syntax `ACTION_DATA(t1_act1)` represented a type like `t1_act1_params_t` above, we could write this:
```
// This code only requires one new thing in the language spec -- a definition for ACTION_DATA(t1_act1)
action t1_act1 (bit<8> p1, bit<16> p2) {
     // code for action here (details not relevant for example)
}

action t1_missed () {
    insert("t1_act1", (ACTION_DATA(t1_act1)) {p1 = 17, p2 = 35});
}
```

For a more general `insert` operation that also let you specify the key to insert, something perhaps called `KEY_SPEC(table_name)` could be a struct type auto-generated from the table's `key` property.  I don't have any known use cases for this generality, though -- just tossing that idea out there in case someone else would like to propose a definition for such a thing.

A crazy idea: allow something that looks more like an action call as the parameter to `insert`.
```
// This code is the most far-out proposal of the bunch, and not needed, given the more conservative approaches above
action t1_act1 (bit<8> p1, bit<16> p2) {
     // code for action here (details not relevant for example)
}

action t1_missed () {
    insert(t1_act1(p1 = 17, p2 = 35));
}
```
That requires some brand new type in the P4_16 language as the type of the expression `t1_act1(p1 = 17, p2 = 35)`.  That sounds like it is low benefit relative to the time required to define it, since I do not know any use cases for it other than this insert extern function.

**Comment by vgurevich** [comment]
@jafingerhut -- I would assume that you want the extern not only to insert the entry, but also to execute the specified action with that specified action data, correct? Or would you like to split these into two independent functionalities?

**Comment by jafingerhut** [comment]
@vgurevich - I am still double-checking details, but it might be important in some use cases to have different behavior in each of these cases:

(a) miss, and add succeeded in adding a new entry
(b) miss, and add failed to add a new entry
(c) hit on an already-existing entry

**Comment by vgurevich** [comment]
@jafingerhut -- my question was mostly about (a), i.e. do we assume that the action specified in the extern would also be executed for the packet and not executed for in case of (b)? This will require the extern to know the outcome of a pretty complex operation before you make a decision to execute the action, but should still be doable (maybe with some restrictions), because I would also state that externs can probably execute somewhat asynchronously from the rest of the data plane program.

Also, is the assumption that aging will be done by the control plane only, you you would also want something like

```
   idle_timeout = delete(); /* Another extern that takes the key as an implicit parameter */
```

In my opinion, everything you are suggesting should be allowed, especially given the fact that the control plane is allowed to manipulate the stateful objects (tables included) completely asynchronously from the data plane. Thus, allowing the data plane to do it  should not open any holes, I think.

**Comment by mbudiu-vmw** [comment]
Our "p4++" proposal asks for the ability of P4 programs to mutate arbitrary control-plane tables. 
I believe that the right way to do this is to finalize the "Safe unions" proposal that @jafingerhut wrote, and then to have each table declaration introduce automatically a safe union type that contains a variant for each action. Then your `insert` function can use a literal value of this union type. 
I have to think a bit about actions that have other non-directionless arguments too.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
