### ISSUE TITLE
Consider further generalizations to the switch statement

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#890]
## Personnel
- [x] **Owner:** @jafingerhut 
- [x] **Supporters:** @mbudiu-vmw 

## Design
- [x] **Document:** [Union Types in P4_16](http://docs.google.com/document/d/1IhC-J-ZZF2mfWcEyXRhlnpNqfAnDHuQ-0RO_dglxTgM/edit)

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/887
- [x] **`p4c`**: https://github.com/p4lang/p4c/pull/2575

## Process
- [x] **LDWG discussion**: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#heading=h.lggdh8yt82ei, at the September LDWG
- [x] **LDWG approved**: at the December 2020 meeting: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#heading=h.dwbckqqyr3di
- [x] **Merged into `p4-spec`**
- [x] **Merged into `p4c`**

That is, over and above the generalizations proposed here: https://github.com/p4lang/p4-spec/pull/887

That PR proposed allowing the switch expression to have types `bit<W>`, `int<W>`, `enum` (either with, or without, an underlying type), or `error`, and required that all switch labels be exact match values of those types, with no duplicates.

It also describes a mechanical translation from the generalized switch statements to the more restricted one that existed before in the P4_16 language specification versions 1.2.1 and earlier.

That transformation also makes it fairly straightforward to consider generalizing switch statements even more, allowing switch expressions to be tuples/lists of one or more sub-expressions, where each tuple/list member has one of the types listed above.

If a tuple/list member had type `bit<W>`, `int<W>`, or `enum` with an underlying `bit<W>` or `int<W>` type, it seems reasonable to allow switch labels to use ternary expressions like `0x0ea0 &&& 0x0ff0` for a member with type `bit<16>`.  The corresponding field of the synthesized table would have match_kind ternary instead of exact.  It seems most efficient if the compiler chose match_kind exact whenever there were only expressions that were single values like `0x0ea0` for that tuple/list member in all switch labels, only using `ternary` if there was at least one expression like `0x0ea0 &&& 0x0ff0` for the tuple/list member among the switch labels.

One could also consider allowing range expressions like `5 ... 15`, which seems like a useful convenience for P4 developers.  As far as the suggested transformation that P4 compiler implementers can use, that works well if the target architecture supports match_kind `range` for tables.  If not, one approach is to use `ternary` and expand ranges into multiple ternary entries when necessary, as was done in p4c's bmv2 back end for transition select statements in this p4c commit: https://github.com/p4lang/p4c/commit/28b5258bc8a310af4d7e38c8e6a534c8ed4593f4

**Comment by jafingerhut** [comment]
Continuing the previous comment, if a tuple/list member had any other type, i.e. `enum` without an underlying type, or `error`, then the simplest proposal is to only define exact match values for such members.  Such values have no portable promises on how they are implemented on target devices, so ternary expressions do not really make sense.  Range expressions do not, either.

**Comment by mbudiu-vmw** [comment]
I am experimenting with migrating the LDWG discussions into items. How about this standard format for an issue?

**Comment by jnfoster** [comment]
I made a few typographical tweaks. See what you think?

**Comment by mbudiu-vmw** [comment]
Looks good. We should have somewhere this template to make it easy to copy-and-paste.
Also, I find that references to the google doc are rather weird.

**Comment by jnfoster** [comment]
Stashed it here

https://github.com/p4lang/p4-spec/wiki/LDWG-Issue-Template

Does that work?
