### ISSUE TITLE
Concrete default arguments for generic parameters?

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#895]
A generic function declaration can include default parameters for its arguments, like this.
```
control MyC<T>(T x) { apply { } }
control C<T>(T x);
package P<T>(C<T> c = MyC<T>());
```
Notice that the default argument has type `C<T>`, exactly the type of the parameter. But the following seems to also be permitted.
```
control MyC(bool x) { apply { } }
control C<T>(T x);
package P<T>(C<T> c = MyC());
```
In this case, the type of the default argument is actually `C<bool>`. The easiest way to accommodate this is to defer typechecking of the default argument until reaching a call site. Unfortunately this allows "impossible" package declarations like the following, where default arguments disagree on their choice of a type parameter.
```
control CBit(inout bit<8> x) {
  apply { }
}

control CInt(inout int<8> x) {
  apply { }
}

control C<T>(inout T param);

package P<T>(C<T> ingress=CBit(), C<T> egress=CInt());
```
There may be a more complicated way to typecheck generic declarations which would reject this last example but accept the earlier ones, but I think the simplest and least surprising solution may be to only allow the very first example.

Right now p4c and petr4 both accept all 3 of these. See cornell-netlab/petr4#87 and p4lang/p4c#1639.

**Comment by mbudiu-vmw** [comment]
So what is the rule: all type variables must appear in the default value?
That may rule out some useful programs. Default argument values were introduced exactly to make specifying complex architectures easier.
I believe that for the last case unification should fail, since it needs to unify T with two different types.

**Comment by mbudiu-vmw** [comment]
BTW: the p4c type checker does not really check the default argument types unless they are being used. So you have to see whether the instantiation P() typechecks or not.

**Comment by mbudiu-vmw** [comment]
In fact, your example is a good argument why default argument values should *not* be typechecked in the declaration.
Indeed, in your example if you use *all* default argument values the program should not typecheck. But if you use *some* of them the program may very well typecheck, depending on the values assigned to the other arguments.
The spec is silent about this, so perhaps we could add something about this in the spec. Do you want to create a PR?
I think that this behavior applies not only to generics, but to all default argument values.

**Comment by hackedy** [comment]
What if we allowed overloaded declarations of packages? Then we could be more specific about combinations of defaults. Something like this instead of the single declaration.
```
package P<T>(C<T> ingress=CBit(), C<T> egress);
package P<T>(C<T> ingress, C<T> egress=CInt());
```

**Comment by mbudiu-vmw** [comment]
Today overload resolution is based on argument names, so this would not compile.
We do not have resolution based on types, although it is a requested feature.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
