### ISSUE TITLE
Structure overlays

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#899]
## Personnel
- [x] **Owner**: @mbudiu-vmw 
- [ ] **Supporters**: @jafingerhut 

## Design
- [ ] **Document**:

## Implementation 
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/656
- [ ] **`p4c`**: 

## Process
- [x] **LDWG discussed**: Refinements are being made
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
