### ISSUE TITLE
Syntax to give actions new names

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#900]
## Personnel
- [x] **Owner**: @vgurevich 
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [x] **Document**: https://github.com/p4lang/p4c/issues/2501

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [x] **LDWG discussed**: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#heading=h.lggdh8yt82ei, September 2020 meeting
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

**Comment by mbudiu-vmw** [comment]
We agreed that @vgurevich will create 2 PRs against the P4-16 spec.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
