### ISSUE TITLE
Parse varbits

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#901]
## Personnel
- [x] **Owner**: @mbudiu-vmw 
- [ ] **Supporters**:

## Design
- [ ] **Document**:

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/883
- [ ] **`p4c`**: 

## Process
- [x] **LDWG discussed**: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#, August 2020 meeting
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

**Comment by mbudiu-vmw** [comment]
See also #264

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
