### ISSUE TITLE
Type constraints for generic types

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#903]
## Personnel
- [x] **Owner**: @jnfoster 
- [ ] **Supporters**:

## Design
- [ ] **Document**:

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
