### ISSUE TITLE
Casts between integers and bools

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#904]
## Personnel
- [x] **Owner**: @mbudiu-vmw 
- [x] **Supporters**: @hackedy

## Design
- [x] **Document**: https://github.com/p4lang/p4c/issues/2444

## Implementation
- [x] **`p4-spec`**: https://github.com/p4lang/p4-spec/pull/906
- [x] **`p4c`**: https://github.com/p4lang/p4c/pull/2658

## Process
- [x] **LDWG discussed**: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#heading=h.p7cqtii56dy, July 2020 meeting
- [x] **LDWG approved**: At the January 2021 meeting
- [ ] **Merged into `p4-spec`**:
- [x] **Merged into `p4c`**:

**Comment by mbudiu-vmw** [comment]
We don't seem to have notes in the Google Doc for the January meeting, when we discussed this issue.

**Comment by jnfoster** [comment]
@jafingerhut Could you input your notes into the Google Doc?

**Comment by mbudiu-vmw** [comment]
Actually I saw the notes. Maybe I didn't refresh.

**Comment by jafingerhut** [comment]
@jnfoster @mbudiu-vmw Glad you see them, as the Google doc is the only place I recorded any notes during the previous meeting.  I see them there when I checked a minute ago.
