### ISSUE TITLE
Metaprogramming for Loops

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#907]
## Personnel
- [ ] **Owner**: 
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [x] **Document**: see below

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: 

## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

Here's an (arguably ugly) way to do statically unrolled loops, but which could be very useful in practice:
Define a new preprocessor macro:
```
#for i (min, max, step)
body
#endfor i
```

This is expanded by the preprocessor into:
```
#define i min
#line original
body
#undef i
#define i (min + step)
#line original
body
...
#undef i
#define i (min + ((max - min) / step) * step)
#line original
body
#undef i
```

**Comment by mbudiu-vmw** [comment]
Related to https://github.com/p4lang/p4-spec/issues/84

**Comment by mbudiu-vmw** [comment]
Explore uses of boost preprocessor to achieve the same goals.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.

Also, we have other issues like #1261 addressing finer-grained proposals.
