### ISSUE TITLE
Should we allow bit<0> values?

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#912]
## Personnel
- [x] **Owner**: @mbudiu-vmw
- [x] **Supporters**: @vgurevich 

## Design
- [x] **Document**: LDWG discussion in February and March 2021

## Implementation
- [x] **`p4-spec`**: #931
- [x] **`p4c`**: https://github.com/p4lang/p4c/pull/2724

## Process
- [x] **LDWG discussed**: April, May 2021
- [x] **LDWG approved**: May 2021
- [x] **Merged into `p4-spec`**:
- [x] **Merged into `p4c`**: https://github.com/p4lang/p4c/pull/2724

======================

**Comment by mbudiu-vmw** [comment]
This came up during the LDWG discussions.

**Comment by mbudiu-vmw** [comment]
We agreed to add a PR to the spec.

**Comment by fruffy** [comment]
My only personal issue with this is that solvers like Z3 do not allow zero bit vectors, so I have to implement a special case for this in the interpreter and omit these header members from equality checking. But I think it should be possible to implement semantics for this.
What about assignments and casts? Are those allowed? 

```p4
#include <core.p4>


header H {
    bit<0>  a;
    bit<0>  b;
}

struct Headers {
    H     h;
}

control ingress(inout Headers h) {

    apply {
        bit<0> zero;
        bit<8> val = 8w1;
        h.h.a = zero;
        h.h.b = (bit<0>) val;
    }
}
```

**Comment by mbudiu-vmw** [comment]
From the discussion today in the LDWG it looks like these would be allowed.
You may need to do something special for these when translating to Z3.

**Comment by mbudiu-vmw** [comment]
We expect to merge #931 soon, so I am closing this issue.
