### ISSUE TITLE
Wordsmithing for action data

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#914]
@QinshiWang pointed out that the description of action data in Section 13.2.1.2 is misleading, and confusing to new P4 programmers. Specifically, it says 

> When used in a match-action table (see Section 13.2.1.2), these parameters will be provided by the control plane.

But actually, action data can come from default actions or const entries. So perhaps we should rewrite this to say that the directionless parameters are bound according to the table entries (which may come from the control-plane or the table declaration itself).

**Comment by mbudiu-vmw** [comment]
I think you should consider submitting a PR that we can discuss at the next LDWG.

**Comment by jnfoster** [comment]
Yep. Just making an issue to track (possibly as much work as doing the wordsmithing, yes :-)

**Comment by QinshiWang** [comment]
In both Sections 13.1 and 13.2.1.2.

**Comment by mbudiu-vmw** [comment]
https://github.com/p4lang/p4-spec/pull/916
