### ISSUE TITLE
What types can be used as indexes into header stacks?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#915]
The spec doesn't say... for example, is `varbit` allowed?

**Comment by jfingerh** [comment]
For compile-time known values, I would think that a reasonably conservative proposal would explicitly support only these types:
+ int
+ bit<W> for any W >= 1
+ int<W> for any W >= 1
+ Any enum type defined with an explicit storage representation that was one of the above
For header stack index expressions that are not compile-time known values, they could not be type int, of course.

**Comment by jnfoster** [comment]
@jnfoster and @jafingerhut will take this design and flesh it out into a full-fledged PR.

**Comment by mbudiu-vmw** [comment]
Fixed in https://github.com/p4lang/p4c/pull/2738
