### ISSUE TITLE
PSA: Add match_kind optional to PSA

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#919]
This match_kind has been added to v1model some time ago, and does not require any data plane changes for a data plane that supports match_kind ternary, since one possible implementation is for match_kind optional to be a control plane API restriction on a ternary field in the data plane.  There might be some data planes that can implement optional more efficiently than ternary, so allowing a P4 developer to explicitly declare fields with match_kind optional could be of some cost benefit for such targets.

**Comment by jnfoster** [comment]
No objection from me! On the contrary, I endorse!

**Comment by blp** [comment]
This aligns well with my experience building software switches, in which wildcarding on a per-field basis is sometimes easier or more efficient to implement than wildcarding on a per-bit basis.

**Comment by jafingerhut** [comment]
I have created this PR intended to address this issue.  As described above, I plan to let this sit for at least a couple of weeks for comments: https://github.com/p4lang/p4-spec/pull/920

**Comment by jafingerhut** [comment]
Closed since PR #920 has been merged into the PSA specification.
