### ISSUE TITLE
PSA: Add standard metadata for packet length

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#922]
The pull request will have more detail on precisely what value this new field will take in all cases, but basically the idea is that for packets from an Ethernet interface, it will be the length of the received Ethernet frame in bytes, including the 4-byte FCS at the end.

One limited way to introduce this is to make it a direction `in` field, so read only, available only in the egress parser and control.

@konne88 @stefanheule @chrisdodd @hanw @gbrebner Pinging you explicitly on this so you are aware of it and can provide any feedback on the brief description above.  I can ping you again (or anyone else you wish) when a more detailed proposal is created as a PR on the current PSA specification.

**Comment by konne88** [comment]
This seems pretty useful. Would it basically be the same as we have in v1 model?

**Comment by jafingerhut** [comment]
@konne88 v1model architecture allows the packet length to be accessed during the ingress control, too.  If that is something you think you need, we should talk.  If egress only is enough, then I was hoping you might double-check whether any use cases you have in mind are OK if the packet length value that is readable in egress is OK if it is the length of the packet received on the input Ethernet interface, with no adjustments from adding/removing headers that might be done during ingress control processing.

**Comment by jafingerhut** [comment]
Another wrinkle/limitation that would be part of the proposal I am thinking of: if a switch device supports cut-through packet forwarding (i.e. ingress control and egress control can begin processing even before the last byte of a large packet has been received on the ingress interface), then even the egress control would not be able to know the packet length.

**Comment by konne88** [comment]
When we need the packet length right now, e.g. to set the length field of an outer header, we just use inner IP header's length field. Since cut-through packet forwarding is pretty common and we would like our P4 programs to be portable, we'd continue to use the current approach. So why even add this feature? It doesn't seem to add much value, and might confuse users since it's so subtle.

**Comment by jafingerhut** [comment]
I have gotten at least one request to add such a thing to PSA, and can ask the one requesting these questions and get back to you.  Note that v1model packet length is about as subtle as this, too.

**Comment by konne88** [comment]
Yeah, I might know the person who asked :)

**Comment by jafingerhut** [comment]
I have created a first draft of a proposed PR to add a packet length field to the PSA specification here.  Feel free to comment in that PR's Github comments if you have any: https://github.com/p4lang/p4-spec/pull/925

**Comment by jafingerhut** [comment]
Given some discussions both here and privately, I would recommend that we consider this PR: https://github.com/p4lang/p4-spec/pull/927 instead of #925.  Rather than add a packet length field that is useless if cut-through switching is enabled in a switch, it seems best to explain explicitly that this is why such a field is of very limited use, and what the most common alternatives are, e.g. fields from which the packet length can be calculated in IPv4 and IPv6 headers.

**Comment by jafingerhut** [comment]
Merged in PR #927, and closed #925 without merging it in.  Thus there is no packet length fields added to the PSA architecture, for the reasons described in the updated PSA spec with #927 merged in.
