### ISSUE TITLE
"action_run" when "default_action" is undefined

### ISSUE THREAD

**Issue by QinshiWang** [p4lang/p4-spec#933]
I refer to P4~16 Spec v1.2.1 throughout this issue.

#### Problem
It's not clear what `action_run` will be when a table application comes to a miss and the table doesn't have a `default_action`.

In Section 13.2, it's said
> The compiler may set the default_action to NoAction (and also insert it into the list of actions) for tables that do not define the default_action property.

That means it's optional for the compiler to set default_action to NoAction.

In Section 13.2.2, it's said
> The action_run field indicates which kind of action was executed (irrespective of whether it was a hit or a miss).

So when it is a miss, `action_run` is the `default_action`. But it's ambiguous when `default_action` is undefined, because setting the `default_action` to `NoAction` is optional. For example,
```
switch (t.apply().action_run) {
    NoAction: { ... } /* Will this be executed if it was a miss and default_action is undefined? */
}
```

#### Suggestion
I would suggest just saying the `default_action` is `NoAction` when it's not explicitly defined.

**Comment by mbudiu-vmw** [comment]
I think this is the right thing to do.

**Comment by mbudiu-vmw** [comment]
I suspect that we were leaving the door open for an architecture to define a custom default action, e.g., drop.
Then the architecture specification has to say what the default action is.

**Comment by QinshiWang** [comment]
> I suspect that we were leaving the door open for an architecture to define a custom default action, e.g., drop.
> Then the architecture specification has to say what the default action is.

That's another issue, because the current spec says
> If a table does not specify the default_action property and no entry matches a given packet, then the table does not affect the packet and processing continues according to the imperative control flow of the program.

I think what @mbudiu-vmw  said can be supported, because the spec indicates the `default_action` can be modified by the control plane as long as it is not declared as const.

**Comment by QinshiWang** [comment]
Solved.
