### ISSUE TITLE
PSA: Consider removing all mentions of control plane APIs from PSA spec

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4-spec#940]
There are many comments in the psa.p4 include file for PSA that describe a control plane API.  These comments were added in 2017 by some of the participants in the P4 architecture working group, but were almost never discussed in the meetings before the PSA specification was published.

Before the PSA spec 1.0 was published, the P4.org API working group was well under way to defining the P4Runtime API.

I consider all of these control plane API comments in the psa.p4 include file vestigial, and would recommend that we delete them, and make an explicit mention somewhere in the PSA specification that there can be multiple different control plane APIs used by PSA target devices, of which one example is the P4Runtime API.  Others exist, too, of course.

**Comment by gbrebner** [comment]
Okay with me.

**Comment by jafingerhut** [comment]
Proposed PR to address this created here: https://github.com/p4lang/p4-spec/pull/1025
