### ISSUE TITLE
P4 DTLS header

### ISSUE THREAD

**Issue by gloriadevitoria** [p4lang/p4-spec#946]
I would like to define a DTLS header. However, I believe I'm defining it in a wrong way, as I analyse logs and see the header's values do not match with the ones shown in Wireshark. I was wondering if you have any idea of how I can define it. Thanks in advance,

**Comment by mbudiu-vmw** [comment]
This is not really the right forum for this question. This is the repository of the P4 language specification documents.
Your question is about programming a specific device (which you didn't indicate).
You should perhaps try one of the P4 mailing lists, the forum https://forum.p4.org/ or the slack channel from p4.org.
