### ISSUE TITLE
Consider allowing P4 implementations to do table apply within actions

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4-spec#947]
I know of at least one P4 implementation where this would be a natural thing to do.

I am pretty sure that there are P4 implementations that would _not_ be able to (or choose not to) support this, so I have no illusions that such a feature would be supported by all implementations.

My first question is: does anyone see an issue in defining the behavior and/or semantics of such an extension to the language?  I have not been able to think of any issues in doing so, yet.

**Comment by jnfoster** [comment]
Andy, 

Could you point us to the part of the spec that would need to change? I just took a quick glance and couldn't find the phrase that forbids applying tables in the body of an action... though it's possible I missed it.

The only restriction I could find is to disallow `switch` statements in Section 13.1.

> The body of an action consists of a sequence of statements and declarations. No switch statements are allowed within an action—the grammar permits them, but a semantic check should reject them. Some targets may impose additional restrictions on action bodies—e.g., only allowing straight-line code, with no conditional statements or expressions.

I didn't see any discussion in the section on invoking tables to suggest this restriction either...

**Comment by jfingerh** [comment]
Appendix F, in the 4th table, the row for 'table' indicates where a table.apply() call is allowed to be made.  There it says that table.apply() is only permitted within a control apply block, and "no" within an action.

**Comment by mbudiu-vmw** [comment]
Personally I find that programming with actions is very unintuitive. So having even more of them would actually make the language harder to use for humans. The actions are mostly useful for targets where they are a close approximation of the way hardware works. Partitioning code into actions is something that a compiler can have a lot of trouble doing since the constraints of a target can be very complex. For targets where action can invoke tables I claim that you should not even write code using actions as all; an API like the KV https://github.com/p4lang/p4c/pull/2739 is preferable.

**Comment by jfingerh** [comment]
The reason I am suggesting an action that can do some_table.apply() call is because the "sub-table" (the one that is invoked from inside of another table's action) does behave exactly like any other P4 table -- it has the same flexible way of specifying keys, and the same control plane API of adding table entries, deleting them, or modifying them, as any other P4 table.

Using an extern definition instead of a table means that we need to go to the trouble of creating a control plane API for this extern that exactly mimics the control plane API of a P4 table.

**Comment by mbudiu-vmw** [comment]
There is a very natural way to define the control-plane API for such an extern: the keys are table keys, and the values are action arguments. In fact, the implementation would compile these KV tables into traditional tables.

**Comment by jfingerh** [comment]
I am lost here -- what is the purpose of defining a new extern that a P4 compiler is expected to emit the same code as it would for a P4 table?

**Comment by mbudiu-vmw** [comment]
That is a possible implementation. For other targets other implementations are possible.
And I will repeat: writing code with actions is rather inconvenient. 
This style would allow you to write traditional imperative code.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
