### ISSUE TITLE
Add the ability to modify extern objects

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#948]
## Personnel
- [x] **Owner**: @hanw
- [x] **Supporters**: @mbudiu-vmw 

## Design
- [x] **Document**: see below

## Implementation
- [ ] **`p4-spec`**: 
- [ ] **`p4c`**: https://github.com/p4lang/p4c/pull/2818
## Process
- [ ] **LDWG discussed**: 
- [ ] **LDWG approved**:
- [ ] **Merged into `p4-spec`**:
- [ ] **Merged into `p4c`**:

======================================

By adding or modifying methods.
Similar to subclasses, but without subtyping.
This issue surfaced during the discussion https://github.com/p4lang/p4c/pull/2818

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
