### ISSUE TITLE
PDF version of the P4-16 lang spec leaves out the notes for nesting type rules 

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#951]
There is a superscript marker for a note on a few of the fields in the nesting type rules table BUT the generated PDF does not have them anywhere to be found.  The HTML has them but at the very end of the HTML file.

Both of these is not very useful when having a printed out version of the spec.

**Comment by jfingerh** [comment]
Can you point at a particular section number & name, and a phrase that has such a superscript?

**Comment by jfingerh** [comment]
Perhaps you mean the superscripts within both of the tables of Section 7.2.7 "Type nesting rules" ?   I see that they are clickable links in the published HTML version, and while the superscript numbers show up in the PDF, and they seem like clickable links, they do not link to anything, and there is no text at the bottom of the PDF pages where they appear.

This might be a limitation or bug of the Madoko formatting system.  If so, we should consider changing those from Madoko footnotes to simply some text like "See Note 1" and having paragraphs below the tables like "Note 1: blah blah ..."

**Comment by mbudiu-vmw** [comment]
We should look to see what kind of latex it generates.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
