### ISSUE TITLE
What types are allowed in select expressions?

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#954]
The spec is silent in this respect. Can you use a struct, or a varbit?
The implementation complains about expressions containing headers only.

**Comment by vgurevich** [comment]
I doubt we can allow varbit, since we do not support equality operation on it, but I think that a struct or a header can be allowed, because thy can be easily casted to/from the tuples that we have in the individual clauses. So, for example, I do not see why this 
```
transition select(hdr.ethernet) {
    (_, 0x010000_000000 &&& 0x010000_000000, _ ): reject; /* Multicast source MAC addresses are not allowed */
   ....
}
```
cannot be automatically desugared into this:
```
transition select(hdr.ethernet.dst_addr, hdr.ethernet.src_addr, hdr.ethernet.ether_type) {
    (_, 0x010000_000000 &&& 0x010000_000000, _ ): reject; /* Multicast source MAC addresses are not allowed */
   ....
}
```

**Comment by vgurevich** [comment]
I also thought that I was raising the same issue with regards to table keys...

**Comment by mbudiu-vmw** [comment]
varbits have equality comparison: https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-varbit-string

**Comment by vgurevich** [comment]
However, there are no literals for `varbit<>` and casts from `varbit<>` to `bit<n>` are not defined.

**Comment by mbudiu-vmw** [comment]
The discussion in the LDWG agreed that we will only support `bit<>` types and lists of such types. The spec should be tightened.
