### ISSUE TITLE
Install Rules For P4 Switches  

### ISSUE THREAD

**Issue by ibrahimssd** [p4lang/p4-spec#964]
Hi, 

I am working on a P4 project. Currently, I add rules using p4Runtime Simple_Swich_CLI. This way is a bit difficult for a huge program. I need to know if there is any controller which could be used in my case. I found Onos but the Onos system is a bit confusing. can anyone suggest other controllers??.

**Comment by mbudiu-vmw** [comment]
This is the repository of the P4 specification documents. This is not the right place to ask such a question.
You should consider one of the mailing lists or the forums at p4.org: https://forum.p4.org
