### ISSUE TITLE
There is no equivalent of 'verify' for controls

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#971]
An assert-like function could be useful in core.p4.
The problem surfaced in https://github.com/p4lang/p4c/pull/2914, where the compiler converts:
```
S a[2];
...
b = a[x];
```
into
```
if (x == 0)
   b = a[0];
else if (x == 1)
  b = a[1];
```
There is no portable way to report an error if `x` has a different value.

**Comment by jnfoster** [comment]
Well, if someone can explain the behavior we are interested in (whether `assert` or `control`), I'm happy to look into expressing it using existing constructs, or finding the minimal "delta" on the language spec...

**Comment by mbudiu-vmw** [comment]
We would like a construct that would make the two programs in the example at the very top equivalent.
As written the second program has fewer behaviors than the first one.

**Comment by jnfoster** [comment]
I may be missing something, but the first program has more behaviors precisely in cases where `x` is less than `0` or greater than `1`. And so `b` gets set to an undefined value. How does a `verify` or `assert` help?

**Comment by jnfoster** [comment]
But the first program _does_ have a behavior when `x` is not `0` or `1`. Per the spec, it sets `b` to an undefined value.

The second program currently has a behavior when `x` is not `0` or `1` -- it leaves `b` unchanged. 

So if we wanted to make the two programs equivalent, in this case, it seems we should add an `else` branch and set `b` to an undefined value?
