### ISSUE TITLE
“This” in abstract methods

### ISSUE THREAD

**Issue by MollyDream** [p4lang/p4-spec#973]
P4 abstract methods allow calling methods of the object by using “this” (Section [10.3.1](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-instantiating-abstract-methods)). It introduces the ability for users to define recursive functions, which may be unintended. Since an abstract extern method “may be invoked by the target architecture” in another extern method (`caller`), calling the `this.caller` in the abstract method definition creates recursion, which may never end.  Example:
```
extern RegisterAction<T, I, U> {
    RegisterAction(Register<T, I> reg);
    U execute(in I index); /* {
        U rv;
        T value = reg.read(index);
        apply(value, rv);
        reg.write(index, value);
        return rv;
    } */
    abstract void apply(inout T value, @optional out U rv);
}

Register<bit<32>,bit<16>>(32w65536, 0) reg;
RegisterAction<bit<32>, bit<16>, bit<32>>(reg) regact = {
    void apply(inout bit<32> value, out bit<32> rv) {
        rv = this.execute(value);
    }
};
```
In this example, calling `regact.execute(x)` will recursively read from the register `reg` and use the result as the next reading index. The manual carefully disables recursive calls in [control](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-calling-restrictions), [parsers](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-calling-restrictions), and [functions](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-functions), so I think it is worth gauging whether this “back door” should be closed by P4 or left as a decision by the architecture.

**Comment by jnfoster** [comment]
We briefly discussed this at the 2/7/22 LDWG. It's a good question, but we are not concerned, because the recursion is clearly via the extern, and not in the language itself.
