### ISSUE TITLE
Instantiation in a block

### ISSUE THREAD

**Issue by MollyDream** [p4lang/p4-spec#975]
The [spec](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-block-stmt) allows instantiations to be a member of a block of statements, but there is no example of that allowed by p4c. Since in the “can be instantiated in this place” table ([Appendix F](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-calling-restrictions)) only parsers and controls have blocks, if an instantiation in a block is valid, it must appear in the parsers state or the control apply block. I tested all the possible instantiations following that table in p4c (parser in parser, extern in parser, value-set in parser, control in control, extern in control, table in control), and none of them are allowed in the block. Similar results are derived from testing with the Tofino compiler. I think it is worth discussing if an `instantiation` should be a member of `statementOrDeclaration` in the P4 grammar.
Litmus Test
```
extern register<T> {
    register(bit<32> size);
    void read(out T result, in bit<32> index);
    void write(in bit<32> index, in T value);
}

control compute2(inout bit<16> x) {
    apply { x = x + 1; }
}

control compute(inout hdr h) {
    register(1) r1; // valid
    compute2() c1; // valid
    apply {
        // register(1) r2; // invalid
        // compute2() c2; // invalid
    }
}
```
Based on the spec `r2` and `c2` should be instantiable in the control apply block, but p4c rejects them. One side note is that even though one may regard the direction invocation of a table as a hidden instantiation in a control apply block, the intrinsic instantiation of a table actually is likely to happen in the control local declaration rather than the apply block since that is also the case for direct type invocation, which is showed by an example in Section [14.1](https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-direct-type-invocation).

**Comment by MollyDream** [comment]
@mbudiu-vmw Also for this post, do you know the intended use case of `instantiation` being a member of `statementOrDeclaration`, which allows instantiation in statements? Can we remove `instantiation` from `statementOrDeclaration`?

**Comment by jafingerhut** [comment]
Given the compile-time nature of P4's object/control/parser instantiation, it does seem reasonable not to support instantiation of objects within a block.  At least, if someone wished to have such an instantiation in some block, it is a straightfoward workaround to move that instantiation to the enclosing parser or control and make it "global" within that parser or control.  The only disadvantage I can see with this restriction is that the scope becomes global to that parser or control's body, so it disallows someone from trying to limit the scope of visibility of the instantiation to a small textual section of the code.

**Comment by jnfoster** [comment]
Was this discussed at the LDWG? I don't recall it...

**Comment by MollyDream** [comment]
@jnfoster No we haven't. It is linked to a pull request that we can go over in the meeting.
