### ISSUE TITLE
Have a method on headerStacks called elementType that returns the type of an element

### ISSUE THREAD

**Issue by mihaibudiu** [p4lang/p4-spec#978]

**Comment by mbudiu-vmw** [comment]
I propose in exchange to have an expression that returns a type which can be used only in typedef:
`typedef typeof(expression) name`
where `typeof` does not evaluate expression, but only returns its type.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
