### ISSUE TITLE
Annotation syntax

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4-spec#99]
The current annotation syntax is fairly limited

    annotation:  '@' name [ '(' expression ')' ]

that is, a single identifer with an optional single expression argument.  Java annotations (which these are base on) are both different and more flexible:

    annotation: '@' name [ '(' [ annotation_element_list ] ')' ]
    annotation_element: annotation | expression | name '=' expression

that is, there may be multiple arguments which may have keyword names associated with them.  There may also be annotations nested in annotations, though I'm not sure what that is useful for (I haven't been able to find any examples of it actually being used).

Do we want to allow more flexibility like this?

**Comment by mbudiu-vmw** [comment]
This is addressed by PR #625 so I will close it again.
