### ISSUE TITLE
Table property `meters` not documented?

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4-spec#993]
Consider the following table:
```
table example {
  key = { ... }
  actions = { ... }
  meters = ...;
  counters = ...;
}
```
This compiles with the BMv2 backend, but I don't see the table properies `meters` and `counters` discussed in the P4 standard. Is this an oversight? 

@jonathan-dilorenzo

**Comment by mbudiu-vmw** [comment]
Because they are actually not standard. Tables can have arbitrary target-specific properties with arbitrary target-specific values. These are bmv2-specific extensions. The ebpf tables have other properties (e.g., implementation).

**Comment by smolkaj** [comment]
Thanks for explaining.

Would it be worth explaining that in the spec? I don't see it mentioned currently, though I may have just been unable to find it.

**Comment by mbudiu-vmw** [comment]
This is this line: "In addition, tables may contain architecture-specific properties (see Section 13.2.1.6). " and that section
https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-additional-table-properties

**Comment by smolkaj** [comment]
Thanks for the pointers and sorry for the noise!
