### ISSUE TITLE
Repeated table properties?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#996]
Section 13.2 of the P4 Language Spec says

> Syntactically a table is defined in terms of a set of key-value properties. 

Note that we say a "set" and not a "list" or a "bag." Does this mean that each key can occur at most once? Or do we mean that each unique key-value pair can occur at most once? @jafingerhut reports that the front-end rejects tables declared with repeated keys. Perhaps we should clarify...

Also, the use of the word "key" is possibly confusing, given that `key` is a required property.

**Comment by mbudiu-vmw** [comment]
Today the table is treated like a namespace and the properties like declarations. That's why you cannot have duplicates.

**Comment by jnfoster** [comment]
Sure. I'll make a PR on the text to clarify the confusing bits...

**Comment by jnfoster** [comment]
Fixed by #1163.

**Comment by jnfoster** [comment]
Closing as fixed.
