### ISSUE TITLE
Are match_kinds compile-time known?

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#998]
This code fails to type check:
```
#include <core.p4> 

match_kind { fuzzy }

T f<T>(T t) { return t; }

control c()() {
    apply {
        if(f(exact) == fuzzy) { }
    }
}
```
because `match_kind`s are not compile-time known values. However, this code does type check:
```
#include <core.p4> 

match_kind { fuzzy }

T f<T>(T t) { return t; }

control c()() {
    apply {
        if(f(exact) == fuzzy) { }
    }
}
```
It is a silly example, but is this what we want?

**Comment by vgurevich** [comment]
I think that the first question to ask is whether match kinds are real types :)

I was just thinking where we can use them in practice and so far the only thing that came to mind was to use them as parameters in a control, e.g.:
```
control c(. . .)
         (match_kind t1_match_kind=exact) 
{
    table t1 {
        key = { hdr.h.f1 : t1_match_kind; }
        actions = { . . . }
        size = 
                    t1_match_kind == exact    ? 65536 : 
                    t1_match_kind == ternary ? 1024    : 
                    0;
    }
    apply {
         . . .
    }
}
```
The compiler stopped at the line `(match_kind t1_match_kind=exact)` with the message:
```
test.p4(140):syntax error, unexpected MATCH_KIND
    (match_kind
     ^^^^^^^^^^
```

**Comment by jnfoster** [comment]
Indeed, there sees to be no way to name the `match_kind` type. But in some cases you can let type inference fill it in...

**Comment by QinshiWang** [comment]
Should we just treat `match_kind` and `error` by utilizing a big part of the mechanism for `enum`? As the Petr4 paper argued that "The match_kind and error types are “open enumerations,” comparable to the extensible exception type in Standard ML".

**Comment by mbudiu-vmw** [comment]
These types are very much like enums.

**Comment by jafingerhut** [comment]
I am not sure, but perhaps this PR is related?  https://github.com/p4lang/p4-spec/pull/1020

Issue I filed recently with a different test program I was trying to make compile with at least p4test, but failed: https://github.com/p4lang/p4c/issues/3091

PR on p4c that is recently merged in (less than an hour ago as I write this comment) that Mihai wrote to fix that issue: https://github.com/p4lang/p4c/pull/3099

@vgurevich You might want to try compiling your test program above with the latest main version of p4c and see if the error message has changed, or maybe there might even not be any error message now?

**Comment by mbudiu-vmw** [comment]
I hope that we have now answered this question in the affirmative. Can we close this issue?
